### Importación de librerías necesárias

In [4]:
import unicodedata
import pandas as pd
import numpy as np
import re

In [ ]:
from src.preprocessing import build_model_text

### Importando el dataset

In [5]:
df_en = pd.read_csv('../Data/raw_data_en.csv')

In [6]:
print(df_en.shape)
df_en.head()

(6000, 5)

,title,text,subject,date,label
0,WATCH: Trump Just Told All The Anti-Gay Bigot...,A whole lot of evangelical Trump voters just d...,News,"November 13, 2016",0
1,"China backs U.N. call for justice in Yemen, U....",GENEVA (Reuters) - China signaled on Wednesday...,worldnews,"September 13, 2017",1
2,THE PEOPLE’S PRESIDENT: Trump Meets With Coal ...,,politics,"Feb 16, 2017",0
3,WSJ REPORTER RIPS INTO DEM CANDIDATES For Thei...,THE WSJ S MARY KISSEL NAILS IT ON THE DEM DEBA...,politics,"Nov 15, 2015",0
4,Lawmakers aim to delay U.S. ceding control of ...,WASHINGTON (Reuters) - Critics of a plan for t...,politicsNews,"September 13, 2016",1

In [7]:
df_clean = df_en.copy()

### Drop empty `text`:

In [8]:
empty_text_mask = (
    df_clean["text"]
    .astype(str)
    .str.strip()
    .eq("")
)

print("Empty texts before:", empty_text_mask.sum())

df_clean = df_clean.loc[
    ~empty_text_mask
].copy()

print("Shape after removing empty texts:", df_clean.shape)

Empty texts before: 66
Shape after removing empty texts: (5934, 5)

Aqui no hacemos `df_clean.dropna()` porque el problema detectado no se detectaba así en la fase EDA.

### Drop Duplicates:

In [9]:
print(
    "Duplicated texts before:",
    df_clean.duplicated(subset=["text"]).sum()
)

df_clean = (
    df_clean
    .drop_duplicates(
        subset=["text"],
        keep="first"
    )
    .copy()
)

print(
    "Duplicated texts after:",
    df_clean.duplicated(subset=["text"]).sum()
)

print("Shape:", df_clean.shape)

Duplicated texts before: 106
Duplicated texts after: 0
Shape: (5828, 5)

In [10]:
duplicate_titles_after_text_dedup = (
    df_clean
    .duplicated(subset=["title"])
    .sum()
)

print("Duplicated titles after text deduplicates:",
      duplicate_titles_after_text_dedup)

Duplicated titles after text deduplicates: 8

In [11]:
pd.set_option('display.max_colwidth',1000)

In [12]:
duplicated_titles = df_clean[
    df_clean["title"].duplicated(keep=False)
].sort_values("title")


display(
    duplicated_titles[
        ["title","text","label"]
    ]
)

,title,text,label
296,China hopes all sides' words and actions reduce tension on Korean peninsula,"BEIJING (Reuters) - China said on Monday that it hopes all sides words and actions can help reduce tensions on the Korean peninsula, after Japanese Prime Minister Shinzo Abe said Japan would shoot down North Korean missiles if necessary. Foreign Ministry spokeswoman Hua Chunying made the comment at a regular news briefing.",1
2269,China hopes all sides' words and actions reduce tension on Korean peninsula,"BEIJING (Reuters) - China said on Monday that it hopes all sides’ words and actions can help reduce tensions on the Korean peninsula, after Japanese Prime Minister Shinzo Abe said Japan would shoot down North Korean missiles if necessary. Foreign Ministry spokeswoman Hua Chunying made the comment at a regular news briefing.",1
2899,China urges North Korea not to go further in a 'dangerous direction',"UNITED NATIONS (Reuters) - China s foreign minister on Thursday called on North Korea not to go further in a dangerous direction with its nuclear program and said negotiations were the only way out of the crisis over Pyongyang s weapons development. Wang Yi also told the annual U.N. General Assembly China was committed to the denuclearization of the Korean Peninsula and there should be no new nuclear weapons north or south of the border, or elsewhere in Northeast Asia. He urged the United States to honor its four no commitment, an apparent reference to an Aug. 1 statement by U.S. Secretary of State Rex Tillerson, in which he said Washington did not seek the collapse or change of the North Korean government, accelerated reunification of the peninsula, or to send its military north of the border. We urge the DPRK not to go further along a dangerous direction, Wang said, referring to North Korea by the acronym of its official name, the Democratic People s Republic of Korea. A...",1
3409,China urges North Korea not to go further in a 'dangerous direction',"UNITED NATIONS (Reuters) - China’s foreign minister on Thursday called on North Korea not to go further in a “dangerous direction” with its nuclear program and said negotiations were the only way out of the crisis over Pyongyang’s weapons development. Wang Yi also told the annual U.N. General Assembly China was committed to the denuclearization of the Korean Peninsula and there should be no new nuclear weapons north or south of the border, or elsewhere in Northeast Asia. He urged the United States to honor its “four ‘no’ commitment,” an apparent reference to an Aug. 1 statement by U.S. Secretary of State Rex Tillerson, in which he said Washington did not seek the collapse or change of the North Korean government, accelerated reunification of the peninsula, or to send its military north of the border. “We urge the DPRK not to go further along a dangerous direction,” Wang said, referring to North Korea by the acronym of its official name, the Democratic People’s Republic of Korea. “A...",1
995,Ex-president George H.W. Bush moved to intensive care; wife hospitalized,"(Reuters) - Former U.S. President George H.W. Bush has been moved to an intensive-care unit at a Houston hospital with pneumonia and was stable and resting comfortably after doctors performed a procedure to clear his airway, his office said on Wednesday. His wife of 72 years, former first lady Barbara Bush, also was admitted to the same hospital on Wednesday as a precaution after experiencing fatigue and coughing, the office said in a statement. Bush, who at 92 is the nation’s oldest living ex-president, has been at Houston Methodist Hospital since Saturday after experiencing shortness of breath, family spokesman Jim McGrath said on Wednesday. Since then, Bush experienced an “acute respiratory problem stemming from pneumonia” and was sedated for the unspecified procedure, his office said. He will remain in the hospital’s intensive-care unit for observation, his office said. Bush and the 91-year-old former first lady marked their 72nd anniversary on Jan. 6. At a White House news con...",1
5603,Ex-president George H.W. Bush moved to intensive care; wife hospitalized,"(Reuters) - Former U.S. President George H.W. Bush has been moved to an intensive-care unit at a Houston hospital with pneumonia and was resting comfortably after doctors performed a procedure to clear his airway, his office said in a statement on Wednesday. His wife, former first lady Barbara Bush, also was admitted to the same hospital on Wednesday as a precaution after experiencing fatigue and coughing, the office said.",1
616,Factbox: Trump fills top jobs for his administration,"(Reuters) - U.S. President-elect Donald Trump is expected to pick Goldman Sachs executive Gary Cohn to head his White House National Economic Council, a group tasked with coordinating economic policy across federal agencies, a Trump transition official told Reuters on Friday. The following is a list of Republican Trump’s selections for top jobs in his administration. All the posts but that of national security adviser, the White House chief of staff, White House director of the National Economic Council and White House strategist require Senate confirmation: Sessions, 69, was the first U.S. senator to endorse Trump’s presidential bid and has been a close ally since. Son of a country-store owner, the Alabama senator and former federal prosecutor has long taken a tough stance on illegal immigration, opposing any path to citizenship for undocumented immigrants. U.S. Representative Pompeo, 52, is a third-term congressman from Kansas who serves on the House of Representatives Intellig...",1
5677,Factbox: Trump fills top jobs for his administration,"(Reuters) - U.S. President-elect Donald Trump on Wednesday announced he has chosen David Shulkin, who currently heads the Department of Veterans Affairs healthcare system, to head the agency. Here is a list of Republican Trump’s selections for top jobs in his administration. NOTE: Senate confirmation is required for all the posts except national security adviser and White House posts. Tillerson, 64, has spent his entire career at Exxon Mobil Corp, where he rose to chairman and chief executive officer in 2006. A civil engineer by training, the Texan joined the world’s largest publicly traded energy company in 1975 and led several of its operations in the United States as well as in Yemen, Thailand and Russia. As Exxon’s chief executive, he maintained close ties with Moscow and opposed U.S. sanctions against Russia for its incursion into Crimea. Mnuchin, 54, is a successful private equity investor, hedge fund manager and Hollywood financier who spent 17 years at Goldman Sachs Group ...",1
1266,Tillerson to visit Pakistan as well as India: senior U.S. official,"WASHINGTON (Reuters) - U.S. Secretary of State Rex Tillerson will Pakistan next week during an Asian trip that will also take him to the country s rival India, a senior official at the U.S. State Department said on Wednesday.",1
4277,Tillerson to visit Pakistan as well as India: senior U.S. official,"WASHINGTON (Reuters) - U.S. Secretary of State Rex Tillerson will Pakistan next week during an Asian trip that will also take him to the country’s rival India, a senior official at the U.S. State Department said on Wednesday.",1
4084,Trump's stop in Vietnam a poignant one for U.S. veterans,"DANANG, Vietnam (Reuters) - Whether they like President Donald Trump or not, the U.S. veterans who gather at Hoa s Place in Danang show little concern that he avoided the war that marked their lives. Trump flies into the Vietnamese resort of Danang on Friday for a summit of Asia-Pacific leaders, landing in a city that for many Americans of his generation was their first sight of Vietnam - and of war. He ll finally be able to put on his resume that he was in Vietnam, said David Clark, 68, who is originally from Akron, Ohio and calls Trump a joke . After serving in Vietnam from 1968 to 1969 with the Marine Corps, he has now returned to help with projects to address the legacy of the war. Trump never served in the military. He received five deferments during the Vietnam War, including one for bone spurs in his heel, the New York Times reported last year. The paper quoted Trump as saying the bones spurs had been temporary . Everyone I know tried to avoid it, said draftee Keit...",1
4136,Trump's stop in Vietnam a poignant one for U.S. veterans,"DANANG, Vietnam (Reuters) - Whether they like President Donald Trump or not, the U.S. veterans who gather at Hoa’s Place in Danang show little concern that he avoided the war that marked their lives. Trump flies into the Vietnamese resort of Danang on Friday for a summit of Asia-Pacific leaders, landing in a city that for many Americans of his generation was their first sight of Vietnam - and of war. “He’ll finally be able to put on his resume that he was in Vietnam,” said David Clark, 68, who is originally from Akron, Ohio and calls Trump “a joke”. After serving in Vietnam from 1968 to 1969 with the Marine Corps, he has now returned to help with projects to address the legacy of the war. Trump never served in the military. He received five deferments during the Vietnam War, including one for bone spurs in his heel, the New York Times reported last year. The paper quoted Trump as saying the bones spurs had been “temporary”. “Everyone I know tried to avoid it,” said draftee Keit...",1
2031,"Turkey urges U.S. to review visa suspension as lira, stocks tumble","ANKARA (Reuters) - Turkey urged the United States on Monday to review its suspension of visa services after the arrest of a U.S. consulate employee sharply escalated tension between the two NATO allies and drove Turkey s currency and stocks lower. Relations between Ankara and Washington have been plagued by disputes over U.S. support for Kurdish fighters in Syria, Turkey s calls for the extradition of a U.S.-based cleric and the indictment of a Turkish former minister in a U.S. court. But last week s arrest of a Turkish employee of the U.S. consulate in Istanbul marked a fresh low. Turkey said the employee had links to U.S.-based Muslim cleric Fethullah Gulen, blamed by Ankara for a failed military coup in July 2016. Gulen denies any connection with the coup. The U.S. embassy in Ankara condemned Ankara s charges as baseless and announced on Sunday night it was halting all non-immigrant visa services in Turkey while it reassessed Turkey s commitment to the security of its missions a...",1
5976,"Turkey urges U.S. to review visa suspension as lira, stocks tumble","ANKARA (Reuters) - Turkey urged the United States on Monday to review its suspension of visa services after the arrest of a U.S. consulate employee sharply escalated tension between the two NATO allies and drove Turkey’s currency and stocks lower. Relations between Ankara and Washington have been plagued by disputes over U.S. support for Kurdish fighters in Syria, Turkey’s calls for the extradition of a U.S.-based cleric and the indictment of a Turkish former minister in a U.S. court. But last week’s arrest of a Turkish employee of the U.S. consulate in Istanbul marked a fresh low. Turkey said the employee had links to U.S.-based Muslim cleric Fethullah Gulen, blamed by Ankara for a failed military coup in July 2016. Gulen denies any connection with the coup. The U.S. embassy in Ankara condemned Ankara’s charges as baseless and announced on Sunday night it was halting all non-immigrant visa services in Turkey while it reassessed Turkey’s commitment to the security of its missions a...",1
4595,U.S. 'making a lot of progress' on North Korea issue: Trump,"NEW YORK (Reuters) - President Donald Trump said on Thursday the United States was making progress on the North Korean issue, ahead of an expected sanctions announcement by Washington over Pyongyang’s ballistic and nuclear weapons program. “I think we’re making a lot of progress in a lot of ways,” Trump said before going into a meeting with South Korean President Moon Jae-in on the sidelines of the U.N. General Assembly.",1
5903,U.S. 'making a lot of progress' on North Korea issue: Trump,"NEW YORK (Reuters) - President Donald Trump said on Thursday the United States was making progress on the North Korean issue, ahead of an expected sanctions announcement by Washington over Pyongyang s ballistic and nuclear weapons program. I think we re making a lot of progress in a lot of ways, Trump said before going into a meeting with South Korean President Moon Jae-in on the sidelines of the U.N. General Assembly.",1

In [13]:
example_titles = duplicated_titles.iloc[0]["title"]

example = df_clean[
    df_clean["title"] == example_titles
][["title","text","label"]]

display(example)

,title,text,label
296,China hopes all sides' words and actions reduce tension on Korean peninsula,"BEIJING (Reuters) - China said on Monday that it hopes all sides words and actions can help reduce tensions on the Korean peninsula, after Japanese Prime Minister Shinzo Abe said Japan would shoot down North Korean missiles if necessary. Foreign Ministry spokeswoman Hua Chunying made the comment at a regular news briefing.",1
2269,China hopes all sides' words and actions reduce tension on Korean peninsula,"BEIJING (Reuters) - China said on Monday that it hopes all sides’ words and actions can help reduce tensions on the Korean peninsula, after Japanese Prime Minister Shinzo Abe said Japan would shoot down North Korean missiles if necessary. Foreign Ministry spokeswoman Hua Chunying made the comment at a regular news briefing.",1

In [14]:
texts = example["text"].tolist()

print("Same exact text", texts[0] == texts[1])
print("lenght text 1", len(texts[0]))
print("lenght text 2", len(texts[1]))

Same exact text False
lenght text 1 327
lenght text 2 327

### Check Class Distribution:

In [15]:
class_distribution = (
    df_clean["label"]
    .value_counts()
    .sort_index()
    .to_frame("count")
)

class_distribution["percentage"] = (
    class_distribution["count"]
    / len(df_clean)
    * 100
)

display(class_distribution)

       count  percentage
label
0       2833   48.610158
1       2995   51.389842

### Drop variables:

subject -> leakage <br>
date    -> sesgo temporal / metadata

In [16]:
df_model = df_clean[
    ["title", "text", "label"]
].copy()

In [17]:
df_model

,title,text,label
0,WATCH: Trump Just Told All The Anti-Gay Bigots And Mike Pence To Go F*ck Themselves,"A whole lot of evangelical Trump voters just discovered they got duped.By picking Mike Pence as his vice-president, Donald Trump sent a message to the LGBT community that their rights are in jeopardy of being rolled back.In fact, one of the reasons why so many conservative Christians tossed their alleged morality out the window to vote for him was precisely because they believed he would pass a constitutional amendment banning same-sex marriage or pack the courts with anti-gay bigots to strike down all the rulings in favor of marriage equality.But during his interview on 60 minutes with Leslie Stahl on Sunday night, Trump once again backed off another campaign promise. Do you support marriage equality? Stahl asked Trump. It s irrelevant because it s already settled, Trump replied. It s law. It was settled in the Supreme Court. I mean, it s done. When Stahl pointed out that Trump s Supreme Court nominees could reverse Obergefell v. Hodges, the case that made same-sex marriage...",0
1,"China backs U.N. call for justice in Yemen, U.S. and Saudis don't","GENEVA (Reuters) - China signaled on Wednesday it was willing to back an international inquiry into atrocities in Yemen, as demanded by the U.N. High Commissioner for Human Rights, but Saudi Arabia and the United States said they did not support the idea. For three years running U.N. human rights chief Zeid Ra ad al-Hussein has asked the 47 countries in the U.N. Human Rights Council to set up an independent investigation into Yemen s war, which has killed at least 10,000, destroyed the economy, led to a cholera epidemic and pushed millions to the brink of famine. Despite his pleas, they have twice supported a Saudi plan to let Yemen investigate by itself. On Wednesday, the Netherlands and Canada unveiled a draft resolution to establish an international commission of inquiry (COI) to ensure that perpetrators of violations and abuses, including those that may constitute war crimes and crimes against humanity, are held accountable . The three-page text was supported by many count...",1
3,WSJ REPORTER RIPS INTO DEM CANDIDATES For Their Lame Rhetoric On ISIS: “Remarkable displays of unintelligible garbage” [Video],"THE WSJ S MARY KISSEL NAILS IT ON THE DEM DEBATE WITH THE THREE CANDIDATES WHO WERE GIVING NO SOLUTIONS ON ISIS: It was one of the most remarkable displays of unintelligible garbage rhetoric that I have ever seen. Amen to that!Mary Kissel: The barbarians are at the gates. We ve seen attacks now from London to Madrid to Beirut to over the Sinai. It is time for American leadership. Hillary said this isn t America s fight. Look, Democrats are dangerously divorced from reality. Hillary says that. President Obama wants to close Gitmo. He said we contained these people. No, we haven t contained them. Bernie Sanders, who s leading in some polls, says the greatest challenge is climate change. What we need is American leadership and the majority of the American people understand we need to send troops back to the Middle East before this global disorder comes to our shores.Marie Bartiromo: I thought it was actually extraordinary, the debate last night. There was no real solution from any o...",0
4,Lawmakers aim to delay U.S. ceding control of Internet's management,"WASHINGTON (Reuters) - Critics of a plan for the U.S. government to cede control of the Internet’s technical management to other countries might succeed in delaying such a move in Congress, a senior lawmaker said on Tuesday. Senator John Thune, a senior Republican from South Dakota, told reporters lawmakers are “trying to work out ... what would be effective in terms of slowing this.” The U.S. Commerce Department oversees the Internet’s management largely because it was invented in the United States. Some Republican politicians, including Senator Ted Cruz of Texas, want to block the handover to global stakeholders, such as businesses, tech experts and public interest advocates. Opponents of the transition said it could stifle online freedom by giving voting rights to authoritarian governments. Tech companies, technical experts and academics have said the transition is overdue and necessary to keep the Internet open and globally oriented, and that the proposal includes safeguards ag...",1
6,"Trump STRANDED, In Full Panic As ANOTHER Performer Drops Out Of Inauguration (DETAILS)","President-elect Donald Trump has had trouble finding people to perform at his inauguration from the moment he won the election. While A-list artists have usually jumped at the opportunity to sing or play for a new President, celebrities have turned Trump down left and right. It s been a massive public embarrassment for Trump, even as his team uses bribery to get gigs and continues to fail.The humiliation is far from over. The VERY few acts that agreed to perform for Trump are now dwindling. The latest to pull out just days before Trump s big day is the B-Street Band, a Bruce Springsteen cover band. The cover band has just announced that, due to the backlash the group received since news broke that they would play for Trump, they are abandoning the gig.In an interview with Rolling Stone, Will Forte, the group s keyboardist, manager, agent and publicist, said that the band received thousands of emails that made the band reconsider. He recalled saying to his band members, We re sta...",0
...,...,...,...
5995,Exiled Venezuelan opposition magistrates resurface in Chile,"SANTIAGO (Reuters) - A group of opposition-appointed Venezuelan judges arrived on Thursday in Chile as exiles after more than two months holed up at the Chilean ambassador s residence in Caracas to avoid arrest in the crisis-hit country. Chile s Foreign Ministry had granted the five parallel magistrates asylum in August. Threatened with jail by Venezuelan President Nicolas Maduro, they remained in Venezuela until last week, when they said they fled the country. Four of the five resurfaced in Santiago on Thursday morning. Another is expected to arrive later in the day. All we can say today is that we were forced to abandon our beloved home of Venezuela, but that another nation has embraced us, and will protect our freedom, Beatriz Ruiz, one of the five, told reporters at Santiago airport. Ruiz is one of 33 unofficial magistrates who were threatened with jail by Maduro after the opposition-led National Assembly appointed them in July to challenge the country s Supreme Court, which...",1
5996,Plague outbreak in Madagascar kills 20: WHO,"NAIROBI (Reuters) - An outbreak of plague has killed 20 people in the space of a month in Madagascar, with a further 84 infected, the World Health Organisation (WHO) said on Friday. Plague is mainly spread by flea-carrying rats. Humans bitten by an infected flea usually develop a bubonic form of plague, which swells lymph nodes and can be treated with antibiotics. But the more dangerous pneumonic form invades the lungs and can kill a person within 24 hours if not treated. About half of the 104 known cases are pneumonic, the WHO said. WHO spokesman Tarik Jasarevic told reporters in Geneva that areas affected included the capital Antananarivo and the port cities of Mahajenga and Toamasina. The U.N. health agency said it feared that the outbreak could worsen because the season for plague, which is endemic in Madagascar, had only just begun, and runs until April. On average, 400 cases are reported each year. The overall risk of further spread at the national level is high, WHO said ...",1
5997,"Trump to visit Asia in November, North Korea in spotlight","WASHINGTON (Reuters) - Donald Trump will travel to Asia in November for the first time since becoming president, stopping in Japan, South Korea, China, Vietnam and the Philippines on a trip expected to be dominated by the North Korea nuclear threat. Joined by his wife Melania, Trump will travel Nov. 3-14. His visit will include attending two major summits, the Asia-Pacific Economic Cooperation forum in Vietnam and the Association of Southeast Asian Nations conclave in the Philippines. Trump s attendance at the Manila summit had been in doubt until recent days, with officials saying he was reluctant to show support for Philippine President Rodrigo Duterte, who has been responsible for a number of anti-American outbursts. A U.S. official said Asian leaders who met Trump at the United Nations General Assembly in New York last week helped persuade him to attend in unity with key Asian allies. An Asian diplomat welcomed Trump s decision to visit Manila because that reassures the regio...",1
5998,Melania Trump calls taped comments by Donald Trump 'boy talk',"(Reuters) - Melania Trump rose to her husband’s defense on Monday, describing lewd comments the Republican presidential nominee made on a leaked 2005 video in which he bragged about groping women as “boy talk.” Trump, who has kept a low profile during her husband’s presidential bid, gave her first television interviews since the Oct. 7 release of the tape that has shaken Donald Trump’s campaign. He trails Democrat Hillary Clinton in opinion polls ahead of the Nov. 8 election. Melania Trump told CNN her husband was engaged in “boy talk, and he was led on - like, egged on - from the host to say dirty and bad stuff” in the conversation with “Access Hollywood” host Billy Bush. NBC said on Monday that Bush was leaving the “Today” show, following his role in the taped conversation with Donald Trump. Melania Trump, a Slovenian-born former model, added in a CNN interview that aired on Monday night that she was surprised because she had never heard her husband use that kind of languag...",1
5999,"#BoycottPenzeys: HATEFUL, DIVISIVE Penzeys Spice Co. Owner Threatens Trump Supporters…Brags About Increased Sales Since Calling All Trump Supporters “Racists”","Bill Penzey, the owner of Penzeys Spices, wrote two separate letters on the Penzeys Spices Facebook page, accusing all Trump s voters of openly embracing racism. Isn t it funny how liberals think they can use the most hateful and divisive language against fellow Americans, then excuse their open hate as an act of love or unity? We re asking Trump supporters and anyone who disagrees with a company owner calling half of America racists to BOYCOTT Penzeys Spices. (List of states where Penzeys Spice stores are located can be found below)Here is an excerpt from his first letter:Please give us a moment to share something we hope you will find very valuable.Our customers come from all walks of life. The kindness of cooks knows no borders or divides. In the aftermath of the election, seeing the intentional damage inflicted on so many outside the white heterosexual male world, we raised our voice. We felt we had to. We did this because we are Penzeys. The Spice business is so intertwine...",0

### Preprocessing:

In [18]:
def normalize_text(text):
    if pd.isna(text):
        return ""

    text = str(text).strip()
    text = re.sub(r"\s+", " ", text)

    return text

In [19]:
def build_model_text(title, text):
    title = normalize_text(title)
    text = normalize_text(text)

    if not text:
        raise ValueError("Article body is required.")

    if title:
        return f"{title}. {text}"

    return text

In [20]:
df_model["content"] = df_model.apply(
    lambda row: build_model_text(
        row["title"],
        row["text"]
    ),
    axis=1
)

In [21]:
df_model

,title,text,label,content
0,WATCH: Trump Just Told All The Anti-Gay Bigots And Mike Pence To Go F*ck Themselves,"A whole lot of evangelical Trump voters just discovered they got duped.By picking Mike Pence as his vice-president, Donald Trump sent a message to the LGBT community that their rights are in jeopardy of being rolled back.In fact, one of the reasons why so many conservative Christians tossed their alleged morality out the window to vote for him was precisely because they believed he would pass a constitutional amendment banning same-sex marriage or pack the courts with anti-gay bigots to strike down all the rulings in favor of marriage equality.But during his interview on 60 minutes with Leslie Stahl on Sunday night, Trump once again backed off another campaign promise. Do you support marriage equality? Stahl asked Trump. It s irrelevant because it s already settled, Trump replied. It s law. It was settled in the Supreme Court. I mean, it s done. When Stahl pointed out that Trump s Supreme Court nominees could reverse Obergefell v. Hodges, the case that made same-sex marriage...",0,"WATCH: Trump Just Told All The Anti-Gay Bigots And Mike Pence To Go F*ck Themselves. A whole lot of evangelical Trump voters just discovered they got duped.By picking Mike Pence as his vice-president, Donald Trump sent a message to the LGBT community that their rights are in jeopardy of being rolled back.In fact, one of the reasons why so many conservative Christians tossed their alleged morality out the window to vote for him was precisely because they believed he would pass a constitutional amendment banning same-sex marriage or pack the courts with anti-gay bigots to strike down all the rulings in favor of marriage equality.But during his interview on 60 minutes with Leslie Stahl on Sunday night, Trump once again backed off another campaign promise. Do you support marriage equality? Stahl asked Trump. It s irrelevant because it s already settled, Trump replied. It s law. It was settled in the Supreme Court. I mean, it s done. When Stahl pointed out that Trump s Supreme Court nom..."
1,"China backs U.N. call for justice in Yemen, U.S. and Saudis don't","GENEVA (Reuters) - China signaled on Wednesday it was willing to back an international inquiry into atrocities in Yemen, as demanded by the U.N. High Commissioner for Human Rights, but Saudi Arabia and the United States said they did not support the idea. For three years running U.N. human rights chief Zeid Ra ad al-Hussein has asked the 47 countries in the U.N. Human Rights Council to set up an independent investigation into Yemen s war, which has killed at least 10,000, destroyed the economy, led to a cholera epidemic and pushed millions to the brink of famine. Despite his pleas, they have twice supported a Saudi plan to let Yemen investigate by itself. On Wednesday, the Netherlands and Canada unveiled a draft resolution to establish an international commission of inquiry (COI) to ensure that perpetrators of violations and abuses, including those that may constitute war crimes and crimes against humanity, are held accountable . The three-page text was supported by many count...",1,"China backs U.N. call for justice in Yemen, U.S. and Saudis don't. GENEVA (Reuters) - China signaled on Wednesday it was willing to back an international inquiry into atrocities in Yemen, as demanded by the U.N. High Commissioner for Human Rights, but Saudi Arabia and the United States said they did not support the idea. For three years running U.N. human rights chief Zeid Ra ad al-Hussein has asked the 47 countries in the U.N. Human Rights Council to set up an independent investigation into Yemen s war, which has killed at least 10,000, destroyed the economy, led to a cholera epidemic and pushed millions to the brink of famine. Despite his pleas, they have twice supported a Saudi plan to let Yemen investigate by itself. On Wednesday, the Netherlands and Canada unveiled a draft resolution to establish an international commission of inquiry (COI) to ensure that perpetrators of violations and abuses, including those that may constitute war crimes and crimes against humanity, are held..."
3,WSJ REPORTER RIPS INTO DEM CANDIDATES For Their Lame Rhetoric On ISIS: “Remarkable displays of unintelligible garbage” [Video],"THE WSJ S MARY KISSEL NAILS IT ON THE DEM DEBATE WITH THE THREE CANDIDATES WHO WERE GIVING NO SOLUTIONS ON ISIS: It was one of the most remarkable displays of unintelligible garbage rhetoric that I have ever seen. Amen to that!Mary Kissel: The barbarians are at the gates. We ve seen attacks now from London to Madrid to Beirut to over the Sinai. It is time for American leadership. Hillary said this isn t America s fight. Look, Democrats are dangerously divorced from reality. Hillary says that. President Obama wants to close Gitmo. He said we contained these people. No, we haven t contained them. Bernie Sanders, who s leading in some polls, says the greatest challenge is climate change. What we need is American leadership and the majority of the American people understand we need to send troops back to the Middle East before this global disorder comes to our shores.Marie Bartiromo: I thought it was actually extraordinary, the debate last night. There was no real solution from any o...",0,"WSJ REPORTER RIPS INTO DEM CANDIDATES For Their Lame Rhetoric On ISIS: “Remarkable displays of unintelligible garbage” [Video]. THE WSJ S MARY KISSEL NAILS IT ON THE DEM DEBATE WITH THE THREE CANDIDATES WHO WERE GIVING NO SOLUTIONS ON ISIS: It was one of the most remarkable displays of unintelligible garbage rhetoric that I have ever seen. Amen to that!Mary Kissel: The barbarians are at the gates. We ve seen attacks now from London to Madrid to Beirut to over the Sinai. It is time for American leadership. Hillary said this isn t America s fight. Look, Democrats are dangerously divorced from reality. Hillary says that. President Obama wants to close Gitmo. He said we contained these people. No, we haven t contained them. Bernie Sanders, who s leading in some polls, says the greatest challenge is climate change. What we need is American leadership and the majority of the American people understand we need to send troops back to the Middle East before this global disorder comes to our..."
4,Lawmakers aim to delay U.S. ceding control of Internet's management,"WASHINGTON (Reuters) - Critics of a plan for the U.S. government to cede control of the Internet’s technical management to other countries might succeed in delaying such a move in Congress, a senior lawmaker said on Tuesday. Senator John Thune, a senior Republican from South Dakota, told reporters lawmakers are “trying to work out ... what would be effective in terms of slowing this.” The U.S. Commerce Department oversees the Internet’s management largely because it was invented in the United States. Some Republican politicians, including Senator Ted Cruz of Texas, want to block the handover to global stakeholders, such as businesses, tech experts and public interest advocates. Opponents of the transition said it could stifle online freedom by giving voting rights to authoritarian governments. Tech companies, technical experts and academics have said the transition is overdue and necessary to keep the Internet open and globally oriented, and that the proposal includes safeguards ag...",1,"Lawmakers aim to delay U.S. ceding control of Internet's management. WASHINGTON (Reuters) - Critics of a plan for the U.S. government to cede control of the Internet’s technical management to other countries might succeed in delaying such a move in Congress, a senior lawmaker said on Tuesday. Senator John Thune, a senior Republican from South Dakota, told reporters lawmakers are “trying to work out ... what would be effective in terms of slowing this.” The U.S. Commerce Department oversees the Internet’s management largely because it was invented in the United States. Some Republican politicians, including Senator Ted Cruz of Texas, want to block the handover to global stakeholders, such as businesses, tech experts and public interest advocates. Opponents of the transition said it could stifle online freedom by giving voting rights to authoritarian governments. Tech companies, technical experts and academics have said the transition is overdue and necessary to keep the Internet ope..."
6,"Trump STRANDED, In Full Panic As ANOTHER Performer Drops Out Of Inauguration (DETAILS)","President-elect Donald Trump has had trouble finding people to perform at his inauguration from the moment he won the election. While A-list artists have usually jumped at the opportunity to sing or play for a new President, celebrities have turned Trump down left and right. It s been a massive public embarrassment for Trump, even as his team uses bribery to get gigs and continues to fail.The humiliation is far from over. The VERY few acts that agreed to perform for Trump are now dwindling. The latest to pull out just days before Trump s big day is the B-Street Band, a Bruce Springsteen cover band. The cover band has just announced that, due to the backlash the group received since news broke that they would play for Trump, they are abandoning the gig.In an interview with Rolling Stone, Will Forte, the group s keyboardist, manager, agent and publicist, said that the band received thousands of emails that made the band reconsider. He recalled saying to his band members, We re sta...",0,"Trump STRANDED, In Full Panic As ANOTHER Performer Drops Out Of Inauguration (DETAILS). President-elect Donald Trump has had trouble finding people to perform at his inauguration from the moment he won the election. While A-list artists have usually jumped at the opportunity to sing or play for a new President, celebrities have turned Trump down left and right. It s been a massive public embarrassment for Trump, even as his team uses bribery to get gigs and continues to fail.The humiliation is far from over. The VERY few acts that agreed to perform for Trump are now dwindling. The latest to pull out just days before Trump s big day is the B-Street Band, a Bruce Springsteen cover band. The cover band has just announced that, due to the backlash the group received since news broke that they would play for Trump, they are abandoning the gig.In an interview with Rolling Stone, Will Forte, the group s keyboardist, manager, agent and publicist, said that the band received thousands of em..."
...,...,...,...,...
5995,Exiled Venezuelan opposition magistrates resurface in Chile,"SANTIAGO (Reuters) - A group of opposition-appointed Venezuelan judges arrived on Thursday in Chile as exiles after more than two months holed up at the Chilean ambassador s residence in Caracas to avoid arrest in the crisis-hit country. Chile s Foreign Ministry had granted the five parallel magistrates asylum in August. Threatened with jail by Venezuelan President Nicolas Maduro, they remained in Venezuela until last week, when they said they fled the country. Four of the five resurfaced in Santiago on Thursday morning. Another is expected to arrive later in the day. All we can say today is that we were forced to abandon our beloved home of Venezuela, but that another nation has embraced us, and will protect our freedom, Beatriz Ruiz, one of the five, told reporters at Santiago airport. Ruiz is one of 33 unofficial magistrates who were threatened with jail by Maduro after the opposition-led National Assembly appointed them in July to challenge the country s Supreme Court, which...",1,"Exiled Venezuelan opposition magistrates resurface in Chile. SANTIAGO (Reuters) - A group of opposition-appointed Venezuelan judges arrived on Thursday in Chile as exiles after more than two months holed up at the Chilean ambassador s residence in Caracas to avoid arrest in the crisis-hit country. Chile s Foreign Ministry had granted the five parallel magistrates asylum in August. Threatened with jail by Venezuelan President Nicolas Maduro, they remained in Venezuela until last week, when they said they fled the country. Four of the five resurfaced in Santiago on Thursday morning. Another is expected to arrive later in the day. All we can say today is that we were forced to abandon our beloved home of Venezuela, but that another nation has embraced us, and will protect our freedom, Beatriz Ruiz, one of the five, told reporters at Santiago airport. Ruiz is one of 33 unofficial magistrates who were threatened with jail by Maduro after the opposition-led National Assembly appointed th..."
5996,Plague outbreak in Madagascar kills 20: WHO,"NAIROBI (Reuters) - An outbreak of plague has killed 20 people in the space of a month in Madagascar, with a further 84 infected, the World Health Organisation (WHO) said on Friday. Plague is mainly spread by flea-carrying rats. Humans bitten by an infected flea usually develop a bubonic form of plague, which swells lymph nodes and can be treated with antibiotics. But the more dangerous pneumonic form invades the lungs and can kill a person within 24 hours if not treated. About half of the 104 known cases are pneumonic, the WHO said. WHO spokesman Tarik Jasarevic told reporters in Geneva that areas affected included the capital Antananarivo and the port cities of Mahajenga and Toamasina. The U.N. health agency said it feared that the outbreak could worsen because the season for plague, which is endemic in Madagascar, had only just begun, and runs until April. On average, 400 cases are reported each year. The overall risk of further spread at the national level is high, WHO said ...",1,"Plague outbreak in Madagascar kills 20: WHO. NAIROBI (Reuters) - An outbreak of plague has killed 20 people in the space of a month in Madagascar, with a further 84 infected, the World Health Organisation (WHO) said on Friday. Plague is mainly spread by flea-carrying rats. Humans bitten by an infected flea usually develop a bubonic form of plague, which swells lymph nodes and can be treated with antibiotics. But the more dangerous pneumonic form invades the lungs and can kill a person within 24 hours if not treated. About half of the 104 known cases are pneumonic, the WHO said. WHO spokesman Tarik Jasarevic told reporters in Geneva that areas affected included the capital Antananarivo and the port cities of Mahajenga and Toamasina. The U.N. health agency said it feared that the outbreak could worsen because the season for plague, which is endemic in Madagascar, had only just begun, and runs until April. On average, 400 cases are reported each year. The overall risk of further sprea..."
5997,"Trump to visit Asia in November, North Korea in spotlight","WASHINGTON (Reuters) - Donald Trump will travel to Asia in November for the first time since becoming president, stopping in Japan, South Korea, China, Vietnam and the Philippines on a trip expected to be dominated by the North Korea nuclear threat. Joined by his wife Melania, Trump will travel Nov. 3-14. His visit will include attending two major summits, the Asia-Pacific Economic Cooperation forum in Vietnam and the Association of Southeast Asian Nations conclave in the Philippines. Trump s attendance at the Manila summit had been in doubt until recent days, with officials saying he was reluctant to show support for Philippine President Rodrigo Duterte, who has been responsible for a number of anti-American outbursts. A U.S. official said Asian leaders who met Trump at the United Nations General Assembly in New York last week helped persuade him to attend in unity with key Asian allies. An Asian diplomat welcomed Trump s decision to visit Manila because that reassures the regio...",1,"Trump to visit Asia in November, North Korea in spotlight. WASHINGTON (Reuters) - Donald Trump will travel to Asia in November for the first time since becoming president, stopping in Japan, South Korea, China, Vietnam and the Philippines on a trip expected to be dominated by the North Korea nuclear threat. Joined by his wife Melania, Trump will travel Nov. 3-14. His visit will include attending two major summits, the Asia-Pacific Economic Cooperation forum in Vietnam and the Association of Southeast Asian Nations conclave in the Philippines. Trump s attendance at the Manila summit had been in doubt until recent days, with officials saying he was reluctant to show support for Philippine President Rodrigo Duterte, who has been responsible for a number of anti-American outbursts. A U.S. official said Asian leaders who met Trump at the United Nations General Assembly in New York last week helped persuade him to attend in unity with key Asian allies. An Asian diplomat welcomed Trump s ..."
5998,Melania Trump calls taped comments by Donald Trump 'boy talk',"(Reuters) - Melania Trump rose to her husband’s defense on Monday, describing lewd comments the Republican presidential nominee made on a leaked 2005 video in which he bragged about groping women as “boy talk.” Trump, who has kept a low profile during her husband’s presidential bid, gave her first television interviews since the Oct. 7 release of the tape that has shaken Donald Trump’s campaign. He trails Democrat Hillary Clinton in opinion polls ahead of the Nov. 8 election. Melania Trump told CNN her husband was engaged in “boy talk, and he was led on - like, egged on - from the host to say dirty and bad stuff” in the conversation with “Access Hollywood” host Billy Bush. NBC said on Monday that Bush was leaving the “Today” show, following his role in the taped conversation with Donald Trump. Melania Trump, a Slovenian-born former model, added in a CNN interview that aired on Monday night that she was surprised because she had never heard her husband use that kind of languag...",1,"Melania Trump calls taped comments by Donald Trump 'boy talk'. (Reuters) - Melania Trump rose to her husband’s defense on Monday, describing lewd comments the Republican presidential nominee made on a leaked 2005 video in which he bragged about groping women as “boy talk.” Trump, who has kept a low profile during her husband’s presidential bid, gave her first television interviews since the Oct. 7 release of the tape that has shaken Donald Trump’s campaign. He trails Democrat Hillary Clinton in opinion polls ahead of the Nov. 8 election. Melania Trump told CNN her husband was engaged in “boy talk, and he was led on - like, egged on - from the host to say dirty and bad stuff” in the conversation with “Access Hollywood” host Billy Bush. NBC said on Monday that Bush was leaving the “Today” show, following his role in the taped conversation with Donald Trump. Melania Trump, a Slovenian-born former model, added in a CNN interview that aired on Monday night that she was surprised because..."

In [ ]:
df_model[["title", "text", "content", "label"]].to_csv("../Data/ml/processed_data_en.csv", index=False)