### Importación de librerías necesárias:

In [88]:
import warnings
warnings.filterwarnings('ignore')

from pathlib import Path
import json
import zipfile
import faiss
import pandas as pd
import numpy as np
from collections import Counter
from datasets import load_dataset
from huggingface_hub import hf_hub_download
from huggingface_hub import list_repo_files

from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from typing import Literal
from pydantic import BaseModel


from dotenv import load_dotenv
from openai import OpenAI

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix,
)

In [3]:
DATA_DIR = Path("../Data/averitec")

RAW_DIR = DATA_DIR / "raw"
CLAIMS_DIR = RAW_DIR / "claims"
KNOWLEDGE_DIR = RAW_DIR / "knowledge_store"

PROCESSED_DIR = DATA_DIR / "processed"

CLAIMS_DIR.mkdir(parents=True, exist_ok=True)
KNOWLEDGE_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

### 1. Descargamos Claims:

In [4]:
averitec = load_dataset(
    "pminervini/averitec"
)

averitec

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

DatasetDict({
    train: Dataset({
        features: ['cached_original_claim_url', 'speaker', 'required_reannotation', 'reporting_source', 'label', 'claim_types', 'fact_checking_article', 'fact_checking_strategies', 'claim', 'justification', 'location_ISO_code', 'original_claim_url', 'questions', 'claim_date'],
        num_rows: 3068
    })
    dev: Dataset({
        features: ['cached_original_claim_url', 'speaker', 'required_reannotation', 'reporting_source', 'label', 'claim_types', 'fact_checking_article', 'fact_checking_strategies', 'claim', 'justification', 'location_ISO_code', 'original_claim_url', 'questions', 'claim_date'],
        num_rows: 500
    })
})

In [5]:
print(averitec["train"])
print(averitec["dev"])

Dataset({
    features: ['cached_original_claim_url', 'speaker', 'required_reannotation', 'reporting_source', 'label', 'claim_types', 'fact_checking_article', 'fact_checking_strategies', 'claim', 'justification', 'location_ISO_code', 'original_claim_url', 'questions', 'claim_date'],
    num_rows: 3068
})
Dataset({
    features: ['cached_original_claim_url', 'speaker', 'required_reannotation', 'reporting_source', 'label', 'claim_types', 'fact_checking_article', 'fact_checking_strategies', 'claim', 'justification', 'location_ISO_code', 'original_claim_url', 'questions', 'claim_date'],
    num_rows: 500
})

### Inspeccionando Claims

In [6]:
sample_claim = averitec["dev"][0]

# sample_claim
# sample_claim.keys()

### Guardando Claims - Averitec

In [7]:
train_df = averitec["train"].to_pandas()
dev_df = averitec["dev"].to_pandas()

In [7]:
len(train_df)
len(dev_df)

500

In [ ]:
train_df.to_json(
    CLAIMS_DIR / "train.json",
    orient="records",
    force_ascii=False,
    indent=2
)

dev_df.to_json(
    CLAIMS_DIR / "dev.json",
    orient="records",
    force_ascii=False,
    indent=2
)

### 2. Preparar AVeriTeC claims para retrieval experiments

In [8]:
train_sample = averitec["train"].select(range(5))

train_sample

Dataset({
    features: ['cached_original_claim_url', 'speaker', 'required_reannotation', 'reporting_source', 'label', 'claim_types', 'fact_checking_article', 'fact_checking_strategies', 'claim', 'justification', 'location_ISO_code', 'original_claim_url', 'questions', 'claim_date'],
    num_rows: 5
})

In [9]:
for i, item in enumerate(train_sample):
    print(f"\n--- CLAIM {i} ---")
    print("Claim:", item["claim"])
    print("Date:", item["claim_date"])
    print("Speaker:", item["speaker"])
    print("Reporting source:", item["reporting_source"])
    print("Gold label:", item["label"])

--- CLAIM 0 ---
Claim: Hunter Biden had no experience in Ukraine or in the energy sector when he joined the board of Burisma.
Date: 25-8-2020
Speaker: Pam Bondi
Reporting source: Speech at The Republican National Convention
Gold label: Supported

--- CLAIM 1 ---
Claim: Donald Trump delivered the largest tax cuts in American history.
Date: 25-8-2020
Speaker: Eric Trump
Reporting source: Speech at The Republican National Convention
Gold label: Refuted

--- CLAIM 2 ---
Claim: In Nigeria … in terms of revenue share, 20% goes to the local government.
Date: 25-8-2020
Speaker: Raila Odinga
Reporting source: YouTube
Gold label: Supported

--- CLAIM 3 ---
Claim: Biden has pledged to stop border wall construction and give amnesty and health care to all illegal immigrants.
Date: 25-8-2020
Speaker: Eric Trump
Reporting source: Speech at The Republican National Convention
Gold label: Supported

--- CLAIM 4 ---
Claim: After the police shooting of Jacob Blake, Gov. Tony Evers & Lt. Gov. Mandela Barnes did not call for peace or encourage calm.
Date: 25-8-2020
Speaker: Senator Howard Marklein
Reporting source: Facebook
Gold label: Refuted

Aquí el Gold label lo mostramos solo para inspeccionar el dataset, no porque vaya a entrar al sistema.

### 3. Download AVeriTeC knowledge store

### Knowledge Store

In [9]:
AVerITEC_REPO = "chenxwh/AVeriTeC"

DEV_KNOWLEDGE_FILE = (
    "data_store/knowledge_store/"
    "dev_knowledge_store.zip"
)

In [10]:
repo_files = list_repo_files(
    repo_id="chenxwh/AVeriTeC"
)

knowledge_files = [
    f for f in repo_files
    if "knowledge_store" in f
]

print(len(knowledge_files))

for f in knowledge_files[:len(knowledge_files)]:
    print(f)

16
data_store/knowledge_store/dev_knowledge_store.zip
data_store/knowledge_store/test/test_0_499.zip
data_store/knowledge_store/test/test_1000_1499.zip
data_store/knowledge_store/test/test_1500_1999.zip
data_store/knowledge_store/test/test_2000_2214.zip
data_store/knowledge_store/test/test_500_999.zip
data_store/knowledge_store/test_updated/output_test_0_499.zip
data_store/knowledge_store/test_updated/output_test_1000_1499.zip
data_store/knowledge_store/test_updated/output_test_1500_1999.zip
data_store/knowledge_store/test_updated/output_test_2000_2214.zip
data_store/knowledge_store/test_updated/output_test_500_999.zip
data_store/knowledge_store/test_updated/readme.md
data_store/knowledge_store/train/train_0_999.zip
data_store/knowledge_store/train/train_1000_1999.zip
data_store/knowledge_store/train/train_2000_3067.zip
src/retrieval/scraper_for_knowledge_store.py

In [ ]:
# knowledge_zip = hf_hub_download(
#     repo_id="chenxwh/AVeriTeC",
#     filename="data_store/knowledge_store/dev_knowledge_store.zip",
#     local_dir=KNOWLEDGE_DIR
# )

### 4. Download a subset of the AVeriTeC train knowledge store

In [11]:
TRAIN_KNOWLEDGE_FILE = (
    "data_store/knowledge_store/train/"
    "train_0_999.zip"
)

knowledge_zip = hf_hub_download(
    repo_id="chenxwh/AVeriTeC",
    filename=TRAIN_KNOWLEDGE_FILE,
    local_dir=KNOWLEDGE_DIR
)

print(knowledge_zip)

C:\Users\natal\OneDrive\Documentos\UCM - Big data, ML and IA\MODULOS\TFM\TFM_Natalia_De_Oliveira_AgenteFakeNews\Data\averitec\raw\knowledge_store\data_store\knowledge_store\train\train_0_999.zip

In [12]:
knowledge_zip = Path(knowledge_zip)

print("Exists:", knowledge_zip.exists())
print("File:", knowledge_zip.name)
print(
    "Size MB:",
    round(knowledge_zip.stat().st_size / 1024**2, 2)
)

Exists: True
File: train_0_999.zip
Size MB: 19769.99

In [13]:
with zipfile.ZipFile(knowledge_zip, "r") as zip_ref:
    names = zip_ref.namelist()

print("Files in ZIP:", len(names))

for name in names[:len(names)]:
    print(name)

Files in ZIP: 1000
0.json
1.json
2.json
3.json
4.json
5.json
6.json
7.json
8.json
9.json
10.json
11.json
12.json
13.json
14.json
15.json
16.json
17.json
18.json
19.json
20.json
21.json
22.json
23.json
24.json
25.json
26.json
27.json
28.json
29.json
30.json
31.json
32.json
33.json
34.json
35.json
36.json
37.json
38.json
39.json
40.json
41.json
42.json
43.json
44.json
45.json
46.json
47.json
48.json
49.json
50.json
51.json
52.json
53.json
54.json
55.json
56.json
57.json
58.json
59.json
60.json
61.json
62.json
63.json
64.json
65.json
66.json
67.json
68.json
69.json
70.json
71.json
72.json
73.json
74.json
75.json
76.json
77.json
78.json
79.json
80.json
81.json
82.json
83.json
84.json
85.json
86.json
87.json
88.json
89.json
90.json
91.json
92.json
93.json
94.json
95.json
96.json
97.json
98.json
99.json
100.json
101.json
102.json
103.json
104.json
105.json
106.json
107.json
108.json
109.json
110.json
111.json
112.json
113.json
114.json
115.json
116.json
117.json
118.json
119.json
120.json
121.json
122.json
123.json
124.json
125.json
126.json
127.json
128.json
129.json
130.json
131.json
132.json
133.json
134.json
135.json
136.json
137.json
138.json
139.json
140.json
141.json
142.json
143.json
144.json
145.json
146.json
147.json
148.json
149.json
150.json
151.json
152.json
153.json
154.json
155.json
156.json
157.json
158.json
159.json
160.json
161.json
162.json
163.json
164.json
165.json
166.json
167.json
168.json
169.json
170.json
171.json
172.json
173.json
174.json
175.json
176.json
177.json
178.json
179.json
180.json
181.json
182.json
183.json
184.json
185.json
186.json
187.json
188.json
189.json
190.json
191.json
192.json
193.json
194.json
195.json
196.json
197.json
198.json
199.json
200.json
201.json
202.json
203.json
204.json
205.json
206.json
207.json
208.json
209.json
210.json
211.json
212.json
213.json
214.json
215.json
216.json
217.json
218.json
219.json
220.json
221.json
222.json
223.json
224.json
225.json
226.json
227.json
228.json
229.json
230.json
231.json
232.json
233.json
234.json
235.json
236.json
237.json
238.json
239.json
240.json
241.json
242.json
243.json
244.json
245.json
246.json
247.json
248.json
249.json
250.json
251.json
252.json
253.json
254.json
255.json
256.json
257.json
258.json
259.json
260.json
261.json
262.json
263.json
264.json
265.json
266.json
267.json
268.json
269.json
270.json
271.json
272.json
273.json
274.json
275.json
276.json
277.json
278.json
279.json
280.json
281.json
282.json
283.json
284.json
285.json
286.json
287.json
288.json
289.json
290.json
291.json
292.json
293.json
294.json
295.json
296.json
297.json
298.json
299.json
300.json
301.json
302.json
303.json
304.json
305.json
306.json
307.json
308.json
309.json
310.json
311.json
312.json
313.json
314.json
315.json
316.json
317.json
318.json
319.json
320.json
321.json
322.json
323.json
324.json
325.json
326.json
327.json
328.json
329.json
330.json
331.json
332.json
333.json
334.json
335.json
336.json
337.json
338.json
339.json
340.json
341.json
342.json
343.json
344.json
345.json
346.json
347.json
348.json
349.json
350.json
351.json
352.json
353.json
354.json
355.json
356.json
357.json
358.json
359.json
360.json
361.json
362.json
363.json
364.json
365.json
366.json
367.json
368.json
369.json
370.json
371.json
372.json
373.json
374.json
375.json
376.json
377.json
378.json
379.json
380.json
381.json
382.json
383.json
384.json
385.json
386.json
387.json
388.json
389.json
390.json
391.json
392.json
393.json
394.json
395.json
396.json
397.json
398.json
399.json
400.json
401.json
402.json
403.json
404.json
405.json
406.json
407.json
408.json
409.json
410.json
411.json
412.json
413.json
414.json
415.json
416.json
417.json
418.json
419.json
420.json
421.json
422.json
423.json
424.json
425.json
426.json
427.json
428.json
429.json
430.json
431.json
432.json
433.json
434.json
435.json
436.json
437.json
438.json
439.json
440.json
441.json
442.json
443.json
444.json
445.json
446.json
447.json
448.json
449.json
450.json
451.json
452.json
453.json
454.json
455.json
456.json
457.json
458.json
459.json
460.json
461.json
462.json
463.json
464.json
465.json
466.json
467.json
468.json
469.json
470.json
471.json
472.json
473.json
474.json
475.json
476.json
477.json
478.json
479.json
480.json
481.json
482.json
483.json
484.json
485.json
486.json
487.json
488.json
489.json
490.json
491.json
492.json
493.json
494.json
495.json
496.json
497.json
498.json
499.json
500.json
501.json
502.json
503.json
504.json
505.json
506.json
507.json
508.json
509.json
510.json
511.json
512.json
513.json
514.json
515.json
516.json
517.json
518.json
519.json
520.json
521.json
522.json
523.json
524.json
525.json
526.json
527.json
528.json
529.json
530.json
531.json
532.json
533.json
534.json
535.json
536.json
537.json
538.json
539.json
540.json
541.json
542.json
543.json
544.json
545.json
546.json
547.json
548.json
549.json
550.json
551.json
552.json
553.json
554.json
555.json
556.json
557.json
558.json
559.json
560.json
561.json
562.json
563.json
564.json
565.json
566.json
567.json
568.json
569.json
570.json
571.json
572.json
573.json
574.json
575.json
576.json
577.json
578.json
579.json
580.json
581.json
582.json
583.json
584.json
585.json
586.json
587.json
588.json
589.json
590.json
591.json
592.json
593.json
594.json
595.json
596.json
597.json
598.json
599.json
600.json
601.json
602.json
603.json
604.json
605.json
606.json
607.json
608.json
609.json
610.json
611.json
612.json
613.json
614.json
615.json
616.json
617.json
618.json
619.json
620.json
621.json
622.json
623.json
624.json
625.json
626.json
627.json
628.json
629.json
630.json
631.json
632.json
633.json
634.json
635.json
636.json
637.json
638.json
639.json
640.json
641.json
642.json
643.json
644.json
645.json
646.json
647.json
648.json
649.json
650.json
651.json
652.json
653.json
654.json
655.json
656.json
657.json
658.json
659.json
660.json
661.json
662.json
663.json
664.json
665.json
666.json
667.json
668.json
669.json
670.json
671.json
672.json
673.json
674.json
675.json
676.json
677.json
678.json
679.json
680.json
681.json
682.json
683.json
684.json
685.json
686.json
687.json
688.json
689.json
690.json
691.json
692.json
693.json
694.json
695.json
696.json
697.json
698.json
699.json
700.json
701.json
702.json
703.json
704.json
705.json
706.json
707.json
708.json
709.json
710.json
711.json
712.json
713.json
714.json
715.json
716.json
717.json
718.json
719.json
720.json
721.json
722.json
723.json
724.json
725.json
726.json
727.json
728.json
729.json
730.json
731.json
732.json
733.json
734.json
735.json
736.json
737.json
738.json
739.json
740.json
741.json
742.json
743.json
744.json
745.json
746.json
747.json
748.json
749.json
750.json
751.json
752.json
753.json
754.json
755.json
756.json
757.json
758.json
759.json
760.json
761.json
762.json
763.json
764.json
765.json
766.json
767.json
768.json
769.json
770.json
771.json
772.json
773.json
774.json
775.json
776.json
777.json
778.json
779.json
780.json
781.json
782.json
783.json
784.json
785.json
786.json
787.json
788.json
789.json
790.json
791.json
792.json
793.json
794.json
795.json
796.json
797.json
798.json
799.json
800.json
801.json
802.json
803.json
804.json
805.json
806.json
807.json
808.json
809.json
810.json
811.json
812.json
813.json
814.json
815.json
816.json
817.json
818.json
819.json
820.json
821.json
822.json
823.json
824.json
825.json
826.json
827.json
828.json
829.json
830.json
831.json
832.json
833.json
834.json
835.json
836.json
837.json
838.json
839.json
840.json
841.json
842.json
843.json
844.json
845.json
846.json
847.json
848.json
849.json
850.json
851.json
852.json
853.json
854.json
855.json
856.json
857.json
858.json
859.json
860.json
861.json
862.json
863.json
864.json
865.json
866.json
867.json
868.json
869.json
870.json
871.json
872.json
873.json
874.json
875.json
876.json
877.json
878.json
879.json
880.json
881.json
882.json
883.json
884.json
885.json
886.json
887.json
888.json
889.json
890.json
891.json
892.json
893.json
894.json
895.json
896.json
897.json
898.json
899.json
900.json
901.json
902.json
903.json
904.json
905.json
906.json
907.json
908.json
909.json
910.json
911.json
912.json
913.json
914.json
915.json
916.json
917.json
918.json
919.json
920.json
921.json
922.json
923.json
924.json
925.json
926.json
927.json
928.json
929.json
930.json
931.json
932.json
933.json
934.json
935.json
936.json
937.json
938.json
939.json
940.json
941.json
942.json
943.json
944.json
945.json
946.json
947.json
948.json
949.json
950.json
951.json
952.json
953.json
954.json
955.json
956.json
957.json
958.json
959.json
960.json
961.json
962.json
963.json
964.json
965.json
966.json
967.json
968.json
969.json
970.json
971.json
972.json
973.json
974.json
975.json
976.json
977.json
978.json
979.json
980.json
981.json
982.json
983.json
984.json
985.json
986.json
987.json
988.json
989.json
990.json
991.json
992.json
993.json
994.json
995.json
996.json
997.json
998.json
999.json

¿Como es cada json?

In [13]:
with zipfile.ZipFile(knowledge_zip, "r") as zip_ref:
    with zip_ref.open("0.json") as f:
        for i in range(3):
            line = f.readline()
            print(f"LINE {i}:")
            print(line[:500])
            print()

LINE 0:
b'{"claim_id": "0", "type": "gold", "query": "_", "url": "https://en.wikipedia.org/wiki/Hunter_Biden", "url2text": ["Robert Hunter Biden (born February 4, 1970) is an American attorney and businessman. Biden has also worked as a hedge fund principal and a venture capital and private equity fund investor.", "He formerly worked as a banker, a lobbyist, and a legal representative for lobbying firms.", "Biden is the second son of U.S. President Joe Biden and his first wife, Neilia Hunter Biden. In 197'

LINE 1:
b'{"claim_id": "0", "type": "question", "query": "Did Hunter Biden have any experience in the energy sector at the time he joined the board of the  Burisma energy company in 2014", "url": "https://www.reuters.com/article/idUSKBN1WX1P6/", "url2text": []}\n'

LINE 2:
b'{"claim_id": "0", "type": "question", "query": "Did Hunter Biden have any experience in the energy sector at the time he joined the board of the  Burisma energy company in 2014", "url": "https://apnews.com/article/joe-biden-europe-business-c49555d51eb243e09a42f7577fc5937f", "url2text": ["FILE - In this Oct. 11, 2012, file photo Hunter Biden waits for the start of the his father\xe2\x80\x99s, Vice President Joe Biden\xe2\x80\x99s, debate at Centre College in Danville, Ky.", "Hunter Biden is expressing regret for b'

In [14]:
knowledge_records = []

with zipfile.ZipFile(knowledge_zip, "r") as zip_ref:
    with zip_ref.open("0.json") as f:
        for line in f:
            line = line.decode("utf-8").strip()

            if line:
                knowledge_records.append(
                    json.loads(line)
                )

print(type(knowledge_records))
print("Number of records:", len(knowledge_records))

<class 'list'>
Number of records: 546

In [ ]:
knowledge_records[0]

{'claim_id': '0',
 'type': 'gold',
 'query': '_',
 'url': 'https://en.wikipedia.org/wiki/Hunter_Biden',
 'url2text': ['Robert Hunter Biden (born February 4, 1970) is an American attorney and businessman. Biden has also worked as a hedge fund principal and a venture capital and private equity fund investor.',
  'He formerly worked as a banker, a lobbyist, and a legal representative for lobbying firms.',
  'Biden is the second son of U.S. President Joe Biden and his first wife, Neilia Hunter Biden. In 1972, when Biden was two years old, a car crash killed his mother, who was driving, and his one-year-old sister, Naomi, and seriously injured both him and his older brother, Beau.',
  "In his memoir, Beautiful Things, Biden wrote of his struggles with drug and alcohol abuse, which escalated after Beau's 2015 death from brain cancer.[1][2]",
  'He was discharged from the U.S. Navy Reserve shortly after his commissioning, due to a failed drug test.',
  'Biden was a founding board member of BHR Partners,[3] a Chinese investment company, in 2013. He served on the board of Burisma Holdings, one of the largest private natural gas producers in Ukraine, from 2014 until his term expired in April 2019.',
  'Since early 2019, Hunter and his father have been the subjects of allegations of corrupt activities concerning Ukraine.',
  "The accusations concern Hunter Biden's business dealings in Ukraine and Joe Biden's anti-corruption efforts there.[4]",
  'The New York Post published an article in October 2020 about a laptop computer that had belonged to Hunter Biden.',
  'The laptop supposedly contained about 129,000 emails and other materials, but the Post provided no evidence of the chain of custody or authenticity of the device.',
  'Other media outlets declined to publish the story, because of that lack of provenance.[5] In March 2022, The New York Times and The Washington Post reported that some of the emails found on the computer were authentic.[6][7]',
  "Some of the Bidens' detractors have said that the laptop contents exposed corruption by Hunter's father, but no evidence of criminal wrongdoing by Joe Biden has been found.[8]",
  "Biden's tax affairs have been under federal criminal investigation since late 2018.[9] On July 26, 2023, Biden pled not guilty to tax charges for filing two years of his tax returns late.[10]",
  'This is a reversal of his prior, guilty plea on June 20, 2023.[11] At that time, he had also admitted to "illegally owning a gun while a drug user" because he knowingly denied drug use when applying for a gun purchase permit.[12][13]',
  'On September 14, 2023, Biden was indicted by a special counsel in Delaware on three federal firearms-related charges, in particular possessing an unloaded pistol for 11 days.[14]',
  'On December 7, 2023, the special counsel indicted Biden on nine additional counts, all tax-related charges including tax evasion.[15]',
  'On January 11, 2024, Biden pleaded not guilty to all tax evasion charges in a Los Angeles federal courthouse.[16]',
  'He is scheduled to face trial on June 20, 2024.[17]',
  'Robert Hunter Biden was born on February 4, 1970,[18] in Wilmington, Delaware. He is the second son of Neilia Biden (née Hunter) and Joe Biden.[19]',
  "Hunter Biden's mother and younger sister Naomi were killed in an automobile crash on December 18, 1972.[20][21]",
  'Biden and his older brother Beau were also seriously injured but survived. Beau suffered multiple broken bones while Hunter sustained a fractured skull and severe traumatic brain injuries.[22]',
  'Both spent several months in the hospital, when their father was sworn into the U.S. Senate in January 1973.[23][24][25]',
  'Hunter and Beau later encouraged their father to marry again,[26] and Jill Jacobs Stevenson became their stepmother in 1977.[19]',
  'Like his father and brother, Biden attended Catholic high school Archmere Academy in Claymont, Delaware.[19]',
  'He graduated with a Bachelor of Arts degree in history from Georgetown University in 1992.[19] During the year after he graduated from college, he served as a Jesuit volunteer at a church in Portland, Oregon, and met Kathleen Buhle, whom he married in 1993.[19]',
  'After attending the Georgetown University Law Center for one year, he transferred to Yale Law School and graduated in 1996.[19]',
  "After graduating from law school in 1996, Biden accepted a consultant position at the bank holding company MBNA, whose employees donated more than $200,000 into Joe Biden's senate campaigns.[19][28] Biden delayed his start date at MBNA to serve as co-chair for his father's reelection campaign.[29]",
  'By 1998, Hunter Biden had risen to the rank of executive vice president at MBNA.[19] Biden\'s hiring and other relationships Joe Biden held with MBNA led Byron York of The American Spectator to refer to Joe Biden as "the senator from MBNA".[30][29]',
  "Biden departed from MBNA in 1998. He then served at the United States Department of Commerce, focusing on ecommerce policy for President Bill Clinton's administration.[31]",
  'In 2001, Biden became a lobbyist, co-founding the firm of Oldaker, Biden & Belair.[32] According to Adam Entous of The New Yorker, Biden and his father established a relationship in which "Biden wouldn\'t ask Hunter about his lobbying clients, and Hunter wouldn\'t tell his father about them.',
  '"[19] That same year, he was rehired by MBNA as a consultant, where he was paid a yearly $100,000 retainer until 2005.[29]',
  "MBNA's rehiring of Biden was controversial because his father was pushing for passage of the Bankruptcy Abuse Prevention and Consumer Protection Act, which was beneficial to the credit card industry and supported by MBNA during Biden's time at the bank.[19][33] The legislation made it more difficult to get bankruptcy protection.[33]",
  'Hunter Biden was appointed to a five-year term on the board of directors of Amtrak by President George W. Bush in 2006.[34]',
  "Biden was the board's vice chairman from July 2006 until 2009, was replaced as vice chairman in January 2010,[35] and resigned from the board in February,[36] shortly after his father became vice president.",
  "Biden said during his father's vice-presidential campaign that it was time for his lobbying activities to end.[19]",
  'In 2006, Biden and his uncle James Biden purchased international hedge fund Paradigm Global Advisors with an $8 million promissory note,[32]',
  'but the joint promotion of the fund by an entity of troubled Stanford Financial Group hastened the unwinding of the company in 2010.[37]',
  'In September 2008, Hunter Biden founded a consultancy company named Seneca Global Advisors that offered to help companies expand into foreign markets.[38]',
  'Biden was a partner in investment vehicles that included the name "Seneca" to denote his participation.[39]',
  'In 2009, he, Devon Archer, and Christopher Heinz founded the investment and advisory firm Rosemont Seneca Partners.[32]',
  'He also co-founded venture capital firm Eudora Global.[27] He held the position of counsel in the law firm Boies Schiller Flexner LLP in 2014.[19]',
  'Biden was on the board of directors of World Food Program USA, a 501(c)(3) charity based in Washington, D.C., that supports the work of the UN World Food Programme from 2011 to 2017; he served as board chairman from 2011 to 2015.[40]',
  "A detailed analysis of Hunter Biden's hard drive by NBC News showed that Biden and his firm were paid $11 million from 2013 to 2018.[41]",
  'Several bank accounts linked to Hunter Biden received $3.8 million in payments from CEFC China Energy,[42] a defunct oil and gas company with links to the Chinese Communist Party.[43]',
  'From 2013 to 2020, Biden served as a member of the board of the China-based private equity fund BHR Partners, of which he acquired a 10% stake in 2017 at a discount to actual value and with borrowed money.[44][45]',
  "The founders of BHR Partners included Biden's Rosemont Seneca Partners investment firm (20% equity), along with US-based Thornton Group LLC (10% equity) and two asset managers registered in China.[46][19][38]",
  'The Chinese-registered asset managers are the Bank of China (via BOC International Holdings-backed Bohai Industrial Investment Fund Management) and Deutsche Bank-backed Harvest Fund Management.[47]',
  'In September 2019, while Trump was accusing Hunter Biden of malfeasance in Ukraine, he also falsely claimed that Biden "walk[ed] out of China with $1.5 billion in a fund".[48]',
  "Later in 2019, The Wall Street Journal confirmed that Trump was wrong about his claim that Hunter received $1.5 billion stating that Trump had no evidence to support the claim and that Trump incorrectly interpreted BHR's past fundraising target of $1.5 billion; BHR invests by raising money from other companies, for each deal, but doesn't keep those funds.[49] Trump publicly called upon China to investigate Hunter Biden's business activities there while his father was vice president.[50][51]",
  'Hunter Biden announced his resignation from the board of directors of BHR Partners, effective end-of-month October 2019, citing "the barrage of false charges" by then-U.S. President Trump.[52][53]',
  "This was confirmed by Biden's attorney, who said in November 2021 that his client no longer held any direct or indirect interest in BHR.[3]",
  'However, as of April 15, 2020, Chinese business records showed that Hunter Biden remained a board member of BHR.[54]',
  'According to his lawyer, Biden had "not received any compensation for being on BHR\'s board of directors" nor had he received any return on his equity share in BHR.[55]',
  'Biden\'s lawyer George Mesires told The Washington Post that BHR Partners had been "capitalized from various sources with a total of 30 million RMB (Renminbi), or about $4.2 million, not $1.5 billion".[48] Hunter Biden’s company Skaneateles LLC owned the 10% equity stake in BHR, and The Wall Street Journal reported that as of December 2020, Skaneateles LLC, solely controlled by Biden,[56] owned 10% of BHR.[57]',
  'In November 2021, New York Times reported that "Chinese corporate records show Skaneateles remains a part owner of BHR".[3] Skaneateles was dissolved in 2022.',
  'BHR Partners invests Chinese venture capital into tech startups, such as an early-stage investment in Chinese auto hailing app DiDi[49] and cross-border acquisitions in automotive and mining, e.g. purchase of a stake in Democratic Republic of Congo copper and cobalt producer Tenke Fungurume Mining.[58][59]',
  'The New York Times reported that BHR Partners helped finance a coal-mining company in Australia that was controlled by a Chinese state-owned enterprise, assisted a subsidiary of a Chinese defense company in acquiring an auto parts manufacturer in Michigan, and facilitated the US$3.8 billion purchase of the DRC cobalt mine.',
  'A former BHR board member told the Times that Biden and the other American BHR founder, Devon Archer, were not involved in the mine deal.[3][60][61]',
  'Biden joined the board of Burisma Holdings owned by Ukrainian oligarch and former politician Mykola Zlochevsky, who was facing a money laundering investigation just after the Ukrainian revolution, in April 2014.[62][63][64]',
  "Biden's business partner, Devon Archer, had joined the board of Burisma several months prior. Biden was hired to help Burisma with corporate governance best practices, while still an attorney with Boies Schiller Flexner, and a consulting firm in which Biden is a partner was also retained by Burisma.[65][66][67]",
  "Christopher Heinz, John Kerry's stepson, opposed his partners Devon Archer and Hunter Biden joining the board in 2014 due to the reputational risk.[63]",
  "Biden served on the board of Burisma until his term expired in April 2019,[66] receiving compensation of up to $50,000 per month in some months.[66][65] Because Joe Biden played a major role in U.S. policy towards Ukraine, some Ukrainian anti-corruption advocates[68][69] and Obama administration officials expressed concern that Hunter Biden having joined the board could create the appearance of a conflict of interest and undermine Joe Biden's anti-corruption work in Ukraine.[19][63]",
  "While serving as vice president, Joe Biden joined other Western leaders in encouraging the government of Ukraine to fire the country's top prosecutor Viktor Shokin,[70][71] who was widely criticized for blocking corruption investigations.[72][73] The Ukrainian parliament voted to remove Shokin in March 2016.[74][75]",
  'Since early 2019, Hunter and his father Joe Biden have been the subjects of false and baseless claims of corrupt activities in a Biden–Ukraine conspiracy theory pushed by then-U.S. President Donald Trump and his allies.[4]',
  'Former President Donald Trump and his personal lawyer Rudy Giuliani claimed in 2019, without evidence, that Joe Biden had sought the dismissal of Shokin in order to protect his son and Burisma Holdings.',
  "Actually, it was the official policy of the United States and the European Union to seek Shokin's removal.[76][68][70][77][78]",
  'There has also been no evidence produced of wrongdoing by Hunter Biden in Ukraine.[79][80] The Ukrainian anti-corruption investigation agency stated in September 2019 that its current investigation of Burisma was restricted solely to investigating the period from 2010 to 2012, before Hunter Biden joined Burisma in 2014.[81]',
  "Shokin, in May 2019, claimed that he was fired because he had been actively investigating Burisma,[82] but U.S. and Ukrainian officials have stated that the investigation into Burisma was dormant at the time of Shokin's dismissal.[63][82][83]",
  'Ukrainian and United States State Department sources note that Shokin was fired for failing to address corruption, including within his office.[77][69][84]',
  'In July 2019, Trump ordered the freezing of $391 million in military aid[85] shortly before a telephone conversation with Ukrainian President Volodymyr Zelenskyy in which Trump asked Zelenskyy to initiate an investigation of the Bidens.[86][87]',
  'Trump falsely told Zelenskyy that "[Joe] Biden went around bragging that he stopped the prosecution" of his son; Joe Biden did not stop any prosecution, did not brag about doing so, and there is no evidence his son was ever under investigation.[88]',
  "The United States House of Representatives initiated a formal impeachment inquiry on September 24, 2019, against Trump on the grounds that he may have sought to use U.S. foreign aid and the Ukrainian government to damage Joe Biden's 2020 presidential campaign.[89]",
  'Ukrainian prosecutor general Yuriy Lutsenko said in May 2019 that Hunter Biden had not violated Ukrainian law.',
  'After Lutsenko was replaced by Ruslan Riaboshapka as prosecutor general, Lutsenko and Riaboshapka said in September and October 2019 respectively that they had seen no evidence of wrongdoing by Hunter Biden.[70][90][91]',
  "During 2019 and into 2020, Republican senators Ron Johnson and Chuck Grassley investigated Hunter Biden's involvement with Burisma, as well as allegations that Democrats colluded with the Ukrainian government to interfere in the 2016 election.",
  'The chairman of the Senate Intelligence Committee Republican senator Richard Burr privately expressed concerns to the senators that their inquiries could assist efforts by Russian intelligence to spread disinformation to disrupt American domestic affairs.[92] American intelligence officials briefed senators in late 2019 about Russian efforts to frame Ukraine for 2016 election interference.[93]',
  "Johnson said he would release findings in spring 2020, as Democrats would be selecting their 2020 presidential nominee, but instead ramped up the investigation at Trump's urging in May 2020, after it became clear that Joe Biden would be the nominee.[94][95] Trump tweeted a press report about the investigations, later stating that he would make allegations of corruption by the Bidens a central theme of his re-election campaign.[93]",
  'Johnson decided in March 2020 against issuing a subpoena for former Ukrainian official Andrii Telizhenko, a Giuliani associate who had made appearances on the pro-Trump cable channel One America News, after the FBI briefed him about concerns Telizhenko could be spreading Russian disinformation.[96]',
  "The State Department revoked Telizhenko's visa in October 2020, and CNN reported the American government was considering sanctioning him as a Russian agent.[97]",
  'CNN reported that Vladislav Davidzon, the editor of Ukrainian magazine The Odessa Review, told CNN that in 2018 Telizhenko offered him money to lobby Republican senators in support of pro-Russian television stations in Ukraine.[98]',
  "When Johnson released the final report on the investigation, it contained no evidence that Joe Biden had pushed for Shokin's removal in order to benefit Hunter or Burisma.[99][100]",
  'In June 2020, former Ukrainian prosecutor general Ruslan Riaboshapka stated that an audit of thousands of old case files he had ordered in October 2019 had found no wrongdoing by Hunter Biden.',
  'Riaboshapka was described by Zelenskyy as "100 percent my person" during the July 2019 call in which Trump asked him to investigate Biden.[101]',
  'Ukrainian lawmaker Andrii Derkach, an associate of Rudy Giuliani with links to[clarification needed] Russian intelligence, released in May 2020 alleged snippets of recordings of Joe Biden speaking with Ukrainian president Petro Poroshenko during the years Hunter Biden worked for Burisma.[102]',
  "The recordings, which were not verified as authentic and appeared heavily edited, depicted Biden linking loan guarantees for Ukraine to the ouster of the country's prosecutor general.",
  'The recordings did not provide evidence to support the ongoing conspiracy theory that Biden wanted the prosecutor fired to protect his son.[103]',
  'Poroshenko denied in June 2020 that Joe Biden ever approached him about Burisma.[104][105] The United States Department of the Treasury sanctioned Derkach in September 2020, stating he "has been an active Russian agent for over a decade, maintaining close connections with the Russian Intelligence Services".',
  'The Treasury Department added Derkach "waged a covert influence campaign centered on cultivating false and unsubstantiated narratives concerning U.S. officials in the upcoming 2020 Presidential Election" including by the release of "edited audio tapes and other unsupported information with the intent to discredit U.S. officials".[106][107] Close associates of Derkach were also sanctioned by the Treasury Department in January 2021.[108]',
  'United States intelligence community analysis released in March 2021 found that Derkach was among proxies of Russian intelligence who promoted and laundered misleading or unsubstantiated narratives about Biden "to US media organizations, US officials, and prominent US individuals, including some close to former President Trump and his administration".[109][110]',
  'Two Republicans on a Senate investigation committee in 2020 claimed that Russian businessperson Yelena Baturina, the wife of former Moscow mayor Yury Luzhkov, wire-transferred $3.5 million in 2014 to Rosemont Seneca Thornton, of which Biden had previously been a partner.',
  'The Washington Post reported in April 2022 that the partners of Rosemont Seneca Thornton had agreed to dissolve the organization before the 2014 wire transfer, though it continued to be operated by Devin Archer to facilitate real estate transactions for eastern and central Asia investors, while Biden was uninvolved.',

In [15]:
with_text = [
    r for r in knowledge_records
    if r.get("url2text")
]

without_text = [
    r for r in knowledge_records
    if not r.get("url2text")
]

print("With text:", len(with_text))
print("Without text:", len(without_text))

With text: 431
Without text: 115

In [16]:
type_counts = Counter(
    r.get("type")
    for r in knowledge_records
)

type_counts

Counter({'question_duplicate': 86,
         'provenance': 85,
         'gpt_url_only': 75,
         'gpt_question': 49,
         'NER': 48,
         'background_questions': 44,
         'most_similar': 44,
         'background': 35,
         'question': 33,
         'same_entity_questions': 19,
         'answer': 17,
         'claim+question': 7,
         'claim': 3,
         'gold': 1})

`0.json` no contiene únicamente “documentos web”

In [17]:
print("Number of records:", len(knowledge_records))
print("With text:", len(with_text))
print("Without text:", len(without_text))
print(type_counts)

Number of records: 546
With text: 431
Without text: 115
Counter({'question_duplicate': 86, 'provenance': 85, 'gpt_url_only': 75, 'gpt_question': 49, 'NER': 48, 'background_questions': 44, 'most_similar': 44, 'background': 35, 'question': 33, 'same_entity_questions': 19, 'answer': 17, 'claim+question': 7, 'claim': 3, 'gold': 1})

No vamos a trabajar con los 546 registros directamente. Nos conviene filtrar registros sin texto, posibles duplicados y registros con type = `gold`.

In [18]:
retrieval_records = [
    r for r in knowledge_records
    if r.get("url2text")
    # and r.get("type") != "gold"
]

print(
    "Records for retrieval:",
    len(retrieval_records)
)

Records for retrieval: 431

In [19]:
urls = [
    r.get("url")
    for r in retrieval_records
    if r.get("url")
]

print("Total URLs:", len(urls))
print("Unique URLs:", len(set(urls)))

Total URLs: 431
Unique URLs: 431

In [20]:
url_counts = Counter(urls)

duplicate_urls = {
    url: count
    for url, count in url_counts.items()
    if count > 1
}

print(
    "Duplicated URLs:",
    len(duplicate_urls)
)

Duplicated URLs: 0

### 5. Creando documentos para la fase RAG

In [ ]:
def clean_text_parts(text_parts):
    """
    Limpia los fragmentos de texto extraídos de una fuente.

    Elimina valores no textuales, strings vacíos y fragmentos exactamente duplicados, manteniendo el orden 
    original.

    Parameters
    ----------
    text_parts : list
        Lista de fragmentos de texto.

    Returns
    -------
    list
        Lista de fragmentos limpios y sin duplicados exactos.
    """
    cleaned_parts = []
    seen = set()

    for part in text_parts:
        if not isinstance(part, str):
            continue

        part = part.strip()

        if not part:
            continue

        # Evita fragmentos exactamente repetidos
        if part in seen:
            continue

        seen.add(part)
        cleaned_parts.append(part)

    return cleaned_parts

In [ ]:
def build_document(record):
    """
    Convierte un registro del Knowledge Store de AVeriTeC en una estructura documental utilizable por el 
    pipeline.

    Parameters
    ----------
    record : dict
        Registro original del Knowledge Store.

    Returns
    -------
    dict
        Documento normalizado con texto y metadatos.
    """
    text_parts = clean_text_parts(
        record.get("url2text", [])
    )

    text = " ".join(text_parts)

    return {
        "claim_id": record.get("claim_id"),
        "url": record.get("url"),
        "source_type": record.get("type"),
        "query": record.get("query"),
        "text_parts": text_parts,
        "text": text
    }

In [19]:
documents = [
    build_document(record)
    for record in retrieval_records
]

print("Documents:", len(documents))

Documents: 431

In [24]:
documents[0]

{'claim_id': '0',
 'url': 'https://en.wikipedia.org/wiki/Hunter_Biden',
 'source_type': 'gold',
 'query': '_',
 'text_parts': ['Robert Hunter Biden (born February 4, 1970) is an American attorney and businessman. Biden has also worked as a hedge fund principal and a venture capital and private equity fund investor.',
  'He formerly worked as a banker, a lobbyist, and a legal representative for lobbying firms.',
  'Biden is the second son of U.S. President Joe Biden and his first wife, Neilia Hunter Biden. In 1972, when Biden was two years old, a car crash killed his mother, who was driving, and his one-year-old sister, Naomi, and seriously injured both him and his older brother, Beau.',
  "In his memoir, Beautiful Things, Biden wrote of his struggles with drug and alcohol abuse, which escalated after Beau's 2015 death from brain cancer.[1][2]",
  'He was discharged from the U.S. Navy Reserve shortly after his commissioning, due to a failed drug test.',
  'Biden was a founding board member of BHR Partners,[3] a Chinese investment company, in 2013. He served on the board of Burisma Holdings, one of the largest private natural gas producers in Ukraine, from 2014 until his term expired in April 2019.',
  'Since early 2019, Hunter and his father have been the subjects of allegations of corrupt activities concerning Ukraine.',
  "The accusations concern Hunter Biden's business dealings in Ukraine and Joe Biden's anti-corruption efforts there.[4]",
  'The New York Post published an article in October 2020 about a laptop computer that had belonged to Hunter Biden.',
  'The laptop supposedly contained about 129,000 emails and other materials, but the Post provided no evidence of the chain of custody or authenticity of the device.',
  'Other media outlets declined to publish the story, because of that lack of provenance.[5] In March 2022, The New York Times and The Washington Post reported that some of the emails found on the computer were authentic.[6][7]',
  "Some of the Bidens' detractors have said that the laptop contents exposed corruption by Hunter's father, but no evidence of criminal wrongdoing by Joe Biden has been found.[8]",
  "Biden's tax affairs have been under federal criminal investigation since late 2018.[9] On July 26, 2023, Biden pled not guilty to tax charges for filing two years of his tax returns late.[10]",
  'This is a reversal of his prior, guilty plea on June 20, 2023.[11] At that time, he had also admitted to "illegally owning a gun while a drug user" because he knowingly denied drug use when applying for a gun purchase permit.[12][13]',
  'On September 14, 2023, Biden was indicted by a special counsel in Delaware on three federal firearms-related charges, in particular possessing an unloaded pistol for 11 days.[14]',
  'On December 7, 2023, the special counsel indicted Biden on nine additional counts, all tax-related charges including tax evasion.[15]',
  'On January 11, 2024, Biden pleaded not guilty to all tax evasion charges in a Los Angeles federal courthouse.[16]',
  'He is scheduled to face trial on June 20, 2024.[17]',
  'Robert Hunter Biden was born on February 4, 1970,[18] in Wilmington, Delaware. He is the second son of Neilia Biden (née Hunter) and Joe Biden.[19]',
  "Hunter Biden's mother and younger sister Naomi were killed in an automobile crash on December 18, 1972.[20][21]",
  'Biden and his older brother Beau were also seriously injured but survived. Beau suffered multiple broken bones while Hunter sustained a fractured skull and severe traumatic brain injuries.[22]',
  'Both spent several months in the hospital, when their father was sworn into the U.S. Senate in January 1973.[23][24][25]',
  'Hunter and Beau later encouraged their father to marry again,[26] and Jill Jacobs Stevenson became their stepmother in 1977.[19]',
  'Like his father and brother, Biden attended Catholic high school Archmere Academy in Claymont, Delaware.[19]',
  'He graduated with a Bachelor of Arts degree in history from Georgetown University in 1992.[19] During the year after he graduated from college, he served as a Jesuit volunteer at a church in Portland, Oregon, and met Kathleen Buhle, whom he married in 1993.[19]',
  'After attending the Georgetown University Law Center for one year, he transferred to Yale Law School and graduated in 1996.[19]',
  "After graduating from law school in 1996, Biden accepted a consultant position at the bank holding company MBNA, whose employees donated more than $200,000 into Joe Biden's senate campaigns.[19][28] Biden delayed his start date at MBNA to serve as co-chair for his father's reelection campaign.[29]",
  'By 1998, Hunter Biden had risen to the rank of executive vice president at MBNA.[19] Biden\'s hiring and other relationships Joe Biden held with MBNA led Byron York of The American Spectator to refer to Joe Biden as "the senator from MBNA".[30][29]',
  "Biden departed from MBNA in 1998. He then served at the United States Department of Commerce, focusing on ecommerce policy for President Bill Clinton's administration.[31]",
  'In 2001, Biden became a lobbyist, co-founding the firm of Oldaker, Biden & Belair.[32] According to Adam Entous of The New Yorker, Biden and his father established a relationship in which "Biden wouldn\'t ask Hunter about his lobbying clients, and Hunter wouldn\'t tell his father about them.',
  '"[19] That same year, he was rehired by MBNA as a consultant, where he was paid a yearly $100,000 retainer until 2005.[29]',
  "MBNA's rehiring of Biden was controversial because his father was pushing for passage of the Bankruptcy Abuse Prevention and Consumer Protection Act, which was beneficial to the credit card industry and supported by MBNA during Biden's time at the bank.[19][33] The legislation made it more difficult to get bankruptcy protection.[33]",
  'Hunter Biden was appointed to a five-year term on the board of directors of Amtrak by President George W. Bush in 2006.[34]',
  "Biden was the board's vice chairman from July 2006 until 2009, was replaced as vice chairman in January 2010,[35] and resigned from the board in February,[36] shortly after his father became vice president.",
  "Biden said during his father's vice-presidential campaign that it was time for his lobbying activities to end.[19]",
  'In 2006, Biden and his uncle James Biden purchased international hedge fund Paradigm Global Advisors with an $8 million promissory note,[32]',
  'but the joint promotion of the fund by an entity of troubled Stanford Financial Group hastened the unwinding of the company in 2010.[37]',
  'In September 2008, Hunter Biden founded a consultancy company named Seneca Global Advisors that offered to help companies expand into foreign markets.[38]',
  'Biden was a partner in investment vehicles that included the name "Seneca" to denote his participation.[39]',
  'In 2009, he, Devon Archer, and Christopher Heinz founded the investment and advisory firm Rosemont Seneca Partners.[32]',
  'He also co-founded venture capital firm Eudora Global.[27] He held the position of counsel in the law firm Boies Schiller Flexner LLP in 2014.[19]',
  'Biden was on the board of directors of World Food Program USA, a 501(c)(3) charity based in Washington, D.C., that supports the work of the UN World Food Programme from 2011 to 2017; he served as board chairman from 2011 to 2015.[40]',
  "A detailed analysis of Hunter Biden's hard drive by NBC News showed that Biden and his firm were paid $11 million from 2013 to 2018.[41]",
  'Several bank accounts linked to Hunter Biden received $3.8 million in payments from CEFC China Energy,[42] a defunct oil and gas company with links to the Chinese Communist Party.[43]',
  'From 2013 to 2020, Biden served as a member of the board of the China-based private equity fund BHR Partners, of which he acquired a 10% stake in 2017 at a discount to actual value and with borrowed money.[44][45]',
  "The founders of BHR Partners included Biden's Rosemont Seneca Partners investment firm (20% equity), along with US-based Thornton Group LLC (10% equity) and two asset managers registered in China.[46][19][38]",
  'The Chinese-registered asset managers are the Bank of China (via BOC International Holdings-backed Bohai Industrial Investment Fund Management) and Deutsche Bank-backed Harvest Fund Management.[47]',
  'In September 2019, while Trump was accusing Hunter Biden of malfeasance in Ukraine, he also falsely claimed that Biden "walk[ed] out of China with $1.5 billion in a fund".[48]',
  "Later in 2019, The Wall Street Journal confirmed that Trump was wrong about his claim that Hunter received $1.5 billion stating that Trump had no evidence to support the claim and that Trump incorrectly interpreted BHR's past fundraising target of $1.5 billion; BHR invests by raising money from other companies, for each deal, but doesn't keep those funds.[49] Trump publicly called upon China to investigate Hunter Biden's business activities there while his father was vice president.[50][51]",
  'Hunter Biden announced his resignation from the board of directors of BHR Partners, effective end-of-month October 2019, citing "the barrage of false charges" by then-U.S. President Trump.[52][53]',
  "This was confirmed by Biden's attorney, who said in November 2021 that his client no longer held any direct or indirect interest in BHR.[3]",
  'However, as of April 15, 2020, Chinese business records showed that Hunter Biden remained a board member of BHR.[54]',
  'According to his lawyer, Biden had "not received any compensation for being on BHR\'s board of directors" nor had he received any return on his equity share in BHR.[55]',
  'Biden\'s lawyer George Mesires told The Washington Post that BHR Partners had been "capitalized from various sources with a total of 30 million RMB (Renminbi), or about $4.2 million, not $1.5 billion".[48] Hunter Biden’s company Skaneateles LLC owned the 10% equity stake in BHR, and The Wall Street Journal reported that as of December 2020, Skaneateles LLC, solely controlled by Biden,[56] owned 10% of BHR.[57]',
  'In November 2021, New York Times reported that "Chinese corporate records show Skaneateles remains a part owner of BHR".[3] Skaneateles was dissolved in 2022.',
  'BHR Partners invests Chinese venture capital into tech startups, such as an early-stage investment in Chinese auto hailing app DiDi[49] and cross-border acquisitions in automotive and mining, e.g. purchase of a stake in Democratic Republic of Congo copper and cobalt producer Tenke Fungurume Mining.[58][59]',
  'The New York Times reported that BHR Partners helped finance a coal-mining company in Australia that was controlled by a Chinese state-owned enterprise, assisted a subsidiary of a Chinese defense company in acquiring an auto parts manufacturer in Michigan, and facilitated the US$3.8 billion purchase of the DRC cobalt mine.',
  'A former BHR board member told the Times that Biden and the other American BHR founder, Devon Archer, were not involved in the mine deal.[3][60][61]',
  'Biden joined the board of Burisma Holdings owned by Ukrainian oligarch and former politician Mykola Zlochevsky, who was facing a money laundering investigation just after the Ukrainian revolution, in April 2014.[62][63][64]',
  "Biden's business partner, Devon Archer, had joined the board of Burisma several months prior. Biden was hired to help Burisma with corporate governance best practices, while still an attorney with Boies Schiller Flexner, and a consulting firm in which Biden is a partner was also retained by Burisma.[65][66][67]",
  "Christopher Heinz, John Kerry's stepson, opposed his partners Devon Archer and Hunter Biden joining the board in 2014 due to the reputational risk.[63]",
  "Biden served on the board of Burisma until his term expired in April 2019,[66] receiving compensation of up to $50,000 per month in some months.[66][65] Because Joe Biden played a major role in U.S. policy towards Ukraine, some Ukrainian anti-corruption advocates[68][69] and Obama administration officials expressed concern that Hunter Biden having joined the board could create the appearance of a conflict of interest and undermine Joe Biden's anti-corruption work in Ukraine.[19][63]",
  "While serving as vice president, Joe Biden joined other Western leaders in encouraging the government of Ukraine to fire the country's top prosecutor Viktor Shokin,[70][71] who was widely criticized for blocking corruption investigations.[72][73] The Ukrainian parliament voted to remove Shokin in March 2016.[74][75]",
  'Since early 2019, Hunter and his father Joe Biden have been the subjects of false and baseless claims of corrupt activities in a Biden–Ukraine conspiracy theory pushed by then-U.S. President Donald Trump and his allies.[4]',
  'Former President Donald Trump and his personal lawyer Rudy Giuliani claimed in 2019, without evidence, that Joe Biden had sought the dismissal of Shokin in order to protect his son and Burisma Holdings.',
  "Actually, it was the official policy of the United States and the European Union to seek Shokin's removal.[76][68][70][77][78]",
  'There has also been no evidence produced of wrongdoing by Hunter Biden in Ukraine.[79][80] The Ukrainian anti-corruption investigation agency stated in September 2019 that its current investigation of Burisma was restricted solely to investigating the period from 2010 to 2012, before Hunter Biden joined Burisma in 2014.[81]',
  "Shokin, in May 2019, claimed that he was fired because he had been actively investigating Burisma,[82] but U.S. and Ukrainian officials have stated that the investigation into Burisma was dormant at the time of Shokin's dismissal.[63][82][83]",
  'Ukrainian and United States State Department sources note that Shokin was fired for failing to address corruption, including within his office.[77][69][84]',
  'In July 2019, Trump ordered the freezing of $391 million in military aid[85] shortly before a telephone conversation with Ukrainian President Volodymyr Zelenskyy in which Trump asked Zelenskyy to initiate an investigation of the Bidens.[86][87]',
  'Trump falsely told Zelenskyy that "[Joe] Biden went around bragging that he stopped the prosecution" of his son; Joe Biden did not stop any prosecution, did not brag about doing so, and there is no evidence his son was ever under investigation.[88]',
  "The United States House of Representatives initiated a formal impeachment inquiry on September 24, 2019, against Trump on the grounds that he may have sought to use U.S. foreign aid and the Ukrainian government to damage Joe Biden's 2020 presidential campaign.[89]",
  'Ukrainian prosecutor general Yuriy Lutsenko said in May 2019 that Hunter Biden had not violated Ukrainian law.',
  'After Lutsenko was replaced by Ruslan Riaboshapka as prosecutor general, Lutsenko and Riaboshapka said in September and October 2019 respectively that they had seen no evidence of wrongdoing by Hunter Biden.[70][90][91]',
  "During 2019 and into 2020, Republican senators Ron Johnson and Chuck Grassley investigated Hunter Biden's involvement with Burisma, as well as allegations that Democrats colluded with the Ukrainian government to interfere in the 2016 election.",
  'The chairman of the Senate Intelligence Committee Republican senator Richard Burr privately expressed concerns to the senators that their inquiries could assist efforts by Russian intelligence to spread disinformation to disrupt American domestic affairs.[92] American intelligence officials briefed senators in late 2019 about Russian efforts to frame Ukraine for 2016 election interference.[93]',
  "Johnson said he would release findings in spring 2020, as Democrats would be selecting their 2020 presidential nominee, but instead ramped up the investigation at Trump's urging in May 2020, after it became clear that Joe Biden would be the nominee.[94][95] Trump tweeted a press report about the investigations, later stating that he would make allegations of corruption by the Bidens a central theme of his re-election campaign.[93]",
  'Johnson decided in March 2020 against issuing a subpoena for former Ukrainian official Andrii Telizhenko, a Giuliani associate who had made appearances on the pro-Trump cable channel One America News, after the FBI briefed him about concerns Telizhenko could be spreading Russian disinformation.[96]',
  "The State Department revoked Telizhenko's visa in October 2020, and CNN reported the American government was considering sanctioning him as a Russian agent.[97]",
  'CNN reported that Vladislav Davidzon, the editor of Ukrainian magazine The Odessa Review, told CNN that in 2018 Telizhenko offered him money to lobby Republican senators in support of pro-Russian television stations in Ukraine.[98]',
  "When Johnson released the final report on the investigation, it contained no evidence that Joe Biden had pushed for Shokin's removal in order to benefit Hunter or Burisma.[99][100]",
  'In June 2020, former Ukrainian prosecutor general Ruslan Riaboshapka stated that an audit of thousands of old case files he had ordered in October 2019 had found no wrongdoing by Hunter Biden.',
  'Riaboshapka was described by Zelenskyy as "100 percent my person" during the July 2019 call in which Trump asked him to investigate Biden.[101]',
  'Ukrainian lawmaker Andrii Derkach, an associate of Rudy Giuliani with links to[clarification needed] Russian intelligence, released in May 2020 alleged snippets of recordings of Joe Biden speaking with Ukrainian president Petro Poroshenko during the years Hunter Biden worked for Burisma.[102]',
  "The recordings, which were not verified as authentic and appeared heavily edited, depicted Biden linking loan guarantees for Ukraine to the ouster of the country's prosecutor general.",
  'The recordings did not provide evidence to support the ongoing conspiracy theory that Biden wanted the prosecutor fired to protect his son.[103]',
  'Poroshenko denied in June 2020 that Joe Biden ever approached him about Burisma.[104][105] The United States Department of the Treasury sanctioned Derkach in September 2020, stating he "has been an active Russian agent for over a decade, maintaining close connections with the Russian Intelligence Services".',
  'The Treasury Department added Derkach "waged a covert influence campaign centered on cultivating false and unsubstantiated narratives concerning U.S. officials in the upcoming 2020 Presidential Election" including by the release of "edited audio tapes and other unsupported information with the intent to discredit U.S. officials".[106][107] Close associates of Derkach were also sanctioned by the Treasury Department in January 2021.[108]',
  'United States intelligence community analysis released in March 2021 found that Derkach was among proxies of Russian intelligence who promoted and laundered misleading or unsubstantiated narratives about Biden "to US media organizations, US officials, and prominent US individuals, including some close to former President Trump and his administration".[109][110]',
  'Two Republicans on a Senate investigation committee in 2020 claimed that Russian businessperson Yelena Baturina, the wife of former Moscow mayor Yury Luzhkov, wire-transferred $3.5 million in 2014 to Rosemont Seneca Thornton, of which Biden had previously been a partner.',
  'The Washington Post reported in April 2022 that the partners of Rosemont Seneca Thornton had agreed to dissolve the organization before the 2014 wire transfer, though it continued to be operated by Devin Archer to facilitate real estate transactions for eastern and central Asia investors, while Biden was uninvolved.',

Antes de obtener los chuncks para cada documento, necesitamos saber más o menos el tamaño:

In [25]:
document_lengths = [
    len(doc["text"])
    for doc in documents
]

print("Min:", min(document_lengths))
print("Max:", max(document_lengths))
print(
    "Average:",
    sum(document_lengths) / len(document_lengths)
)

Min: 71
Max: 3601339
Average: 60943.7030162413

In [26]:
lengths_df = pd.Series(
    document_lengths
)

lengths_df.describe()

count    4.310000e+02
mean     6.094370e+04
std      2.884391e+05
min      7.100000e+01
25%      2.881500e+03
50%      5.078000e+03
75%      1.088100e+04
max      3.601339e+06
dtype: float64

Ahora mismo tenemos, 1 URL - 1 Documento, y lo que queremos tener es 1 Documentos - Varios chunks

`Las 10 URLs/documentos completos más grandes dentro de los 430 documentos asociados a la claim 0.`

In [27]:
largest_documents = sorted(
    documents,
    key=lambda x: len(x["text"]),
    reverse=True
)[:10]

for i, doc in enumerate(largest_documents):
    print(f"\n--- DOCUMENT {i} ---")
    print("Length:", len(doc["text"]))
    print("URL:", doc["url"])
    print("Type:", doc["source_type"])
    print("Number of text parts:", len(doc["text_parts"]))

--- DOCUMENT 0 ---
Length: 3601339
URL: https://healthmasters.com/daily-news-articles-archive
Type: most_similar
Number of text parts: 42458

--- DOCUMENT 1 ---
Length: 2365109
URL: https://www.nps.gov/aboutus/foia/upload/COVID-19-Emails-Correspondence-DOI-NPS-2020-000736-Release-Date-01032022.pdf
Type: question_duplicate
Number of text parts: 35069

--- DOCUMENT 2 ---
Length: 2018490
URL: https://www.govinfo.gov/content/pkg/CHRG-116hhrg39405/pdf/CHRG-116hhrg39405.pdf
Type: most_similar
Number of text parts: 24250

--- DOCUMENT 3 ---
Length: 1955363
URL: https://www.intelligence.senate.gov/sites/default/files/documents/report_volume5.pdf
Type: answer
Number of text parts: 21893

--- DOCUMENT 4 ---
Length: 1695500
URL: https://www.congress.gov/116/crpt/hrpt346/CRPT-116hrpt346.pdf
Type: gpt_question
Number of text parts: 25747

--- DOCUMENT 5 ---
Length: 1534213
URL: https://docs.house.gov/billsthisweek/20191216/CRPT-116hrpt346.pdf
Type: gpt_question
Number of text parts: 16930

--- DOCUMENT 6 ---
Length: 937176
URL: https://kar.kent.ac.uk/92181/1/Sakwa%20-%20Deception%20full%20v4%20-%20final.pdf
Type: most_similar
Number of text parts: 11060

--- DOCUMENT 7 ---
Length: 916208
URL: https://www.stat.iastate.edu/people/mack-shelley/cv.pdf
Type: question_duplicate
Number of text parts: 8839

--- DOCUMENT 8 ---
Length: 775298
URL: https://www.justsecurity.org/wp-content/uploads/2019/12/impeachment-report-majority-schiff-intelligence-december-3-2019.pdf
Type: gpt_question
Number of text parts: 8699

--- DOCUMENT 9 ---
Length: 722816
URL: https://www.archaegraph.pl/lib/l231bv/KsiegaAMP2Ebook-kmkp3tld.pdf
Type: most_similar
Number of text parts: 9648

In [28]:
for i, doc in enumerate(largest_documents[:5]):
    print(f"\n--- DOCUMENT {i} PREVIEW ---")
    print(doc["text"][:1000])

--- DOCUMENT 0 PREVIEW ---
Bidenomics Fail: White House Plans Downshift In Electric Vehicle Transition As Demand Slides Rolling Disaster: Ford Halts 2024 F-150 Lightning Shipments Doctor warns WHO pandemic treaty includes 'gain of function' data sharing WHO pandemic treaty: “Torrent of fake news” has put negotiations at risk, says WHO chief Midwest and East Coast set to see the mercury soar 20 to 40 degrees above average as February ends with record-smashing warmth as low-pressure system sweeps across the U.S. Cruise ship 'hit by CHOLERA outbreak': Brits among thousands of passengers stuck in quarantine on Norwegian Dawn liner 'floating aimlessly' off coast of Africa after it was barred from docking in Mauritius 'to avoid health risks' Politico Reporter on MSNBC Frets That Christian Nationalists Believe Americans' Rights Come From God, Not the Government (VIDEO) “Waves of refugees in their millions will be unleashed…reaching far into…the USA”: Billy Meier, 1947 Banks will 'tokenize' customer deposits to pave way

--- DOCUMENT 1 PREVIEW ---
NEPA climate overhaul could unleash energy projects The White House is poised to exclude climate considerations from its rewrite of rules surrounding the nation's core environmental law, according to a draft memo obtained by E&E News. If finalized, the proposed changes could clear the way for energy projects like the Keystone XL pipeline that federal judges Iran could launch cyberattacks after U.S. strike — experts Polar bear study sets road map for ANWR seismic testing Energy Transfer to pay record fine over Pa. explosion, fire N.M. researchers get funds for methane leak detection Group wants court review of shutdown costs at coal plant Navajo maintains electric line that carried coal-fired power Get all of the stories in today's Energywire, plus an in-depth archive with thousands of articles on your issues, detailed Special Reports and much more at https://www.energywire.com. Forgot your passcodes? Call us at 202-628-6500 now and we'll set you up instantly. To send a press release, f

--- DOCUMENT 2 PREVIEW ---
Printed for the use of the Committee on the Judiciary Available http://judiciary.house.gov or www.govinfo.gov PERRY APELBAUM, Majority Staff Director & Chief Counsel Article, A blog Post by Jonathan Turley, ‘‘White House Issues Defiant Letter Refusing to Cooperate in Impeachment Proceedings,’’ October 9, 2019 Sub- mitted by the Honorable Jerrold Nadler ............................................................ Article, ABC News, ‘‘ABC News’ Oval Office Interview with President Trump,’’ June 13, 2019 Submitted by the Honorable Jerrold Nadler .............. Article, ABC News, ‘‘FBI director pushes back on debunked conspiracy theory about 2016 election interference,’’ December 9, 2019 Submitted by the Hon- orable Jerrold Nadler ........................................................................................... Article, ABC News, ‘‘President Trump’s Former National Security Advisor ‘deeply disturbed’ by Ukraine scandal: ‘whole world is watching,’ ’’ Sep- tember 29, 2019 Submitted

--- DOCUMENT 3 PREVIEW ---
RUSSIAN ACTIVE MEASURES CAMPAIGNS AND INTERFERENCE (U) FINDINGS ·········································································································· ......... (U) METHODOLOGY ....................................................................................................... (U) The Committee's Authority and Focus ..................................................................... (U) The Committee's Power to Investigate .................................................................... (U) The Committee's Counterintelligence Focus ........................................................... (U) A Bipartisan Investigation ......................................................... ; .............................. (U) Legal Issues Encountered ........................................ '.. ............................................... (U) Executive Privilege ........... .' ....................................................................................... 8

--- DOCUMENT 4 PREVIEW ---
DECEMBER 15, 2019.—Referred to the House Calendar and ordered to be IMPEACHMENT OF DONALD J. TRUMP PRESIDENT OF THE UNITED STATES AARON HILLER, Deputy Chief Counsel and Chief Oversight Counsel DANIEL SCHWARZ, Director of Strategic Communications MOH SHARMA, Director of Member Services and Outreach and Policy Advisor JOHN WILLIAMS, Parliamentarian and Senior Counsel JAMES PARK, Chief Counsel of Constitution Subcommittee BOBBY PARMITER, Deputy Staff Director, Chief Counsel PAUL TAYLOR, Chief Counsel, Constitution Subcommittee Introduction .............................................................................................................. The Impeachment Inquiry ...................................................................................... Constitutional Grounds for Presidential Impeachment ........................................ Article I: Abuse of Power ........................................................................................ Article II: Obstruction of

### 6. Chunks

In [20]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=150
)

In [30]:
chunks = []

for doc_id, doc in enumerate(documents):
    split_texts = text_splitter.split_text(
        doc["text"]
    )

    for chunk_id, chunk_text in enumerate(split_texts):
        chunks.append({
            "claim_id": doc["claim_id"],
            "document_id": doc_id,
            "chunk_id": chunk_id,
            "url": doc["url"],
            "source_type": doc["source_type"],
            "query": doc["query"],
            "text": chunk_text
        })

In [ ]:
print("Documents:", len(documents))
print("Chunks:", len(chunks))

Documents: 431
Chunks: 31051

Cada chunks conserva correctamente claim_id, document_id, url, source_type, query y el texto del chunk.

In [ ]:
chunks[0]

{'claim_id': '0',
 'document_id': 0,
 'chunk_id': 0,
 'url': 'https://en.wikipedia.org/wiki/Hunter_Biden',
 'source_type': 'gold',
 'query': '_',
 'text': "Robert Hunter Biden (born February 4, 1970) is an American attorney and businessman. Biden has also worked as a hedge fund principal and a venture capital and private equity fund investor. He formerly worked as a banker, a lobbyist, and a legal representative for lobbying firms. Biden is the second son of U.S. President Joe Biden and his first wife, Neilia Hunter Biden. In 1972, when Biden was two years old, a car crash killed his mother, who was driving, and his one-year-old sister, Naomi, and seriously injured both him and his older brother, Beau. In his memoir, Beautiful Things, Biden wrote of his struggles with drug and alcohol abuse, which escalated after Beau's 2015 death from brain cancer.[1][2] He was discharged from the U.S. Navy Reserve shortly after his commissioning, due to a failed drug test. Biden was a founding board member of BHR Partners,[3] a Chinese investment company, in 2013. He served on the board of Burisma Holdings, one of the largest private natural gas"}

¿Cuantos chunks genera cada URL?

In [ ]:
chunks_per_document = Counter(
    chunk["document_id"]
    for chunk in chunks
)

pd.Series(
    list(chunks_per_document.values())
).describe()

count     431.000000
mean       72.044084
std       339.319093
min         1.000000
25%         4.000000
50%         6.000000
75%        13.000000
max      4237.000000
dtype: float64

- Tenemos 431 documentos;
- Cada documento genera en promedio ~72 chunks;
- El documento típico genera bastante menos: la mediana es ~6;
- El 75% genera 13 chunks o menos;
- Un documento extremo genera 4.237 chunks.

In [ ]:
print(
    "Maximum chunks from one document:",
    max(chunks_per_document.values())
)

Maximum chunks from one document: 4237

In [ ]:
sum(chunks_per_document.values()) #Número total de chunks

31051

El chunking funciona técnicamente, pero todavía no pasamos a embeddings sin controlar el efecto de los documentos extremadamente grandes.

In [ ]:
chunk_counts = pd.Series(
    chunks_per_document
).sort_values(ascending=False)

chunk_counts.head(10)

321    4237
29     2783
335    2374
91     2301
132    1995
133    1806
341    1102
46     1078
144     912
349     851
dtype: int64

¿Qué porcentaje del vector store acabaría perteneciendo solo a los 10 documentos más grandes?

In [ ]:
top_10_chunks = chunk_counts.head(10).sum()

print(
    "Chunks from top 10 largest documents:",
    top_10_chunks
)

print(
    "Percentage of all chunks:",
    round(
        100 * top_10_chunks / len(chunks),
        2
    )
)

Chunks from top 10 largest documents: 19439
Percentage of all chunks: 62.6

Los diez documentos que generan la mayor cantidad de chunks representan el 62,6% de todos los chunks para el claim 0. Esto refleja la presencia de varias páginas web y documentos PDF muy grandes en la base de conocimientos de AVeriTeC. Estos documentos no se eliminarán porque podrían contener evidencia relevante; en su lugar, la recuperación incluirá más adelante una restricción de diversidad de fuentes para evitar que un solo documento domine el conjunto final de evidencia.

Todos los chunks participarán en la búsqueda y cualquiera podrá ser recuperado. Lo que limitaremos es cuántos fragmentos de una misma fuente llegarán al conjunto final de evidencias.

### 7. Embeddings

¿Que queremos saber? ¿qué vectores de chunks están más cerca del vector de la claim?

In [ ]:
len(chunks)

31051

In [21]:
embedding_model = SentenceTransformer("BAAI/bge-small-en-v1.5")

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 2303.64it/s]

Aún no embebemos los 30961 chunks, probamos apenas con uno.

In [ ]:
sample_text = chunks[0]["text"]

sample_embedding = embedding_model.encode(
    sample_text,
    normalize_embeddings=True
)

print(type(sample_embedding))
print(sample_embedding.shape) #Las 384 dimensiones conjuntamente representan la información semántica del texto.

<class 'numpy.ndarray'>
(384,)

Embedding del claim 0:

In [ ]:
claim_0 = train_df.iloc[0]["claim"]

In [ ]:
claim_0

'Hunter Biden had no experience in Ukraine or in the energy sector when he joined the board of Burisma.'

In [ ]:
claim_embedding = embedding_model.encode(
    claim_0,
    normalize_embeddings=True
)

print(claim_embedding.shape)

(384,)

Vamos a hacer una similitud manual.

In [ ]:
similarity = np.dot(
    claim_embedding,
    sample_embedding
)

print(similarity) #Cuanto mayor sea, más similitud semántica.
#No es probabilidad de que el chunk demuestre que la claim es verdadera. Solo significa: este fragmento parece 
#semánticamente relacionado con la claim.

# Un chunk puede tener una similitud altísima y estar refutando la claim.
# Eso lo veremos verificado después el Evidence Verifier.

0.6494279

In [ ]:
print(sample_embedding.shape)
print(claim_embedding.shape)
print(similarity)

(384,)
(384,)
0.6494279

Generando embeddings completos:

In [ ]:
chunk_texts = [chunk["text"] for chunk in chunks]

In [ ]:
chunk_embeddings = embedding_model.encode(
    chunk_texts,
    batch_size=64,
    show_progress_bar=True,
    normalize_embeddings=True
)

Batches: 100%|██████████| 486/486 [2:04:23<00:00, 15.36s/it]

In [ ]:
print(type(chunk_embeddings))
print(chunk_embeddings.shape) #30.961 vectores de 384 dimensiones

<class 'numpy.ndarray'>
(31051, 384)

### 8. Vector store

En este paso, crearemos la estructura que permite buscar eficientemente qué vectores son más parecidos a una query (claim).

In [ ]:
embedding_dim = chunk_embeddings.shape[1]

In [ ]:
index = faiss.IndexFlatIP(embedding_dim)

In [ ]:
print(index.ntotal) #tenemos que añadir los embeddings

0

In [ ]:
chunk_embeddings_faiss = (chunk_embeddings.astype("float32"))

In [ ]:
index.add(chunk_embeddings_faiss)

In [ ]:
print("Vectores indexados:",index.ntotal)

Vectores indexados: 31051

In [ ]:
query_embedding = (
    claim_embedding
    .astype("float32")
    .reshape(1, -1)
)

In [ ]:
query_embedding.shape

(1, 384)

### 9. Retrieval

Recuperamos los 10 más proximos:

In [ ]:
k = 10
scores, indices = index.search(
    query_embedding,
    k
)

In [ ]:
print(scores.shape)
print(indices.shape)

(1, 10)
(1, 10)

In [ ]:
print(scores[0]) #score es similitud semántica.
print(indices[0])

[0.8068609  0.79276973 0.7905766  0.75146747 0.74707484 0.74565995
 0.73625815 0.7356435  0.7335564  0.73089916]
[ 3058  5644  3059  8344  5908   153   163  5915 23765 30980]

El chunk chunks[3058] es uno de los fragmentos con mayor similitud semántica respecto al claim 0.

In [ ]:
retrieved_chunks = []

for score, idx in zip(
    scores[0],
    indices[0]
):
    chunk = chunks[int(idx)]

    retrieved_chunks.append({
        "score": float(score),
        "document_id": chunk["document_id"],
        "chunk_id": chunk["chunk_id"],
        "url": chunk["url"],
        "source_type": chunk["source_type"],
        "text": chunk["text"]
    })

El claim que estamos buscando es: `Hunter Biden had no experience in Ukraine or in the energy sector when he joined the board of Burisma`

In [ ]:
for i, result in enumerate(
    retrieved_chunks,
    start=1
):
    print(f"\n--- RESULT {i} ---")
    print("Score:", result["score"])
    print(
        "Document:",
        result["document_id"]
    )
    print(
        "Chunk:",
        result["chunk_id"]
    )
    print("URL:", result["url"])
    print(
        "Text:",
        result["text"][:700]
    )

--- RESULT 1 ---
Score: 0.8068609237670898
Document: 30
Chunk: 0
URL: https://www.washingtonexaminer.com/?p=731178
Text: A defense attorney for President Trump’s Senate impeachment trial slammed Hunter Biden’s employment with Ukrainian gas company Burisma Holdings, saying the former vice president’s son lacked the experience necessary to land the job and its salary. “Hunter Biden is paid over $83,000 a month, while the average American family of four during that time, each year, made less than $54,000, and that’s according to U.S. Census Bureau during that time,” said Pam Bondi. Bondi, 54, submitted a list of articles she said shows Biden did not have the background required to sit on the board of Burisma. She suggested it was his connection to his father that helped secure the lucrative gig and shield him fro

--- RESULT 2 ---
Score: 0.792769730091095
Document: 61
Chunk: 1
URL: https://www.cnn.com/politics/live-news/impeachment-hearing-11-19-19/h_e2df04c755f6130b6b48459d8a6d6171
Text: of the inquiry, Republicans have pointed out that Hunter Biden did not have any experience in corporate governance or in the energy sector before taking the job at Burisma. Hunter Biden previously said that it showed “poor judgment” to take the job while his dad led US policy toward Ukraine, but he denied that there were any conflicts of interest.

--- RESULT 3 ---
Score: 0.7905765771865845
Document: 30
Chunk: 1
URL: https://www.washingtonexaminer.com/?p=731178
Text: any of the usual qualifications of a board member,” she said. “Hunter Biden had no experience in natural gas, no experience in the energy sector, no experience with Ukrainian regulatory affairs. She added, “So, naturally, the media has asked questions about his board membership. Why was Hunter Biden on this board?” Bondi highlights Hunter Biden’s disproportionate pay and lack of experience in Ukrainehttps://t.co/vOncfdIxnM pic.twitter.com/HEzH7nPk6B Hunter Biden, 50, has been pivotal to the defense team as it seeks to draw contrasts between Trump and the Bidens over their dealings in Ukraine. He earned $50,000 a month on the board of Burisma Holdings, a natural gas firm, from 2014 to 2019. S

--- RESULT 4 ---
Score: 0.7514674663543701
Document: 100
Chunk: 6
URL: https://www.voanews.com/a/usa_us-politics_hunter-biden-tried-keep-low-profile-trump-wouldnt-let-him/6177081.html
Text: a stake in the firm until after his father left office in 2017. Then in April 2014, just two months after protests overthrew Ukraine’s pro-Moscow President Viktor Yanukovych, Hunter Biden, at a partner’s suggestion, joined the board of Burisma, a natural gas company founded by Yanukovych ally Mykola Zlochevsky. Former Polish President Aleksander Kwaśniewski was another high-profile board member. At the time, Vice President Biden was steering the Obama administration efforts to strengthen the nascent democratic government in Kyiv. At the Obama administration’s urging, the new government was investigating whether Zlochevsky had used his office for Burisma’s financial benefit. To rights activis

--- RESULT 5 ---
Score: 0.7470748424530029
Document: 86
Chunk: 2
URL: https://www.csmonitor.com/USA/Politics/2019/0930/Joe-and-Hunter-Biden-Three-questions-about-Ukraine-corruption
Text: leveled at the Bidens. In April 2014, Hunter Biden joined the board of directors of Burisma Holdings, the largest natural gas producer in Ukraine. At the time Burisma was whitewashing its image, say anti-corruption activists, by inviting high-profile Americans and Europeans to join the board. The former president of Poland, Aleksander Kwasniewski, had recently been added to the board, as had one of Hunter’s investment company partners, Devon Archer. Hunter Biden had no previous experience in the natural gas industry, Ukraine, or regulatory oversight, as his title at Burisma suggested. “Adding these people with these fancy names to the board made Burisma, [which] got licenses to extract gas i

--- RESULT 6 ---
Score: 0.7456599473953247
Document: 9
Chunk: 0
URL: https://www.eenews.net/articles/how-a-small-gas-firm-in-ukraine-led-to-impeachment-inquiry/
Text: A hiring decision by an obscure Ukranian energy company five years ago sparked the historic House inquiry that could lead to just the third impeachment of an American president in almost 250 years. In 2014, Burisma Holdings hired Hunter Biden, the son of then-Vice President Joe Biden, to be on its board. It was a job that paid Hunter Biden, who was not an energy expert, up to $50,000 a month for consulting on "matters of transparency," among other functions, according to a release from the company at the time. "Burisma’s track record of innovations and industry leadership in the field of natural gas means that it can be a strong driver of a strong economy in Ukraine," Hunter Biden said in a

--- RESULT 7 ---
Score: 0.7362581491470337
Document: 13
Chunk: 0
URL: https://www.cbsnews.com/news/hunter-biden-interview-he-says-in-interview-he-did-nothing-improper-in-work-for-ukrainian-energy-company-burisma/
Text: Hunter Biden says he did "nothing improper" in work for Ukrainian company Hunter Biden, the son of presidential Democratic candidate Joe Biden, admitted in an interview on ABC News' "Good Morning America" that he exercised "poor judgment" in working on the board of a Ukrainian energy company—but said he did "nothing improper" in doing so. His role on the board of Burisma spurred President Donald Trump to ask Ukraine's president in a now-infamous July 25 call to investigate the Bidens for corruption and to tell reporters earlier this month that both Ukraine and China should look into the Bidens. The president's Ukraine call led the U.S. House to launch a formal impeachment inquiry against Mr.

--- RESULT 8 ---
Score: 0.7356435060501099
Document: 87
Chunk: 1
URL: https://apnews.com/united-states-presidential-election-9d4595ba4f3140c6bb6a3473a91f4a4c
Text: officials to investigate the Bidens. Hunter Biden was named a paid board member of Burisma Holdings in April 2014. The company’s founder was a political ally of Viktor Yanukovych, Ukraine’s Russia-friendly president, who was driven out in February 2014 by mass protests. Yanukovych’s ouster prompted the Obama administration to move quickly to deepen ties with Ukraine’s new government. Joe Biden played a leading role, traveling to Ukraine and speaking frequently with its new Western-friendly president. The younger Biden’s business role raised concerns among anticorruption advocates that Burisma was seeking to gain influence with the Obama administration. At the time, the company ran a natural

--- RESULT 9 ---
Score: 0.7335563898086548
Document: 335
Chunk: 1006
URL: https://www.govinfo.gov/content/pkg/CHRG-116hhrg39405/pdf/CHRG-116hhrg39405.pdf
Text: Biden's work for Burisma prompted concerns among State Department officials at the time that the connection could complicate Vice President Biden's diplomacy in Ukraine, former officials said. "I have had no role whatsoever in relation to any investigation of Burisma, or any of its officers," Hunter Biden said Wednesday in a statement. "1 explicitly limited my roJe to focus on corporate governance best practices to facilitate Burisma's desire to expand g1obally." Hunter Biden, who left Burisma's board last month, was one of many politically prominent Americans of both major parties who made money in Ukraine over the last decade. In several cases - most notably that of Paul Manafort, Presiden

--- RESULT 10 ---
Score: 0.7308991551399231
Document: 421
Chunk: 2
URL: https://www.nbcnews.com/politics/donald-trump/hunter-biden-did-not-violate-anything-former-ukrainian-prosecutor-says-n1059136
Text: investigation,” he told the Post. Lutsenko added that whatever wrongdoing there might have been at Burisma took place before Hunter Biden joined the company. “Hunter Biden cannot be responsible for violations of the management of Burisma that took place two years before his arrival,” Lutsenko told the Post.

Los primeros resultados contienen precisamente conceptos como Hunter Biden, Burisma, Ukraine, energy sector, experience, natural gas, etc. No está recuperando simplemente documentos sobre política estadounidense en general.

Según los documentos recuperados, en la búsqueda de los 10 más cercanos a nuestra claim, el retriever está encontrando exactamente la información que se esperaba, pero aqui todavía no nos dice: SUPPORTED O REFUTED

En este ejemplo concreto, la concentración de chunks no está provocando que una sola URL domine la búsqueda, como nos temíamos.

El retrieval semántico basado en embeddings recupera fragmentos altamente relacionados con la claim de consulta. En la primera prueba, 9 de los 10 resultados proceden de documentos distintos, por lo que la fuerte concentración de chunks observada en algunos documentos extensos no ha provocado, en este caso, una monopolización evidente de los resultados.Pero `atención`, aqui tenemos una sola claim, no podemos todavía afirmar que el retriever funciona perfectamente.

### 10. Retrieval Evaluation usando Averitec (Train)

Vamos a hacer una comprobación intermedia, usando la clasificación que ya proporciona averitec

In [ ]:
gold_questions = train_df.iloc[0]["questions"]

for i, question in enumerate(gold_questions):
    print(f"\n--- GOLD QUESTION {i} ---")
    print("Question:", question["question"])

    for answer in question["answers"]:
        print("Answer:", answer["answer"])
        print("Source URL:", answer["source_url"])

--- GOLD QUESTION 0 ---
Question: Did Hunter Biden have any experience in the energy sector at the time he joined the board of the  Burisma energy company in 2014
Answer: No
Source URL: https://en.wikipedia.org/wiki/Hunter_Biden

--- GOLD QUESTION 1 ---
Question: Did Hunter Biden have any experience in Ukraine at the time he joined the board of the  Burisma energy company in 2014
Answer: No
Source URL: https://en.wikipedia.org/wiki/Hunter_Biden

Aunque nuestro retrieval no haya devuelto Wikipedia en el Top-10, sí ha encontrado otro documento que contiene la información necesaria para verificar las dos cuestiones.

¿Cuál es el mejor chunk de la fuente gold y en qué posición global estaría?

In [ ]:
gold_url = "https://en.wikipedia.org/wiki/Hunter_Biden"

gold_indices = [
    i
    for i, chunk in enumerate(chunks)
    if chunk["url"] == gold_url
]

print("Number of gold chunks:", len(gold_indices))

Number of gold chunks: 90

In [ ]:
gold_scores = np.array([
    np.dot(
        query_embedding[0],
        chunk_embeddings_faiss[i]
    )
    for i in gold_indices
])

best_gold_position = np.argmax(gold_scores)

best_gold_idx = gold_indices[best_gold_position]
best_gold_score = gold_scores[best_gold_position]

print("Best gold chunk index:", best_gold_idx)
print("Best gold score:", best_gold_score)
print()
print(chunks[best_gold_idx]["text"][:1000])

Best gold chunk index: 13
Best gold score: 0.7020207

an attorney with Boies Schiller Flexner, and a consulting firm in which Biden is a partner was also retained by Burisma.[65][66][67] Christopher Heinz, John Kerry's stepson, opposed his partners Devon Archer and Hunter Biden joining the board in 2014 due to the reputational risk.[63] Biden served on the board of Burisma until his term expired in April 2019,[66] receiving compensation of up to $50,000 per month in some months.[66][65] Because Joe Biden played a major role in U.S. policy towards Ukraine, some Ukrainian anti-corruption advocates[68][69] and Obama administration officials expressed concern that Hunter Biden having joined the board could create the appearance of a conflict of interest and undermine Joe Biden's anti-corruption work in Ukraine.[19][63] While serving as vice president, Joe Biden joined other Western leaders in encouraging the government of Ukraine to fire the country's top prosecutor Viktor Shokin,[70][71] who was widely criticized for blocking corruption

La evidencia gold existe y es bastante relevante, pero hay 44 chunks que el modelo considera semánticamente más parecidos.

In [ ]:
all_scores = np.dot(
    chunk_embeddings_faiss,
    query_embedding[0]
)

gold_rank = (
    np.sum(all_scores > best_gold_score)
    + 1
)

print("Best gold chunk rank:", gold_rank)

Best gold chunk rank: 45

El mejor chunk perteneciente a la fuente gold de Wikipedia ocupa el rank 45 dentro de todos los chunks ordenados por similitud con la claim 0.

### 11. Funciones reutilizables y empaquetado de funciones para el Pipeline final

A partir de este punto se agrupan las versiones definitivas de las funciones desarrolladas durante las etapas anteriores para poder reutilizarlas en el pipeline completo y además empaquetamos las piezas usadas individualmente como funciones definitivas.

In [22]:
def clean_text_parts(text_parts):
    cleaned_parts = []
    seen = set()

    for part in text_parts:
        if not isinstance(part, str):
            continue

        part = part.strip()

        if not part:
            continue

        # Evita fragmentos exactamente repetidos
        if part in seen:
            continue

        seen.add(part)
        cleaned_parts.append(part)

    return cleaned_parts

In [23]:
def build_document(record):
    text_parts = clean_text_parts(
        record.get("url2text", [])
    )

    text = " ".join(text_parts)

    return {
        "claim_id": record.get("claim_id"),
        "url": record.get("url"),
        "source_type": record.get("type"),
        "query": record.get("query"),
        "text_parts": text_parts,
        "text": text
    }

In [24]:
def load_knowledge_records(knowledge_zip, claim_id):
    """
    Carga los registros del Knowledge Store asociados a una claim de AVeriTeC.

    La función localiza el archivo JSON correspondiente a la claim aunque se encuentre dentro de una 
    subcarpeta del ZIP, permitiendo utilizar la misma función con los Knowledge Stores de train y dev.

    Parameters
    ----------
    knowledge_zip : Path
        Ruta al archivo ZIP del Knowledge Store.

    claim_id : int
        Identificador de la claim.

    Returns
    -------
    list
        Registros del Knowledge Store asociados a la claim.
    """

    target_file = f"{claim_id}.json"

    knowledge_records = []

    with zipfile.ZipFile(knowledge_zip, "r") as zip_ref:

        # Buscamos el JSON de la claim independientemente de la carpeta interna del ZIP.
        matching_files = [
            name
            for name in zip_ref.namelist()
            if name.rsplit("/", 1)[-1] == target_file
        ]

        if not matching_files:
            raise FileNotFoundError(
                f"No se encontró {target_file} dentro de {knowledge_zip}"
            )

        file_name = matching_files[0]

        with zip_ref.open(file_name) as f:

            for line in f:

                line = line.decode("utf-8").strip()

                if line:
                    knowledge_records.append(
                        json.loads(line)
                    )

    return knowledge_records

In [ ]:
def retrieve_evidence(
    claim,
    embedding_model,
    index,
    chunks,
    candidate_k=50,
    final_k=10,
    max_chunks_per_document=2,
):
    """
    Recupera evidencias semánticamente relevantes para una afirmación, aplicando además una restricción de
    diversidad por documento.

    Parameters
    ----------
    claim : str
        Afirmación que se quiere verificar.

    embedding_model
        Modelo de SentenceTransformer utilizado para generar el embedding de la afirmación.

    index
        Índice FAISS que contiene los embeddings de los chunks.

    chunks : list[dict]
        Lista de chunks con su texto y metadatos.
        El orden de esta lista debe coincidir con el orden de los vectores almacenados en el índice FAISS.

    candidate_k : int, default=50
        Número de candidatos iniciales recuperados mediante FAISS antes de aplicar la restricción de 
        diversidad.

    final_k : int, default=10
        Número máximo de chunks de evidencia que se devolverán finalmente.

    max_chunks_per_document : int, default=2
        Número máximo de chunks que se permite seleccionar procedentes del mismo documento.

    Returns
    -------
    list[dict]
        Lista de evidencias recuperadas. Para cada chunk se devuelve su score de similitud, identificador 
        del documento, identificador del chunk, URL, tipo de fuente y texto.
    """

    # 1. Generamos el embedding de la afirmación
    query_embedding = embedding_model.encode(
        claim,
        normalize_embeddings=True
    )

    # FAISS espera una matriz bidimensional:
    # (número de consultas, dimensión del embedding)
    query_embedding = (
        query_embedding
        .astype("float32")
        .reshape(1, -1)
    )

    # 2. Recuperamos un conjunto inicial amplio de candidatos
    # ordenados por similitud semántica con la afirmación
    scores, indices = index.search(
        query_embedding,
        candidate_k
    )

    # 3. Seleccionamos las evidencias finales aplicando
    # diversidad por documento
    selected = []

    # Guarda cuántos chunks hemos seleccionado de cada documento
    document_counts = {}

    for score, idx in zip(scores[0], indices[0]):

        # FAISS puede devolver -1 si no encuentra suficientes resultados
        if idx == -1:
            continue

        chunk = chunks[int(idx)]

        document_id = chunk["document_id"]

        # Número de chunks ya seleccionados de este documento
        current_count = document_counts.get(
            document_id,
            0
        )

        # Si ya hemos alcanzado el máximo permitido para este documento, ignoramos este chunk
        if current_count >= max_chunks_per_document:
            continue

        # Añadimos el chunk al conjunto final de evidencias
        selected.append({
            "score": float(score),
            "document_id": document_id,
            "chunk_id": chunk["chunk_id"],
            "url": chunk["url"],
            "source_type": chunk["source_type"],
            "text": chunk["text"],
        })

        # Actualizamos el contador de chunks seleccionados para este documento
        document_counts[document_id] = (
            current_count + 1
        )

        # Terminamos cuando alcanzamos el número deseado de evidencias finales
        if len(selected) == final_k:
            break

    return selected

In [26]:
def select_relevant_documents(
    claim,
    documents,
    top_n=100,
):
    """
    Preselecciona los documentos más relacionados con una afirmación mediante similitud TF-IDF.

    Esta etapa se utiliza como filtro previo al chunking y a la generación de embeddings, con el objetivo de reducir el 
    coste computacional del retrieval semántico.

    Parameters
    ----------
    claim : str
        Afirmación para la que se quieren recuperar evidencias.

    documents : list[dict]
        Lista completa de documentos asociados al knowledge store
        de la claim.

    top_n : int, default=100
        Número máximo de documentos que se conservarán después
        de la preselección.

    Returns
    -------
    list[dict]
        Documentos seleccionados y ordenados de mayor a menor
        similitud TF-IDF con la afirmación.
    """

    document_texts = [
        document["text"]
        for document in documents
    ]

    vectorizer = TfidfVectorizer(
        stop_words="english",
        max_features=30000
    )

    # Representamos la claim y los documentos en el mismo
    # espacio TF-IDF
    tfidf_matrix = vectorizer.fit_transform(
        [claim] + document_texts
    )

    claim_vector = tfidf_matrix[0]
    document_vectors = tfidf_matrix[1:]

    similarities = cosine_similarity(
        claim_vector,
        document_vectors
    )[0]

    ranked_indices = similarities.argsort()[::-1]

    selected_documents = []

    for idx in ranked_indices[:top_n]:

        document = documents[int(idx)].copy()

        document["document_score"] = float(
            similarities[idx]
        )

        selected_documents.append(document)

    return selected_documents

In [ ]:
def deduplicate_documents_by_url(documents):
    """
    Elimina documentos duplicados que apuntan a la misma URL.

    Se conserva únicamente la primera aparición de cada URL.

    Parameters
    ----------
    documents : list
        Lista de documentos normalizados.

    Returns
    -------
    list
        Lista de documentos sin URLs duplicadas.
    """
    documents_by_url = {}

    for document in documents:
        url = document["url"]

        if url not in documents_by_url:
            documents_by_url[url] = document
            continue

        current_document = documents_by_url[url]

        if len(document["text"]) > len(current_document["text"]):
            documents_by_url[url] = document

    return list(documents_by_url.values())

In [ ]:
def build_claim_index(
    claim,
    knowledge_records,
    embedding_model,
    text_splitter,
    max_chunks_before_filter=40000,
    top_n_documents=100,
):
    """
    Construye el índice vectorial de una claim de AVeriTeC.

    El proceso:
    1. transforma los registros del Knowledge Store en documentos;
    2. elimina documentos vacíos;
    3. elimina URLs duplicadas;
    4. realiza un chunking inicial;
    5. aplica una preselección TF-IDF si el número de chunks
       supera el umbral definido;
    6. genera los chunks definitivos;
    7. calcula embeddings;
    8. construye un índice FAISS.

    Parameters
    ----------
    claim : str
        Afirmación para la que se quiere construir el índice.

    knowledge_records : list[dict]
        Registros del knowledge store asociados a la claim.

    embedding_model
        Modelo SentenceTransformer utilizado para generar embeddings.

    text_splitter
        Objeto utilizado para dividir los documentos en chunks.

    max_chunks_before_filter : int, default=40000
        Número máximo de chunks que se permite procesar directamente.
        Si se supera este valor, se aplica una preselección TF-IDF de documentos.

    top_n_documents : int, default=100
        Número de documentos que se conservarán cuando sea necesario aplicar la preselección TF-IDF.

    Returns
    -------
    chunks : list[dict]
        Lista final de chunks utilizados para construir el índice.

    index
        Índice FAISS que contiene los embeddings de los chunks.

    info : dict
        Información sobre el proceso de construcción del índice, incluyendo número de documentos, número de chunks y si
        se utilizó preselección TF-IDF.
    """

    # 1. Conservamos únicamente los registros que contienen texto
    retrieval_records = [
        record
        for record in knowledge_records
        if record.get("url2text")
    ]

    # 2. Construimos los documentos
    documents = [
        build_document(record)
        for record in retrieval_records
    ]

    original_documents = len(documents)

    # 3. Eliminamos URLs duplicadas
    documents = deduplicate_documents_by_url(
        documents
    )

    unique_documents = len(documents)

    # 4. Generamos inicialmente los chunks para conocer el tamaño real del corpus
    chunks = []

    for document_id, document in enumerate(documents):

        split_texts = text_splitter.split_text(
            document["text"]
        )

        for chunk_id, chunk_text in enumerate(split_texts):

            chunks.append({
                "claim_id": document["claim_id"],
                "document_id": document_id,
                "chunk_id": chunk_id,
                "url": document["url"],
                "source_type": document["source_type"],
                "query": document["query"],
                "text": chunk_text,
            })

    initial_chunks = len(chunks)

    # 5. Comprobamos si el corpus es demasiado grande
    use_tfidf_filter = (
        initial_chunks > max_chunks_before_filter
    )

    if use_tfidf_filter:

        print(
            f"Corpus grande detectado: {initial_chunks} chunks."
        )

        print(
            f"Se aplicará TF-IDF para seleccionar "
            f"{top_n_documents} documentos."
        )

        # Seleccionamos los documentos más relacionados
        documents = select_relevant_documents(
            claim=claim,
            documents=documents,
            top_n=top_n_documents
        )

        # Volvemos a crear los chunks,
        # esta vez únicamente con los documentos seleccionados
        chunks = []

        for document_id, document in enumerate(documents):

            split_texts = text_splitter.split_text(
                document["text"]
            )

            for chunk_id, chunk_text in enumerate(split_texts):

                chunks.append({
                    "claim_id": document["claim_id"],
                    "document_id": document_id,
                    "chunk_id": chunk_id,
                    "url": document["url"],
                    "source_type": document["source_type"],
                    "query": document["query"],
                    "text": chunk_text,
                })

    else:

        print(
            f"Corpus manejable: {initial_chunks} chunks."
        )

        print(
            "No es necesario aplicar preselección TF-IDF."
        )

    final_chunks = len(chunks)

    print("Documentos originales:", original_documents)
    print("Documentos únicos:", unique_documents)
    print("Documentos finales:", len(documents))
    print("Chunks iniciales:", initial_chunks)
    print("Chunks finales:", final_chunks)

    # 6. Extraemos únicamente el texto de los chunks
    chunk_texts = [
        chunk["text"]
        for chunk in chunks
    ]

    # 7. Generamos los embeddings SOLO del corpus final
    chunk_embeddings = embedding_model.encode(
        chunk_texts,
        batch_size=64,
        show_progress_bar=True,
        normalize_embeddings=True
    )

    chunk_embeddings = chunk_embeddings.astype(
        "float32"
    )

    # 8. Construimos el índice FAISS
    embedding_dim = chunk_embeddings.shape[1]

    index = faiss.IndexFlatIP(
        embedding_dim
    )

    index.add(
        chunk_embeddings
    )

    # Información útil para analizar posteriormente el proceso
    info = {
        "original_documents": original_documents,
        "unique_documents": unique_documents,
        "final_documents": len(documents),
        "initial_chunks": initial_chunks,
        "final_chunks": final_chunks,
        "tfidf_filter_used": use_tfidf_filter,
    }

    return chunks, index, info

Probamos las funciones:

In [39]:
knowledge_records_1 = load_knowledge_records(
    knowledge_zip,
    claim_id=1
)

claim_1 = train_df.iloc[1]["claim"]

chunks_1, index_1, info_1 = build_claim_index(
    claim=claim_1,
    knowledge_records=knowledge_records_1,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    max_chunks_before_filter=40000,
    top_n_documents=100,
)

Corpus grande detectado: 69700 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 768
Documentos únicos: 767
Documentos finales: 100
Chunks iniciales: 69700
Chunks finales: 1845

Batches: 100%|██████████| 29/29 [03:28<00:00,  7.20s/it]

In [44]:
results = retrieve_evidence(
    claim=claim_1,
    embedding_model=embedding_model,
    index=index_1,
    chunks=chunks_1,
    candidate_k=50,
    final_k=10,
    max_chunks_per_document=2,
)

In [ ]:
for i, result in enumerate(results, start=1):

    print(f"\n--- RESULT {i} ---")
    print("Score:", round(result["score"],3))
    print("Document:", result["document_id"])
    print("Chunk:", result["chunk_id"])
    print("URL:", result["url"])
    print("Text:", result["text"][:700])

--- RESULT 1 ---
Score: 0.876
Document: 1
Chunk: 0
URL: https://trumpwhitehouse.archives.gov/briefings-statements/president-donald-j-trump-achieved-biggest-tax-cuts-reforms-american-history/
Text: BIGGEST TAX CUTS AND REFORMS: Because of President Donald J. Trump, Americans will benefit from the biggest tax cuts and reforms in American history. - President Trump’s tax cuts are the biggest gross tax cuts in American history, cutting over $5.5 trillion in taxes over ten years. - The President’s tax law included substantial reforms to make taxes simpler and fairer, which helped offset the cost of the tax cuts and thereby limit the net tax cut to $1.5 trillion. - President Trump cut the corporate tax rate from 35 percent to 21 percent, the largest percentage point reduction of the top marginal rate in history. - President Trump’s tax cuts include the biggest increase in the child tax cred

--- RESULT 2 ---
Score: 0.845
Document: 11
Chunk: 0
URL: https://www.theguardian.com/us-news/2017/apr/26/trump-tax-cuts-proposal-deductions-brackets
Text: The Trump administration unveiled what it called the biggest tax cuts “in history” on Wednesday, in a move that will simplify the US tax system, slash taxes for businesses large and small – including Trump’s own – eliminate inheritance taxes and set the president on a collision course with Congress over the likely $2tn-plus cost of the proposal. Critics immediately called it “basically a huge tax cut for the rich”. The plan would cut the US’s individual income tax brackets from seven to three (10%, 25% and 35%) and slash US corporate tax rates from 35% to 15%. “We have a once-in-a-generation opportunity to do something really big,” said Gary Cohn, chief economic adviser to Donald Trump. “Thi

--- RESULT 3 ---
Score: 0.842
Document: 2
Chunk: 0
URL: https://www.cnn.com/2017/12/15/politics/is-trumps-bill-largest-tax-cut-in-history-no/index.html
Text: Editor’s Note: Editor’s note: An earlier version of this story first appeared in December. Trump has said the tax cuts Congress passed would be the biggest ever They would not, according to the way the government measures tax cuts President Donald Trump has bragged – and did so again during his State of the Union address Tuesday – that the tax cuts Congress passed would be the biggest in history. There’s no doubt the tax legislation slashed corporate tax rates and will give 80% of individual filers a tax cut, according to some estimates. But arguably, President Barack Obama passed a larger tax cut by making most of President George W. Bush’s cuts permanent. President Ronald Reagan definitely

--- RESULT 4 ---
Score: 0.836
Document: 18
Chunk: 0
URL: https://www.crfb.org/blogs/trumps-tax-cut-largest-reagan
Text: During the first Presidential debate on September 26, Republican Presidential candidate Donald Trump said "my tax cut is the biggest since Ronald Reagan." While there are a few different ways to measure the revenue effect, we find this statement to be largely true. According to our recent estimates, Donald Trump's proposed tax changes -- from his tax and health plans -- would reduce revenue by $5.8 trillion over ten years, which is 2.5 percent of GDP over that time. Jerry Tempalski of the Treasury Department has compiled the revenue estimate made at the time of passage of every major tax bill going back to 1940, both in inflation-adjusted dollars and as a percent of GDP. As a percent of GDP,

--- RESULT 5 ---
Score: 0.829
Document: 42
Chunk: 2
URL: https://apnews.com/article/bbd344ade2b74e17a172ac5a371ba756
Text: into law. TRUMP: “It’s the largest tax cut in the history of our country.” — remarks Wednesday. THE FACTS: It isn’t. For months Trump has refused to recognize larger tax cuts in history, of which there have been many, or to grant that other presidents have enacted big tax cuts since Ronald Reagan in the 1980s. An October analysis by the Committee for a Responsible Federal Budget found that it would be the eighth biggest since 1918. As a percentage of the total economy, Reagan’s 1981 cut is the biggest followed by the 1945 rollback of taxes that financed World War II. Trump’s plan is also smaller than cuts in 1948, 1964 and 1921, and probably in other years. Valued at $1.5 trillion over 10 ye

--- RESULT 6 ---
Score: 0.827
Document: 30
Chunk: 1
URL: https://apnews.com/article/north-america-donald-trump-ap-top-news-laws-politics-14611d629c8b4e86818a39df96b86e5f
Text: Not so, in either case. For months Trump has refused to recognize larger tax cuts in history, of which there have been many, or to grant that other presidents have enacted big tax cuts since Ronald Reagan in the 1980s. The White House won’t explain how he arrives at his conclusion. An October analysis by the Committee for a Responsible Federal Budget found that it would be the eighth biggest since 1918. As a percentage of the total economy, Reagan’s 1981 cut is the biggest followed by the 1945 rollback of taxes that financed World War II. Trump’s plan is also smaller than cuts in 1948, 1964 and 1921, and probably in other years. Additionally, a Treasury Department analysis found Reagan’s 198

--- RESULT 7 ---
Score: 0.825
Document: 4
Chunk: 0
URL: https://www.crfb.org/blogs/president-trumps-tax-cut-largest-history
Text: Is President Trump's Tax Cut the Largest in History? In their tax reform framework memo, the Trump Administration calls their plan "The Biggest Individual and Business Tax Cut in American History." And during their briefing, National Economic Council Director Gary Cohn said of the plan it's "...one of the biggest tax cuts in the American history." Though we don't know all the details of the plan, from our estimate it does appear to be quite large. In nominal dollars, it would almost certainly be the largest in history. But as a share of Gross Domestic Product (GDP), a few previous tax cuts would be larger. By our rough estimate, Trump's plan would be the third largest tax cut since 1940. To

--- RESULT 8 ---
Score: 0.823
Document: 10
Chunk: 1
URL: https://www.forbes.com/sites/chuckjones/2019/03/16/fact-checking-trumps-recent-economic-tweets/
Text: and wrote the following, “The President made his oft-repeated assertion that the Tax Cuts and Jobs Act (TCJA) constitutes the largest tax cut in U.S. history. However, this is not true by any measure. The tax cuts are among the largest in nominal terms, but even then they are still smaller than tax cuts passed at the beginning of 2013. And this is largely due to inflation and because the economy grows over time, leaving more tax revenue to cut.” The CRFB calculated that the tax cut was the 12th largest in history as a percentage of GDP with Trump’s being 0.6% of GDP. The CRFB added, “Adjusted for inflation, the TCJA is the fourth largest tax cut in history, behind the tax cuts in 2013, 2010,

--- RESULT 9 ---
Score: 0.822
Document: 59
Chunk: 0
URL: https://www.boston.com/news/politics/2018/01/31/the-ap-fact-checked-trumps-state-of-the-union-address/
Text: The AP fact checked Trump’s State of the Union address WASHINGTON (AP) — Boastful even within the traditional confines of a State of the Union speech, President Donald Trump inflated the impact of his tax cuts Tuesday night, declared an end to a “war” on energy that did not exist when he took office and displayed a faulty grasp of immigration policy. A look at some of the statements in his speech and how they compare with the facts: TRUMP: “We enacted the biggest tax cuts and reform in American history.” THE FACTS: No truer now than in the countless other times he has said the same. The December tax overhaul ranks behind Ronald Reagan’s in the early 1980s, post-World War II tax cuts and at l

--- RESULT 10 ---
Score: 0.818
Document: 36
Chunk: 1
URL: https://abcnews.go.com/Politics/state-union-fact-check-donald-trump-claiming/story?id=52712047
Text: year comes with a $1.5 trillion price tag, and according to the Committee for a Responsible Federal Budget, an independent bipartisan public policy organization, it ranks as the 12th largest tax cut as a percentage of GDP and fourth largest in inflation-adjusted dollars since 1918. If the plan is extended, the group estimates the bill would cost $2.2 trillion, making it the eighth largest tax cut as a percentage of GDP and fourth largest in inflation-adjusted dollars since 1918. The tax cut signed into law by President Ronald Reagan in 1981 was the largest since 1918 -- reducing federal revenues by 2.9 percent of GDP, according to the Treasury Department. The president also claimed roughly 3

In [ ]:
gold_questions_1 = train_df.iloc[1]["questions"]

for i, question in enumerate(gold_questions_1):
    print(f"\n--- GOLD QUESTION {i} ---")
    print("Question:", question["question"])

    for answer in question["answers"]:
        print("Answer:", answer["answer"])
        print("Source URL:", answer["source_url"])

--- GOLD QUESTION 0 ---
Question: Did the 2017 tax bill deliver the largest tax cuts in American history?
Answer: This tax cut is the 8th largest as a percent of Gross Domestic Product (GDP) since 1918 and the 4th largest in inflation-adjusted dollars.
Source URL: https://www.crfb.org/blogs/president-trumps-tax-cut-largest-history-yet

--- GOLD QUESTION 1 ---
Question: Has there been larger tax bills than the 2017 tax bill?
Answer: Three tax bills have been larger: American Taxpayer Relief Act of 2012 (enacted in 2013);
Tax Relief, Unemployment Insurance Reauthorization, and Job Creation Act of 2010 and
Economic Recovery Tax Act of 1981
Source URL: https://www.treasury.gov/resource-center/tax-policy/tax-analysis/Documents/WP81-Table2013.pdf

observandos las URL Gold

In [ ]:
gold_urls_1 = set()

for question in gold_questions_1:
    for answer in question["answers"]:
        if answer["source_url"]:
            gold_urls_1.add(answer["source_url"])

print(gold_urls_1)

{'https://www.crfb.org/blogs/president-trumps-tax-cut-largest-history-yet', 'https://www.treasury.gov/resource-center/tax-policy/tax-analysis/Documents/WP81-Table2013.pdf'}

In [ ]:
retrieved_corpus_urls = {
    chunk["url"]
    for chunk in chunks_1
}

for url in gold_urls_1:
    print(
        url,
        "->",
        "PRESENTE" if url in retrieved_corpus_urls else "NO PRESENTE"
    )

https://www.crfb.org/blogs/president-trumps-tax-cut-largest-history-yet -> PRESENTE
https://www.treasury.gov/resource-center/tax-policy/tax-analysis/Documents/WP81-Table2013.pdf -> NO PRESENTE

Con top_n_documents=100, una de las dos fuentes gold de la claim 1 no quedó en el corpus preseleccionado, aunque el retrieval final recuperó múltiples evidencias alternativas pertinentes.

### 12. Evidence Verifier

In [29]:
class EvidenceAssessment(BaseModel):
    """
    Evaluación de una evidencia concreta respecto a la claim.
    """

    evidence_id: int

    relation: Literal[
        "SUPPORTS",
        "REFUTES",
        "NEUTRAL"
    ]

    reason: str


class VerificationResult(BaseModel):
    """
    Resultado global de la verificación factual de una claim utilizando exclusivamente las evidencias 
    recuperadas.
    """

    verdict: Literal[
        "SUPPORTED",
        "REFUTED",
        "NOT_ENOUGH_EVIDENCE",
        "CONFLICTING_EVIDENCE"
    ]

    evidence_sufficient: bool

    evidence_assessments: list[EvidenceAssessment]

    explanation: str

In [89]:
env_path = Path("../.env")
loaded = load_dotenv(dotenv_path=env_path)
client = OpenAI()

Transformando Results al formato deseado para el LLM:

In [ ]:
def format_evidences_for_llm(evidences):
    """
    Convierte las evidencias recuperadas por el RAG en un texto structurado que pueda ser utilizado por el 
    Evidence Verifier.

    No se incluyen los scores de similitud para evitar que el LLM interprete relevancia semántica como grado
    de veracidad.

    Parameters
    ----------
    evidences : list[dict]
        Lista de evidencias devuelta por retrieve_evidence().

    Returns
    -------
    str
        Evidencias numeradas con su URL y texto.
    """

    formatted_evidences = []

    for evidence_id, evidence in enumerate(evidences, start=1):

        formatted_evidences.append(
            f"""
            EVIDENCE {evidence_id}
            URL: {evidence["url"]}
            TEXT:
            {evidence["text"]}
            """.strip()
            )

    return "\n\n".join(formatted_evidences)

Probamos la función:

In [ ]:
# evidence_text.__class__

In [45]:
evidence_text = format_evidences_for_llm(results)

print(evidence_text)

EVIDENCE 1
            URL: https://trumpwhitehouse.archives.gov/briefings-statements/president-donald-j-trump-achieved-biggest-tax-cuts-reforms-american-history/
            TEXT:
            BIGGEST TAX CUTS AND REFORMS: Because of President Donald J. Trump, Americans will benefit from the biggest tax cuts and reforms in American history. - President Trump’s tax cuts are the biggest gross tax cuts in American history, cutting over $5.5 trillion in taxes over ten years. - The President’s tax law included substantial reforms to make taxes simpler and fairer, which helped offset the cost of the tax cuts and thereby limit the net tax cut to $1.5 trillion. - President Trump cut the corporate tax rate from 35 percent to 21 percent, the largest percentage point reduction of the top marginal rate in history. - President Trump’s tax cuts include the biggest increase in the child tax credit in history. - The Child Tax Credit was increased by $573.4 billion over ten years, larger than any previous change to credits specifically targeting families. - President Trump’s tax cuts included some of the most substantial reforms to the tax code in American history. - The Tax Cuts and Jobs

EVIDENCE 2
            URL: https://www.theguardian.com/us-news/2017/apr/26/trump-tax-cuts-proposal-deductions-brackets
            TEXT:
            The Trump administration unveiled what it called the biggest tax cuts “in history” on Wednesday, in a move that will simplify the US tax system, slash taxes for businesses large and small – including Trump’s own – eliminate inheritance taxes and set the president on a collision course with Congress over the likely $2tn-plus cost of the proposal. Critics immediately called it “basically a huge tax cut for the rich”. The plan would cut the US’s individual income tax brackets from seven to three (10%, 25% and 35%) and slash US corporate tax rates from 35% to 15%. “We have a once-in-a-generation opportunity to do something really big,” said Gary Cohn, chief economic adviser to Donald Trump. “This is about growing the economy, creating jobs.” Cohn and Steven Mnuchin, the treasury secretary, were short on details of the plan that, if passed, would be the largest overhaul of the US tax system since the Reagan era. “We are moving as quickly as we can,” said Mnuchin. The announcement comes amid

EVIDENCE 3
            URL: https://www.cnn.com/2017/12/15/politics/is-trumps-bill-largest-tax-cut-in-history-no/index.html
            TEXT:
            Editor’s Note: Editor’s note: An earlier version of this story first appeared in December. Trump has said the tax cuts Congress passed would be the biggest ever They would not, according to the way the government measures tax cuts President Donald Trump has bragged – and did so again during his State of the Union address Tuesday – that the tax cuts Congress passed would be the biggest in history. There’s no doubt the tax legislation slashed corporate tax rates and will give 80% of individual filers a tax cut, according to some estimates. But arguably, President Barack Obama passed a larger tax cut by making most of President George W. Bush’s cuts permanent. President Ronald Reagan definitely did. And Presidents John F. Kennedy and Lyndon Johnson probably did, too. “It will be the biggest tax decrease, or tax cut, in the history of our country,” Trump said at the White House last month. Tax analysts have been unequivocal that Trump’s claim is not true. “While it is not the largest tax

EVIDENCE 4
            URL: https://www.crfb.org/blogs/trumps-tax-cut-largest-reagan
            TEXT:
            During the first Presidential debate on September 26, Republican Presidential candidate Donald Trump said "my tax cut is the biggest since Ronald Reagan." While there are a few different ways to measure the revenue effect, we find this statement to be largely true. According to our recent estimates, Donald Trump's proposed tax changes -- from his tax and health plans -- would reduce revenue by $5.8 trillion over ten years, which is 2.5 percent of GDP over that time. Jerry Tempalski of the Treasury Department has compiled the revenue estimate made at the time of passage of every major tax bill going back to 1940, both in inflation-adjusted dollars and as a percent of GDP. As a percent of GDP, the ten-year cost of Trump's tax plan exceeds the four-year cost of every tax cut since the Economic Recovery Tax Act of 1981, the major tax cut passed in the first year of Ronald Reagan's Presidency that cost 2.9 percent of GDP over four years. The four-year cost, as a percent of GDP, of Trump's

EVIDENCE 5
            URL: https://apnews.com/article/bbd344ade2b74e17a172ac5a371ba756
            TEXT:
            into law. TRUMP: “It’s the largest tax cut in the history of our country.” — remarks Wednesday. THE FACTS: It isn’t. For months Trump has refused to recognize larger tax cuts in history, of which there have been many, or to grant that other presidents have enacted big tax cuts since Ronald Reagan in the 1980s. An October analysis by the Committee for a Responsible Federal Budget found that it would be the eighth biggest since 1918. As a percentage of the total economy, Reagan’s 1981 cut is the biggest followed by the 1945 rollback of taxes that financed World War II. Trump’s plan is also smaller than cuts in 1948, 1964 and 1921, and probably in other years. Valued at $1.5 trillion over 10 years, the plan is indeed large and expensive. But it’s much smaller than originally intended. Back in the spring, it was shaping up as a $5.5 trillion package. Even then it would have only been the third largest since 1940 as a share of gross domestic product. VICE PRESIDENT MIKE PENCE: “You’re

EVIDENCE 6
            URL: https://apnews.com/article/north-america-donald-trump-ap-top-news-laws-politics-14611d629c8b4e86818a39df96b86e5f
            TEXT:
            Not so, in either case. For months Trump has refused to recognize larger tax cuts in history, of which there have been many, or to grant that other presidents have enacted big tax cuts since Ronald Reagan in the 1980s. The White House won’t explain how he arrives at his conclusion. An October analysis by the Committee for a Responsible Federal Budget found that it would be the eighth biggest since 1918. As a percentage of the total economy, Reagan’s 1981 cut is the biggest followed by the 1945 rollback of taxes that financed World War II. Trump’s plan is also smaller than cuts in 1948, 1964 and 1921, and probably in other years. Additionally, a Treasury Department analysis found Reagan’s 1981 tax cut had an annual average cost of nearly 2 percent of GDP. This would translate into roughly $400 billion in today’s dollars. The tax cuts peak at $280 billion in 2019. Valued at $1.5 trillion over 10 years, the plan is indeed large and expensive. But it’s much smaller than originally

EVIDENCE 7
            URL: https://www.crfb.org/blogs/president-trumps-tax-cut-largest-history
            TEXT:
            Is President Trump's Tax Cut the Largest in History? In their tax reform framework memo, the Trump Administration calls their plan "The Biggest Individual and Business Tax Cut in American History." And during their briefing, National Economic Council Director Gary Cohn said of the plan it's "...one of the biggest tax cuts in the American history." Though we don't know all the details of the plan, from our estimate it does appear to be quite large. In nominal dollars, it would almost certainly be the largest in history. But as a share of Gross Domestic Product (GDP), a few previous tax cuts would be larger. By our rough estimate, Trump's plan would be the third largest tax cut since 1940. To evaluate this claim, we use a 2013 Treasury Department analysis that compares the projected revenue effect of major tax bills since 1940. The analysis uses one-year estimates for laws enacted between 1940 and 1967, two-year estimates for laws enacted between 1968 and 1977, and four-year estimates

EVIDENCE 8
            URL: https://www.forbes.com/sites/chuckjones/2019/03/16/fact-checking-trumps-recent-economic-tweets/
            TEXT:
            and wrote the following, “The President made his oft-repeated assertion that the Tax Cuts and Jobs Act (TCJA) constitutes the largest tax cut in U.S. history. However, this is not true by any measure. The tax cuts are among the largest in nominal terms, but even then they are still smaller than tax cuts passed at the beginning of 2013. And this is largely due to inflation and because the economy grows over time, leaving more tax revenue to cut.” The CRFB calculated that the tax cut was the 12th largest in history as a percentage of GDP with Trump’s being 0.6% of GDP. The CRFB added, “Adjusted for inflation, the TCJA is the fourth largest tax cut in history, behind the tax cuts in 2013, 2010, and 1981. It is the fourth largest whether looking at the official $1.5 trillion cost of the legislation, or our $2.2 trillion estimate excluding the gimmicky use of expirations and delays that artificially reduced the bill's cost.” The best economy only applies to developed countries Trump’s

EVIDENCE 9
            URL: https://www.boston.com/news/politics/2018/01/31/the-ap-fact-checked-trumps-state-of-the-union-address/
            TEXT:
            The AP fact checked Trump’s State of the Union address WASHINGTON (AP) — Boastful even within the traditional confines of a State of the Union speech, President Donald Trump inflated the impact of his tax cuts Tuesday night, declared an end to a “war” on energy that did not exist when he took office and displayed a faulty grasp of immigration policy. A look at some of the statements in his speech and how they compare with the facts: TRUMP: “We enacted the biggest tax cuts and reform in American history.” THE FACTS: No truer now than in the countless other times he has said the same. The December tax overhaul ranks behind Ronald Reagan’s in the early 1980s, post-World War II tax cuts and at least several more. An analysis by the Committee for a Responsible Federal Budget in the fall put Trump’s package as the eighth biggest since 1918. As a percentage of the total economy, Reagan’s 1981 cut is the biggest followed by the 1945 rollback of taxes that financed World War II. Valued at $1.5

EVIDENCE 10
            URL: https://abcnews.go.com/Politics/state-union-fact-check-donald-trump-claiming/story?id=52712047
            TEXT:
            year comes with a $1.5 trillion price tag, and according to the Committee for a Responsible Federal Budget, an independent bipartisan public policy organization, it ranks as the 12th largest tax cut as a percentage of GDP and fourth largest in inflation-adjusted dollars since 1918. If the plan is extended, the group estimates the bill would cost $2.2 trillion, making it the eighth largest tax cut as a percentage of GDP and fourth largest in inflation-adjusted dollars since 1918. The tax cut signed into law by President Ronald Reagan in 1981 was the largest since 1918 -- reducing federal revenues by 2.9 percent of GDP, according to the Treasury Department. The president also claimed roughly 3 million workers have received bonuses stemming from the tax cuts. That figure appears to come from a conservative political advocacy group, Americans for Tax Reform, which recently wrote based on anecdotes, “At least 3 million Americans are receiving special tax reform bonuses.” TRUMP CLAIM: “We

In [ ]:
def verify_evidence(
    claim,
    evidences,
    client,
    model="gpt-5.6-terra",
    language=None,
):
    """
    Verifica una claim utilizando exclusivamente las evidencias recuperadas por el sistema RAG.

    Parameters
    ----------
    claim : str
        Afirmación que se quiere verificar.

    evidences : list[dict]
        Evidencias recuperadas por retrieve_evidence().

    client
        Cliente de OpenAI.

    model : str
        Modelo LLM utilizado para realizar la verificación.

    Returns
    -------
    VerificationResult
        Resultado estructurado de la verificación factual.
    """

    # Preparamos las evidencias recuperadas en un formato comprensible para el LLM
    evidence_text = format_evidences_for_llm(evidences)

    if language == "es":
        language_instruction = (
            "Write the explanation and reasons in Spanish."
        )
    elif language == "en":
        language_instruction = (
            "Write the explanation and reasons in English."
        )
    
    instructions = f"""
    You are an Evidence Verifier for a fact-checking system.

    Your task is to verify a claim using ONLY the evidence provided to you.

    Do not use external knowledge.
    Do not assume facts that are not present in the evidence.

    A claim may contain multiple factual components.
    When this happens, consider the different components of the claim before assigning evidence relationships and the 
    final verdict.

    For each evidence item, determine its relationship to the claim:

    - SUPPORTS:
    The evidence provides factual information that supports the claim as a whole, or supports an important component without
    contradicting or leaving unresolved another essential component of the claim.

    - REFUTES:
    The evidence provides factual information that contradicts the claim as a whole, or directly contradicts an essential 
    component in a way that makes the overall claim false.

    - NEUTRAL:
    The evidence is related to the claim but does not provide enough information to support or refute it as a whole. 
    Use NEUTRAL when the evidence addresses only one component of a multi-part claim and leaves other essential
    components unresolved.

    Then determine the overall verdict:

    - SUPPORTED:
    The available evidence is sufficient to support the claim as a whole.

    - REFUTED:
    The available evidence is sufficient to refute the claim as a whole.

    - NOT_ENOUGH_EVIDENCE:
    The available evidence does not contain enough information to reach a justified conclusion about the claim.

    - CONFLICTING_EVIDENCE:
    The available evidence supports some important factual aspects of the claim while refuting, contradicting, or 
    substantially qualifying other important aspects, so that labeling the whole claim simply SUPPORTED or REFUTED would
    lose relevant information.

    Use this verdict also for cherry-picking cases, where the claim relies on factually supported information but 
    selectively combines, omits, or frames evidence in a way that produces a misleading overall conclusion.

    Do not automatically label a multi-part claim REFUTED simply because one component is contradicted if other important 
    components are supported.
    In such cases, consider whether CONFLICTING_EVIDENCE is more appropriate.

    Set evidence_sufficient to true when the provided evidence contains enough factual information to justify the selected
    verdict, including when the evidence is sufficient to establish that the case is CONFLICTING_EVIDENCE.

    Set evidence_sufficient to false when the appropriate verdict is
    NOT_ENOUGH_EVIDENCE.

    Assess every evidence item provided.

    Base the final verdict on the content of the evidence, not on retrieval similarity scores.

    {language_instruction}
    """

    response = client.responses.parse(
        model=model,
        instructions=instructions,
        input=f"""
    CLAIM:
    {claim}

    EVIDENCE:
    {evidence_text}
    """,
            text_format=VerificationResult,
        )

    return response.output_parsed

Probamos la función verify_evidence para la claim 1:

In [ ]:
verification_1 = verify_evidence(
    claim=claim_1,
    evidences=results,
    client=client,
)

print(verification_1.model_dump_json(indent=2))

{
  "verdict": "REFUTED",
  "evidence_sufficient": true,
  "evidence_assessments": [
    {
      "evidence_id": 1,
      "relation": "SUPPORTS",
      "reason": "The archived Trump White House statement explicitly says that Trump's tax cuts were the biggest gross tax cuts and reforms in American history, citing more than $5.5 trillion in gross cuts over ten years."
    },
    {
      "evidence_id": 2,
      "relation": "NEUTRAL",
      "reason": "This article reports that the Trump administration called its proposal the biggest tax cut in history, but it describes an announced proposal rather than establishing that Trump delivered the largest enacted tax cuts. It also does not independently verify the historical comparison."
    },
    {
      "evidence_id": 3,
      "relation": "REFUTES",
      "reason": "CNN states that the enacted tax cuts would not be the biggest in history under the government's way of measuring tax cuts, identifying Reagan's cuts as definitely larger and Kennedy/Johnson-era cuts as probably larger."
    },
    {
      "evidence_id": 4,
      "relation": "REFUTES",
      "reason": "This analysis finds Trump's proposed changes to be the biggest since Reagan, not the biggest in all American history, and says Reagan's 1981 tax cut had a larger revenue cost as a share of GDP."
    },
    {
      "evidence_id": 5,
      "relation": "REFUTES",
      "reason": "The AP directly concludes that Trump's statement is untrue. It reports that the tax plan ranked eighth biggest since 1918 and was smaller than several earlier tax cuts, including Reagan's 1981 cut."
    },
    {
      "evidence_id": 6,
      "relation": "REFUTES",
      "reason": "The AP says there have been many larger tax cuts in history and reports that Trump's plan ranked eighth since 1918, while Reagan's 1981 tax cut was largest as a share of GDP."
    },
    {
      "evidence_id": 7,
      "relation": "REFUTES",
      "reason": "Although this evidence says Trump's plan would almost certainly be the largest in nominal dollars, it states that several previous cuts were larger as a share of GDP and estimates Trump's as only the third largest since 1940. Thus it does not support the unqualified claim that it was the largest in history."
    },
    {
      "evidence_id": 8,
      "relation": "REFUTES",
      "reason": "The cited assessment says the Tax Cuts and Jobs Act was not the largest by any measure, placing it twelfth by GDP share and fourth after inflation adjustment."
    },
    {
      "evidence_id": 9,
      "relation": "REFUTES",
      "reason": "The AP fact check directly rejects the claim, stating that the tax overhaul ranked behind Reagan-era and post-World War II tax cuts, among others, and was eighth biggest since 1918."
    },
    {
      "evidence_id": 10,
      "relation": "REFUTES",
      "reason": "This evidence reports that Trump's tax cut ranked twelfth by GDP share and fourth in inflation-adjusted dollars, while Reagan's 1981 tax cut was the largest since 1918 by GDP share."
    }
  ],
  "explanation": "While the Trump White House characterized the cuts as the largest on a gross-dollar basis, multiple provided fact checks and analyses conclude that the enacted Trump tax cuts were not the largest in American history under historically comparable measures such as share of GDP or inflation-adjusted cost. The evidence identifies several larger prior cuts, especially Reagan's 1981 tax cut. Therefore, the categorical claim is refuted."
}

In [ ]:
gold_label_1 = train_df.iloc[1]["label"]

print("Predicted verdict:", verification_1.verdict)
print("Gold label:", gold_label_1)

Predicted verdict: REFUTED
Gold label: Refuted

### 12.1 Función global

In [32]:
def verify_averitec_claim(
    claim_id,
    claim,
    knowledge_zip,
    embedding_model,
    text_splitter,
    client,
):
    """
    Ejecuta el pipeline completo de verificación factual para una claim de AVeriTeC.

    Parameters
    ----------
    claim_id : int
        Identificador de la claim en AVeriTeC.

    claim : str
        Texto de la afirmación que se quiere verificar.

    knowledge_zip : str or Path
        ZIP que contiene el knowledge store correspondiente.

    embedding_model
        Modelo utilizado para generar embeddings.

    text_splitter
        Objeto utilizado para dividir los documentos en chunks.

    client
        Cliente de OpenAI utilizado por el Evidence Verifier.

    Returns
    -------
    dict
        Resultado completo del pipeline, incluyendo información del retrieval, evidencias recuperadas y
        verificación factual.
    """

    # 1. Cargamos el knowledge store asociado a la claim
    knowledge_records = load_knowledge_records(
        knowledge_zip=knowledge_zip,
        claim_id=claim_id
    )

    # 2. Construimos el índice vectorial
    chunks, index, retrieval_info = build_claim_index(
        claim=claim,
        knowledge_records=knowledge_records,
        embedding_model=embedding_model,
        text_splitter=text_splitter
    )

    # 3. Recuperamos las evidencias más relevantes
    evidences = retrieve_evidence(
        claim=claim,
        embedding_model=embedding_model,
        index=index,
        chunks=chunks
    )

    # 4. El LLM verifica la claim utilizando esas evidencias
    verification = verify_evidence(
        claim=claim,
        evidences=evidences,
        client=client
    )

    return {
        "claim_id": claim_id,
        "claim": claim,
        "retrieval_info": retrieval_info,
        "evidences": evidences,
        "verification": verification,
    }

Los labels definidos en AveriTec son: 'Supported', 'Refuted', 'Conflicting Evidence/Cherrypicking','Not Enough Evidence' y el LLM nos da: SUPPORTED, REFUTED, NOT_ENOUGH_EVIDENCE, CONFLICTING_EVIDENCE, por lo tanto creamos una función para normalizar los labels.

In [33]:
def normalize_averitec_label(label):
    """
    Convierte las etiquetas originales de AVeriTeC al formato
    utilizado por el Evidence Verifier.
    """

    label_mapping = {
        "Supported": "SUPPORTED",
        "Refuted": "REFUTED",
        "Not Enough Evidence": "NOT_ENOUGH_EVIDENCE",
        "Conflicting Evidence/Cherrypicking": "CONFLICTING_EVIDENCE",
    }

    return label_mapping[label]

Antes de probar el pipeline completo, comprobamos la salida con las labels normalizadas:

In [ ]:
gold_label_1 = train_df.iloc[1]["label"]

gold_normalized_1 = normalize_averitec_label(
    gold_label_1
)

print("Predicted:", verification_1.verdict)
print("Gold:", gold_normalized_1)
print(
    "Correct:",
    verification_1.verdict == gold_normalized_1
)

Antes de dar continuidad a probar el pipeline para todos los claims, vamos a comprobar con Claim 0:

In [45]:
claim_id_test = 0

claim_test = train_df.iloc[claim_id_test]["claim"]

result_0 = verify_averitec_claim(
    claim_id=claim_id_test,
    claim=claim_test,
    knowledge_zip=knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
)

Corpus manejable: 31051 chunks.
No es necesario aplicar preselección TF-IDF.
Documentos originales: 431
Documentos únicos: 431
Documentos finales: 431
Chunks iniciales: 31051
Chunks finales: 31051

Batches: 100%|██████████| 486/486 [1:41:08<00:00, 12.49s/it]

In [46]:
predicted_0 = result_0["verification"].verdict

gold_0 = normalize_averitec_label( #Normalizamos la label de averitec con el LLM
    train_df.iloc[claim_id_test]["label"]
)

print("Claim:", claim_test)
print("Predicted:", predicted_0)
print("Gold:", gold_0)
print("Correct:", predicted_0 == gold_0)

Claim: Hunter Biden had no experience in Ukraine or in the energy sector when he joined the board of Burisma.
Predicted: SUPPORTED
Gold: SUPPORTED
Correct: True

In [47]:
#Viendo el resultado:
print(
    result_0["verification"].model_dump_json(indent=2)
)

{
  "verdict": "SUPPORTED",
  "evidence_sufficient": true,
  "evidence_assessments": [
    {
      "evidence_id": 1,
      "relation": "SUPPORTS",
      "reason": "It reports Pam Bondi's statement that Hunter Biden had no experience in natural gas, the energy sector, or Ukrainian regulatory affairs before joining Burisma."
    },
    {
      "evidence_id": 2,
      "relation": "SUPPORTS",
      "reason": "It states that Republicans pointed out Hunter Biden had no experience in the energy sector before taking the Burisma job. It does not address Ukraine-specific experience."
    },
    {
      "evidence_id": 3,
      "relation": "SUPPORTS",
      "reason": "It reports the statement that Hunter Biden had no experience in natural gas, the energy sector, or Ukrainian regulatory affairs, and identifies his Burisma board service as beginning in 2014."
    },
    {
      "evidence_id": 4,
      "relation": "SUPPORTS",
      "reason": "It explicitly describes Hunter Biden as 'a man with no experience in Ukraine or energy' when he joined Burisma's board in April 2014."
    },
    {
      "evidence_id": 5,
      "relation": "SUPPORTS",
      "reason": "It explicitly says that when he joined Burisma in April 2014, Hunter Biden had no previous experience in the natural gas industry or Ukraine."
    },
    {
      "evidence_id": 6,
      "relation": "SUPPORTS",
      "reason": "It says Hunter Biden was not an energy expert when Burisma hired him for its board in 2014. It does not address Ukraine experience."
    },
    {
      "evidence_id": 7,
      "relation": "NEUTRAL",
      "reason": "It discusses Hunter Biden's admission of poor judgment and his defense of the work, but provides no information establishing or disproving his prior Ukraine or energy-sector experience."
    },
    {
      "evidence_id": 8,
      "relation": "NEUTRAL",
      "reason": "It establishes that Hunter Biden joined Burisma in 2014 and later appeared at energy-related conferences, but does not state whether he had relevant experience before joining."
    },
    {
      "evidence_id": 9,
      "relation": "NEUTRAL",
      "reason": "It says Hunter Biden said his role focused on corporate-governance practices and notes scrutiny of his Ukraine experience, but does not establish whether he had prior experience in Ukraine or energy."
    },
    {
      "evidence_id": 10,
      "relation": "NEUTRAL",
      "reason": "It concerns alleged wrongdoing at Burisma before Hunter Biden's arrival, not his qualifications or previous experience."
    }
  ],
  "explanation": "The claim is supported by multiple evidence items. Most directly, Evidence 4 states that Hunter Biden had no experience in either Ukraine or energy when he joined Burisma, and Evidence 5 likewise states that he had no previous experience in the natural-gas industry or Ukraine at that time. Other evidence also supports the lack of energy-sector experience. No evidence establishes relevant prior experience that would contradict the claim."
}

Hasta aqui tenemos una señal muy importante, porque ahora tenemos dos casos distintos funcionando end-to-end: claim 0 y claim 1, pero todavía no podemos hablar de rendimiento del sistema: son solo dos casos.

Vamos a probar con una claim con una label un poco más complicada `Not Enough Evidence`.

In [52]:
nei_sample = train_df[
    train_df["label"] == "Not Enough Evidence"
].iloc[0]

claim_id_nei = nei_sample.name
claim_nei = nei_sample["claim"]

print("Claim ID:", claim_id_nei)
print("Claim:", claim_nei)
print("Gold:", nei_sample["label"])

Claim ID: 21
Claim: There is a ‘global average’ for the number of judges and magistrates to number of people in Kenya.
Gold: Not Enough Evidence

In [53]:
result_nei = verify_averitec_claim(
    claim_id=claim_id_nei,
    claim=claim_nei,
    knowledge_zip=knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
)

Corpus grande detectado: 106806 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 780
Documentos únicos: 780
Documentos finales: 100
Chunks iniciales: 106806
Chunks finales: 6051

Batches: 100%|██████████| 95/95 [20:06<00:00, 12.70s/it]

In [54]:
predicted_nei = result_nei["verification"].verdict

gold_nei = normalize_averitec_label(
    nei_sample["label"]
)

print("Claim:", claim_nei)
print("Predicted:", predicted_nei)
print("Gold:", gold_nei)
print("Correct:", predicted_nei == gold_nei)

Claim: There is a ‘global average’ for the number of judges and magistrates to number of people in Kenya.
Predicted: NOT_ENOUGH_EVIDENCE
Gold: NOT_ENOUGH_EVIDENCE
Correct: True

In [55]:
print(
    "Evidence sufficient:",
    result_nei["verification"].evidence_sufficient
)

Evidence sufficient: False

Vamos a probar la ultima label: `Conflicting Evidence/Cherrypicking`

In [56]:
conflicting_sample = train_df[
    train_df["label"] == "Conflicting Evidence/Cherrypicking"
].iloc[0]

claim_id_conflicting = conflicting_sample.name
claim_conflicting = conflicting_sample["claim"]

print("Claim ID:", claim_id_conflicting)
print("Claim:", claim_conflicting)
print("Gold:", conflicting_sample["label"])

Claim ID: 7
Claim: Margaret Sanger was a racist who believed in eugenics. Her goal when founding Planned Parenthood was to eradicate minorities.
Gold: Conflicting Evidence/Cherrypicking

In [57]:
result_conflicting = verify_averitec_claim(
    claim_id=claim_id_conflicting,
    claim=claim_conflicting,
    knowledge_zip=knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
)

Corpus grande detectado: 93797 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 769
Documentos únicos: 767
Documentos finales: 100
Chunks iniciales: 93797
Chunks finales: 2033

Batches: 100%|██████████| 32/32 [05:27<00:00, 10.23s/it]

In [58]:
predicted_conflicting = (
    result_conflicting["verification"].verdict
)

gold_conflicting = normalize_averitec_label(
    conflicting_sample["label"]
)

print("Claim:", claim_conflicting)
print("Predicted:", predicted_conflicting)
print("Gold:", gold_conflicting)
print(
    "Correct:",
    predicted_conflicting == gold_conflicting
)

print(
    "Evidence sufficient:",
    result_conflicting["verification"].evidence_sufficient
)

Claim: Margaret Sanger was a racist who believed in eugenics. Her goal when founding Planned Parenthood was to eradicate minorities.
Predicted: REFUTED
Gold: CONFLICTING_EVIDENCE
Correct: False
Evidence sufficient: True

In [59]:
print(
    result_conflicting["verification"].model_dump_json(indent=2)
)

{
  "verdict": "REFUTED",
  "evidence_sufficient": true,
  "evidence_assessments": [
    {
      "evidence_id": 1,
      "relation": "SUPPORTS",
      "reason": "It describes Sanger's eugenics program, including her call for sterilization of people characterized as mentally or physically disabled, and states that Planned Parenthood cited her eugenicism and racism."
    },
    {
      "evidence_id": 2,
      "relation": "SUPPORTS",
      "reason": "It reports that Planned Parenthood of Greater New York cited Sanger's documented racist legacy and deep belief in eugenic ideology."
    },
    {
      "evidence_id": 3,
      "relation": "SUPPORTS",
      "reason": "It asserts that Sanger repeatedly expressed racist intentions and that Planned Parenthood manifested those ideologies. It does not specifically document an objective of eradicating minorities."
    },
    {
      "evidence_id": 4,
      "relation": "SUPPORTS",
      "reason": "This is substantively the same as Evidence 3 and asserts that Sanger expressed racist intentions and that Planned Parenthood reflected them, without specifically establishing a goal of eradicating minorities."
    },
    {
      "evidence_id": 5,
      "relation": "SUPPORTS",
      "reason": "It directly documents Sanger's stated support for eugenics and quotes her 1919 writing that birth control would help eugenicists pursue 'racial betterment.' It does not establish that her goal in founding Planned Parenthood was to eradicate minorities."
    },
    {
      "evidence_id": 6,
      "relation": "SUPPORTS",
      "reason": "It quotes a statement describing Sanger's racist legacy and overwhelming evidence of her deep belief in eugenic ideology. It does not provide evidence for the alleged goal of eradicating minorities."
    },
    {
      "evidence_id": 7,
      "relation": "REFUTES",
      "reason": "Although it reports Sanger's eugenic statement, it presents evidence and expert views disputing that she was racist: her defenders cite work providing contraceptive services in Black communities for parental choice, and historian Linda Gordon says she should not be treated like defenders of slavery or segregation."
    },
    {
      "evidence_id": 8,
      "relation": "SUPPORTS",
      "reason": "It quotes a statement calling Planned Parenthood's founder a racist white woman and discusses its alleged racist history. It does not substantiate the specific allegation that the founding goal was to eradicate minorities."
    },
    {
      "evidence_id": 9,
      "relation": "REFUTES",
      "reason": "It explicitly says that Sanger 'did not seem to be a racist,' while noting that racist eugenicists were involved in her movement. Thus, it disputes the categorical assertion that she was racist."
    },
    {
      "evidence_id": 10,
      "relation": "REFUTES",
      "reason": "It states that the allegation that Sanger and Planned Parenthood located clinics in Black neighborhoods to control Black populations is untrue, and quotes an archival-project director saying Sanger wanted all women to have access to birth control. This contradicts the claim that her founding goal was to eradicate minorities."
    }
  ],
  "explanation": "The evidence provides substantial support that Sanger embraced or collaborated with eugenic ideas, while the characterization of her as racist is disputed by some of the supplied material. Crucially, no evidence establishes that her purpose in founding Planned Parenthood was to eradicate minorities; Evidence 10 directly rejects a closely related population-control allegation and gives an alternative purpose of universal access to birth control. Because the claim makes that alleged eradication goal as a definitive part of the assertion, the available evidence refutes the claim as stated."
}

In [60]:
print("Gold justification:")
print(conflicting_sample["justification"])

Gold justification:
Evidence is conflicting with Margaret Sanger, as she was a progressive who believed in racial integration. She voted for Norman Thomas. She worked with progressive Black people—W.E.B. Du Bois, for example, who, along with Mary McCleod Bethune and Adam Clayton Powell Sr., served on the board of the Negro Project, a network of birth control and maternal health clinics Sanger established in Harlem and the South, etc. However, it does seem that Sanger believed in eugenics and thought people, especially poor people, often had too many kids to care for properly and that too many of those kids were born physically disabled (or, in the language of the day, "feeble-minded"). She did not oppose forced sterilization.

In [61]:
print("\nGold questions:")
print(conflicting_sample["questions"])

Gold questions:
[{'answers': array([{'answer': 'Eugenics is the practice or advocacy of improving the human species by selectively mating people with specific desirable hereditary traits. It aims to reduce human suffering by “breeding out” disease, disabilities and so-called undesirable characteristics from the human population', 'answer_type': 'Extractive', 'boolean_explanation': None, 'cached_source_url': 'https://web.archive.org/web/20230420103906/https://www.history.com/topics/european-history/eugenics', 'source_medium': 'Web text', 'source_url': 'https://www.history.com/topics/germany/eugenics'}],
       dtype=object), 'question': 'What is eugenics?'}
 {'answers': array([{'answer': "I think the greatest sin in the world is bringing children into the world -- that have disease from their parents, that have no chance in the world to be a human being practically. Delinquents, prisoners, all sorts of things just marked when they're born. That to me is the greatest sin -- that people can -- can commit", 'answer_type': 'Extractive', 'boolean_explanation': None, 'cached_source_url': 'https://web.archive.org/web/20230201061838/https://sites.utexas.edu/ransomcentermagazine/2012/04/20/tmwi/', 'source_medium': 'Video', 'source_url': 'https://sites.utexas.edu/ransomcentermagazine/2012/04/20/tmwi/'}],
       dtype=object), 'question': 'What were Sangers views on eugenics?'}
 {'answers': array([{'answer': 'As her biographer Ellen Chesler told me, she was a progressive who believed in racial integration. She voted for Norman Thomas. She worked with progressive Black people—W.E.B. Du Bois, for example, who along with Mary McCleod Bethune and Adam Clayton Powell Sr. served on the board of the Negro Project, a network of birth control and maternal health clinics Sanger established in Harlem and the South. In 1966, Martin Luther King accepted Planned Parenthood’s first Margaret Sanger Award, and in his statement offered a vigorous endorsement of voluntary birth control.', 'answer_type': 'Extractive', 'boolean_explanation': None, 'cached_source_url': 'https://web.archive.org/web/20230130085631/https://www.thenation.com/article/society/canceling-margaret-sanger/', 'source_medium': 'Web text', 'source_url': 'https://www.thenation.com/article/society/canceling-margaret-sanger/'}],
       dtype=object), 'question': 'Was Sanger a racist?'}
 {'answers': array([{'answer': 'Although she did not single out Black people, Sanger was, yes, a eugenicist. She thought people, especially poor people, often had too many kids to care for properly and that too many of those kids were born physically disabled (or in the language of the day, “feeble-minded”). She did not oppose forced sterilization.', 'answer_type': 'Extractive', 'boolean_explanation': None, 'cached_source_url': 'https://web.archive.org/web/20230130085631/https://www.thenation.com/article/society/canceling-margaret-sanger/', 'source_medium': 'Web text', 'source_url': 'https://www.thenation.com/article/society/canceling-margaret-sanger/'}],
       dtype=object), 'question': 'Was Sanger a eugenicist?'}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ]

El resultado no es el esperado y posiblemente algunas de las partes del pipeline necesite algunos ajustes, El primer paso realizado es modificar el prompt de la función `verify_evidence`, volver a ejecutar la función, sin generar nuevamente embeddings ni faiss, y ver que resultado aporta:

Old prompt:

instructions = <br>
"""
    You are an Evidence Verifier for a fact-checking system. <br>
    Your task is to verify a claim using ONLY the evidence provided to you. <br>
    Do not use external knowledge. <br>
    Do not assume facts that are not present in the evidence. <br>
    For each evidence item, determine its relationship to the claim: <br>
    - SUPPORTS: <br>
    The evidence contains information that supports the claim. <br>
    - REFUTES:<br>
    The evidence contains information that contradicts the claim.<br>
    - NEUTRAL:<br>
    The evidence is related to the topic but does not provide enough<br>
    information to support or refute the claim.<br>
    Then determine the overall verdict:<br>
    - SUPPORTED:<br>
    The available evidence is sufficient to support the claim.<br>
    - REFUTED:<br>
    The available evidence is sufficient to refute the claim.<br>
    - NOT_ENOUGH_EVIDENCE:<br>
    The evidence does not contain enough information to reach a conclusion.<br>
    - CONFLICTING_EVIDENCE:<br>
    The evidence contains substantial incompatible information supporting
    and refuting the claim, and the conflict cannot be resolved from the
    provided evidence. <br>
    Set evidence_sufficient to true only when the retrieved evidence contains
    enough factual information to reach a justified conclusion. <br>
    Assess every evidence item provided.<br>
    Base the final verdict on the content of the evidence, not on retrieval
    similarity scores.<br>
    Write all reasons and the final explanation in English.
"""

In [64]:
verification_conflicting_v2 = verify_evidence(
    claim=claim_conflicting,
    evidences=result_conflicting["evidences"],
    client=client
)

print(
    verification_conflicting_v2.model_dump_json(indent=2)
)

{
  "verdict": "CONFLICTING_EVIDENCE",
  "evidence_sufficient": true,
  "evidence_assessments": [
    {
      "evidence_id": 1,
      "relation": "NEUTRAL",
      "reason": "It characterizes Sanger's eugenics as racist and coercive and reports her support for sterilizing people with disabilities, supporting the eugenics/racism portion. However, it does not establish that her goal in founding Planned Parenthood was to eradicate minorities."
    },
    {
      "evidence_id": 2,
      "relation": "NEUTRAL",
      "reason": "It reports that Planned Parenthood of Greater New York cited Sanger's documented racist legacy and deep belief in eugenics. It does not provide evidence that Planned Parenthood was founded with the goal of eradicating minorities."
    },
    {
      "evidence_id": 3,
      "relation": "NEUTRAL",
      "reason": "It asserts that Sanger had racist intentions and that Planned Parenthood manifested those ideologies, but the excerpt provides no specific substantiation of the asserted intention to eradicate minorities."
    },
    {
      "evidence_id": 4,
      "relation": "NEUTRAL",
      "reason": "This duplicates the assertion that Sanger had racist intentions and Planned Parenthood reflected them, without establishing that the organization's founding goal was eradication of minorities."
    },
    {
      "evidence_id": 5,
      "relation": "NEUTRAL",
      "reason": "It supports that Sanger held eugenic beliefs, including writing about racial betterment and eliminating the 'unfit.' But it does not show that her purpose in founding Planned Parenthood was to eradicate minorities."
    },
    {
      "evidence_id": 6,
      "relation": "NEUTRAL",
      "reason": "It reports a Planned Parenthood affiliate's statement about overwhelming evidence of Sanger's belief in eugenics and a racist legacy. It leaves the claimed founding goal of eradicating minorities unresolved."
    },
    {
      "evidence_id": 7,
      "relation": "NEUTRAL",
      "reason": "It documents Sanger's support for limiting reproduction among people described as mentally and physically defective, but also presents historians' and defenders' views disputing that she was racist. It does not establish or directly disprove the alleged goal of eradicating minorities."
    },
    {
      "evidence_id": 8,
      "relation": "NEUTRAL",
      "reason": "It quotes a statement calling Planned Parenthood's founder a racist white woman and discusses the organization's racist history. It does not substantiate the specific claim that Sanger founded it to eradicate minorities."
    },
    {
      "evidence_id": 9,
      "relation": "NEUTRAL",
      "reason": "It presents a view that Sanger did not seem racist, while noting her associations with racist eugenicists. This bears on the racism component but does not address the alleged goal of eradicating minorities."
    },
    {
      "evidence_id": 10,
      "relation": "REFUTES",
      "reason": "It reports Esther Katz's statement that the assertion that Sanger and Planned Parenthood located clinics in Black neighborhoods to control Black populations is untrue, directly contradicting the claim's alleged anti-minority eradication purpose. The excerpt also provides context that complicates equating Sanger with defenders of slavery or segregation."
    }
  ],
  "explanation": "The evidence substantially supports that Sanger embraced or collaborated with eugenic ideas, and several items characterize her legacy as racist. However, the specific assertion that her goal in founding Planned Parenthood was to eradicate minorities is not established by the supporting excerpts and is directly challenged by Evidence 10's account that claims of controlling Black populations through clinic placement are untrue. Thus, the evidence supports important aspects of the claim while contradicting or failing to substantiate its central alleged purpose, warranting a conflicting-evidence verdict."
}

Antes de dar al nuevo prompt como correcto, vamos a comprobar que no ha roto el razonamiento de las otras labels que antes salían bien:

In [66]:
#Claim 0 
verification_0_v2 = verify_evidence(
    claim=claim_test,
    evidences=result_0["evidences"],
    client=client
)

print("Predicted:", verification_0_v2.verdict)
print("Gold: SUPPORTED")
print(
    "Evidence sufficient:",
    verification_0_v2.evidence_sufficient
)

Predicted: SUPPORTED
Gold: SUPPORTED
Evidence sufficient: True

In [ ]:
#Not enough evidence
verification_nei_v2 = verify_evidence(
    claim=claim_nei,
    evidences=result_nei["evidences"],
    client=client
)

print("Predicted:", verification_nei_v2.verdict)
print("Gold: NOT_ENOUGH_EVIDENCE")
print(
    "Evidence sufficient:",
    verification_nei_v2.evidence_sufficient
)

Predicted: NOT_ENOUGH_EVIDENCE
Gold: NOT_ENOUGH_EVIDENCE
Evidence sufficient: False

In [75]:
#claim 1 
verification_1_v2 = verify_evidence(
    claim=claim_1,
    evidences=results,
    client=client
)

print("Predicted:", verification_1_v2.verdict)
print("Gold: REFUTED")
print(
    "Evidence sufficient:",
    verification_1_v2.evidence_sufficient
)

Predicted: REFUTED
Gold: REFUTED
Evidence sufficient: True

El diseño y el prompt V2 funcionan de forma coherente en las cuatro pruebas manuales realizadas.

Antes de asumir el nuevo prompt como el definitivo vamos a probar el pipeline completo con otras claims diferentes.  <br>

Primero seleccionamos una muestra pequeña y balanceada, por ejemplo 3 claims por clase = 12 claims, además de las que ya hemos usado. Así comprobamos que el pipeline aguanta varios ejemplos. <br>

Como ahora nuestro knowledge store descargado corresponde al bloque 0–999, podemos seleccionar únicamente claims de ese rango:

In [49]:
evaluation_set = train_df.loc[:999].copy()

evaluation_sample = (
    evaluation_set
    .groupby("label", group_keys=False)
    .sample(n=3, random_state=42) #random_state para la reproducibilidad
)

evaluation_sample[
    ["claim", "label"]
]

,claim,label
275,A study finds a diet heavy with kimchi—spiced ...,Conflicting Evidence/Cherrypicking
961,Michael Bloomberg “did not poll well as mayor ...,Conflicting Evidence/Cherrypicking
929,Government of India is monitoring all forms of...,Conflicting Evidence/Cherrypicking
777,Billionaire philanthropist and Microsoft found...,Not Enough Evidence
770,Half of UK adults are now being paid by the st...,Not Enough Evidence
255,"Sanitation coverage is now at 25%, from 16%.",Not Enough Evidence
233,"BLM injures 1000 police officers, kills36 peop...",Refuted
349,The CDC may have to stop calling COVID-19 an ‘...,Refuted
574,"Walmart Tweeted ""We wont be Rebuilding Walmart...",Refuted
611,The COVID-19 pandemic has helped bolster the r...,Supported
82,Auto workers across Michigan could have lost t...,Supported
845,Being long term unemployed for a year or over ...,Supported

In [50]:
evaluation_sample.label.unique()

array(['Conflicting Evidence/Cherrypicking', 'Not Enough Evidence',
       'Refuted', 'Supported'], dtype=object)

En este caso no vamos a hacer claim por claim, vamos a crear una función que haga todo el proceso.

In [34]:
def evaluate_averitec_sample(
    evaluation_sample,
    knowledge_zip,
    embedding_model,
    text_splitter,
    client,
    output_path,
):
    """
    Evalúa una muestra de claims de AVeriTeC utilizando el pipeline completo de verificación factual.

    Los resultados se guardan después de evaluar cada claim.
    Si existe un archivo previo de resultados, la evaluación continúa únicamente con las claims pendientes.

    Parameters
    ----------
    evaluation_sample : pd.DataFrame
        Muestra de claims que se quiere evaluar.

    knowledge_zip : str or Path
        ZIP que contiene los knowledge stores.

    embedding_model
        Modelo utilizado para generar embeddings.

    text_splitter
        Divisor utilizado para generar chunks.

    client
        Cliente de OpenAI utilizado por el Evidence Verifier.

    output_path : str or Path
        Ruta donde se guardarán progresivamente los resultados.

    Returns
    -------
    pd.DataFrame
        Tabla con los resultados de evaluación.
    """

    output_path = Path(output_path)

    # 1. Comprobamos si ya existen resultados anteriores
    if output_path.exists():

        existing_results = pd.read_csv(
            output_path
        )

        evaluation_results = (
            existing_results.to_dict("records")
        )

        completed_claim_ids = set(
            existing_results["claim_id"]
            .astype(int)
            .tolist()
        )

        print(
            f"Resultados anteriores encontrados: "
            f"{len(completed_claim_ids)} claims."
        )

    else:

        evaluation_results = []
        completed_claim_ids = set()

    # 2. Recorremos la muestra de evaluación
    for claim_id, row in evaluation_sample.iterrows():

        claim_id = int(claim_id)

        # Si ya está evaluada, no repetimos el cálculo
        if claim_id in completed_claim_ids:

            print(
                f"\nClaim {claim_id} ya evaluada. "
                "Se omite."
            )

            continue

        claim = row["claim"]

        gold_label = normalize_averitec_label(
            row["label"]
        )

        print(f"\nEvaluando claim {claim_id}...")
        print("Gold:", gold_label)

        # 3. Ejecutamos el pipeline completo
        result = verify_averitec_claim(
            claim_id=claim_id,
            claim=claim,
            knowledge_zip=knowledge_zip,
            embedding_model=embedding_model,
            text_splitter=text_splitter,
            client=client,
        )

        predicted_label = (
            result["verification"].verdict
        )

        # 4. Guardamos el resultado de la claim
        evaluation_results.append({
            "claim_id": claim_id,
            "claim": claim,
            "gold": gold_label,
            "predicted": predicted_label,
            "correct": predicted_label == gold_label,
            "evidence_sufficient": (
                result["verification"].evidence_sufficient
            ),
            "explanation": (
                result["verification"].explanation
            ),
        })

        completed_claim_ids.add(claim_id)

        # 5. Guardamos un checkpoint después de cada claim
        results_df = pd.DataFrame(
            evaluation_results
        )

        results_df.to_csv(
            output_path,
            index=False,
            encoding="utf-8"
        )

        print("Predicted:", predicted_label)
        print(
            "Correct:",
            predicted_label == gold_label
        )
        print(
            f"Resultados guardados: {len(results_df)}"
        )

    return pd.DataFrame(evaluation_results)

Vamos a crear un proceso de protección, en el caso de alguna interrupción en alguna de las 12 claims, tener las demás guardadas y no perder el proceso. Además, si tenemos que volver a ejecutar, la función detectará si la claim ya se ha guardado y no volverá a ejecutarla.

In [52]:
EVALUATION_RESULTS_PATH = (
    PROCESSED_DIR / "evaluation_sample_results.csv"
)

In [55]:
evaluation_results_df = evaluate_averitec_sample(
    evaluation_sample=evaluation_sample,
    knowledge_zip=knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
    output_path=EVALUATION_RESULTS_PATH,
)

Resultados anteriores encontrados: 11 claims.

Claim 275 ya evaluada. Se omite.

Claim 961 ya evaluada. Se omite.

Claim 929 ya evaluada. Se omite.

Claim 777 ya evaluada. Se omite.

Claim 770 ya evaluada. Se omite.

Claim 255 ya evaluada. Se omite.

Claim 233 ya evaluada. Se omite.

Claim 349 ya evaluada. Se omite.

Claim 574 ya evaluada. Se omite.

Claim 611 ya evaluada. Se omite.

Claim 82 ya evaluada. Se omite.

Evaluando claim 845...
Gold: SUPPORTED
Corpus manejable: 38173 chunks.
No es necesario aplicar preselección TF-IDF.
Documentos originales: 623
Documentos únicos: 623
Documentos finales: 623
Chunks iniciales: 38173
Chunks finales: 38173

Batches: 100%|██████████| 597/597 [1:25:54<00:00,  8.63s/it]

Predicted: CONFLICTING_EVIDENCE
Correct: False
Resultados guardados: 12

In [56]:
evaluation_results_df[
    [
        "claim_id",
        "gold",
        "predicted",
        "correct",
        "evidence_sufficient"
    ]
]

,claim_id,gold,predicted,correct,evidence_sufficient
0,275,CONFLICTING_EVIDENCE,CONFLICTING_EVIDENCE,True,True
1,961,CONFLICTING_EVIDENCE,CONFLICTING_EVIDENCE,True,True
2,929,CONFLICTING_EVIDENCE,SUPPORTED,False,True
3,777,NOT_ENOUGH_EVIDENCE,REFUTED,False,True
4,770,NOT_ENOUGH_EVIDENCE,NOT_ENOUGH_EVIDENCE,True,False
5,255,NOT_ENOUGH_EVIDENCE,NOT_ENOUGH_EVIDENCE,True,False
6,233,REFUTED,NOT_ENOUGH_EVIDENCE,False,False
7,349,REFUTED,REFUTED,True,True
8,574,REFUTED,NOT_ENOUGH_EVIDENCE,False,False
9,611,SUPPORTED,SUPPORTED,True,True
10,82,SUPPORTED,SUPPORTED,True,True
11,845,SUPPORTED,CONFLICTING_EVIDENCE,False,True

### Análisis preliminar de la evaluación

Una vez validado manualmente el comportamiento del `Evidence Verifier` sobre ejemplos
representativos de las cuatro clases de AVeriTeC, se realizó una primera evaluación
exploratoria sobre una muestra balanceada de 12 afirmaciones del conjunto de entrenamiento,
seleccionando tres ejemplos por clase.

El sistema clasificó correctamente 7 de las 12 afirmaciones evaluadas. Este resultado no
se interpreta como una estimación final del rendimiento del sistema, ya que la muestra es
pequeña y pertenece al conjunto de entrenamiento, utilizado durante el desarrollo del
pipeline y del prompt del verificador. Su finalidad es principalmente diagnóstica: comprobar
el comportamiento del pipeline completo sobre ejemplos no inspeccionados previamente e
identificar posibles fuentes de error antes de realizar la evaluación sobre el conjunto
de desarrollo (`dev`).

Los errores observados no presentan un único patrón. En algunos casos, el sistema devuelve
`NOT_ENOUGH_EVIDENCE` junto con `evidence_sufficient=False` para afirmaciones cuyo gold
label es `REFUTED`. Esto puede indicar que el problema no se encuentra necesariamente en
el razonamiento del LLM, sino en una etapa anterior del pipeline: las evidencias recuperadas
por el RAG podrían no contener la información necesaria para refutar la afirmación.

En otros casos, el sistema considera que existe evidencia suficiente, pero asigna una clase
distinta de la etiqueta gold. Estos errores pueden estar relacionados con la interpretación
de las evidencias por parte del `Evidence Verifier`, por ejemplo al distinguir entre
evidencia que contradice directamente una afirmación y evidencia que simplemente describe
una situación alternativa, o al tratar afirmaciones que contienen matices temporales,
cuantitativos o múltiples componentes factuales.

Por este motivo, antes de modificar nuevamente el prompt o los parámetros de recuperación,
se realizará un análisis individual de las predicciones incorrectas. El objetivo será
distinguir entre dos tipos principales de error:

1. **Errores de retrieval:** la evidencia necesaria existe en el Knowledge Store, pero no
   aparece entre los fragmentos recuperados por el sistema.

2. **Errores de verificación:** las evidencias recuperadas contienen información suficiente,
   pero el LLM interpreta incorrectamente su relación con la afirmación o selecciona un
   veredicto diferente al gold.

Esta separación permitirá identificar qué componente del pipeline debe mejorarse sin
modificar innecesariamente etapas que estén funcionando correctamente.

In [57]:
evaluation_results_df["correct"].value_counts()

correct
True     7
False    5
Name: count, dtype: int64

In [59]:
errors_df = evaluation_results_df[
    evaluation_results_df["correct"] == False
][
    [
        "claim_id",
        "claim",
        "gold",
        "predicted",
        "evidence_sufficient",
        "explanation",
    ]
]

# errors_df

In [60]:
for _, row in errors_df.iterrows():

    print("\n" + "=" * 80)

    print("CLAIM ID:", row["claim_id"])
    print("CLAIM:", row["claim"])
    print("GOLD:", row["gold"])
    print("PREDICTED:", row["predicted"])
    print(
        "EVIDENCE SUFFICIENT:",
        row["evidence_sufficient"]
    )

    print("\nEXPLANATION:")
    print(row["explanation"])

================================================================================
CLAIM ID: 929
CLAIM: Government of India is monitoring all forms of communications, both online and telephonic.
GOLD: CONFLICTING_EVIDENCE
PREDICTED: SUPPORTED
EVIDENCE SUFFICIENT: True

EXPLANATION:
The evidence consistently describes India’s Centralized Monitoring System as giving government or law-enforcement agencies centralized, direct capabilities to intercept and monitor telephone communications and Internet activity. Several items explicitly characterize this capability as covering all phone and Internet communications or all telecom networks in India. Although some sources describe the system as being rolled out, in pilot mode, or planned at the time of publication, the evidence sufficiently supports the claim’s broad assertion that the Government of India monitors online and telephonic communications.

================================================================================
CLAIM ID: 777
CLAIM: Billionaire philanthropist and Microsoft founder Bill Gates worked  specifically to end livestock production.
GOLD: NOT_ENOUGH_EVIDENCE
PREDICTED: REFUTED
EVIDENCE SUFFICIENT: True

EXPLANATION:
The evidence consistently shows Gates and the Gates Foundation funding and promoting livestock breeding, health, vaccines, productivity, and livestock-based livelihoods. This directly contradicts the assertion that Gates worked specifically to end livestock production.

================================================================================
CLAIM ID: 233
CLAIM: BLM injures 1000 police officers, kills36 people and does $8 billion in damage .
GOLD: REFUTED
PREDICTED: NOT_ENOUGH_EVIDENCE
EVIDENCE SUFFICIENT: False

EXPLANATION:
The evidence contains reports of individual officer injuries and protest-related property damage, but it does not provide evidence that BLM injured 1,000 police officers, killed 36 people, or caused $8 billion in damage. No supplied source establishes the asserted totals or the claimed causal attribution to BLM. Therefore, the evidence is insufficient to verify or conclusively refute the claim.

================================================================================
CLAIM ID: 574
CLAIM: Walmart Tweeted "We wont be Rebuilding Walmarts in Cities without police"
GOLD: REFUTED
PREDICTED: NOT_ENOUGH_EVIDENCE
EVIDENCE SUFFICIENT: False

EXPLANATION:
None of the provided evidence reproduces, attributes, dates, or otherwise verifies the alleged Walmart tweet: “We wont be Rebuilding Walmarts in Cities without police.” Several items discuss Walmart's cooperation with police or security measures, but these facts neither establish nor directly contradict that Walmart posted the specific statement. ამიტომ, the evidence is insufficient to verify the claim.

================================================================================
CLAIM ID: 845
CLAIM: Being long term unemployed for a year or over nearly halves your chances of ever getting back into employment.
GOLD: SUPPORTED
PREDICTED: CONFLICTING_EVIDENCE
EVIDENCE SUFFICIENT: True

EXPLANATION:
The evidence consistently indicates that longer unemployment is associated with worse hiring or interview prospects, and some evidence shows an approximately halved measure by seven to eight months. However, it does not establish that being unemployed for a year or more nearly halves the chance of ever returning to employment. Moreover, Evidence 5 reports that three-quarters of long-term unemployed people find work within a year and that prospects after 18 months are not much lower than for those unemployed 6 to 18 months. Thus, the evidence supports a duration-related disadvantage but conflicts with the claim's broad and specific framing.

#### Primera separación diagnóstica según `evidence_sufficient`

Queremos mirar qué dice AVeriTeC en su gold justification para entender qué aspecto semántico ha interpretado de otra forma nuestro verifier.

Aqui 233 y 574 quedan excluídas de este primer bloque porque ambas tienen: `evidence_sufficient=False` y aqui la hipótesis inicial es distinta: quizá el verifier no puede responder porque el RAG no le ha entregado la evidencia adecuada.

In [ ]:
for claim_id in [929, 777, 845]:

    print("\n" + "=" * 80)
    print("CLAIM ID:", claim_id)

    print("\nCLAIM:")
    print(train_df.loc[claim_id, "claim"])

    print("\nGOLD:")
    print(train_df.loc[claim_id, "label"])

    print("\nGOLD JUSTIFICATION:")
    print(train_df.loc[claim_id, "justification"])

================================================================================
CLAIM ID: 929

CLAIM:
Government of India is monitoring all forms of communications, both online and telephonic.

GOLD:
Conflicting Evidence/Cherrypicking

GOLD JUSTIFICATION:
Government of India monitors some forms of communications, but not all of them.

================================================================================
CLAIM ID: 777

CLAIM:
Billionaire philanthropist and Microsoft founder Bill Gates worked  specifically to end livestock production.

GOLD:
Not Enough Evidence

GOLD JUSTIFICATION:
Theres not enough evidence for the claim to be proven or unproven, whilst one answer finds that Bill Gates has back a number of star up meat alternative projects in an attempt to lower carbon footprints theres, no answer could be found on if he wants to end the livestock production altogether so theres not enough evidence presented to proove the claim is true or false.

================================================================================
CLAIM ID: 845

CLAIM:
Being long term unemployed for a year or over nearly halves your chances of ever getting back into employment.

GOLD:
Supported

GOLD JUSTIFICATION:
The first question and answer pair supports the claim.

Analizamos ahora, otra vez, 845 aparte porque su gold justification es demasiado simple:

Vamos a mirar el primer question/answer gold y analizaremos más adelante los top-10 que recupera nuestro retrieval:

In [63]:
questions_845 = train_df.loc[845, "questions"]

print("Número de preguntas:", len(questions_845))

print("\nFIRST GOLD QUESTION:")
print(questions_845[0]["question"])

print("\nFIRST GOLD ANSWER(S):")

for answer in questions_845[0]["answers"]:
    print("\nAnswer:")
    print(answer["answer"])

    print("\nSource URL:")
    print(answer["source_url"])

Número de preguntas: 2

FIRST GOLD QUESTION:
Does being out of unemployment for a year or over halve your chances of ever getting back into employment?

FIRST GOLD ANSWER(S):

Answer:
Recent analysis suggests people unemployed for one to two years have a 44 per cent smaller chance of finding work within the next year than people unemployed for less than three months. For those unemployed longer, the likelihood is even slimmer.

Source URL:
Metadata

### Análisis de las predicciones incorrectas

La evaluación exploratoria sobre 12 afirmaciones permitió identificar cinco predicciones
incorrectas. Antes de modificar el `Evidence Verifier` o los parámetros del sistema de
recuperación, se analizaron individualmente estos casos con el objetivo de determinar
en qué etapa del pipeline podía haberse originado el error.

Esta distinción es relevante porque una predicción final incorrecta no implica
necesariamente que el LLM haya razonado incorrectamente. El pipeline contiene dos etapas
principales antes de generar el veredicto:

`Knowledge Store → Retrieval → Evidencias recuperadas → Evidence Verifier → Veredicto`

Por tanto, un error puede producirse porque el sistema de recuperación no haya seleccionado
la evidencia necesaria, o porque el `Evidence Verifier` haya interpretado incorrectamente
evidencias que sí eran suficientes.

| Claim ID | Gold | Predicción | Diagnóstico preliminar |
|---|---|---|---|
| 929 | `CONFLICTING_EVIDENCE` | `SUPPORTED` | Posible error del `Evidence Verifier` |
| 777 | `NOT_ENOUGH_EVIDENCE` | `REFUTED` | Posible error del `Evidence Verifier` |
| 233 | `REFUTED` | `NOT_ENOUGH_EVIDENCE` | Posible error de retrieval |
| 574 | `REFUTED` | `NOT_ENOUGH_EVIDENCE` | Posible error de retrieval |
| 845 | `SUPPORTED` | `CONFLICTING_EVIDENCE` | Error todavía ambiguo entre retrieval y verificación |

#### Claim 929

La afirmación sostiene que el Gobierno de India monitoriza **todas** las formas de
comunicación, tanto online como telefónicas. El gold label de AVeriTeC es
`CONFLICTING_EVIDENCE` y su justificación indica que el Gobierno monitoriza algunas formas
de comunicación, pero no todas.

El `Evidence Verifier`, sin embargo, clasificó la afirmación como `SUPPORTED`. En su propia
explicación reconoció que algunas fuentes describían el sistema como planificado, en fase
piloto o todavía en proceso de despliegue, pero terminó considerando suficiente la evidencia
para respaldar la afirmación completa.

Este caso sugiere un posible problema de interpretación relacionado con el alcance de la
afirmación. Expresiones como *some*, *certain* o la existencia de capacidad para realizar
una actividad no implican necesariamente una afirmación absoluta como *all forms of
communications*. Por tanto, el verificador debe prestar especial atención a cuantificadores,
alcance y estado temporal de los hechos.

#### Claim 777

La afirmación indica que Bill Gates trabajó específicamente para terminar con la producción
ganadera. AVeriTeC la clasifica como `NOT_ENOUGH_EVIDENCE`, ya que existen evidencias sobre
su apoyo a proyectos de alternativas a la carne y reducción de emisiones, pero no evidencia
suficiente para determinar si su objetivo era eliminar completamente la producción ganadera.

El sistema predijo `REFUTED` porque recuperó evidencias sobre financiación de sanidad animal,
productividad ganadera y medios de vida relacionados con el ganado, interpretando estas
actividades como una contradicción directa de la afirmación.

Sin embargo, la existencia de actividades diferentes o aparentemente opuestas no constituye
por sí sola una refutación. Para clasificar una afirmación como `REFUTED`, la evidencia debe
contradecir directamente el hecho afirmado o hacerlo lógicamente incompatible. Este caso
sugiere que el `Evidence Verifier` puede estar utilizando un criterio demasiado amplio para
considerar que una evidencia refuta una afirmación.

#### Claims 233 y 574

Las claims 233 y 574 presentan un patrón diferente. Ambas tienen gold label `REFUTED`, pero
el sistema devuelve `NOT_ENOUGH_EVIDENCE` junto con `evidence_sufficient=False`.

En la claim 233, relativa a cifras de policías heridos, fallecidos y daños económicos
atribuidos a BLM, el verificador indica que las evidencias recuperadas mencionan incidentes
individuales, pero no proporcionan información suficiente para confirmar ni refutar las
cantidades concretas indicadas en la afirmación.

En la claim 574, relativa a un supuesto tweet de Walmart, el verificador señala que ninguna
de las evidencias recuperadas permite verificar que el mensaje existiera ni demuestra
directamente que fuera falso.

En ambos casos, la conclusión `NOT_ENOUGH_EVIDENCE` es coherente con las evidencias que el
LLM afirma haber recibido. Por ello, estos errores podrían encontrarse en una etapa anterior:
la evidencia necesaria para refutar las afirmaciones puede existir dentro del Knowledge
Store de AVeriTeC, pero no haber sido seleccionada entre los fragmentos finales recuperados
por el sistema. Estos casos se analizarán posteriormente comparando las evidencias
recuperadas con las evidencias de referencia del dataset.

#### Claim 845

La claim 845 afirma que permanecer desempleado durante un año o más reduce casi a la mitad
la probabilidad de volver a encontrar empleo. El sistema la clasificó como
`CONFLICTING_EVIDENCE`, mientras que AVeriTeC la etiqueta como `SUPPORTED`.

La justificación general del dataset únicamente indicaba que el primer par
pregunta-respuesta respaldaba la afirmación, por lo que se inspeccionó específicamente dicha
evidencia gold. La respuesta de referencia indica que las personas desempleadas durante
entre uno y dos años tienen una probabilidad un **44 % menor** de encontrar trabajo durante
el año siguiente que aquellas desempleadas durante menos de tres meses, y que la probabilidad
disminuye todavía más para periodos de desempleo superiores.

Esta evidencia respalda claramente los elementos centrales de la claim:

`one year or over → unemployed for one to two years`

y

`nearly halves the chances → 44 % smaller chance`.

Existe una pequeña diferencia entre la formulación *ever getting back into employment* y la
evidencia, que se refiere a encontrar empleo durante el año siguiente. Sin embargo, los
anotadores de AVeriTeC consideraron que la correspondencia semántica era suficiente para
clasificar la afirmación como `SUPPORTED`.

El `Evidence Verifier` había considerado conflictiva la evidencia porque también encontró
información indicando que una parte importante de los desempleados de larga duración vuelve
a encontrar trabajo. No obstante, estas dos afirmaciones no son necesariamente
contradictorias: es posible que muchas personas vuelvan a trabajar y, simultáneamente, que
su probabilidad de hacerlo sea considerablemente inferior a la de personas que llevan menos
tiempo desempleadas.

Este caso muestra que `CONFLICTING_EVIDENCE` no debe utilizarse simplemente porque existan
estadísticas o formulaciones diferentes. Debe existir una contradicción factual relevante
entre evidencias que afecte al veredicto de la claim.

No obstante, todavía debe comprobarse si la evidencia gold del 44 % fue realmente recuperada
entre los fragmentos enviados al LLM. Si estaba presente, el error correspondería
principalmente al `Evidence Verifier`; si no estaba presente, el sistema de retrieval habría
contribuido al error.

En consecuencia, esta primera evaluación muestra que los fallos del sistema no proceden
necesariamente de un único componente. Algunos casos apuntan a problemas de recuperación de
evidencia, mientras que otros revelan posibles limitaciones en la interpretación semántica
del `Evidence Verifier`. Por este motivo, no se modifica todavía el prompt ni la estrategia
de recuperación: primero se completará el diagnóstico de los errores para evitar corregir
un componente cuando el problema se encuentre en otro.

Seguimos verificando la claim 845, 233 y 574:

In [64]:
claim_id = 845
claim = train_df.loc[claim_id, "claim"]

result_845 = verify_averitec_claim(
    claim_id=claim_id,
    claim=claim,
    knowledge_zip=knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
)

Corpus manejable: 38173 chunks.
No es necesario aplicar preselección TF-IDF.
Documentos originales: 623
Documentos únicos: 623
Documentos finales: 623
Chunks iniciales: 38173
Chunks finales: 38173

Batches: 100%|██████████| 597/597 [1:43:37<00:00, 10.41s/it]

In [65]:
for i, evidence in enumerate(
    result_845["evidences"],
    start=1
):
    print("\n" + "=" * 80)
    print(f"EVIDENCE {i}")
    print("Score:", round(evidence["score"], 4))
    print("URL:", evidence["url"])
    print("\nTEXT:")
    print(evidence["text"])

================================================================================
EVIDENCE 1
Score: 0.805
URL: https://time.com/34114/unemployment-hiring-rate/

TEXT:
Only one in 10 long-term people who have been unemployed for six months or more are hired every year, according to a Princeton study that affirms the bleak outlook for many long-term job seekers. With the unemployment rate near five-year lows amid a post-recession recovery, the long-term unemployed are still struggling to find jobs. Even in regions with the strongest job markets, the rate of hiring for the long-term jobless is no better. Alan Krueger, lead researcher and a former chief White House economic advisor, told CNBC that long-term job seekers are prone to becoming discouraged and putting less effort into finding a job. Meanwhile, employers can be skeptical of potential hires who have not worked for six months. “A concerted effort will be needed to raise the employment prospects of the long-term unemployed, especially as they are likely to withdraw from the job market at an increasing rate,” Kreuger wrote in the paper. - Jane Fonda Champions Climate Action for Every Generation

================================================================================
EVIDENCE 2
Score: 0.805
URL: https://www.linkedin.com/pulse/question-proposed-linkedin-someone-unemployed-over-do-matt

TEXT:
you must be more open and flexible. After all, your ultimate goal is to get back to work! Something else I say in the book and tell job seekers is this. And it’s something very important for long-term unemployed to realize. Employers know that the bad economy has resulted in your being out of work for longer than normal. So employers today accept that you’ll be out of work for a longer-than-usual amount of time. But there will come a point where employers will not accept the bad economy as an excuse. And turn their attention to YOU! In other words, they’ll eventually start blaming you for the unemployment. Something you don’t want employers saying or even thinking, trust me on this! So doing whatever it takes to get yourself back to work is crucial for success. And for preventing employers from feeling or outright blaming you for your being out of work for so long. Something I have found many job seekers unaware of until it’s too late. So I want to let you all know about this ahead of

================================================================================
EVIDENCE 3
Score: 0.803
URL: https://fivethirtyeight.com/features/the-biggest-predictor-of-how-long-youll-be-unemployed-is-when-you-lose-your-job/

TEXT:
higher odds of becoming long-term unemployed. For those who didn’t receive benefits, the odds of becoming long-term unemployed were even higher at 40 percent.9 If extended benefits aren’t to blame, that brings us back to luck. The long-term unemployed are mostly people who lost jobs at a time when companies weren’t hiring. Once they had been out of work for more than a few months, their chances of getting hired fell off dramatically: Multiple experiments have found that employers are reluctant to consider candidates who have been out of work for more than six months, even when those candidates are more qualified. Worse, recent research from former Obama administration economics adviser Alan Krueger and others suggests that most of the long-term unemployed are unlikely to find stable employment even if the economy improves. Taken together, these are discouraging findings. A weak economy can cause long-term unemployment, but a stronger economy can’t fix it. That suggests policymakers’

================================================================================
EVIDENCE 4
Score: 0.7988
URL: https://www.linkedin.com/pulse/question-proposed-linkedin-someone-unemployed-over-do-matt

TEXT:
unemployed for 2yrs plus on top of that going through a divorce in which my Ex was from out of the country and had one child. I got a double whammy and top of that looking for a job with a positive state of mind. I believe challenges happens to all in part of our human life. A lot of people that are long term unemployed are hard working people just only a few might take advantage, but most would like to get back on their feet. There isn’t any solid jobs where you can stick around for 30 plus years. If I had the capital, I would start my own business.. I know it’s risky, but you know marriage is as well (: Peace to all……..I wish you the very best in the journey call “Life” - I was looking for work for nearly 4 years and have recently received a job. I wasn’t being lazy. I tried everything I could to get a job: speculative letters, applying online, speculative e-mails, handing out CV’s by hand and a lot more. - Most likely in this market it is bad luck. I know some of the most

================================================================================
EVIDENCE 5
Score: 0.7929
URL: https://money.cnn.com/2012/06/14/news/economy/long-term-unemployment/index.htm

TEXT:
longer, making it more difficult for people to find new jobs. There are 5.4 million people who've been out of work for more than six months, which is generally considered when long-term unemployment begins. While the share of long-term unemployed is down a bit from its peak last year, it's still at record-high levels. So is the average length of time it takes to get a job, which has hovered around 40 weeks for the past year. The news, however, isn't all bad, according to the Fed economists. Their study debunks the view that the long-term unemployed will never find new positions. Even at this weak re-employment rate, about half of the long-term unemployed will find a job within six months, and three-quarters within a year. And the chances of finding a job for those out of work 18 months or more is not much lower than those who've been jobless between 6 and 18 months. "[There's] a low risk that the U.S. labor market will suffer from a bout of persistently elevated long-term

================================================================================
EVIDENCE 6
Score: 0.7925
URL: https://fivethirtyeight.com/features/the-biggest-predictor-of-how-long-youll-be-unemployed-is-when-you-lose-your-job/

TEXT:
One characteristic distinguishes the long-term unemployed from the rest of America’s jobless. It isn’t how many hours they worked at their old job, or what industry they came from, or even their level of education. A FiveThirtyEight analysis shows that by far the single biggest predictor of whether someone will be out of work for a year or more is the state of the economy when he or she loses his or her job.1 Over the past 15 years, a period spanning two recessions, a one-point increase in the unemployment rate increased an individual’s odds of remaining unemployed for at least a year by about 35 percent. No other characteristic — age, sex, race, marital status, education or occupation, among others — had even close to that big an effect. Americans who had the misfortune of losing their jobs during the height of the most recent recession in 2009 were more than four times as likely to end up out of work for a year or longer than those who lost their jobs during the comparatively good

================================================================================
EVIDENCE 7
Score: 0.788
URL: https://www.brookings.edu/wp-content/uploads/2016/07/2014a_krueger.pdf

TEXT:
to assess the hypothesis that the long- term unemployed are on the margins of the labor market. To preview our main findings, we tentatively conclude that the long-term unemployed are less connected to the economy than the short-term unemployed, and that many eventually withdraw from the labor force. The chance of holding a full-time, steady job for those who became unemployed in the 2008–12 period was 19 percent at the start of their unemployment spell, 11 percent after 7 months without working, and only 6 percent after 2 years with- out working.1 Nearly half of those who were jobless for seven months or longer had withdrawn from the labor force within 15 months of becom- ing unemployed in 2012. Even at times when—or in regions where—the economy is relatively strong, the long-term unemployed face long odds of returning to steady, full-time employment. We also find that the long-term unemployed are about 60 percent as effective at matching to job openings as are the short-term

================================================================================
EVIDENCE 8
Score: 0.7875
URL: https://www.motherjones.com/kevin-drum/2013/12/10-reasons-long-term-unemployment-national-catastrophe/

TEXT:
of your peers and puts stress on your family, making it likely that further awful things, like divorce or suicide, will be in your near future.” - It’s long-lasting. Cristobal Young reports that “job loss has consequences that linger even after people return to work. Finding a job, on average, recovers only about two thirds of the initial harm of losing a job….Evidence from Germany finds subjective scarring of broadly similar magnitude that lasts for at least 3 to 5 years.“ - It dramatically reduces the prospect of getting another job. There’s always been plenty of anecdotal evidence that employers don’t like job candidates who have long spells of unemployment, but recent research suggests that this attitude has become even worse in the current weak economy. Rand Ghayad, a visiting scholar at the Boston Fed, sent out a bunch of fictitious resumes for 600 job openings. Each batch of resumes was slightly different (industry experience, job switching history, etc.), and all of these

================================================================================
EVIDENCE 9
Score: 0.7867
URL: https://money.cnn.com/2012/06/14/news/economy/long-term-unemployment/index.htm

TEXT:
NEW YORK (CNNMoney) -- We all know by now that it's hard for the long-term unemployed to get back into the workforce. But just how hard is it? Economists at the San Francisco Federal Reserve put a number on the odds. In the first few weeks after losing their jobs, about 3 in 10 people are able to find work. But after about a year of being out of work, the chances of landing a job fall to just 1 in 10 per month. People with the best job prospects tend to find new opportunities fairly quickly. But those who come from industries that are downsizing or who have outdated skills can wind up unemployed for many months or even years. Though this has long been true, the Great Recession has hit the long-term unemployed even harder. The unemployment rate was higher during the 1980s recession, but the most recent economic downturn has lasted longer, making it more difficult for people to find new jobs. There are 5.4 million people who've been out of work for more than six months, which is

================================================================================
EVIDENCE 10
Score: 0.7839
URL: https://obamawhitehouse.archives.gov/the-press-office/2014/01/31/remarks-president-long-term-unemployment

TEXT:
it’s a lot harder to look for work if you can’t put gas in the gas tank, if you’re worried about whether there’s food on the table for your kid. If Mom isn’t making the rent and paying her phone bill, it’s a lot harder for her to follow up with a potential employer. Unemployment insurance provides that extra bit of security so that losing your livelihood doesn’t mean you lose everything that you’ve worked so hard to build. And that’s true whether you’ve been out of work for one month or six months. But folks who have been unemployed the longest often have the toughest time getting back to work. It’s a cruel Catch-22 -– the longer you’re unemployed, the more unemployable you may seem. Now, this is an illusion, but it’s one that unfortunately we know statistically is happening out there. According to one study, if you’ve been out of work eight months, you’re likely to get called back for an interview only about half as often as if you’ve been out of work one month -- even with the

La conclusión importante es: no es un error puramente de retrieval ni puramente del verifier; hay contribución de ambos.

La evidencia que Averitec utilizó decía: 1–2 años desempleado, implica 44 % menos probabilidad de encontrar trabajo. Esa formulación concreta no aparece en nuestro Top-10. Nuestro RAG recuperó documentos `muy relacionados`, pero no ese fragmento exacto.

Un problema que vemos: El verifier utilizó especialmente Evidence 5 para justificar `CONFLICTING_EVIDENCE`. El verifier está tomando estadísticas diferentes como contradictorias.

`Conclusión:` El Retrieval recupera información muy relevante, pero no el fragmento gold específico del 44 %. Por otro lado el Evidence Verifier interpreta como contradictorias evidencias que pueden coexistir perfectamente.

In [66]:
claim_id = 233
claim = train_df.loc[claim_id, "claim"]

result_233 = verify_averitec_claim(
    claim_id=claim_id,
    claim=claim,
    knowledge_zip=knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
)

Corpus grande detectado: 150586 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 1115
Documentos únicos: 1112
Documentos finales: 100
Chunks iniciales: 150586
Chunks finales: 8933

Batches: 100%|██████████| 140/140 [41:39<00:00, 17.86s/it]

In [67]:
for i, evidence in enumerate(
    result_233["evidences"],
    start=1
):
    print("\n" + "=" * 80)
    print(f"EVIDENCE {i}")
    print("Score:", round(evidence["score"], 4))
    print("URL:", evidence["url"])
    print("\nTEXT:")
    print(evidence["text"])

================================================================================
EVIDENCE 1
Score: 0.65
URL: https://www.pewresearch.org/social-trends/2017/01/11/behind-the-badge/

TEXT:
police say their jobs are harder now as a consequence of recent high-profile fatal incidents involving blacks and police. Overall, fully 86% of officers say their jobs are harder, including substantial majorities of officers in police departments with fewer than 300 officers as well as those working in “mega departments” with 2,600 officers or more (84% and 89%, respectively). In fact, across every major demographic group analyzed for this survey, about eight-in-ten officers or more say these high-profile incidents have made policing more challenging and more dangerous. While the impact of these incidents is broadly felt, officers in larger departments are far more likely than those in small agencies to say these incidents have had an impact. For example, roughly half of officers (54%) in departments with fewer than 300 officers say their peers have become less willing to stop and question people who seem suspicious. By contrast, fully 86% of police in departments with 2,600 officers

================================================================================
EVIDENCE 2
Score: 0.6386
URL: https://www.cambridge.org/core/journals/perspectives-on-politics/article/black-lives-matter-evidence-that-policecaused-deaths-predict-protest-activity/BFA2E74F4BCB25C3C222807E8B1111D4

TEXT:
on deaths caused by police to the dates between January 1, 2013, the earliest date for which the data is available, and August 9, 2014, the date of death of Michael Brown and the beginning of our protest observation period. During that time, at least 1730 people were killed by the police;Footnote 55 we remove from this dataset deaths that were caused by vehicle collisions, leaving a total of 1,637 people killed by police, including 439 Black people. A total of 235 victims were unarmed, including 80 unarmed Black people. Table 2 summarizes the data on police-caused deaths and Black Lives Matter protests by locality. The table shows the total number of localities in our analysis, and breaks these localities down by the presence/absence of at least one documented Black Lives Matter protest during the observation period. Footnote 56 Overall, from August 2014 to August 2015, Black Lives Matter protests occurred in 14% of U.S. cities with population over 30,000. Note: Based on all cities

================================================================================
EVIDENCE 3
Score: 0.6382
URL: https://www.foxnews.com/us/george-floyd-death-here-are-the-cities-protesting

TEXT:
day turned into night, a handful of stores in Manhattan had their windows broken and merchandise stolen. Officers sprayed crowds with chemicals, and video showed two police cruisers lurching into a crowd of demonstrators on a Brooklyn street, knocking several to the ground, after people attacked it with thrown objects, including something on fire. Since the protests began days ago, at least 790 people have been arrested, 33 officers have been injured and 27 police vehicles have been damaged or destroyed, police said. New York City Mayor Bill de Blasio, a Democrat, blamed the destruction on a small number of agitators who he said “do not represent this city” and were purposely trying to incite violence against police. “We appreciate and respect all peaceful protest, but now it is time for people to go home,” de Blasio told reporters outside the city's emergency management headquarters just after 11:30 p.m. “What we’re seeing is people coming in from outside, a lot of them are

================================================================================
EVIDENCE 4
Score: 0.6378
URL: https://theanarchistlibrary.org/library/kristian-williams-our-enemies-in-blue

TEXT:
A total of 105 patrol officers died on the job in 2012. Less half of those (51) died as the result of violence, and another 48 died in traffic accidents.[134] Between 1961 and 2012, 3,847 cops were murdered and 2,946 died in accidents—averaging about 75 murders and 58 fatal accidents in a typical year.[135] Naturally it is not to be lost sight of that these numbers represent human lives, not widgets or sacks of potatoes. But let’s also remember that there were 4,383 fatal work injuries in 2012. As dangerous professions go, according to the Bureau of Labor Statistics, policing is not even in the top ten. In terms of total fatalities, more truck drivers are killed than any other kind of worker (741 in 2012). A better measure of occupational risk, however, is the rate of work-related deaths per 100,000 workers. In 2012, for example, it was 17.4 for truck drivers.[136] At 15.0 deaths per 100,000, policing is slightly less dangerous than being a maintenance worker (15.7) and slightly more

================================================================================
EVIDENCE 5
Score: 0.636
URL: https://www.aclu.org/news/criminal-law-reform/defunding-the-police-will-actually-make-us-safer

TEXT:
city council members and mayors) stop allocating funds for the police to acquire more militarized equipment and instead ask for that money to go toward community-run violence-prevention programs. We can demand that our federal government redirect the money that funds police presence in schools to putting counselors in schools instead. Funneling so many resources into law enforcement instead of education, affordable housing, and accessible health care has caused significant harm to communities. Police violence is actually a leading cause of death for Black men: A recent study found that 1 in 1,000 Black men can expect to be killed by police, and public health experts have described police violence as a serious public health issue. For a country like ours, which considers itself a modern democracy that pushes ideals of freedom and justice for all, that number should be truly shocking. Much of the work police do is merely engage in the daily harassment of Black communities for minor

================================================================================
EVIDENCE 6
Score: 0.6343
URL: https://www.cnn.com/2020/07/18/us/chicago-protest-18-police-injured/index.html

TEXT:
then shot with fireworks.” The officer fears the growing violence puts officers lives in danger. “The lack of leadership has already gotten dozens of officers hurt….if the police aren’t allowed to do what is needed we will be burying one of our own,” the veteran officer told CNN. The incident comes two days after three NYPD officers and a top chief were injured after a clash with protesters. A 24-year-old female was arrested for striking the officers with a cane as they tried to arrest a protester, the department said. “Three officers violently attacked by protesters crossing the Brooklyn Bridge,” the department said on its verified Twitter page. “The officers sustained serious injuries. This is not peaceful protest, this will not be tolerated.” CNN’s Chandler Thornton contributed to this report.

================================================================================
EVIDENCE 7
Score: 0.6328
URL: https://www.usatoday.com/story/money/usaandmain/2020/06/09/floyd-protests-riots-looting-damage-insurance-coverage/5318935002/

TEXT:
this could be one of the costliest U.S. civil disorders, said Loretta Worters, vice president of media relations at the Insurance Information Institute. The nation's highest recorded financial damages due to civil disorder stem from the acquittal in 1992 of Los Angeles Police Department officers for using excessive force in the arrest and beating of Rodney King. The estimated loss was $735 million or $1.4 billion adjusted in 2020 dollars, according to data from Property Claim Services, a Verisk Analytics company. It could take months to assess the financial toll related to recent unrest. Small-business insurance policies generally cover damage to windows, doors, light fixtures and contents, including furniture, office supplies, machinery and computers, plus the cost of boarding up windows and securing the business. Damage to cars is covered under auto insurance policies, which include comprehensive coverage. Paul Blume, senior vice president, state government and member relations for

================================================================================
EVIDENCE 8
Score: 0.632
URL: https://www.usccr.gov/files/pubs/2018/11-15-Police-Force.pdf

TEXT:
and 10.13 per million for Native American people. This means that black and Native American people were fatally shot by officers―over twice and three times comparaed Source: https://www.theguardian.com/us-news/ng-interactive/2015/jun/01/the-counted-police-killings- Data collected by Guardian reporters also revealed pronounced racial disparities in the number of unarmed suspects killed by police in the first half of 2015. Thirty-two percent of black people killed by police in 2015 were unarmed, as were 25 percent of Latino people, compared to 15 percent of white people.115 This means that while people of color make up fewer than 38 percent 113 Due to the issues of data collection and reporting discussed above, these are the best data available and thus, do not represent true totals. See e.g., Guardian, “The Counted,” supra note 87. At the time of this report the Guardian did not have 2017 data available; Mapping Police Violence, https://mappingpoliceviolence.org/ (last accessed Oct.

================================================================================
EVIDENCE 9
Score: 0.6303
URL: https://www.usccr.gov/files/pubs/2018/11-15-Police-Force.pdf

TEXT:
that 2.1 per 100,000 sworn officers were killed by African-Americans in 2017.1047 3.9 per 100,000 sworn officers were killed by whites in 2016. Given the relative size of the populations, this means that 0.12 whites per million whites killed a police officer in 2016, but 0.37 blacks per million blacks killed a police officer in 2016. Are these numbers tiny? Yes. Does it mean that blacks are three times as likely to kill police In 2017, 223 African-Americans were killed by police.1049 The African-American population was about 43,646,369. This means that 0.5 African-Americans per 100,000 were killed by police officers. Also in 2017, 636 whites (including both Hispanic and non-Hispanic whites) out of 249,500,890 were killed by police officers. This means that 0.26 whites per 100,000 whites were This is important because since African-Americans are disproportionately likely to be involved in crime, they are also disproportionately likely to encounter police officers. Even the most law-

================================================================================
EVIDENCE 10
Score: 0.6283
URL: https://www.nbcnews.com/news/us-news/police-shot-hit-vehicles-george-floyd-protests-n1221856

TEXT:
A police officer in Las Vegas was critically wounded as others in New York and St. Louis were also injured during ongoing civil unrest sparked by last week's death of George Floyd in Minneapolis, officials said Tuesday. "This has been a long night for your police department ... and a tragic night for our community," Las Vegas Metropolitan Police Department Sheriff Joseph Lombardo told reporters Tuesday. "With these protests, which are leading to riots, one tragedy is only leading to another." Police had responded to the area outside the Circus Circus Hotel & Casino at about 11:30 p.m. to assist with what was described as a group of "rioters," and as officers were taking a person into custody a shot was fired from across the street, striking the officer, police said. Full coverage of George Floyd’s death and protests around the country "Our officers were taking rocks and bottles from the crowd ... when a shot rang out and the officer went down," said Lombardo, who called the wounded

Viendo el Top-10 de 233, la respuesta del LLM tiene bastante sentido. Para poder marcarla como REFUTED, idealmente necesitaríamos evidencia que contradiga una o varias de las cifras de la claim de manera suficientemente directa, sin embargo, nuestro Top-10 contiene principalmente información relacionada con protestas, policía y disturbios, pero no las cifras concretas de la claim. 

Aqui diferente de la claim 845 el retrieval no ha recuperado información suficiente, por tanto aqui el problema se encuentra en la etapa de recuperación de evidencia, cuya causa concreta
se analizará posteriormente. Otro detalle importante aqui son los scores recuperados, que están alrededor del 0.6, mientras que en la claim 845 estaban alrededor de 0.8; Esto no implica que debemos convertir estas evidencias en malas porque el score no tiene un umbral universal de verdad o calidad, pero comparativamente, sí es coherente con lo que estamos viendo: el retriever parece haber encontrado coincidencias semánticas mucho menos alineadas con la claim 233 que con la 845.

Para la claim 233 todavía nos falta una verificación, ¿Qué evidencia utilizó AVeriTeC para determinar que la claim era Refuted?

In [70]:
claim_id = 233

print("CLAIM:")
print(train_df.loc[claim_id, "claim"])

print("\nGOLD:")
print(train_df.loc[claim_id, "label"])

print("\nGOLD JUSTIFICATION:")
print(train_df.loc[claim_id, "justification"])

print("\nQUESTIONS AND ANSWERS:")

questions = train_df.loc[claim_id, "questions"]

for i, qa in enumerate(questions, start=1):

    print("\n" + "=" * 80)
    print(f"QUESTION {i}:")
    print(qa["question"])

    print("\nANSWERS:")

    for answer in qa["answers"]:
        print("\nAnswer:")
        print(answer["answer"])

        print("\nSource:")
        print(answer["source_url"])

CLAIM:
BLM injures 1000 police officers, kills36 people and does $8 billion in damage .

GOLD:
Refuted

GOLD JUSTIFICATION:
Only about 19 people have been confirmed dead as a result of the protests and about 700 police officers nationwide

QUESTIONS AND ANSWERS:

================================================================================
QUESTION 1:
Have there been news reports about how many people have been injured?

ANSWERS:

Answer:
WASHINGTON — More than 700 law enforcement officers have been injured on the job during nationwide protests over the death of George Floyd — with nearly 300 of those among New York’s Finest, according to the Department of Justice and the NYPD.

Source:
https://nypost.com/2020/06/08/more-than-700-officers-injured-in-george-floyd-protests-across-us/

================================================================================
QUESTION 2:
Is there any estimates of how much it has cost in damages?

ANSWERS:

Answer:
Not an exact amount but estimates are made.

Prior to 2020, the costliest civil disorder event in U.S. was the 1992 Los Angeles riots, according to PCS, the insurance industry's primary source for compiling and reporting insured losses resulting from catastrophes, from hurricanes to wildfires.

That five-day event caused about $1.4 billion in 2020 dollars, according to PCS. Two days of riots following the funeral of Freddie Gray caused $26 million in losses in Baltimore alone.

Protests for police reform, racial injustice continue to spread across the USVideo
But losses stemming from the Floyd protests are likely to far exceed that. In Minneapolis, where some 400 businesses were damaged, owners and insurance experts estimate costs of the damage to exceed $500 million, according to the Minneapolis Star Tribune.

Source:
https://www.foxnews.com/politics/george-floyd-protests-expensive-civil-disturbance-us-history

================================================================================
QUESTION 3:
How many people have died?

ANSWERS:

Answer:
Though curfews are lifting and protests remain predominantly peaceful, the death toll from two weeks of demonstrations over the death of George Floyd continues to creep upward, with at least 19 people—a majority of whom are black—now dead.

Source:
https://www.forbes.com/sites/jemimamcevoy/2020/06/08/14-days-of-protests-19-dead/

La diferencia más importante aqui es que nuestro Evidence Verifier no recibió estas evidencias concretas, y respecto a los daños, nuestro retrieval sí recuperó información relacionada. 

La cadena de errores sería: Knowledge Store de AVeriTeC, contiene evidencia útil: 700+ officers / 19 deaths, pero nuestro retrieval, NO selecciona esos fragmentos en el Top-10. El Evidence Verifier recibe información relacionada pero no decisiva
y determina `NOT_ENOUGH_EVIDENCE` con `evidence_sufficient=False`. Por lo tanto, en esta claim concluimos que el problema es del retrieval y no del verifier. 

En este caso, no deberíamos arreglar este problema modificando el prompt para que el LLM “adivine” que 1.000 o 36 son falsas. El problema está antes: necesitamos aumentar la probabilidad de recuperar evidencia que responda específicamente a las distintas partes de una claim numérica y multicomponente.

In [68]:
claim_id = 574
claim = train_df.loc[claim_id, "claim"]

result_574 = verify_averitec_claim(
    claim_id=claim_id,
    claim=claim,
    knowledge_zip=knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
)

Corpus grande detectado: 63998 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 850
Documentos únicos: 850
Documentos finales: 100
Chunks iniciales: 63998
Chunks finales: 2243

Batches: 100%|██████████| 36/36 [08:18<00:00, 13.85s/it]

In [69]:
for i, evidence in enumerate(
    result_574["evidences"],
    start=1
):
    print("\n" + "=" * 80)
    print(f"EVIDENCE {i}")
    print("Score:", round(evidence["score"], 4))
    print("URL:", evidence["url"])
    print("\nTEXT:")
    print(evidence["text"])

================================================================================
EVIDENCE 1
Score: 0.7229
URL: https://www.ufcw.org/press-releases/protests-for-better-jobs-at-walmart-sweep-stores-nationwide/

TEXT:
said Dorothy Halvorson, a Walmart employee in Placerville, California, who has worked at the store for 11 years and plans to take part in civil disobedience today. “We know that we are closer to change at Walmart than ever before – and it’s clear that Walmart knows it too. We won’t stop protesting until we get change. This Black Friday is historic, and we will only grow stronger from here.” In recent weeks, protesting Walmart workers have received an outpouring of national support. Calling for an end to Walmart’s illegal retaliation and attempts to silence workers who speak out for better working conditions, workers have walked off their jobs in a dozen cities, including Los Angeles, Seattle, Chicago, Ohio, Dallas, Florida, Washington, D.C. and elsewhere. “The civil disobedience by Walmart workers and supporters across the country is a testament to the immense courage of these workers fighting for dignity, respect and a decent wage — the same things that working people have marched

================================================================================
EVIDENCE 2
Score: 0.7188
URL: https://www.businessinsider.com/walmart-stores-in-kansas-city-missouri-mass-shooting-threat-2019-8

TEXT:
Mississippi. In a post to Facebook on Friday evening, the Kansas City Police Department said it was getting "a ton" of messages regarding the social media threat. "We are getting a ton of messages right now regarding a threat of violence at a local Walmart that was posted on Reddit and elsewhere," the Facebook post said. "We became aware of this threat yesterday and have been working with our federal partners to address it. The department posted an update on Saturday that said: "As of this morning we are working closely with the FBI and other law enforcement partners to investigate this threat and vet the information that is being developed. Thank you to everyone that has been keeping an eye out and alerting us to this concerning post."

================================================================================
EVIDENCE 3
Score: 0.7084
URL: https://www.tampabay.com/news/localgovernment/tampa-council-getting-report-on-police-calls-to-walmart/2282840/

TEXT:
to me with prevention programs they're trying to save money." Walmart officials did not respond directly to Reddick's concerns but said each store is analyzed to determine the level of security needed. "We will continue to monitor what is happening in that store and we have the strongest safety measures in place," said Walmart spokeswoman, Deisha Barnett. Reddick requested council be briefed on the policing of Walmart in response to a Tampa Bay Times investigation that found local Walmarts in Hillsborough, Pinellas, Pasco and Hernando counties accounted for nearly 16,800 police calls in a single year. The calls came in the rate of about two calls an hour, every hour of every day, for shoplifting or other thefts, but also for noncriminal incidents like rowdy teenagers and panhandling. The Times investigation found that calls diverted police resources from other law enforcement tasks. The report presented to the council Thursday shows that Walmart stores are still a regular trouble spot

================================================================================
EVIDENCE 4
Score: 0.7024
URL: https://baynews9.com/fl/tampa/news/2015/4/9/port_richey_police_n

TEXT:
Walmart is the wrong place to attempt these crimes. And while Walmart is effective at detecting these crimes, we will continue to collaborate with local police to focus on crime prevention.”

================================================================================
EVIDENCE 5
Score: 0.6978
URL: https://fortune.com/2016/12/18/minnesota-police-walmart-guards/

TEXT:
that condemn Walmart for spending too little on security at its stores across the country, not just in Minnesota. The ads have brought the issue into a national spotlight, notes City Pages. To address concerns, Walmart has started to implement crime deterrence programs like “Restorative Justice” and “More at the Door,” a Walmart spokesperson told Fortune in an email. (The latter of the two brings back greeters to the entrances of its stores). “We’re encouraged by a 35% reduction in calls to law enforcement agencies nationwide, on average, since we began implementing crime deterrence programs like Restorative Justice and More at the Door,” he said. “We’ll continue our outreach to law enforcement across the country as part of our ongoing commitment to meet our customers’ and associates’ expectations of a safe and enjoyable shopping experience.” This story has been updated to reflect response from Walmart.

================================================================================
EVIDENCE 6
Score: 0.697
URL: https://baynews9.com/fl/tampa/news/2015/4/9/port_richey_police_n

TEXT:
“I’ve seen the police around a lot, which I’m glad that they are at least catching some things that are going wrong,” said customer Donna Carder. Police say in the last two weeks crime has reduced only slightly. They hope the crime rate will go down significantly within the next six months. At that time, they will re-evaluate the plan to see if it’s working. If not, the agency will meet again with Walmart officials to try another plan. We spoke with Walmart about the issue. The company said it wants to continue to work with Port Richey police to keep the crimes from being attempted at its stores. “Unfortunately criminal activity such as shoplifting is a challenge all retailers deal with," Walmart said in a statement. "Our asset protection team does a great job in identifying people who break the law in our stores which demonstrates that Walmart is the wrong place to attempt these crimes. And while Walmart is effective at detecting these crimes, we will continue to collaborate with

================================================================================
EVIDENCE 7
Score: 0.6929
URL: https://www.mprnews.org/story/2016/10/27/wal-mart-police-calls

TEXT:
that are being let go because they are responding to Walmart," Okada said. In St. Paul, the Walmart generated 1,400 police service calls over the year ending in August. More than two-thirds concerned shoplifting or other forms of theft, according to police records. But City Council Member Dai Thao said the company is stepping up to address crime and public safety issues, staffing two off-duty cops daily. "It's contained and it's being taken care of and being dealt with," Thao said. "Walmart is being a good partner with the city of St. Paul and the police department." Shakopee Police Chief Jeff Tate doesn't view the top ranking number of calls to the local Walmart as unreasonable or burdensome at this point. The store has been a good citizen, he said, supporting several community-building initiatives, and it works to deter crime. "I've heard from chiefs around the country that have said how Walmart's a problem and they help pay for an officer for their location," Tate said. "Now, we're

================================================================================
EVIDENCE 8
Score: 0.6927
URL: https://spectrumlocalnews.com/ap-top-news/2019/11/14/walmart-hires-off-duty-officers-ahead-of-el-paso-reopening0

TEXT:
and take care of her.” The retail giant reopened the store amid ongoing lawsuits over security on the day of the mass shooting. The interior of the building was rebuilt after authorities took more than 10 days to finish processing blood and bone fragments in the massive crime scene. “There was a time that Walmart hired off-duty officers and for some time prior (to) August 3rd that ceased,” El Paso police spokesman Enrique Carrillo said in an email. When Police Chief Greg Allen first revealed the phasing out of officers during a City Council meeting, council members discussed possibly requiring that off-duty officers be hired at large stores, though the idea hasn’t been implemented. Instead, Walmart started hiring off-duty officers at their stores throughout the city, from its sprawling Supercenters to its smaller neighborhood grocery stores. “We’re covering Walmarts, we’re also covering Sam’s (Club),” said El Paso police union president Ron Martin. “Even the neighborhood Walmarts are

================================================================================
EVIDENCE 9
Score: 0.6918
URL: https://www.mprnews.org/story/2016/10/27/wal-mart-police-calls

TEXT:
from chiefs around the country that have said how Walmart's a problem and they help pay for an officer for their location," Tate said. "Now, we're not at that threshold yet where we're out there so much that we need to explore that kind of option." The Shakopee store is among the local Walmarts that have seen gunfire in recent years. But Tate said the incident in Shakopee was a matter of a Craigslist deal gone bad. "That had nothing to do with the actual store, other than they used the parking lot as a meeting location for an exchange," he said. "And that exchange went bad. That was why those rounds were fired."

================================================================================
EVIDENCE 10
Score: 0.6916
URL: https://www.businessinsider.com/walmart-stores-in-kansas-city-missouri-mass-shooting-threat-2019-8

TEXT:
City Police Department. Jorgenson said he could not provide information on whether a suspect has been identified or any other details while the investigation is ongoing. The Kansas City Police Department has assigned off-duty officers to local Walmart stores for added security as the investigation continues, he said. A Walmart spokeswoman told Business Insider the company was aware of the post and has been "in close contact" with stores. "We take threats like this seriously and have added additional security as appropriate," the spokeswoman said. "We will continue to help federal and local authorities with their investigation to determine the source and any credibility of a threat, which has not been substantiated." The threat comes after shootings at two Walmart stores last week that killed at least 24 people in El Paso, Texas, and Southaven, Mississippi. In a post to Facebook on Friday evening, the Kansas City Police Department said it was getting "a ton" of messages regarding the

Esta claim 574 parece todavía más clara que la 233: con el Top-10 que recuperó nuestro RAG, el Evidence Verifier tenía muy difícil llegar a `REFUTED`.

Al mirar las 10 evidencias, prácticamente todas hablan de la relación de Walmart con la policía, seguridad, colaboración con fuerzas del orden, amenazas o llamadas policiales en tiendas, pero ninguna habla del supuesto tweet ni de si fue verdadero o falso. 

El retriever encontró contenido semánticamente relacionado con los términos de la claim, pero no evidencia sobre la autenticidad de la publicación, por eso el LLM concluyó antes algo como: No tengo ninguna evidencia que reproduzca,
atribuya o desmienta el supuesto tweet: `NOT_ENOUGH_EVIDENCE`. Así que, igual que con la 233, el problema apunta muy claramente al retrieval.

¿Qué evidencia utilizó AVeriTeC para determinar que la claim era Refuted?

In [71]:
claim_id = 574

print("CLAIM:")
print(train_df.loc[claim_id, "claim"])

print("\nGOLD:")
print(train_df.loc[claim_id, "label"])

print("\nGOLD JUSTIFICATION:")
print(train_df.loc[claim_id, "justification"])

print("\nQUESTIONS AND ANSWERS:")

questions = train_df.loc[claim_id, "questions"]

for i, qa in enumerate(questions, start=1):

    print("\n" + "=" * 80)
    print(f"QUESTION {i}:")
    print(qa["question"])

    print("\nANSWERS:")

    for answer in qa["answers"]:
        print("\nAnswer:")
        print(answer["answer"])

        print("\nSource:")
        print(answer["source_url"])

CLAIM:
Walmart Tweeted "We wont be Rebuilding Walmarts in Cities without police"

GOLD:
Refuted

GOLD JUSTIFICATION:
The claim has been shown to be fake and no results from Walmart show that statement.

QUESTIONS AND ANSWERS:

================================================================================
QUESTION 1:
Did Walmart tweet "We wont be Rebuilding Walmarts in Cities without police"

ANSWERS:

Answer:
No

Source:
https://twitter.com/search?q=%22we%20wont%20be%20rebuilding%20Walmarts%20in%20cities%20without%20police%22%20(from%3AWalmart)&src=typed_query

================================================================================
QUESTION 2:
What tweet does the claim refer to?

ANSWERS:

Answer:
A facebook post from Facebook user M. Cody Clifton

Source:
https://web.archive.org/web/20200909211847/https://www.facebook.com/photo.php?fbid=10157247843507011&set=a.376354472010&type=3&theater

================================================================================
QUESTION 3:
Is the post from Facebook user M. Cody Clifton confirmed real?

ANSWERS:

Answer:
False, the tweet appears to be fabricated

Source:
https://web.archive.org/web/20200909211847/https://www.facebook.com/photo.php?fbid=10157247843507011&set=a.376354472010&type=3&theater

AVeriTeC dispone de evidencia que ataca exactamente el núcleo de la claim, es decir el tweet no aparece en Walmart, la imagen/post procede de otro usuario y el contenido está fabricado, esto justifica `REFUTED`. En cambio, nuestro Top-10 no contenía nada de eso. Recuperó páginas sobre Walmart y policía, seguridad, llamadas policiales, amenazas, agentes fuera de servicio, etc, por eso el verifier dijo: `NOT_ENOUGH_EVIDENCE`, evidence_sufficient = False.

La cadena de error queda clara, Knowledge Store contiene evidencia que demuestra: "tweet fabricated" pero retrieve_evidence NO selecciona esos fragmentos, por lo tanto Evidence Verifier solo recibe contenido relacionado
con Walmart + policía y no puede refutar el tweet y concluir `NOT_ENOUGH_EVIDENCE`. Por lo tanto, en esta fase se concluye que el error se origina antes del `Evidence Verifier`, dentro del proceso de recuperación/preparación de evidencia.
La causa concreta se analiza posteriormente en el diagnóstico final de retrieval.

Además, 574 refuerza algo que ya vimos en 233: nuestro retrieval funciona bien para encontrar contenido temáticamente relacionado, pero no siempre encuentra la evidencia que responde exactamente a la pregunta verificadora.

### 13. Modificaciones en el sistema Global

El análisis de las predicciones incorrectas permitió identificar tres patrones generales
relacionados con la interpretación de las evidencias por parte del `Evidence Verifier`:
el tratamiento insuficiente de cuantificadores y alcance, la consideración de actividades
alternativas como refutaciones directas y el uso de `CONFLICTING_EVIDENCE` ante evidencias
diferentes pero no necesariamente contradictorias.

A partir de estos resultados se introduce una tercera versión del prompt (`V3`) que refuerza
estos criterios sin modificar las clases de salida, la estructura Pydantic ni el pipeline
de retrieval. Los cambios se formulan como reglas generales y no como correcciones
específicas para las claims analizadas.

El objetivo no es optimizar el prompt para acertar los ejemplos de entrenamiento, sino
corregir patrones de razonamiento generalizables detectados durante el análisis de errores.

In [ ]:
def verify_evidence(
    claim,
    evidences,
    client,
    model="gpt-5.6-terra",
    language=None,
):
    """
    Verifica una claim utilizando exclusivamente las evidencias recuperadas por el sistema RAG.

    Parameters
    ----------
    claim : str
        Afirmación que se quiere verificar.

    evidences : list[dict]
        Evidencias recuperadas por retrieve_evidence().

    client
        Cliente de OpenAI.

    model : str
        Modelo LLM utilizado para realizar la verificación.

    Returns
    -------
    VerificationResult
        Resultado estructurado de la verificación factual.
    """

    # Preparamos las evidencias recuperadas en un formato comprensible para el LLM
    evidence_text = format_evidences_for_llm(evidences)

    if language == "es":
        language_instruction = (
            "Write the explanation and reasons in Spanish."
        )
    elif language == "en":
        language_instruction = (
            "Write the explanation and reasons in English."
        )

    instructions = f"""
    You are an Evidence Verifier for a fact-checking system.

    Your task is to verify a claim using ONLY the evidence provided to you.

    Do not use external knowledge.
    Do not assume facts that are not present in the evidence.

    A claim may contain multiple factual components.
    When this happens, consider the different components of the claim before assigning evidence relationships and the 
    final verdict.

    Pay careful attention to quantifiers, scope, and temporal status.
    Evidence supporting "some", "many", "certain", "planned", "pilot", "partially deployed", or similar limited statements
    does not automatically support a claim asserting "all", "always", "fully implemented", or another broader or absolute
    statement.

    For each evidence item, determine its relationship to the claim:

    - SUPPORTS:
    The evidence provides factual information that supports the claim as a whole, or supports an important component without 
    contradicting or leaving unresolved another essential component of the claim.

    - REFUTES:
    The evidence provides factual information that contradicts the claim as a whole, or directly contradicts an essential
    component in a way that makes the overall claim false.

    Do not classify evidence as REFUTES merely because it describes a different, alternative, or apparently opposing  
    activity. REFUTES requires a direct contradiction or a factual relationship that is logically incompatible
    with the claim.

    - NEUTRAL:
    The evidence is related to the claim but does not provide enough information to support or refute it as a whole.

    Use NEUTRAL when the evidence addresses only one component of a multi-part claim and leaves other essential components
    unresolved.

    Then determine the overall verdict:

    - SUPPORTED:
    The available evidence is sufficient to support the claim as a whole.

    - REFUTED:
    The available evidence is sufficient to refute the claim as a whole.

    - NOT_ENOUGH_EVIDENCE:
    The available evidence does not contain enough information to reach a justified conclusion about the claim.

    - CONFLICTING_EVIDENCE:
    The available evidence supports some important factual aspects of the claim while refuting, contradicting, or 
    substantially qualifying other important aspects, so that labeling the whole claim simply SUPPORTED or REFUTED would
    lose relevant information.

    Use this verdict also for cherry-picking cases, where the claim relies on factually supported information but 
    selectively combines, omits, or frames evidence in a way that produces a misleading overall conclusion.

    Do not use CONFLICTING_EVIDENCE merely because different evidence items contain different statistics, perspectives, 
    wording, or levels of detail.
    The evidence must contain a meaningful factual incompatibility that affects the truth or interpretation of the claim.

    Do not automatically label a multi-part claim REFUTED simply because one component is contradicted if other important
    components are supported.
    In such cases, consider whether CONFLICTING_EVIDENCE is more appropriate.

    Set evidence_sufficient to true when the provided evidence contains enough factual information to justify the selected 
    verdict, including when the evidence is sufficient to establish that the case is CONFLICTING_EVIDENCE.

    Set evidence_sufficient to false when the appropriate verdict is NOT_ENOUGH_EVIDENCE.

    Assess every evidence item provided.

    Base the final verdict on the content of the evidence, not on retrieval similarity scores.

    {language_instruction}
    """
    response = client.responses.parse(
        model=model,
        instructions=instructions,
        input=f"""
    CLAIM:
    {claim}

    EVIDENCE:
    {evidence_text}
    """,
            text_format=VerificationResult,
        )

    return response.output_parsed

Vamos a probar estas claims. Las claims 929,777 y 845 para ver si corrige los tres patrones que motivaron el cambio, y 275
770, 349 y 611 porque queremos comprobar que prompt V3 NO rompe casos que prompt V2 ya resolvía correctamente

In [72]:
regression_claim_ids = [
    929,  # Error V2: CONFLICTING -> SUPPORTED
    777,  # Error V2: NEI -> REFUTED
    845,  # Error V2: SUPPORTED -> CONFLICTING

    275,  # CONFLICTING correcta previamente
    770,  # NEI correcta previamente
    349,  # REFUTED correcta previamente
    611,  # SUPPORTED correcta previamente
]

In [73]:
regression_sample = train_df.loc[
    regression_claim_ids
].copy()

El objetivo de este regression check no es obtener una nueva estimación de rendimiento,
sino comprobar si las modificaciones del prompt corrigen los patrones detectados sin
degradar ejemplos que la versión anterior clasificaba correctamente.

In [79]:
regression_results_df = evaluate_averitec_sample(
    evaluation_sample=regression_sample,
    knowledge_zip=knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
    output_path=PROCESSED_DIR / "regression_v3_results.csv",
)

Resultados anteriores encontrados: 5 claims.

Claim 929 ya evaluada. Se omite.

Claim 777 ya evaluada. Se omite.

Claim 845 ya evaluada. Se omite.

Claim 275 ya evaluada. Se omite.

Claim 770 ya evaluada. Se omite.

Evaluando claim 349...
Gold: REFUTED
Corpus grande detectado: 43075 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 589
Documentos únicos: 589
Documentos finales: 100
Chunks iniciales: 43075
Chunks finales: 7702

Batches: 100%|██████████| 121/121 [21:02<00:00, 10.44s/it]

Predicted: REFUTED
Correct: True
Resultados guardados: 6

Evaluando claim 611...
Gold: SUPPORTED
Corpus grande detectado: 81000 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 733
Documentos únicos: 733
Documentos finales: 100
Chunks iniciales: 81000
Chunks finales: 3063

Batches: 100%|██████████| 48/48 [06:21<00:00,  7.95s/it]

Predicted: SUPPORTED
Correct: True
Resultados guardados: 7

In [80]:
regression_results_df[
    [
        "claim_id",
        "gold",
        "predicted",
        "correct",
        "evidence_sufficient",
    ]
]

,claim_id,gold,predicted,correct,evidence_sufficient
0,929,CONFLICTING_EVIDENCE,CONFLICTING_EVIDENCE,True,True
1,777,NOT_ENOUGH_EVIDENCE,REFUTED,False,True
2,845,SUPPORTED,NOT_ENOUGH_EVIDENCE,False,False
3,275,CONFLICTING_EVIDENCE,SUPPORTED,False,True
4,770,NOT_ENOUGH_EVIDENCE,NOT_ENOUGH_EVIDENCE,True,False
5,349,REFUTED,REFUTED,True,True
6,611,SUPPORTED,SUPPORTED,True,True

In [81]:
regression_results_df["correct"].value_counts()

correct
True     4
False    3
Name: count, dtype: int64

Vamos a leer las explicaciones de las 3 claims que todavía siguen mal:

Con esto podemos ver si V3 necesita algun ajuste o si alguna de las nuevas reglas está creando más problemas de los que resuelve.

In [82]:
for claim_id in [777, 845, 275]:

    row = regression_results_df[
        regression_results_df["claim_id"] == claim_id
    ].iloc[0]

    print("\n" + "=" * 80)
    print("CLAIM ID:", claim_id)

    print("\nCLAIM:")
    print(row["claim"])

    print("\nGOLD:")
    print(row["gold"])

    print("\nPREDICTED:")
    print(row["predicted"])

    print("\nEVIDENCE SUFFICIENT:")
    print(row["evidence_sufficient"])

    print("\nEXPLANATION:")
    print(row["explanation"])

================================================================================
CLAIM ID: 777

CLAIM:
Billionaire philanthropist and Microsoft founder Bill Gates worked  specifically to end livestock production.

GOLD:
NOT_ENOUGH_EVIDENCE

PREDICTED:
REFUTED

EVIDENCE SUFFICIENT:
True

EXPLANATION:
The evidence consistently shows Gates and the Gates Foundation funding, promoting, or investigating measures to improve livestock breeding, health, productivity, and veterinary access, especially for poor farmers. These activities are directly incompatible with the claim that he worked specifically to end livestock production.

================================================================================
CLAIM ID: 845

CLAIM:
Being long term unemployed for a year or over nearly halves your chances of ever getting back into employment.

GOLD:
SUPPORTED

PREDICTED:
NOT_ENOUGH_EVIDENCE

EVIDENCE SUFFICIENT:
False

EXPLANATION:
The evidence consistently indicates that prolonged unemployment is associated with worse hiring or interview prospects. However, it does not provide a like-for-like comparison showing that unemployment lasting a year or more nearly halves the probability of ever returning to employment. Several sources instead measure monthly hiring rates, interview callbacks, or steady full-time employment at particular times. Therefore the claim's specific magnitude, one-year threshold, and 'ever getting back into employment' outcome are not sufficiently established.

================================================================================
CLAIM ID: 275

CLAIM:
A study finds a diet heavy with kimchi—spiced fermented cabbage and other vegetables—helps lower South Korea's COVID-19 fatalities.

GOLD:
CONFLICTING_EVIDENCE

PREDICTED:
SUPPORTED

EVIDENCE SUFFICIENT:
True

EXPLANATION:
The evidence consistently documents a French/European study or early analysis that associated high consumption of fermented cabbage foods, including kimchi, with lower reported COVID-19 fatality rates in South Korea and other countries. The claim is supported as a report of what the study found. Several items characterize the conclusion as preliminary, correlational, or a proposed mechanism rather than established individual-level causation; however, the claim itself only says that a study finds such a relationship.

#### Refinamiento del prompt tras el regression check

El regression check mostró que la versión V3 corregía algunos errores de interpretación,
pero también introducía nuevos problemas. En particular, el verifier seguía considerando
como refutación algunas actividades alternativas que no constituían una contradicción
directa, exigía en algunos casos una correspondencia demasiado literal entre claim y
evidencia, y podía dejar de detectar conflictos cuando una limitación modificaba de forma
significativa la interpretación de la afirmación.

Por este motivo se realiza un ajuste menor del prompt (`V3.1`). La nueva versión refuerza
que una refutación debe basarse en una contradicción factual explícita, que permite considerar
evidencia semánticamente equivalente aunque no reproduzca literalmente la claim y aclara
que `CONFLICTING_EVIDENCE` puede utilizarse cuando una evidencia introduce una limitación
o matización que altera de forma material el significado de la afirmación.

No se modifican las clases de salida, la estructura Pydantic ni el componente de retrieval.

In [ ]:
def verify_evidence(
    claim,
    evidences,
    client,
    model="gpt-5.6-terra",
    language=None,
):
    """
    Verifica una claim utilizando exclusivamente las evidencias recuperadas por el sistema RAG.

    Parameters
    ----------
    claim : str
        Afirmación que se quiere verificar.

    evidences : list[dict]
        Evidencias recuperadas por retrieve_evidence().

    client
        Cliente de OpenAI.

    model : str
        Modelo LLM utilizado para realizar la verificación.

    Returns
    -------
    VerificationResult
        Resultado estructurado de la verificación factual.
    """

    # Preparamos las evidencias recuperadas en un formato comprensible para el LLM
    evidence_text = format_evidences_for_llm(evidences)

    if language == "es":
        language_instruction = (
            "Write the explanation and reasons in Spanish."
        )
    elif language == "en":
        language_instruction = (
            "Write the explanation and reasons in English."
        )
  
    instructions = f"""
    You are an Evidence Verifier for a fact-checking system.

    Your task is to verify a claim using ONLY the evidence provided to you.

    Do not use external knowledge.
    Do not assume facts that are not present in the evidence.

    A claim may contain multiple factual components.
    When this happens, consider the different components of the claim before assigning evidence relationships and the 
    final verdict.

    Pay careful attention to quantifiers, scope, and temporal status.
    Evidence supporting "some", "many", "certain", "planned", "pilot", "partially deployed", or similar limited statements
    does not automatically support a claim asserting "all", "always", "fully implemented", or another broader or absolute 
    statement.

    For each evidence item, determine its relationship to the claim:

    - SUPPORTS:
    The evidence provides factual information that supports the claim as a whole, or supports an important component without
    contradicting or leaving unresolved another essential component of the claim.

    Evidence does not need to reproduce the exact wording of the claim.
    It may SUPPORT the claim when it expresses the same relevant factual meaning using different wording, measurements, 
    time windows, or formulations, provided that those differences do not materially change the factual conclusion.

    - REFUTES:
    The evidence provides factual information that directly contradicts the claim as a whole, or directly contradicts an
    essential component in a way that makes the overall claim false.

    Do not classify evidence as REFUTES merely because it describes a different, alternative, opposite-looking, or 
    competing activity.

    REFUTES requires an explicit factual contradiction with the claim or with an essential factual component of it. 
    Do not infer that a claim is false only because the evidence describes behavior that appears inconsistent with
    it unless the evidence itself establishes the contradiction.

    - NEUTRAL:
    The evidence is related to the claim but does not provide enough information to support or refute it as a whole.

    Use NEUTRAL when the evidence addresses only one component of a multi-part claim and leaves other essential components
    unresolved.

    Then determine the overall verdict:

    - SUPPORTED:
    The available evidence is sufficient to support the claim as a whole.

    Do not require an exact lexical or numerical match when the evidence conveys substantially the same factual conclusion
    and the differences do not materially alter the meaning of the claim.

    - REFUTED:
    The available evidence is sufficient to directly contradict the claim as a whole or an essential factual component 
    that makes the overall claim false.

    - NOT_ENOUGH_EVIDENCE:
    The available evidence does not contain enough information to reach a justified conclusion about the claim.

    - CONFLICTING_EVIDENCE:
    The available evidence supports some important factual aspects of the claim while refuting, contradicting, or 
    substantially qualifying other important aspects, so that labeling the whole claim simply SUPPORTED or REFUTED would
    lose relevant information.

    Use this verdict also for cherry-picking cases, where the claim relies on factually supported information but 
    selectively combines, omits, or frames evidence in a way that produces a misleading overall conclusion.

    Do not use CONFLICTING_EVIDENCE merely because different evidence items contain different statistics, perspectives,
    wording, or levels of detail.

    However, a limitation, qualification, difference in scope, or contextual condition should be considered relevant when
    it materially changes the interpretation, strength, or overall meaning of the claim. In such cases, 
    CONFLICTING_EVIDENCE may be more appropriate than SUPPORTED


    Do not automatically label a multi-part claim REFUTED simply because one component is contradicted if other important 
    components are supported. In such cases, consider whether CONFLICTING_EVIDENCE is more appropriate.

    Set evidence_sufficient to true when the provided evidence contains enough factual information to justify the selected
    verdict, including when the evidence is sufficient to establish that the case is CONFLICTING_EVIDENCE.

    Set evidence_sufficient to false when the appropriate verdict is NOT_ENOUGH_EVIDENCE.

    Assess every evidence item provided.

    Base the final verdict on the content of the evidence, not on retrieval similarity scores.

    {language_instruction}
    """
    response = client.responses.parse(
        model=model,
        instructions=instructions,
        input=f"""
    CLAIM:
    {claim}

    EVIDENCE:
    {evidence_text}
    """,
            text_format=VerificationResult,
        )

    return response.output_parsed

In [84]:
regression_results_df = evaluate_averitec_sample(
    evaluation_sample=regression_sample,
    knowledge_zip=knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
    output_path=PROCESSED_DIR / "regression_v3_1_results.csv",
)

Evaluando claim 929...
Gold: CONFLICTING_EVIDENCE
Corpus grande detectado: 46749 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 514
Documentos únicos: 513
Documentos finales: 100
Chunks iniciales: 46749
Chunks finales: 5563

Batches: 100%|██████████| 87/87 [17:45<00:00, 12.25s/it]

Predicted: CONFLICTING_EVIDENCE
Correct: True
Resultados guardados: 1

Evaluando claim 777...
Gold: NOT_ENOUGH_EVIDENCE
Corpus manejable: 36072 chunks.
No es necesario aplicar preselección TF-IDF.
Documentos originales: 629
Documentos únicos: 629
Documentos finales: 629
Chunks iniciales: 36072
Chunks finales: 36072

Batches: 100%|██████████| 564/564 [1:51:39<00:00, 11.88s/it]

Predicted: REFUTED
Correct: False
Resultados guardados: 2

Evaluando claim 845...
Gold: SUPPORTED
Corpus manejable: 38173 chunks.
No es necesario aplicar preselección TF-IDF.
Documentos originales: 623
Documentos únicos: 623
Documentos finales: 623
Chunks iniciales: 38173
Chunks finales: 38173

Batches: 100%|██████████| 597/597 [1:42:24<00:00, 10.29s/it]

Predicted: NOT_ENOUGH_EVIDENCE
Correct: False
Resultados guardados: 3

Evaluando claim 275...
Gold: CONFLICTING_EVIDENCE
Corpus grande detectado: 120682 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 1112
Documentos únicos: 1110
Documentos finales: 100
Chunks iniciales: 120682
Chunks finales: 1416

Batches: 100%|██████████| 23/23 [03:28<00:00,  9.08s/it]

Predicted: SUPPORTED
Correct: False
Resultados guardados: 4

Evaluando claim 770...
Gold: NOT_ENOUGH_EVIDENCE
Corpus grande detectado: 81689 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 1501
Documentos únicos: 1500
Documentos finales: 100
Chunks iniciales: 81689
Chunks finales: 4012

Batches: 100%|██████████| 63/63 [11:11<00:00, 10.66s/it]

Predicted: NOT_ENOUGH_EVIDENCE
Correct: True
Resultados guardados: 5

Evaluando claim 349...
Gold: REFUTED
Corpus grande detectado: 43075 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 589
Documentos únicos: 589
Documentos finales: 100
Chunks iniciales: 43075
Chunks finales: 7702

Batches: 100%|██████████| 121/121 [16:19<00:00,  8.10s/it]

Predicted: REFUTED
Correct: True
Resultados guardados: 6

Evaluando claim 611...
Gold: SUPPORTED
Corpus grande detectado: 81000 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 733
Documentos únicos: 733
Documentos finales: 100
Chunks iniciales: 81000
Chunks finales: 3063

Batches: 100%|██████████| 48/48 [07:02<00:00,  8.79s/it]

Predicted: SUPPORTED
Correct: True
Resultados guardados: 7

In [85]:
regression_results_df[
    [
        "claim_id",
        "gold",
        "predicted",
        "correct",
        "evidence_sufficient",
    ]
]

,claim_id,gold,predicted,correct,evidence_sufficient
0,929,CONFLICTING_EVIDENCE,CONFLICTING_EVIDENCE,True,True
1,777,NOT_ENOUGH_EVIDENCE,REFUTED,False,True
2,845,SUPPORTED,NOT_ENOUGH_EVIDENCE,False,False
3,275,CONFLICTING_EVIDENCE,SUPPORTED,False,True
4,770,NOT_ENOUGH_EVIDENCE,NOT_ENOUGH_EVIDENCE,True,False
5,349,REFUTED,REFUTED,True,True
6,611,SUPPORTED,SUPPORTED,True,True

#### Selección de la versión final del Evidence Verifier

El regression check de la versión V3.1 no mostró mejoras adicionales respecto a V3.
Las siete claims utilizadas obtuvieron exactamente las mismas predicciones en ambas
versiones.

Aunque V3 y V3.1 corrigieron la clasificación de la claim 929, no corrigieron los errores
de las claims 777 y 845 y, además, introdujeron una regresión en la claim 275, que había sido
clasificada correctamente por V2.

Por tanto, las modificaciones posteriores a V2 no muestran una mejora global y consistente
del comportamiento del verifier. Para evitar continuar ajustando el prompt sobre un número
reducido de ejemplos del conjunto de entrenamiento, se decide detener el proceso de
optimización y conservar V2 como versión final del `Evidence Verifier`.

Los errores restantes se mantienen como limitaciones observadas del sistema y serán
considerados en el análisis de resultados, sin realizar nuevos ajustes antes de la evaluación
sobre el conjunto `dev`.

#### Configuración final del Evidence Verifier

Tras comparar V2, V3 y V3.1 mediante el regression check, se conserva V2 como versión
final del prompt. A partir de este punto, esta configuración se considera congelada y será
la utilizada durante la evaluación sobre el conjunto `dev`.

In [ ]:
def verify_evidence(
    claim,
    evidences,
    client,
    model="gpt-5.6-terra",
    language=None,
):
    """
    Verifica una claim utilizando exclusivamente las evidencias recuperadas por el sistema RAG.

    Parameters
    ----------
    claim : str
        Afirmación que se quiere verificar.

    evidences : list[dict]
        Evidencias recuperadas por retrieve_evidence().

    client
        Cliente de OpenAI.

    model : str
        Modelo LLM utilizado para realizar la verificación.

    Returns
    -------
    VerificationResult
        Resultado estructurado de la verificación factual.
    """

    # Preparamos las evidencias recuperadas en un formato comprensible para el LLM
    evidence_text = format_evidences_for_llm(evidences)

    if language == "es":
        language_instruction = (
            "Write the explanation and reasons in Spanish."
        )
    elif language == "en":
        language_instruction = (
            "Write the explanation and reasons in English."
        )
   
    instructions = f"""
    You are an Evidence Verifier for a fact-checking system.

    Your task is to verify a claim using ONLY the evidence provided to you.

    Do not use external knowledge.
    Do not assume facts that are not present in the evidence.

    A claim may contain multiple factual components.
    When this happens, consider the different components of the claim before assigning evidence relationships and the 
    final verdict.

    For each evidence item, determine its relationship to the claim:

    - SUPPORTS:
    The evidence provides factual information that supports the claim as a whole, or supports an important component without
    contradicting or leaving unresolved another essential component of the claim.

    - REFUTES:
    The evidence provides factual information that contradicts the claim as a whole, or directly contradicts an essential 
    component in a way that makes the overall claim false.

    - NEUTRAL:
    The evidence is related to the claim but does not provide enough information to support or refute it as a whole. 
    Use NEUTRAL when the evidence addresses only one component of a multi-part claim and leaves other essential
    components unresolved.

    Then determine the overall verdict:

    - SUPPORTED:
    The available evidence is sufficient to support the claim as a whole.

    - REFUTED:
    The available evidence is sufficient to refute the claim as a whole.

    - NOT_ENOUGH_EVIDENCE:
    The available evidence does not contain enough information to reach a justified conclusion about the claim.

    - CONFLICTING_EVIDENCE:
    The available evidence supports some important factual aspects of the claim while refuting, contradicting, or 
    substantially qualifying other important aspects, so that labeling the whole claim simply SUPPORTED or REFUTED would
    lose relevant information.

    Use this verdict also for cherry-picking cases, where the claim relies on factually supported information but 
    selectively combines, omits, or frames evidence in a way that produces a misleading overall conclusion.

    Do not automatically label a multi-part claim REFUTED simply because one component is contradicted if other important 
    components are supported.
    In such cases, consider whether CONFLICTING_EVIDENCE is more appropriate.

    Set evidence_sufficient to true when the provided evidence contains enough factual information to justify the selected
    verdict, including when the evidence is sufficient to establish that the case is CONFLICTING_EVIDENCE.

    Set evidence_sufficient to false when the appropriate verdict is
    NOT_ENOUGH_EVIDENCE.

    Assess every evidence item provided.

    Base the final verdict on the content of the evidence, not on retrieval similarity scores.

    {language_instruction}
    """

    response = client.responses.parse(
        model=model,
        instructions=instructions,
        input=f"""
    CLAIM:
    {claim}

    EVIDENCE:
    {evidence_text}
    """,
            text_format=VerificationResult,
        )

    return response.output_parsed

### 14. Diagnóstico final del componente de retrieval

El análisis de errores mostró que las claims 233 y 574 fueron clasificadas como
`NOT_ENOUGH_EVIDENCE` porque las evidencias necesarias para resolverlas no aparecieron
entre los fragmentos finalmente recuperados.

Antes de congelar el sistema se realiza una última inspección del retrieval para determinar
en qué etapa se pierde la evidencia relevante. El objetivo no es optimizar nuevos
hiperparámetros sobre estas claims, sino distinguir si la evidencia de referencia queda
fuera durante la preselección documental o si, estando disponible en el índice vectorial,
no alcanza las primeras posiciones de la búsqueda semántica.

Este análisis se realiza únicamente con fines diagnósticos y no modifica todavía la
configuración del pipeline.

¿Que queremos averiguar exactamente? Para 233 y 574 ya sabemos que Knowledge Store contiene evidencia buena pero el Top-10 final no contiene esa evidencia, pero nos falta saber dónde la perdemos: Knowledge Store completo, TF-IDF prefilter (si se activa), chunks que llegan a FAISS, candidate_k = 50, diversificación y Top-10.

Hay tres posibilidades:

A -  El documento gold ni siquiera sobrevive al TF-IDF: problema de preselección documental

B -  Sobrevive y está en FAISS, pero queda fuera del Top-50: problema de búsqueda semántica/query

C -  Está dentro del Top-50, pero no llega al Top-10: problema de selección/diversificación final

Vamos a empezar por la claim 233

In [87]:
claim_id = 233
claim = train_df.loc[claim_id, "claim"]

#Ya conocemos de antes las URLs
gold_urls_233 = [
    "https://nypost.com/2020/06/08/more-than-700-officers-injured-in-george-floyd-protests-across-us/",
    "https://www.foxnews.com/politics/george-floyd-protests-expensive-civil-disturbance-us-history",
    "https://www.forbes.com/sites/jemimamcevoy/2020/06/08/14-days-of-protests-19-dead/",
]

Reconstruimos el retrieval sin llamar al LLM

In [88]:
knowledge_records = load_knowledge_records(
    knowledge_zip=knowledge_zip,
    claim_id=claim_id,
)

chunks, index, retrieval_info = build_claim_index(
    claim=claim,
    knowledge_records=knowledge_records,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
)

Corpus grande detectado: 150586 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 1115
Documentos únicos: 1112
Documentos finales: 100
Chunks iniciales: 150586
Chunks finales: 8933

Batches: 100%|██████████| 140/140 [34:30<00:00, 14.79s/it]

Vamos a ver si las URL están dentro de los chunks que llegaron a Faiss

In [89]:
for gold_url in gold_urls_233:

    matching_chunks = [
        chunk
        for chunk in chunks
        if chunk["url"] == gold_url
    ]

    print("\n" + "=" * 80)
    print("GOLD URL:")
    print(gold_url)

    print("Chunks in final FAISS index:", len(matching_chunks))

================================================================================
GOLD URL:
https://nypost.com/2020/06/08/more-than-700-officers-injured-in-george-floyd-protests-across-us/
Chunks in final FAISS index: 0

================================================================================
GOLD URL:
https://www.foxnews.com/politics/george-floyd-protests-expensive-civil-disturbance-us-history
Chunks in final FAISS index: 0

================================================================================
GOLD URL:
https://www.forbes.com/sites/jemimamcevoy/2020/06/08/14-days-of-protests-19-dead/
Chunks in final FAISS index: 0

Este resultado significa que FAISS nunca pudo recuperar esas evidencias. Pero todavía hay dos posibilidades:

A -  Las URLs estaban en el Knowledge Store y se perdieron durante la preselección TF-IDF

B -  Las URLs del Knowledge Store no coinciden exactamente con las URLs gold que estamos comparando (archive URL, parámetros, http/https, etc.)

Así que el siguiente paso es comprobar si esas fuentes existen antes del build_claim_index().

In [90]:
for gold_url in gold_urls_233:

    matching_records = [
        record
        for record in knowledge_records
        if record.get("url") == gold_url
    ]

    print("\n" + "=" * 80)
    print("GOLD URL:")
    print(gold_url)

    print("Records in original Knowledge Store:", len(matching_records))

================================================================================
GOLD URL:
https://nypost.com/2020/06/08/more-than-700-officers-injured-in-george-floyd-protests-across-us/
Records in original Knowledge Store: 2

================================================================================
GOLD URL:
https://www.foxnews.com/politics/george-floyd-protests-expensive-civil-disturbance-us-history
Records in original Knowledge Store: 2

================================================================================
GOLD URL:
https://www.forbes.com/sites/jemimamcevoy/2020/06/08/14-days-of-protests-19-dead/
Records in original Knowledge Store: 2

Con los resultados obtenido, tenemos que Knowledge Store sí contiene la evidencia gold pero la preselección documental la elimina y por tanto FAISS no llega a verla. En ese caso el problema de la 233 estaría antes del retrieval vectorial, concretamente en la selección previa de documentos, muy probablemente en el select_relevant_documents() con TF-IDF.

Aquí solo queremos confirmar que la URL existe y que tiene contenido textual utilizable

In [91]:
for gold_url in gold_urls_233:

    matching_records = [
        record
        for record in knowledge_records
        if record.get("url") == gold_url
    ]

    print("\n" + "=" * 80)
    print("GOLD URL:")
    print(gold_url)

    for i, record in enumerate(matching_records, start=1):

        text_parts = record.get("url2text", [])

        print(f"\nRecord {i}")
        print("Source type:", record.get("type"))
        print("Text parts:", len(text_parts))

        if text_parts:
            print("Example:")
            print(text_parts[0][:500])

================================================================================
GOLD URL:
https://nypost.com/2020/06/08/more-than-700-officers-injured-in-george-floyd-protests-across-us/

Record 1
Source type: gold
Text parts: 14
Example:
WASHINGTON — More than 700 law enforcement officers have been injured on the job during nationwide protests over the death of George Floyd — with nearly 300 of those among New York’s Finest, according to the Department of Justice and the NYPD.

Record 2
Source type: answer
Text parts: 14
Example:
WASHINGTON — More than 700 law enforcement officers have been injured on the job during nationwide protests over the death of George Floyd — with nearly 300 of those among New York’s Finest, according to the Department of Justice and the NYPD.

================================================================================
GOLD URL:
https://www.foxnews.com/politics/george-floyd-protests-expensive-civil-disturbance-us-history

Record 1
Source type: gold
Text parts: 51
Example:
The costliest civil disorder in U.S. history: That's what insurance experts and city officials say the riots and demonstrations following the death of George Floyd are shaping up to be.

Record 2
Source type: most_similar
Text parts: 51
Example:
The costliest civil disorder in U.S. history: That's what insurance experts and city officials say the riots and demonstrations following the death of George Floyd are shaping up to be.

================================================================================
GOLD URL:
https://www.forbes.com/sites/jemimamcevoy/2020/06/08/14-days-of-protests-19-dead/

Record 1
Source type: gold
Text parts: 26
Example:
Topline: Though curfews are lifting and protests remain predominantly peaceful, the death toll from two weeks of demonstrations over the death of George Floyd continues to creep upward, with at least 19 people—a majority of whom are black—now dead.

Record 2
Source type: question_duplicate
Text parts: 26
Example:
Topline: Though curfews are lifting and protests remain predominantly peaceful, the death toll from two weeks of demonstrations over the death of George Floyd continues to creep upward, with at least 19 people—a majority of whom are black—now dead.

Comprobamos directamente el TF-IDF

In [92]:
documents_233 = []

for record in knowledge_records:

    document = build_document(record)

    if document["text"].strip():
        documents_233.append(document)


selected_documents_233 = select_relevant_documents(
    claim=claim,
    documents=documents_233,
    top_n=100,
)

In [93]:
selected_urls_233 = {
    document["url"]
    for document in selected_documents_233
}

for gold_url in gold_urls_233:

    print("\n" + "=" * 80)
    print("GOLD URL:")
    print(gold_url)

    print(
        "Selected by TF-IDF:",
        gold_url in selected_urls_233
    )

================================================================================
GOLD URL:
https://nypost.com/2020/06/08/more-than-700-officers-injured-in-george-floyd-protests-across-us/
Selected by TF-IDF: False

================================================================================
GOLD URL:
https://www.foxnews.com/politics/george-floyd-protests-expensive-civil-disturbance-us-history
Selected by TF-IDF: False

================================================================================
GOLD URL:
https://www.forbes.com/sites/jemimamcevoy/2020/06/08/14-days-of-protests-19-dead/
Selected by TF-IDF: False

Con este resultado vemos que aquí el problema no está en FAISS ni en el prompt, sino en la preselección TF-IDF que introdujimos para reducir el volumen de chunks. Vamos a averiguar en qué posiciones quedaron realmente esas tres fuentes dentro del ranking TF-IDF. Eso nos dirá si el problema se arreglaría razonablemente con 150, 200, 300 documentos, o si están muchísimo más abajo y el enfoque necesita otra cosa.

In [ ]:
document_texts = [
    document["text"]
    for document in documents_233
]

vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=30000
)

tfidf_matrix = vectorizer.fit_transform(
    [claim] + document_texts
)

claim_vector = tfidf_matrix[0]
document_vectors = tfidf_matrix[1:]

similarities = cosine_similarity(
    claim_vector,
    document_vectors
)[0]

ranked_indices = similarities.argsort()[::-1]


for gold_url in gold_urls_233:

    print("\n" + "=" * 80)
    print("GOLD URL:")
    print(gold_url)

    matching_indices = [
        i
        for i, document in enumerate(documents_233)
        if document["url"] == gold_url
    ]

    for idx in matching_indices:

        rank = np.where(ranked_indices == idx)[0][0] + 1

        print("TF-IDF rank:", rank)
        print("TF-IDF score:", similarities[idx])

================================================================================
GOLD URL:
https://nypost.com/2020/06/08/more-than-700-officers-injured-in-george-floyd-protests-across-us/
TF-IDF rank: 365
TF-IDF score: 0.04782416188507958
TF-IDF rank: 364
TF-IDF score: 0.04782416188507958

================================================================================
GOLD URL:
https://www.foxnews.com/politics/george-floyd-protests-expensive-civil-disturbance-us-history
TF-IDF rank: 223
TF-IDF score: 0.07034084951328859
TF-IDF rank: 222
TF-IDF score: 0.07034084951328859

================================================================================
GOLD URL:
https://www.forbes.com/sites/jemimamcevoy/2020/06/08/14-days-of-protests-19-dead/
TF-IDF rank: 330
TF-IDF score: 0.05127622588384461
TF-IDF rank: 329
TF-IDF score: 0.05127622588384461

La inspección del ranking TF-IDF muestra que las fuentes gold de la claim 233
aparecen en posiciones relativamente bajas: aproximadamente 222–223 para FoxNews,
329–330 para Forbes y 364–365 para NYPost.

Por tanto, aumentar ligeramente el número de documentos preseleccionados no resolvería
el problema. Para garantizar la inclusión de todas las fuentes sería necesario conservar
más de 360 documentos, reduciendo de forma considerable el beneficio computacional de
la etapa de prefiltrado.

Este resultado sugiere que la limitación no depende únicamente del valor de
`top_n_documents`, sino del uso de la claim completa como única consulta léxica. En
afirmaciones multicomponente, distintas fuentes pueden aportar evidencia relevante para
componentes diferentes de la claim y presentar una similitud léxica limitada con la
afirmación completa.

En consecuencia, una posible mejora futura consistiría en generar subclaims o preguntas
de verificación y realizar la recuperación de evidencia de forma independiente para cada
componente.

Ahora para la claim 574 haremos practicamente lo mismo, pero de forma más directa.

In [95]:
claim_id = 574
claim = train_df.loc[claim_id, "claim"]

gold_urls_574 = [
    "https://twitter.com/search?q=%22we%20wont%20be%20rebuilding%20Walmarts%20in%20cities%20without%20police%22%20(from%3AWalmart)&src=typed_query",
    "https://web.archive.org/web/20200909211847/https://www.facebook.com/photo.php?fbid=10157247843507011&set=a.376354472010&type=3&theater",
]

In [96]:
knowledge_records_574 = load_knowledge_records(
    knowledge_zip=knowledge_zip,
    claim_id=claim_id,
)

In [97]:
for gold_url in gold_urls_574:

    matching_records = [
        record
        for record in knowledge_records_574
        if record.get("url") == gold_url
    ]

    print("\n" + "=" * 80)
    print("GOLD URL:")
    print(gold_url)

    print("Records in original Knowledge Store:", len(matching_records))

================================================================================
GOLD URL:
https://twitter.com/search?q=%22we%20wont%20be%20rebuilding%20Walmarts%20in%20cities%20without%20police%22%20(from%3AWalmart)&src=typed_query
Records in original Knowledge Store: 1

================================================================================
GOLD URL:
https://web.archive.org/web/20200909211847/https://www.facebook.com/photo.php?fbid=10157247843507011&set=a.376354472010&type=3&theater
Records in original Knowledge Store: 1

In [98]:
documents_574 = []

for record in knowledge_records_574:

    document = build_document(record)

    if document["text"].strip():
        documents_574.append(document)

In [99]:
selected_documents_574 = select_relevant_documents(
    claim=claim,
    documents=documents_574,
    top_n=100,
)

In [100]:
selected_urls_574 = {
    document["url"]
    for document in selected_documents_574
}

for gold_url in gold_urls_574:

    print("\n" + "=" * 80)
    print("GOLD URL:")
    print(gold_url)

    print(
        "Selected by TF-IDF:",
        gold_url in selected_urls_574
    )

================================================================================
GOLD URL:
https://twitter.com/search?q=%22we%20wont%20be%20rebuilding%20Walmarts%20in%20cities%20without%20police%22%20(from%3AWalmart)&src=typed_query
Selected by TF-IDF: False

================================================================================
GOLD URL:
https://web.archive.org/web/20200909211847/https://www.facebook.com/photo.php?fbid=10157247843507011&set=a.376354472010&type=3&theater
Selected by TF-IDF: False

In [102]:
document_texts = [
    document["text"]
    for document in documents_574
]

vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=30000
)

tfidf_matrix = vectorizer.fit_transform(
    [claim] + document_texts
)

claim_vector = tfidf_matrix[0]
document_vectors = tfidf_matrix[1:]

similarities = cosine_similarity(
    claim_vector,
    document_vectors
)[0]

ranked_indices = similarities.argsort()[::-1]


for gold_url in gold_urls_574:

    print("\n" + "=" * 80)
    print("GOLD URL:")
    print(gold_url)

    matching_indices = [
        i
        for i, document in enumerate(documents_574)
        if document["url"] == gold_url
    ]

    for idx in matching_indices:

        rank = np.where(ranked_indices == idx)[0][0] + 1

        print("TF-IDF rank:", rank)
        print("TF-IDF score:", similarities[idx])

================================================================================
GOLD URL:
https://twitter.com/search?q=%22we%20wont%20be%20rebuilding%20Walmarts%20in%20cities%20without%20police%22%20(from%3AWalmart)&src=typed_query

================================================================================
GOLD URL:
https://web.archive.org/web/20200909211847/https://www.facebook.com/photo.php?fbid=10157247843507011&set=a.376354472010&type=3&theater

In [104]:
for gold_url in gold_urls_574:

    matching_records = [
        record
        for record in knowledge_records_574
        if record.get("url") == gold_url
    ]

    print("\n" + "=" * 80)
    print("GOLD URL:")
    print(gold_url)

    for i, record in enumerate(matching_records, start=1):

        text_parts = record.get("url2text", [])

        print(f"\nRecord {i}")
        print("Source type:", record.get("type"))
        print("Text parts:", len(text_parts))

        if text_parts:
            print("Example:")
            print(text_parts[0][:500])

================================================================================
GOLD URL:
https://twitter.com/search?q=%22we%20wont%20be%20rebuilding%20Walmarts%20in%20cities%20without%20police%22%20(from%3AWalmart)&src=typed_query

Record 1
Source type: gold
Text parts: 0

================================================================================
GOLD URL:
https://web.archive.org/web/20200909211847/https://www.facebook.com/photo.php?fbid=10157247843507011&set=a.376354472010&type=3&theater

Record 1
Source type: gold
Text parts: 0

#### Diagnóstico de retrieval para la claim 574

La inspección de las fuentes gold muestra que las dos URLs utilizadas por AVeriTeC
están presentes en el Knowledge Store. Sin embargo, ambos registros presentan
`url2text` vacío.

Como el pipeline descarta los documentos sin contenido textual antes de la etapa de
chunking, estas fuentes no llegan a la preselección TF-IDF ni al índice FAISS. Por tanto,
el `Evidence Verifier` nunca recibe la evidencia que permite refutar la claim.

A diferencia de la claim 233, donde la evidencia relevante se pierde durante la
preselección TF-IDF, en la claim 574 la pérdida ocurre en una etapa anterior debido a la
ausencia de texto extraíble en las fuentes gold.

Este caso muestra una limitación adicional del sistema: la calidad del retrieval depende
también de la disponibilidad de contenido textual en las fuentes recuperadas, especialmente
en redes sociales, páginas archivadas o contenidos difíciles de extraer automáticamente.

Con esto ya tenemos dos tipos distintos de fallo de retrieval:

- 233: la evidencia existe y tiene texto, pero TF-IDF la elimina

- 574: la evidencia existe como URL, pero no tiene texto utilizable

Eso es bastante bueno para el análisis porque muestra que no hay un único `problema de retrieval`, sino fallos en etapas distintas.

#### Decisión final sobre el componente de retrieval

El análisis de las claims 233 y 574 muestra que los errores de recuperación no se
originan en un único punto del pipeline.

En la claim 233, las evidencias gold están disponibles y contienen texto, pero son
eliminadas por la preselección TF-IDF antes de llegar al índice vectorial. Además, sus
posiciones en el ranking TF-IDF son suficientemente bajas como para que aumentar
moderadamente `top_n_documents` no garantice su recuperación sin incrementar de forma
importante el coste computacional.

En la claim 574, las fuentes gold están presentes en el Knowledge Store, pero no contienen
texto extraíble en `url2text`, por lo que no pueden ser incorporadas al pipeline de
retrieval textual.

Estos resultados indican limitaciones estructurales relacionadas tanto con la
preselección basada en la claim completa como con la disponibilidad de contenido textual
de las fuentes. Por este motivo, no se realizan nuevos ajustes de retrieval antes de la
evaluación sobre `dev`.

La configuración actual se mantiene congelada y las mejoras basadas en generación de
subclaims, preguntas de verificación, recuperación multi-query o mecanismos alternativos
de extracción de contenido se consideran extensiones futuras del sistema.

### 15. Congelación de la configuración antes de la evaluación en dev
#### (Cierre de la fase de desarrollo)

Tras las pruebas realizadas sobre el conjunto de entrenamiento, se fija la configuración
del sistema que será utilizada durante la evaluación posterior.

La configuración congelada incluye:

- preselección TF-IDF de documentos cuando el número de chunks supera el límite definido;
- `top_n_documents=100`;
- embeddings `BAAI/bge-small-en-v1.5`;
- índice FAISS con similitud basada en producto interno sobre embeddings normalizados;
- recuperación inicial de `candidate_k=50`;
- selección final de 10 evidencias con control de diversidad por documento;
- versión V2 del prompt del `Evidence Verifier`;
- las cuatro clases normalizadas de AVeriTeC.

A partir de este punto no se realizarán nuevos ajustes utilizando las etiquetas o errores
del conjunto `dev`. Este conjunto se utilizará exclusivamente como evaluación held-out
del sistema congelado.

### 16. Evaluación final sobre el conjunto dev

Una vez finalizada la fase de desarrollo y congelada la configuración del sistema,
se utiliza el conjunto `dev` de AVeriTeC como conjunto held-out para evaluar su
capacidad de generalización sobre afirmaciones no utilizadas durante el proceso de
ajuste.

`Conjunto held-out se refiere al conjunto dejado aparte.`

`holdout: Se refiere a la práctica de dividir un conjunto de datos en dos subconjuntos distintos: uno para entrenar un modelo y otro para evaluar su rendimiento`

Durante esta fase no se realizarán modificaciones en el prompt, el componente de
retrieval ni los hiperparámetros del pipeline a partir de los resultados obtenidos.

La evaluación comparará las predicciones generadas por el sistema con las etiquetas
gold de AVeriTeC y se calcularán métricas globales y por clase.

In [37]:
DEV_KNOWLEDGE_FILE = (
    "data_store/knowledge_store/"
    "dev_knowledge_store.zip"
)

knowledge_zip = hf_hub_download(
    repo_id="chenxwh/AVeriTeC",
    filename=DEV_KNOWLEDGE_FILE,
    local_dir=KNOWLEDGE_DIR
)

print(knowledge_zip)

C:\Users\natal\OneDrive\Documentos\UCM - Big data, ML and IA\MODULOS\TFM\TFM_Natalia_De_Oliveira_AgenteFakeNews\Data\averitec\raw\knowledge_store\data_store\knowledge_store\dev_knowledge_store.zip

In [38]:
dev_knowledge_zip = (
    KNOWLEDGE_DIR
    / "data_store"
    / "knowledge_store"
    / "dev_knowledge_store.zip"
)

print(dev_knowledge_zip)
print("Exists:", dev_knowledge_zip.exists())

..\Data\averitec\raw\knowledge_store\data_store\knowledge_store\dev_knowledge_store.zip
Exists: True

Viendo la distribución de las clases en Dev:

In [39]:
dev_df["label"].value_counts()

label
Refuted                               305
Supported                             122
Conflicting Evidence/Cherrypicking     38
Not Enough Evidence                    35
Name: count, dtype: int64

In [109]:
dev_df["label"].value_counts(normalize=True)

label
Refuted                               0.610
Supported                             0.244
Conflicting Evidence/Cherrypicking    0.076
Not Enough Evidence                   0.070
Name: proportion, dtype: float64

Esto nos confirma que dev está bastante desbalanceado, por eso no usaremos una muestra aleatoria simple de 40 claims, porque probablemente saldrían muchas Refuted y muy pocas de las clases minoritarias. Para nuestro objetivo de evaluar el comportamiento por clase, mantendremos la idea de una muestra estratificada y balanceada:

10 Refuted <br>
10 Supported <br>
10 Conflicting Evidence/Cherrypicking <br>
10 Not Enough Evidence

#### Selección de la muestra de evaluación

El conjunto `dev` contiene 500 afirmaciones y presenta una distribución de clases
desbalanceada, con una mayoría de ejemplos `Refuted` (61 %) y una representación
considerablemente menor de `Conflicting Evidence/Cherrypicking` y
`Not Enough Evidence`.

Dado el coste computacional del pipeline completo, se utiliza una muestra estratificada
balanceada de 40 claims, seleccionando 10 ejemplos de cada una de las cuatro clases.

Esta estrategia permite evaluar de forma comparable el comportamiento del sistema en
todas las categorías y evita que las métricas estén dominadas por la clase mayoritaria.

In [40]:
dev_evaluation_sample = (
    dev_df
    .groupby("label", group_keys=False)
    .sample(n=10, random_state=42)
)

dev_evaluation_sample["label"].value_counts()

label
Conflicting Evidence/Cherrypicking    10
Not Enough Evidence                   10
Refuted                               10
Supported                             10
Name: count, dtype: int64

Vamos a ejecutar las 40 claims con la configuración ya congelada:

In [41]:
DEV_RESULTS_PATH = PROCESSED_DIR / "dev_evaluation_results.csv"

In [44]:
dev_results_df = evaluate_averitec_sample(
    evaluation_sample=dev_evaluation_sample,
    knowledge_zip=dev_knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
    output_path=DEV_RESULTS_PATH,
)

Resultados anteriores encontrados: 40 claims.

Claim 457 ya evaluada. Se omite.

Claim 482 ya evaluada. Se omite.

Claim 43 ya evaluada. Se omite.

Claim 115 ya evaluada. Se omite.

Claim 427 ya evaluada. Se omite.

Claim 370 ya evaluada. Se omite.

Claim 50 ya evaluada. Se omite.

Claim 389 ya evaluada. Se omite.

Claim 360 ya evaluada. Se omite.

Claim 148 ya evaluada. Se omite.

Claim 209 ya evaluada. Se omite.

Claim 210 ya evaluada. Se omite.

Claim 68 ya evaluada. Se omite.

Claim 153 ya evaluada. Se omite.

Claim 394 ya evaluada. Se omite.

Claim 233 ya evaluada. Se omite.

Claim 183 ya evaluada. Se omite.

Claim 76 ya evaluada. Se omite.

Claim 223 ya evaluada. Se omite.

Claim 192 ya evaluada. Se omite.

Claim 333 ya evaluada. Se omite.

Claim 52 ya evaluada. Se omite.

Claim 23 ya evaluada. Se omite.

Claim 80 ya evaluada. Se omite.

Claim 91 ya evaluada. Se omite.

Claim 316 ya evaluada. Se omite.

Claim 120 ya evaluada. Se omite.

Claim 193 ya evaluada. Se omite.

Claim 268 ya evaluada. Se omite.

Claim 234 ya evaluada. Se omite.

Claim 222 ya evaluada. Se omite.

Claim 327 ya evaluada. Se omite.

Claim 57 ya evaluada. Se omite.

Claim 93 ya evaluada. Se omite.

Claim 305 ya evaluada. Se omite.

Claim 347 ya evaluada. Se omite.

Claim 194 ya evaluada. Se omite.

Claim 199 ya evaluada. Se omite.

Claim 262 ya evaluada. Se omite.

Claim 255 ya evaluada. Se omite.

In [45]:
y_true = dev_results_df["gold"]
y_pred = dev_results_df["predicted"]

accuracy = accuracy_score(y_true, y_pred)
macro_f1 = f1_score(y_true, y_pred, average="macro")

print("Accuracy:", accuracy)
print("Macro-F1:", macro_f1)

print("\nClassification report:")
print(classification_report(y_true, y_pred))

Accuracy: 0.4
Macro-F1: 0.3630555555555556

Classification report:
                      precision    recall  f1-score   support

CONFLICTING_EVIDENCE       0.00      0.00      0.00        10
 NOT_ENOUGH_EVIDENCE       0.36      0.50      0.42        10
             REFUTED       0.40      0.60      0.48        10
           SUPPORTED       0.62      0.50      0.56        10

            accuracy                           0.40        40
           macro avg       0.35      0.40      0.36        40
        weighted avg       0.35      0.40      0.36        40

In [46]:
labels = [
    "SUPPORTED",
    "REFUTED",
    "NOT_ENOUGH_EVIDENCE",
    "CONFLICTING_EVIDENCE",
]

cm = confusion_matrix(
    y_true,
    y_pred,
    labels=labels,
)

cm

array([[5, 2, 2, 1],
       [0, 6, 3, 1],
       [2, 2, 5, 1],
       [1, 5, 4, 0]])

#### Resultados sobre el conjunto dev

La evaluación sobre una muestra estratificada de 40 claims obtuvo una
accuracy de 0.40 y un macro-F1 de 0.36.

El comportamiento varía de forma considerable entre clases. El sistema obtiene mejores
resultados en `SUPPORTED` y `REFUTED`, mientras que presenta dificultades especialmente
relevantes en `CONFLICTING_EVIDENCE`, clase para la que no se obtiene ninguna predicción
correcta en la muestra evaluada.

La matriz de confusión muestra que las claims gold `CONFLICTING_EVIDENCE` tienden a ser
clasificadas principalmente como `REFUTED` o `NOT_ENOUGH_EVIDENCE`, lo que indica una
limitación del sistema para distinguir entre una contradicción directa y situaciones en
las que la evidencia apoya y refuta distintos aspectos de una misma claim o introduce
matices sustanciales.

Dado que `dev` se utiliza como conjunto held-out, estos resultados no se emplearán para
realizar nuevos ajustes del prompt o del componente de retrieval. Se utilizarán como
medida final de generalización del componente factual y como base para el análisis de
limitaciones y posibles mejoras futuras.

### 16.1 Análisis descriptivos de los errores de `dev`

In [47]:
dev_errors_df = dev_results_df[
    dev_results_df["correct"] == False
].copy()

dev_errors_df[
    [
        "claim_id",
        "claim",
        "gold",
        "predicted",
        "evidence_sufficient",
    ]
]

,claim_id,claim,gold,predicted,evidence_sufficient
0,457,The Radio Act in Canada makes it a crime to li...,CONFLICTING_EVIDENCE,REFUTED,True
1,482,"Donald trump said: ""Joe Biden recently raised ...",CONFLICTING_EVIDENCE,NOT_ENOUGH_EVIDENCE,False
2,43,Donald Trump said that $15 an hour is too much...,CONFLICTING_EVIDENCE,REFUTED,True
3,115,More people who wear masks become sick with CO...,CONFLICTING_EVIDENCE,REFUTED,True
4,427,U.S. citizens should show up at polling places...,CONFLICTING_EVIDENCE,NOT_ENOUGH_EVIDENCE,False
5,370,Government of India has imposed taxes on all s...,CONFLICTING_EVIDENCE,REFUTED,True
6,50,Twitter now putting warnings on tweets that ar...,CONFLICTING_EVIDENCE,NOT_ENOUGH_EVIDENCE,False
7,389,The cardinal and unforgivable sin of a French ...,CONFLICTING_EVIDENCE,SUPPORTED,True
8,360,These unlicensed vaccines will be administered...,CONFLICTING_EVIDENCE,NOT_ENOUGH_EVIDENCE,False
9,148,U.S. President Donald Trump has suspended all ...,CONFLICTING_EVIDENCE,REFUTED,True
12,68,Joe Biden said 'If Your 8-Year-Old Child Says ...,NOT_ENOUGH_EVIDENCE,REFUTED,True
13,153,President Trump and I have a plan to improve h...,NOT_ENOUGH_EVIDENCE,CONFLICTING_EVIDENCE,True
14,394,"Under Trump's watch, auto assembly plants have...",NOT_ENOUGH_EVIDENCE,REFUTED,True
18,223,Nigeria's petrol prices are lower than Saudi A...,NOT_ENOUGH_EVIDENCE,SUPPORTED,True
19,192,It makes no sense for oil to be cheaper in Nig...,NOT_ENOUGH_EVIDENCE,SUPPORTED,True
20,333,Development Control Department of the Abuja Me...,REFUTED,NOT_ENOUGH_EVIDENCE,False
21,52,President Ferdinand Marcos and Dr. Jose Rizal ...,REFUTED,NOT_ENOUGH_EVIDENCE,False
22,23,Joe Biden wants to ban fracking,REFUTED,CONFLICTING_EVIDENCE,True
27,193,Two E-6B Mercury planes were deployed because ...,REFUTED,NOT_ENOUGH_EVIDENCE,False
31,327,Carlos Gimenez approved a 67% pay raise for hi...,SUPPORTED,CONFLICTING_EVIDENCE,True
32,57,While serving as Town Supervisor on Grand Isla...,SUPPORTED,REFUTED,True
33,93,US Judge Amy Coney Barrett graduated at the to...,SUPPORTED,NOT_ENOUGH_EVIDENCE,False
34,305,"Photo Showing the remains of Vladimir Komarov,...",SUPPORTED,NOT_ENOUGH_EVIDENCE,False
37,199,For a cumulative 29 of Nigeria's 60 years of e...,SUPPORTED,REFUTED,True

In [49]:
len(dev_errors_df)

24

In [48]:
(
    dev_errors_df
    .groupby(["gold", "predicted"])
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
)

                    gold             predicted  count
1   CONFLICTING_EVIDENCE               REFUTED      5
0   CONFLICTING_EVIDENCE   NOT_ENOUGH_EVIDENCE      4
7                REFUTED   NOT_ENOUGH_EVIDENCE      3
10             SUPPORTED               REFUTED      2
4    NOT_ENOUGH_EVIDENCE               REFUTED      2
9              SUPPORTED   NOT_ENOUGH_EVIDENCE      2
5    NOT_ENOUGH_EVIDENCE             SUPPORTED      2
2   CONFLICTING_EVIDENCE             SUPPORTED      1
3    NOT_ENOUGH_EVIDENCE  CONFLICTING_EVIDENCE      1
6                REFUTED  CONFLICTING_EVIDENCE      1
8              SUPPORTED  CONFLICTING_EVIDENCE      1

Tras la evaluación se identificaron 24 predicciones incorrectas de las
40 claims evaluadas. Los errores no se distribuyen uniformemente entre las clases.

La principal dificultad se observa en `CONFLICTING_EVIDENCE`: ninguna de las diez
claims de esta categoría fue clasificada correctamente. Cinco fueron clasificadas
como `REFUTED`, cuatro como `NOT_ENOUGH_EVIDENCE` y una como `SUPPORTED`.

También se observan errores `REFUTED: NOT_ENOUGH_EVIDENCE`, así como confusiones
entre `SUPPORTED`, `REFUTED` y `NOT_ENOUGH_EVIDENCE`.

Para estudiar las posibles causas sin realizar nuevos ajustes sobre el conjunto, se selecciona un pequeño conjunto de errores representativos. El análisis será exclusivamente descriptivo y no se utilizará para modificar la configuración congelada del sistema. Vamos a seleccionar claims en las que vamos a poder revisar el retrieval y el evidence verifier.

In [50]:
representative_dev_ids = [
    457,  # CONFLICTING:  REFUTED, evidence_sufficient=True
    482,  # CONFLICTING:  NEI, evidence_sufficient=False
    333,  # REFUTED: NEI, evidence_sufficient=False
    68,   # NEI: REFUTED, evidence_sufficient=True
    57,   # SUPPORTED: REFUTED, evidence_sufficient=True
    93,   # SUPPORTED: NEI, evidence_sufficient=False
]

representative_dev_errors = dev_errors_df[
    dev_errors_df["claim_id"].isin(representative_dev_ids)
].copy()

representative_dev_errors[
    [
        "claim_id",
        "claim",
        "gold",
        "predicted",
        "evidence_sufficient",
        "explanation",
    ]
]

,claim_id,claim,gold,predicted,evidence_sufficient,explanation
0,457,The Radio Act in Canada makes it a crime to li...,CONFLICTING_EVIDENCE,REFUTED,True,The evidence indicates that false or misleadin...
1,482,"Donald trump said: ""Joe Biden recently raised ...",CONFLICTING_EVIDENCE,NOT_ENOUGH_EVIDENCE,False,The evidence supports the limited fact that Bi...
12,68,Joe Biden said 'If Your 8-Year-Old Child Says ...,NOT_ENOUGH_EVIDENCE,REFUTED,True,The evidence documents Biden's town-hall remar...
20,333,Development Control Department of the Abuja Me...,REFUTED,NOT_ENOUGH_EVIDENCE,False,The evidence establishes that AMMC/FCTA develo...
32,57,While serving as Town Supervisor on Grand Isla...,SUPPORTED,REFUTED,True,The evidence consistently places Nate McMurray...
33,93,US Judge Amy Coney Barrett graduated at the to...,SUPPORTED,NOT_ENOUGH_EVIDENCE,False,The evidence consistently supports that Amy Co...

Vamos a ver la claim `457`. Con esta claim queremos responder a lo siguiente: ¿El retrieval recuperó información que mostraba support + contradiction, pero el verifier la redujo a REFUTED?
o ¿el retrieval ya perdió la parte de la evidencia que hacía que el gold fuera `CONFLICTING_EVIDENCE`?

In [51]:
claim_id = 457

row_457 = dev_df.loc[claim_id]

result_457 = verify_averitec_claim(
    claim_id=claim_id,
    claim=row_457["claim"],
    knowledge_zip=dev_knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
)

Corpus grande detectado: 171628 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 973
Documentos únicos: 972
Documentos finales: 100
Chunks iniciales: 171628
Chunks finales: 9848

Batches: 100%|██████████| 154/154 [29:16<00:00, 11.41s/it]

In [52]:
print("Claim:")
print(row_457["claim"])

print("\nGold:")
print(normalize_averitec_label(row_457["label"]))

print("\nPredicted:")
print(result_457["verification"].verdict)

print("\nEvidence sufficient:")
print(result_457["verification"].evidence_sufficient)

print("\nExplanation:")
print(result_457["verification"].explanation)

Claim:
The Radio Act in Canada makes it a crime to lie to the public via airwaves.

Gold:
CONFLICTING_EVIDENCE

Predicted:
REFUTED

Evidence sufficient:
True

Explanation:
The evidence indicates that Canadian broadcast policy may prohibit false or misleading news, but the cited account says such false-news provisions are regulations rather than criminal offences after the relevant Criminal Code provision was ruled unconstitutional. Therefore, the assertion that the Radio Act makes lying to the public via airwaves a crime is refuted.

In [53]:
for i, evidence in enumerate(result_457["evidences"], start=1):
    print(f"\n--- EVIDENCE {i} ---")
    print("URL:", evidence["url"])
    print("Source type:", evidence["source_type"])
    print("Score:", evidence["score"])
    print("Text:", evidence["text"][:1500])

--- EVIDENCE 1 ---
URL: https://www.snopes.com/fact-check/canadian-fox/
Source type: question_duplicate
Score: 0.7134578227996826
Text: Since at least 2011, rumors have circulated claiming the Fox News television channel has been banned in Canada due to their running afoul of Canadian Radio-Television and Telecommunications Commission (CRTC) prohibitions that make it "illegal to broadcast lies and label it news": One prominent example of this rumor stated, for example, that: America's middle class battles for its survival on the Wisconsin barricades — against various Koch Oil surrogates and the corporate toadies at Fox News — fans of enlightenment, democracy and justice can take comfort from a significant victory north of the Wisconsin border. Fox News will not be moving into Canada after all! The reason: Canadian regulators announced last week they would reject efforts by Canada's right-wing Prime Minister, Stephen Harper, to repeal a law that forbids lying on broadcast news. Canada's Radio Act requires that "a licenser may not broadcast ... any false or misleading news." The provision has kept Fox News and right-wing

--- EVIDENCE 2 ---
URL: https://www.tampabay.com/archive/2014/07/14/is-fox-news-banned-in-canada/
Source type: question_duplicate
Score: 0.7082459926605225
Text: Jr. "The (false news) provision has kept Fox News and right wing talk radio out of Canada and helped make Canada a model for liberal democracy and freedom," wrote Kennedy. "As a result of that law, Canadians enjoy high-quality news coverage including the kind of foreign affairs and investigative journalism that flourished in this country before Ronald Reagan abolished the 'Fairness Doctrine' in 1987." What Kennedy is likely referring to are provisions in Canadian broadcast policy, include the Radio Act and other policies, that prohibit "any false or misleading news." These provisions against spreading misinformation used to be part of Canada's criminal code, according to Canadian media lawyer Paul Schabas. They were famously evoked to send Holocaust denier and neo-Nazi publisher Ernst Zundel to trial in the 1980s. After the Canadian Supreme Court ruled that the code violated freedom of expression rights and thus was unconstitutional, the false news provisions were just regulations.

--- EVIDENCE 3 ---
URL: https://www.ourcommons.ca/Content/Committee/372/HERI/Reports/RP1032284/herirp02/herirp02-e.pdf
Source type: question_duplicate
Score: 0.70818692445755
Text: is spelled out Section 3(1) begins by repeating the principle that the Canadian system should be “effectively owned and controlled by Canadians.” It also reaffirms the long-standing perspective that the airwaves are a public trust to be used by its trustees in the public interest when it declares that: (b) the Canadian broadcasting system, operating primarily in the English and French languages and comprising public, private and community elements, makes use of radio frequencies that are public property and provides, through its programming, a public service essential to the maintenance and enhancement of serve to safeguard, enrich and strengthen the cultural, encourage the development of Canadian expression by providing a wide range of programming that reflects Canadian attitudes, opinions, ideas, values and artistic opportunities arising out of its operations, serve the needs including equal rights, the linguistic duality and multicultural and multiracial nature of Canadian society

--- EVIDENCE 4 ---
URL: https://aviation.stackexchange.com/questions/75135/can-i-use-audio-containing-canadian-atc-broadcast-radio-transmissions-in-a-youtu
Source type: same_entity_questions
Score: 0.7041230201721191
Text: subsection 9(2) of the Radiocommunication Act, no person shall divulge the contents, or the existence, of communications transmitted, received or intercepted by a radio station, except as permitted by the addressee of the message or his/her accredited agent, or to authorized officials of the Government of Canada, officers of the court or an operator of a telecommunications system as is necessary to forward or deliver the communication. These restrictions do not apply to a message of distress, urgency, safety or to messages addressed to “ALL STATIONS” (i.e. weather reports, storm warnings, etc.). As outlined in section 9.1 of the Act, any person who violates the privacy of communications is liable, on summary conviction, in the case of an individual, to a fine not exceeding twenty-five thousand dollars or to imprisonment for a term not exceeding one year, or to both, or, in the case of a person other than an individual, on summary conviction, to a fine not exceeding seventy-five

--- EVIDENCE 5 ---
URL: https://www.ourcommons.ca/Content/Committee/372/HERI/Reports/RP1032284/herirp02/herirp02-e.pdf
Source type: question_duplicate
Score: 0.6995543241500854
Text: and collect subscription fees: why, asked the court, “would Parliament provide for Canadian ownership, Canadian production, Canadian content in its broadcasting and then simply leave the door open for unregulated, foreign broadcasting to come in and sweep it aside? What Lastly, this particular interpretation provides protection to the holders of copyright and complements the scheme of the Copyright Act. An absolute prohibition against decoding except where authorization is granted by the person with the lawful right to transmit and authorize decoding of the signal extends protection to the holders of copyright in the program itself, since it would prohibit the unauthorized reception of signals that violate One of the major concerns as a result of this decision was a fear that the several hundred thousand Canadians who own grey market satellite systems would be vulnerable to criminal charges because they were in breach of the Radiocommunication Act. It is worth remembering that these

--- EVIDENCE 6 ---
URL: https://laws-lois.justice.gc.ca/eng/acts/r-2/page-2.html
Source type: most_similar
Score: 0.6956620216369629
Text: in a confidential manner and not be further disclosed without the express consent of the person responsible for disclosing the information; and (c) only be in respect of contraventions of the laws of a foreign state that have consequences that would not be considered penal under Canadian law. 6 (1) The Governor in Council may make regulations (a) respecting technical requirements and technical standards in relation to (b) prescribing the eligibility of persons to whom radio authorizations, or any class thereof, may be issued, including eligibility criteria based on (i) in the case of an individual, citizenship or permanent residence, or (ii) in the case of a corporation, residence, ownership or control of the corporation, and the citizenship or permanent residence status of the directors and officers of the corporation; (c) prescribing the qualifications of persons to whom radio authorizations, or any class thereof, may be issued, including examinations to be administered; (d)

--- EVIDENCE 7 ---
URL: https://ised-isde.canada.ca/site/broadcasting-telecommunications-legislative-review/en/canadas-communications-future-time-act
Source type: question
Score: 0.6932050585746765
Text: While such orders will not be able to stop all online piracy, they have the potential to reduce it substantially, particularly when coupled with the availability of affordable legal sites. In Canada, the courts appear to have the necessary toolkit to address instances of copyright infringement on the Internet pursuant to provisions of the Copyright Act and the Federal Courts Act. We defer to other fora on whether the Copyright Act needs to be amended to develop other processes for obtaining blocking orders. With respect to the second approach, sections 9 and 10 of the Radiocommunication Act currently make it an offence to decode, retransmit, and operate devices, equipment, or components to receive an unlawfully decrypted subscription program. These provisions should be moved to the Broadcasting Act and expanded to include all forms of media content, whether received through satellites or through the Internet. Consequential amendments should also be made to ensure proper enforcement of

--- EVIDENCE 8 ---
URL: https://laws-lois.justice.gc.ca/eng/acts/r-2/fulltext.html
Source type: question
Score: 0.6915252804756165
Text: and other persons employed in working the station. (2) The person who owns or controls the station of which possession is assumed pursuant to subsection (1) shall give up possession of it and the operators and other persons employed as described in that subsection shall, during the time of possession thereunder, diligently and faithfully obey such orders, and transmit and receive such signals, calls and radiograms, as they are required to receive and transmit by any duly authorized officer of the Government of Canada. (3) Where the Minister and the person who owns or controls any radio station taken possession of by the Crown under this section cannot agree on the compensation to be paid by the Crown for the taking of possession, the Minister shall refer the matter to the Federal Court for adjudication and the Expropriation Act is, with such modifications as the circumstances require, applicable for the purpose of determining the amount of the compensation, if any, and the amount of

--- EVIDENCE 9 ---
URL: https://laws.justice.gc.ca/eng/acts/R-2/FullText.html
Source type: gold
Score: 0.6915252804756165
Text: and other persons employed in working the station. (2) The person who owns or controls the station of which possession is assumed pursuant to subsection (1) shall give up possession of it and the operators and other persons employed as described in that subsection shall, during the time of possession thereunder, diligently and faithfully obey such orders, and transmit and receive such signals, calls and radiograms, as they are required to receive and transmit by any duly authorized officer of the Government of Canada. (3) Where the Minister and the person who owns or controls any radio station taken possession of by the Crown under this section cannot agree on the compensation to be paid by the Crown for the taking of possession, the Minister shall refer the matter to the Federal Court for adjudication and the Expropriation Act is, with such modifications as the circumstances require, applicable for the purpose of determining the amount of the compensation, if any, and the amount of

--- EVIDENCE 10 ---
URL: https://ised-isde.canada.ca/site/broadcasting-telecommunications-legislative-review/en/canadas-communications-future-time-act
Source type: question
Score: 0.690600574016571
Text: to strengthen the compliance regime for both licences and registrations, the Broadcasting Act be amended to include provisions for Administrative Monetary Penalties, similar to the general scheme in the Telecommunications Act, with maximum thresholds set at a level high enough to create a deterrent for foreign undertakings. - We recommend that to address piracy, sections 9 and 10 of the Radiocommunication Act — which state that it is an offence to decode, retransmit, or operate devices, equipment, or components to receive unlawfully decrypted subscription programs — be moved to the Broadcasting Act and be expanded to include all forms of media content, whether received through satellites or the Internet. - We recommend that to ensure the national public broadcaster is able to adapt to a more open, global, and competitive media communications environment, the Broadcasting Act be amended to remove the specific reference to radio and television in the mandate of CBC/Radio-Canada. This

##### Claim 457 — `CONFLICTING_EVIDENCE`: `REFUTED`

La claim afirma que la legislación canadiense convierte en delito mentir al público
a través de las ondas de radio.

La evidencia recuperada contiene información relevante para los distintos componentes
de la afirmación. Por una parte, se recupera información que indica que la regulación
canadiense de radiodifusión contempla restricciones sobre noticias falsas o engañosas.
Por otra, una de las evidencias señala explícitamente que las disposiciones relativas
a noticias falsas dejaron de constituir una infracción penal tras declararse
inconstitucional la correspondiente disposición del código penal, permaneciendo como
regulaciones.

Por tanto, el retrieval proporciona información suficiente para identificar tanto una
base factual parcialmente respaldada como una caracterización incorrecta de dicha
regulación como delito.

El `Evidence Verifier` identifica ambos aspectos en su explicación, pero asigna finalmente
`REFUTED`. El error se atribuye principalmente al razonamiento del verifier, que da
prioridad al componente contradicho (`crime`) y reduce el veredicto global a `REFUTED`,
en lugar de conservar la combinación de elementos respaldados y contradichos mediante
`CONFLICTING_EVIDENCE`.

En este caso, `evidence_sufficient=True` resulta coherente: la evidencia recuperada es
suficiente para alcanzar una conclusión, pero el error se produce en la asignación de
la clase final.

Vamos a ver la Claim `482`. Con esta claim queremos saber si ¿faltó recuperar evidencia suficiente
para mostrar el conflicto? o ¿sí estaba la evidencia, pero el verifier no supo interpretarla?

In [54]:
claim_id = 482

row_482 = dev_df.loc[claim_id]

result_482 = verify_averitec_claim(
    claim_id=claim_id,
    claim=row_482["claim"],
    knowledge_zip=dev_knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
)

Corpus grande detectado: 43689 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 794
Documentos únicos: 793
Documentos finales: 100
Chunks iniciales: 43689
Chunks finales: 2773

Batches: 100%|██████████| 44/44 [05:23<00:00,  7.34s/it]

In [55]:
print("Claim:")
print(row_482["claim"])

print("\nGold:")
print(normalize_averitec_label(row_482["label"]))

print("\nPredicted:")
print(result_482["verification"].verdict)

print("\nEvidence sufficient:")
print(result_482["verification"].evidence_sufficient)

print("\nExplanation:")
print(result_482["verification"].explanation)

Claim:
Donald trump said: "Joe Biden recently raised his hand on the debate stage and promised he was going to give it away, your health care dollars to illegal immigrants, which is going to bring massive number of immigrants into our country."

Gold:
CONFLICTING_EVIDENCE

Predicted:
NOT_ENOUGH_EVIDENCE

Evidence sufficient:
False

Explanation:
The evidence confirms an important underlying event: Biden raised his hand during a debate in response to a question about coverage for undocumented immigrants. It also documents other Trump comments on that event. However, none of the provided evidence contains or otherwise verifies the specific statement attributed to Trump, particularly the wording about giving away health-care dollars and causing a massive number of immigrants to enter the country. Therefore, the evidence is insufficient to verify the claim that Trump said this quotation.

In [56]:
for i, evidence in enumerate(result_482["evidences"], start=1):
    print(f"\n--- EVIDENCE {i} ---")
    print("URL:", evidence["url"])
    print("Source type:", evidence["source_type"])
    print("Score:", evidence["score"])
    print("Text:", evidence["text"][:1500])

--- EVIDENCE 1 ---
URL: https://www.cnbc.com/2019/07/05/joe-biden-vows-to-bring-back-obamacare-individual-mandate-penalty.html
Source type: question
Score: 0.8146544694900513
Text: Trump said. "How about taking care of American Citizens first!? That's the end of that race!" However, Trump's rhetoric was not surprising to Biden. "This is part of what Trump is playing on," he said, playing on people's fears of having open borders and people flowing into the U.S. Biden said providing health care to people who are sick "is just common decency."

--- EVIDENCE 2 ---
URL: https://kffhealthnews.org/morning-breakout/all-democratic-candidates-support-health-care-for-undocumented-immigrants-we-do-ourselves-no-favors-when-millions-cant-access-care/
Source type: question
Score: 0.8076920509338379
Text: if he would provide federally supported health coverage to undocumented immigrants, Biden quickly corrected her. You cannot let people who are sick, no matter where they come from, no matter what their status, go uncovered. You can’t do that. It’s just going to be taken care of. Period. You have to. It’s the humane thing to do,” he insisted. Democratic Rivals Attack Biden, With Harris Leading The Way On Race Issues Trump, who was attending the Group of 20 summit in Japan, was paying attention to the debate and weighed in after all 10 Democrats raised their hands to declare that they would support providing health care for undocumented immigrants. “All Democrats just raised their hands for giving millions of illegal aliens unlimited health care,” Trump said on Twitter during the debate. “How about taking care of American Citizens first!? That’s the end of that race!” (Scherer, Olorunnipa and Janes, 6/28) Trump Slams Democrats Over Health Care For Undocumented Immigrants Immigration has

--- EVIDENCE 3 ---
URL: https://khn.org/morning-breakout/all-democratic-candidates-support-health-care-for-undocumented-immigrants-we-do-ourselves-no-favors-when-millions-cant-access-care/
Source type: gold
Score: 0.8076920509338379
Text: if he would provide federally supported health coverage to undocumented immigrants, Biden quickly corrected her. You cannot let people who are sick, no matter where they come from, no matter what their status, go uncovered. You can’t do that. It’s just going to be taken care of. Period. You have to. It’s the humane thing to do,” he insisted. Democratic Rivals Attack Biden, With Harris Leading The Way On Race Issues Trump, who was attending the Group of 20 summit in Japan, was paying attention to the debate and weighed in after all 10 Democrats raised their hands to declare that they would support providing health care for undocumented immigrants. “All Democrats just raised their hands for giving millions of illegal aliens unlimited health care,” Trump said on Twitter during the debate. “How about taking care of American Citizens first!? That’s the end of that race!” (Scherer, Olorunnipa and Janes, 6/28) Trump Slams Democrats Over Health Care For Undocumented Immigrants Immigration has

--- EVIDENCE 4 ---
URL: https://www.usatoday.com/story/news/factcheck/2020/07/24/fact-check-biden-doesnt-say-taxpayers-must-pay-immigrant-health-care/5485242002/
Source type: question
Score: 0.7897235155105591
Text: on stage — including Biden — were asked to raise their hand "if your government plan would provide coverage for undocumented immigrants." Biden joined all the other candidates in raising his hand. Eight days later, on July 5, 2019, Biden addresses the question again in an interview with CNN's Chris Cuomo, who asked if the candidate believes that people here illegally "should have health care in this country." More: Trump administration urges Supreme Court to end Affordable Care Act amid coronavirus pandemic Biden responded: "I think undocumented people need to have a means by which they can be covered when they're sick. And so the idea is that's what I think we should be doing by building more clinics around the country. Not just for undocumented, for other people when they're ill, when they're sick. People need — this is just common decency." Cuomo: "Well over 50% of people polled say undocumented people shouldn't have health care on our dime." Biden: "Well, I mean, I'll tell you

--- EVIDENCE 5 ---
URL: https://www.detroitnews.com/story/news/politics/2020/02/15/first-time-biden-calls-obama-deportations-big-mistake/111328380/
Source type: background_questions
Score: 0.7856146693229675
Text: 20-minute interview was posted to Ramos’ Facebook page, and Biden aides said portions would be broadcast in coming days on Univision as Biden and his Democratic presidential rivals campaigned in Nevada ahead of the Feb. 22 caucuses, the third nominating contest and the first with a significant Latino population. Biden emphasized to Ramos his proposals to expand legal immigration, bolster the asylum process and end construction of a U.S.-Mexico border wall. The project has been President Donald Trump’s hallmark anti-immigration effort. “This is a big country,” Biden told Ramos, dismissing “the idea we can’t accommodate more people in the interest of the United States.” He called “legal as well as undocumented immigrants” key contributors to the U.S. economy and society. “We stand up and act like it’s a burden,” he said. “It is not a burden. It’s a gift.” Ramos and Biden had a testy exchange during Democrats’ September primary debate when the high-profile Latino journalist noted Obama’s

--- EVIDENCE 6 ---
URL: https://apnews.com/article/5c0bfde98f11556abc4339dd18c6f5af
Source type: gpt_question
Score: 0.7844200730323792
Text: — President Donald Trump is assailing Joe Biden for immigration proposals that Biden actually isn’t proposing. Trump’s account of what his Democratic presidential rival says he’d do with people in the country illegally is false in almost every detail. Trump issued his heated indictment of Biden’s immigration policies and other plans in a sprawling performance from the Rose Garden on Tuesday and carried on with the theme Wednesday. In addition to misrepresenting Biden’s still-evolving agenda, Trump ignored the fact that the Obama-Biden administration aggressively deported people, drawing fierce criticism from some advocates for immigrants. Here’s a look at Trump’s assertions and how they compare with the facts: TRUMP: “Sign new immigrants up for welfare immediately. This is Joe Biden. So they walk off, and they come in, and they put a foot into our land, and we sign up new immigrants up for welfare. We sign them up immediately. They get welfare benefits. United States citizens don’t

--- EVIDENCE 7 ---
URL: https://www.cnbc.com/2019/12/11/joe-biden-releases-immigration-reform-plan-targeting-trump-border-policies.html
Source type: background_questions
Score: 0.7800905704498291
Text: admissions cap to 125,000 from the current 18,000, among other provisions in the plan. Biden also aims to invest $4 billion in Central America to stem violence, spur economic development and target corruption in order to slow a wave of migration to the U.S. "Trump has waged an unrelenting assault on our values and our history as a nation of immigrants," the Biden campaign wrote in its plan. "It's wrong, and it stops when Joe Biden is elected president." Trump entered the White House in 2017 promising to crack down on illegal immigration, portraying many migrants as violent or likely to take jobs from American citizens. A few of his administration's measures to deter immigration, most notably family separation, have sparked furor and charges of cruelty from Democrats and some Republicans. The president leaned into his 2016 rhetoric during a reelection rally in the key swing state of Pennsylvania on Tuesday night. He shared graphic stories of murders and sexual assaults he said were

--- EVIDENCE 8 ---
URL: https://www.factcheck.org/2020/07/trump-distorts-bidens-immigration-plans/
Source type: question
Score: 0.7775207757949829
Text: illegal immigrants.” But it links to a December 2019 video of Biden saying, under his plan, they would be able to “buy into the system.” In the clip, Telemundo’s José Díaz-Balart asks Biden, “Under your plan … would the 11, 12 million undocumented immigrants that live in the United States, that have been here, many of them for generations, would they have access to health insurance?” Biden responds, “Yes. If they can buy into the system like everyone else.” He later says, again, “they will be able to buy in” under the Affordable Care Act, which Díaz-Balart noted is currently not allowed under the health care law. The task force also “recommends extending Affordable Care Act coverage to DACA recipients, [and] allowing undocumented immigrants to purchase unsubsidized coverage in the ACA marketplaces.” That’s not the same as providing “government health care for all illegal aliens.” Trump: Sign new immigrants up for welfare immediately. This is Joe Biden. So they walk off, and they come

--- EVIDENCE 9 ---
URL: https://www.snopes.com/fact-check/biden-undocumented-healthcare/
Source type: question
Score: 0.7745550870895386
Text: summary, even though Biden did state that the U.S. had an obligation to ensure immigrants received health care, his views were largely misrepresented and did not reflect his current policy. While he would extend health care access to undocumented immigrants through the marketplace, it was far from the government-subsidized, taxpayer-funded plan it was made out to be by Trump.

--- EVIDENCE 10 ---
URL: https://www.cnbc.com/2019/12/11/joe-biden-releases-immigration-reform-plan-targeting-trump-border-policies.html
Source type: background_questions
Score: 0.7698683738708496
Text: over the deportation practices of the Obama White House when he served as vice president. His campaign wrote that "Joe Biden understands the pain felt by every family across the U.S. that has had a loved one removed from the country, including under the Obama-Biden Administration, and he believes we must do better to uphold our laws humanely and preserve the dignity of immigrant families, refugees, and asylum-seekers." Biden wants to stop the Trump administration's separation of migrant children from parents, end extended detention and reverse restrictions on travel from several predominantly Muslim countries, according to his campaign. At the same time, Biden wants to create a pathway to citizenship for about 11 million undocumented immigrants in the U.S., expand access to work visas in areas of economic need and boost the annual U.S. refugee admissions cap to 125,000 from the current 18,000, among other provisions in the plan. Biden also aims to invest $4 billion in Central America

##### Claim 482 — `CONFLICTING_EVIDENCE`: `NOT_ENOUGH_EVIDENCE`

La claim atribuye a Donald Trump una declaración sobre la posición de Joe Biden
respecto a la cobertura sanitaria de inmigrantes indocumentados.

Las evidencias recuperadas permiten confirmar varios componentes relevantes de la
afirmación. Se documenta que Biden levantó la mano durante un debate ante una pregunta
sobre cobertura sanitaria para inmigrantes indocumentados y también se recuperan
declaraciones de Trump reaccionando a dicho episodio. Asimismo, otras evidencias
matizan la interpretación de la posición de Biden, indicando que permitir el acceso
o la compra de cobertura sanitaria no equivale necesariamente a proporcionar atención
sanitaria pública gratuita.

Sin embargo, las evidencias recuperadas no contienen de forma explícita la cita completa
atribuida a Trump en la claim. El `Evidence Verifier` centra su decisión en esta ausencia
y devuelve `NOT_ENOUGH_EVIDENCE`, estableciendo `evidence_sufficient=False`.

El error se considera mixto. Aunque el retrieval no recupera la formulación exacta de
la cita, sí proporciona información suficiente sobre varios de sus componentes
materiales y sobre la posible tergiversación de la posición de Biden. El verifier no
integra estas evidencias parciales como un posible caso de información factual combinada
con una caracterización engañosa, lo que habría favorecido `CONFLICTING_EVIDENCE`.

Vamos a ver la claim `333`. Aqui queremos comprobar si el error viene realmente del retrieval. Queremos saber si ¿La evidencia que permitía refutar la claim estaba en el Knowledge Store pero no llegó al Top-10? o ¿Sí llegó al Top-10 y aun así el verifier no la interpretó bien?

In [57]:
claim_id = 333

row_333 = dev_df.loc[claim_id]

result_333 = verify_averitec_claim(
    claim_id=claim_id,
    claim=row_333["claim"],
    knowledge_zip=dev_knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
)

Corpus grande detectado: 87143 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 488
Documentos únicos: 488
Documentos finales: 100
Chunks iniciales: 87143
Chunks finales: 832

Batches: 100%|██████████| 13/13 [01:42<00:00,  7.85s/it]

In [58]:
print("Claim:")
print(row_333["claim"])

print("\nGold:")
print(normalize_averitec_label(row_333["label"]))

print("\nPredicted:")
print(result_333["verification"].verdict)

print("\nEvidence sufficient:")
print(result_333["verification"].evidence_sufficient)

print("\nExplanation:")
print(result_333["verification"].explanation)

Claim:
Development Control Department of the Abuja Metropolitan Management Council (AMMC), an agency of the Federal Capital Territory Administration (FCTA)of Nigeria, in 2020 marked 37 Estates for demolition.

Gold:
REFUTED

Predicted:
NOT_ENOUGH_EVIDENCE

Evidence sufficient:
False

Explanation:
The evidence supports that AMMC includes or works through a Development Control Department and that FCTA/AMMC authorities have conducted demolition-related marking and demolition activities, including a 2020 case involving one community. However, none of the evidence states that the Development Control Department marked 37 estates for demolition in 2020. The claim's central numerical and event-specific assertion is therefore unverified.

In [59]:
for i, evidence in enumerate(result_333["evidences"], start=1):
    print(f"\n--- EVIDENCE {i} ---")
    print("URL:", evidence["url"])
    print("Source type:", evidence["source_type"])
    print("Score:", evidence["score"])
    print("Text:", evidence["text"][:1500])

--- EVIDENCE 1 ---
URL: https://dailypost.ng/2018/01/31/abuja-master-plan-fcta-vows-demolish-750-buildings/
Source type: provenance
Score: 0.8339827060699463
Text: Abuja Master Plan: FCTA vows to demolish 750 buildings The Federal Capital Territory Administration (FCTA) has vowed to demolish 750 illegal building in the nation’s capital in order to restore its Master Plan. The Coordinator, Abuja Metropolitan Management Council, AMMC, Shuaibu Umar, made this known while speaking at a press parley held in Abuja, on Wednesday. According to him, the 750 illegal shanties marked for demolition were located in Lugbe District. Umar also revealed that additional structures that breached the permitted 30 meters proximity to High Tension Lines as well as those that stood in the way of Transmission Company of Nigeria (TCN)’s work on a new transmission station will be removed. The Coordinator maintained that the dream of making Abuja a smart city is attainable; adding that efforts are being made towards achieving that goal. He, however, stressed that attitudinal change by residents of the FCT was required. He said: “Abuja is planned to be a clean city where

--- EVIDENCE 2 ---
URL: https://ammcsite.wordpress.com/
Source type: background_questions
Score: 0.8323035836219788
Text: The Abuja Metropolitan Management Council (AMMC) coordinates six service departments of the Federal Capital Territory Administration to effectively manage and restore the Federal Capital Territory Master Plan. It is responsible for granting permits for public/private developments, and monitoring of physical development activities in line with provisions of the Abuja Master Plan and Development Control guidelines.

--- EVIDENCE 3 ---
URL: https://en.wikipedia.org/wiki/Federal_Capital_Territory_Administration
Source type: gpt_question
Score: 0.8277156949043274
Text: and others.[1][3] The Abuja Metropolitan Management Council (AMMC) was created in 2010 to be responsible for "the efficient running and operation of municipal services within the FCT". It was created as corporation and governed by a board of directors comprising the FCT Minister as chairman, the Executive Secretary of the FCDA as vice chairman, a Co-ordinator, and five other part-time members appointed by the Minister. Members of the AMMC board may hold office for up to two periods of four years each, although they may be dismissed and replaced by the FCT minister at any time. The chief executive officer of the council has the title of Director-General, and is appointed by the president of Nigeria.[4] Departments of Parks and Recreation, Development Control, Facilities Maintenance and Management, Road Traffic Services, and Urban Affairs were created for the council at the time of the AMMC's creation.[4] - ^ a b c "Official Website of the Federal Capital Territory Administration".

--- EVIDENCE 4 ---
URL: https://pmnewsnigeria.com/2012/06/28/19-villages-to-be-flattened-in-nigerias-capital/
Source type: gpt_question
Score: 0.8220146298408508
Text: Nigeria’s Federal Capital Territory Administration (FCTA) plans to demolish 19 villages in the territory, an official of the authority said on Thursday in Abuja. Mrs. Josie Mudashiru, Head of Public Relations Unit, Department of Development Control, Abuja Metropolitan Management Council (AMMC), made this known to the News Agency of Nigeria (NAN). Mudashiru listed the affected villages as Idu, Karmo-Dape, Tasha, Gwagwa, Suburi, Zauda, Jahi, Gishiri, Mabushi, Mpape, Kuchigoro, Chika, Aleita, Piwoyi, Lugbe, Pyakassa, Tudun-wada, Dei-dei and Guzape. She said that AMMC had begun a two-month sensitisation programme for residents of the areas. “We have commenced sensitisation programmes in Hausa, Ibo, Yoruba, Gbagi and pidgin English in the affected areas before the demolition exercise. We have involved chiefs, youths and other stakeholders in the sensitisation programme. We will proceed for marking after the programme, and hopefully, the demolition will commence before the end of 2012,”

--- EVIDENCE 5 ---
URL: https://guardian.ng/news/abuja-master-plan-fcta-to-demolish-shanties-estates/
Source type: background
Score: 0.8183801174163818
Text: Abuja master plan: FCTA to demolish shanties, estates The Federal Capital Territory Authority (FCTA) has disclosed it would demolish over 750 illegal shanties. The FCTA said all the structures did not conform to the Abuja Master Plan. Coordinator of Abuja Metropolitan Management Council (AMMC), Umar Shuaibu, said: “In continuation of its sanitisation of the Federal Capital, the AMMC visited Lugbe and found out that no fewer than 750 illegal shanties were built under high tension wires in Tudun Wada Peace Village. All such structures are to be removed including those that breach the legally permitted 30 metres proximity to the electrical installation.” Shuaibu said other properties to be demolished include the Lugbe FHA Farm Market. He noted that the demolition is in the interest of the public. He advised estate developers to always approach the Department of Development Control for necessary approvals. Get the latest news delivered straight to your inbox every day of the week. Stay

--- EVIDENCE 6 ---
URL: https://viewpointhousingnews.com/2019/05/06/ammc-issued-1697-building-permits-demolished-327-shanties-in-1yr/
Source type: same_entity_questions
Score: 0.8181828260421753
Text: The Abuja Metropolitan Management Council (AMMC) said it has issued 1,697 approvals for residential, commercial, as well as recreational development to prospective developers out of 1,870 applications made between 2017 and 2018. AMMC said the approvals which were issued through its Department of Development Control represented 90 per cent of the 1,870 submissions, adding that the approvals were estimated to have impacted positively through the creation of 4,060 jobs in the city which cut across all professions in the building industry. AMMC is the body responsible for control of development in the Federal Capital Territory (FCT), including processing and approving of building plans and control of physical development, as well as design and maintenance of facilities, among other numerous functions. The council carries out its function through seven departments, particularly the Departments of Development Control, Parks and Recreation and Outdoor Advertisement and Signage’s. The

--- EVIDENCE 7 ---
URL: https://businessday.ng/news/article/fcta-demolishes-134-houses-in-apo-akpmajenya-abuja-suburb/
Source type: question_duplicate
Score: 0.8173232078552246
Text: The Federal Capital Territory Administration (FCTA) Saturday demolished 134 houses in Apo Akpmajenya community of Abuja to allow for the construction of a major road network in the area. Chairman, FCT Ministerial Task Force on City Sanitation, Ikharo Attah who coordinated the exercise said the Minister, Muhammad Musa Bello is poised to safeguard the fidelity of the Abuja Master Plan. Attah explained that the FCT Administration has satisfied all the requirements of the law before carrying out the exercise as there were several months of serving notices of demolition. Also speaking, the Director FCTA Department of Development Control, Muhktar Galadima explained that the community was earlier marked for demolition in January 2020. According to him, relevant agencies of government had engaged the residents and sensitized them on the need to leave the area as it falls within the corridor of the Outer Southern Express Way OSEX and one of the road interchanges linking Oladipo Diya, which is

--- EVIDENCE 8 ---
URL: https://www.peoplesdailyng.com/tackling-abuses-against-abuja-master-plan/
Source type: background
Score: 0.8060266971588135
Text: and Kwali lack good facilities. As part of efforts to maintain Abuja’s master plan, the Abuja Municipal Management Agency (AMMA) was created in 2005, and the agency was later renamed Abuja Metropolitan Management Council (AMMC) in 2007 and given more power. The council is saddled with the responsibility of guiding, directing and controlling the physical development of the FCT, with the main aim of preserving the city’s master plan. Also, the agency is expected to give permits for all forms of physical development in the FCT, while providing specific guidelines for the development of individual and public property. However, the failure of most residents to abide by regulations of AMMC on the city’s management has resulted in frequent sanctions, mostly in form of demolition of structures that have not been approved. These sanctions have, nonetheless, generated controversies between the development control department of AMMC and some FCT residents. In spite of the residents’ complaints

--- EVIDENCE 9 ---
URL: https://naija247news.com/2020/08/15/fcta-demolishes-134-houses-in-apo-akpmajenya-indigenous-community/
Source type: question_duplicate
Score: 0.8038281798362732
Text: Abuja, Aug. 15, 2020 The Federal Capital Territory Administration (FCTA) on Saturday demolished 134 houses at Apo Akpmajenya indigenous community, to pave way for the construction of a major road network in the area. Naija247news reports that the exercise was coordinated by the FCT Task Force on City Sanitation, under the leadership of Mr Ikharo Attah. Briefing newsmen shorty after the exercise, Malam Muktar Galadima, the Director, Department of Development Control, FCTA, explained that the community had been marked for demolition since January. Galadima said that prior to the demolition, the FCTA, through its relevant agencies, interfaced with the inhabitants of the settlement on the need for them to vacate the area. He said that the area fell under the corridor of the planed Outer Southern Expressway (OSEX). He said the community fell on one of the road interchanges linking Oladipo Diya Road, which is an arterial road with the outer southern expressway. Also, Malam Nasir Suleiman,

--- EVIDENCE 10 ---
URL: https://dailypost.ng/2019/07/29/abuja-property-owners-risk-demolition-prosecution/
Source type: provenance
Score: 0.799065887928009
Text: Abuja property owners risk demolition, prosecution The Federal Capital Territory (FCT), administration has vowed to prosecute developers raising illegal structures which were distorting the Abuja Master Plan. “The illegal structures built largely on waterways are causing damage to lives and property in the FCT. We won’t accept that,” Mr Suleiman Abdurahmeed, Acting Coordinator and Director of Administration and Finance, Abuja Metropolitan Management Council (AMMC,) told newsmen on Monday in Abuja. He said that the incessant flooding in some parts of Abuja and environs had called for emergency attention from relevant authorities of the federal capital, saying that the assessment tour would provide the authorities with first hand information toward taking remedial steps. “The essence of this exercise is to go round and appraise the damage caused by the flood; we want to assess the extent of the damage so as to determine the remedial measures and ways to forestall any recurrence”, NAN

##### Claim 333 — `REFUTED`: `NOT_ENOUGH_EVIDENCE`

La claim afirma que el Development Control Department del AMMC marcó 37 estates
para demolición en 2020.

Las evidencias recuperadas contienen información relevante sobre el papel del AMMC
y del Department of Development Control, así como distintos casos de marcado y demolición
de estructuras en Abuja. Sin embargo, ninguna de las evidencias recuperadas menciona
específicamente que se marcaran 37 estates para demolición en 2020.

El `Evidence Verifier` devuelve `NOT_ENOUGH_EVIDENCE` y establece
`evidence_sufficient=False`, una decisión coherente con la información que recibió,
ya que el componente numérico y temporal central de la claim no aparece verificado
ni contradicho en el Top-10 recuperado.

Dado que la etiqueta gold es `REFUTED`, el error se atribuye principalmente al componente
de retrieval: la evidencia necesaria para refutar la afirmación específica no llegó
al conjunto final de evidencias proporcionadas al verifier.

Vamos a ver la claim `68`. Aqui queremos ver un tipo de error diferente al de la claim 333. Aqui queremos ver si ¿el retrieval recuperó evidencia que realmente contradice la claim, o el verifier interpretó como contradicción algo que solo era parcial, indirectamente relacionado o insuficiente?

In [60]:
claim_id = 68

row_68 = dev_df.loc[claim_id]

result_68 = verify_averitec_claim(
    claim_id=claim_id,
    claim=row_68["claim"],
    knowledge_zip=dev_knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
)

Corpus grande detectado: 59678 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 687
Documentos únicos: 687
Documentos finales: 100
Chunks iniciales: 59678
Chunks finales: 5342

Batches: 100%|██████████| 84/84 [16:14<00:00, 11.60s/it]

In [61]:
print("Claim:")
print(row_68["claim"])

print("\nGold:")
print(normalize_averitec_label(row_68["label"]))

print("\nPredicted:")
print(result_68["verification"].verdict)

print("\nEvidence sufficient:")
print(result_68["verification"].evidence_sufficient)

print("\nExplanation:")
print(result_68["verification"].explanation)

Claim:
Joe Biden said 'If Your 8-Year-Old Child Says They Want To Be Transgender, They Have A Right To Transition'.

Gold:
NOT_ENOUGH_EVIDENCE

Predicted:
REFUTED

Evidence sufficient:
True

Explanation:
The evidence establishes that Biden discussed an eight- or ten-year-old saying they wanted to be transgender and called for zero discrimination and equal rights. However, the direct transcript does not show him saying that an eight-year-old who says they want to be transgender has a right to transition. Commentary that interprets his remarks as support for transition does not establish the claimed quotation or its asserted right to transition.

In [62]:
for i, evidence in enumerate(result_68["evidences"], start=1):
    print(f"\n--- EVIDENCE {i} ---")
    print("URL:", evidence["url"])
    print("Source type:", evidence["source_type"])
    print("Score:", evidence["score"])
    print("Text:", evidence["text"][:1500])

--- EVIDENCE 1 ---
URL: https://www.prnewswire.com/news-releases/why-joe-biden-is-wrong-on-gender-transition-for-eight-year-olds-frc-action-explains-301154164.html
Source type: question_duplicate
Score: 0.8444463610649109
Text: Why Joe Biden Is Wrong on Gender Transition for Eight-Year-Olds: FRC Action Explains WASHINGTON, Oct. 16, 2020 /PRNewswire/ -- Last night, during a townhall on ABC, Joe Biden endorsed gender transition for eight-year-old children. Biden seemed to be promoting the unfounded belief that all children with "gender dysphoria" are innately and immutably "transgender," by referring sarcastically to "the idea that an 8-year-old or a 10-year-old, decides, you know, I want to be transgender -- that's what I think I'd like to be, make my life a lot easier." In response, Family Research Council released Friday a new issue analysis publication that details the scientific evidence of long-term harm of gender transition procedures on minors. Peter Sprigg, Senior Fellow for Policy Studies at Family Research Council Action, who authored the publication, stated: "Joe Biden is wrong to encourage gender transitions for 8-year-old children. The implementation of invasive physiological gender transition

--- EVIDENCE 2 ---
URL: https://finance.yahoo.com/news/joe-biden-promises-mom-transgender-170710065.html
Source type: gpt_question
Score: 0.8402959108352661
Text: Biden said without missing a beat. Biden was an early advocate for marriage equality (by politician standards, anyway), and during the town hall, he recounted how his father taught him that love is love.. “The idea that an 8-year-old child or a 10-year-old child decides, ‘I decided I want to be transgender. That’s what I think I’d like to be. It’d make my life a lot easier’ — there should be zero discrimination,” he said. Some have interpreted that quote to be a statement that he things gender identity is a choice, but it seems like it was simply him saying that thinking it’s a choice doesn’t make any logical sense, when life is still so difficult for transgender children and adults. And while Biden got the number wrong on how many transgender and nonbinary people of color have been murdered in 2020, he got his message across that this is unacceptable. “There is no reason to suggest that there should be any right denied your [trans] daughter that your other daughter has a right to be

--- EVIDENCE 3 ---
URL: https://finance.yahoo.com/news/joe-biden-promises-mom-transgender-170710065.html
Source type: gpt_question
Score: 0.8338537216186523
Text: unacceptable. “There is no reason to suggest that there should be any right denied your [trans] daughter that your other daughter has a right to be and do,” Biden said. Yeah, he’s not always the smoothest of talkers, but his point is the right one. Some other parents of transgender kids were happy to see this happen on a national stage. Thank you for saying my trans child deserves the same rights as everyone else. I was already voting for you but now my vote has more meaning behind it. I haven't felt this good since President Obama was in office. Thank you for giving me so much hope for a better tomorrow. Hearing Joe Biden say that my trans child deserves the same rights as everyone else meant more than me to me than a lot of parents will ever understand. Thank you @joebiden for giving me hope that my son can have the future he deserves. — 🏳️🌈NastyMommaDragon ❄️🌊🧷🗳🏖🗽 (@mommadragon4) October 16, 2020 “Hearing Joe Biden say that my trans child deserves the same rights as everyone else

--- EVIDENCE 4 ---
URL: https://www.prnewswire.com/news-releases/why-joe-biden-is-wrong-on-gender-transition-for-eight-year-olds-frc-action-explains-301154164.html
Source type: question_duplicate
Score: 0.833853006362915
Text: stated: "Joe Biden is wrong to encourage gender transitions for 8-year-old children. The implementation of invasive physiological gender transition procedures—puberty blockers, cross-sex hormones, and/or gender reassignment surgery—upon minors raises grave concerns. "Joe Biden's answer in last night's townhall ignores studies that have shown that, when left to themselves, most children with such conditions outgrow them and do not identify as 'transgender' adults. However, such conditions and identities are increasingly being embraced and actively affirmed, not only through 'social transition' (changing one's public expression of gender identity), but through radical physiological interventions as well. These include the use of drugs to block normal puberty, cross-sex hormones, and gender reassignment surgery. Biden was right about only one thing—these procedures do not make a child's life easier," concluded Sprigg. "Each of these procedures has serious negative side effects—up to and

--- EVIDENCE 5 ---
URL: https://thefederalist.com/2020/10/19/joe-biden-tells-mom-he-supports-transgendering-eight-year-old-kids/
Source type: question_duplicate
Score: 0.82746821641922
Text: At presidential candidate Joe Biden’s TV town hall last week, the mother of “two girls, eight and 10” whose “youngest daughter is transgender” asked if he would reverse President Trump’s supposed “dangerous and discriminatory agenda” against trans people. Biden’s response? That he will “flat-out just change the law.” Biden continued, “The idea that an 8-year-old child or a 10-year-old child decides, you know, ‘I decided I want to be transgender. That’s what I think I’d like to be. It would make my life a lot easier.’ There should be zero discrimination.” Greenlighting the “transition” of eight-year-olds in the name of non-discrimination to advance your political career has to be one of the most cynical political moves of this presidential contest. Biden is a supporter of the Equality Act, legislation House Democrats passed in 2019. That bill’s form of “nondiscrimination” against transgender people would require ending sex-based privacy protections in prisons, homeless and abused

--- EVIDENCE 6 ---
URL: https://thefederalist.com/2020/10/19/joe-biden-tells-mom-he-supports-transgendering-eight-year-old-kids/
Source type: question_duplicate
Score: 0.8238542079925537
Text: their ability to choose permanent, life-altering medical treatments? That’s exactly what it means when an eight-year-old “decides to be transgender.” We’re not talking simply about children rejecting superficial gender stereotypes. In 2020 we all know that women can be successful SCOTUS nominees, and men can be accomplished artists and bakers. Affirming the confusion of a “transgender” child is something altogether different. Something that sets children up to be lifelong customers of Big Pharma and cosmetic surgeons. Let’s take a look at the trans activist’s prescribed path for an eight-year-old who wants to “transition,” shall we? While some trans children do not participate in all these activities, Biden’s platform makes way for all of them to be open to children, and indeed the preferred path for such children, despite their dangerous, damaging, and life-altering effects. First, for little girls who want to “present” as boys, parents can purchase “little packers” (or crochet their

--- EVIDENCE 7 ---
URL: https://www.nbcnews.com/feature/nbc-out/parent-transgender-child-questions-biden-trans-rights-n1243720
Source type: gpt_question
Score: 0.8204011917114258
Text: Joe Biden took a question at his town hall on Thursday from the mother of an 8-year-old transgender girl who cited several of the Trump administration’s anti-transgender policies, including the ban on trans people serving openly in the military, and then asked Biden how he would protect the “lives and rights of LGBTQ people.” “I will flat out just change the law, eliminate those executive orders,” Biden, the Democratic presidential nominee, said. He also acknowledged the disparities trans women of color face, particularly Black trans women and the high level of violence and murder they face. The Human Rights Campaign says that at least 33 trans or gender-nonconforming Americans have been killed this year so far. Another audience member, in a discussion about the Supreme Court, asked Biden what he would say to LGBTQ Americans who are “very worried right now about erosions of their rights and our democracy as a whole.” “I think there’s great reason to be concerned for the LGBTQ

--- EVIDENCE 8 ---
URL: https://www.cbsnews.com/news/biden-town-hall-transgender-rights-zero-discrimination/
Source type: question_duplicate
Score: 0.8130255937576294
Text: out that Biden was incorrect in saying a transgender child "decides" to be trans. However, others commended the candidate on his answer and for bring up the murders of transgender women, which has surged this year, according to Trans Equality. "My youngest came out in April as a transgender girl & my blood freezes daily at the thought of four more years of hatred & discrimination from the POTUS. I cried through #BidenTownHall answer with relief & hope. Please help protect my child," one Twitter user wrote. "Having a trans child myself, I thought the same thing. Biden gives us hope," another replied. "Didn't love all the language Biden used while answering the Q from the mom of a trans kid, but watching a presidential candidate acknowledge the humanity of trans adults and kids (and the epidemic of murders of trans [women of color]) made me tear up," another person tweeted. "I was actually really happy to see Biden's support for trans folk tonight, even if his wording wasn't perfect

--- EVIDENCE 9 ---
URL: https://www.cbsnews.com/news/biden-town-hall-transgender-rights-zero-discrimination/
Source type: question_duplicate
Score: 0.7959730625152588
Text: Biden tells mother of transgender daughter there should be "zero discrimination" The mother of a transgender daughter asked Democratic presidential nominee Joe Biden asked how he would protect LBTQ rights if he is elected president – and Biden said he would just "flat-out change the law." Biden took questions at a televised town hall on Thursday, held opposite one with President Trump on a separate network after the second presidential debate was canceled. "The Trump administration has attacked the rights of transgender people, banning them from military service, weakening nondiscriminatory protections and even removing the word 'transgender' from some government websites," Mieke Haeck said to Biden at ABC's town hall. "How will you as president reverse this dangerous and discriminatory agenda and ensure that the lives and rights of LGBTQ people are protected under U.S?" "I would just flat-out change the law," Biden said. "I would eliminated [Mr. Trump's] executive orders, number one."

--- EVIDENCE 10 ---
URL: https://abcnews.go.com/Politics/read-full-transcript-joe-bidens-abc-news-town/story?id=73643517
Source type: question_duplicate
Score: 0.7916384935379028
Text: transgender. That's what I think I'd like to be. It would make my life a lot easier. There should be zero discrimination. And what's happening is too many transgender women of color are being murdered. They're being murdered. And I think it's up now to 17, don't hold me to that number. But it's -- it's higher now? BIDEN: And that's just this year. And so I promise you there is no reason to suggest that there should be any right denied your daughter or daughters, whichever one or two ... BIDEN: ... one, your daughter -- that your other daughter has a right to be and do. None, zero. And by the way, my son Bo, passed away; he was the attorney general in the state of Delaware. He was the guy who got the first transgender passed in the state of Delaware and because of a young man who became a woman who worked for him in the attorney general offices. STEPHANOPOULOS: We've got one more segment coming up. Thank you. ANNOUNCER: "The Vice President and the People," a special edition of "20/20."

##### Claim 68 — `NOT_ENOUGH_EVIDENCE`: `REFUTED`

La claim atribuye a Joe Biden una declaración según la cual un niño de ocho años que
manifieste querer ser transgénero tendría derecho a realizar una transición.

El retrieval recupera evidencias directamente relacionadas con el episodio, incluyendo
la transcripción del town hall en la que Biden habla de un niño de ocho o diez años que
dice querer ser transgénero y defiende la ausencia de discriminación y la igualdad de
derechos.

Sin embargo, la formulación específica relativa a un supuesto "right to transition"
no aparece explícitamente en la transcripción recuperada. Algunas fuentes secundarias
interpretan sus declaraciones como apoyo a la transición de menores, pero esta
interpretación no equivale a demostrar que Biden pronunciara la afirmación atribuida
en la claim.

El `Evidence Verifier` devuelve `REFUTED` y `evidence_sufficient=True`, interpretando
la ausencia de la cita exacta en la evidencia recuperada como una refutación. Dado que
esta ausencia no demuestra necesariamente que la declaración nunca se produjera o que
no exista una formulación equivalente en otra fuente, el error se atribuye
principalmente al verifier, que alcanza una conclusión más fuerte de la que permite
la evidencia disponible.

Vamos a analizar la claim `57`. Aqui queremos analizar si ¿el retrieval recuperó evidencia que realmente apoyaba la claim pero el verifier la interpretó al revés? o ¿el retrieval trajo evidencia contradictoria / incompleta que llevó al verifier a REFUTED?

In [63]:
claim_id = 57

row_57 = dev_df.loc[claim_id]

result_57 = verify_averitec_claim(
    claim_id=claim_id,
    claim=row_57["claim"],
    knowledge_zip=dev_knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
)

Corpus grande detectado: 99616 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 658
Documentos únicos: 658
Documentos finales: 100
Chunks iniciales: 99616
Chunks finales: 1426

Batches: 100%|██████████| 23/23 [02:37<00:00,  6.84s/it]

In [64]:
print("Claim:")
print(row_57["claim"])

print("\nGold:")
print(normalize_averitec_label(row_57["label"]))

print("\nPredicted:")
print(result_57["verification"].verdict)

print("\nEvidence sufficient:")
print(result_57["verification"].evidence_sufficient)

print("\nExplanation:")
print(result_57["verification"].explanation)

Claim:
While serving as Town Supervisor on Grand Island, Nebraska, US Nate McMurray voted to raise taxes on homeowners.

Gold:
SUPPORTED

Predicted:
REFUTED

Evidence sufficient:
True

Explanation:
The evidence repeatedly identifies Nate McMurray as Town Supervisor of Grand Island, New York/Western New York, not Grand Island, Nebraska. This directly contradicts an essential factual component of the claim. None of the evidence establishes that he voted to raise taxes on homeowners, but the claim as written is nevertheless refuted by its incorrect location.

In [65]:
for i, evidence in enumerate(result_57["evidences"], start=1):
    print(f"\n--- EVIDENCE {i} ---")
    print("URL:", evidence["url"])
    print("Source type:", evidence["source_type"])
    print("Score:", evidence["score"])
    print("Text:", evidence["text"][:1500])

--- EVIDENCE 1 ---
URL: https://ballotpedia.org/Nate_McMurray
Source type: question
Score: 0.7750569581985474
Text: in business development to Grand Island. He has championed the State’s plan for a major hike and bike trail along the waterfront, secured Grand Island as the location for the State’s Western New York Visitors’ Center, and spearheaded removal of the much-despised toll barriers at the North and South Grand Island Bridges... Nate’s experience as Grand Island Town Supervisor has taught him important lessons. “We are barely scratching the surface of Western New York’s potential,” Nate says. “We have amazing people, wonderful natural resources, and unbelievable potential. With the right leadership and some hard work, there is no limit to what we can do!” With his wide-ranging experience, deep love for Western New York, and vision for our future: Nathan McMurray is the perfect fit for the 27th District. The following is an example of an ad from McMurray's 2018 election campaign. Note: The finance data shown here comes from the disclosures required of candidates and parties. Depending on the

--- EVIDENCE 2 ---
URL: https://buffalonews.com/news/local/nathan-mcmurray-from-unknown-long-shot-to-serious-contender/article_a9163bc1-d04a-51ac-b0b9-2d0aaa78cb7a.html
Source type: question
Score: 0.7715582847595215
Text: and has been on a whirlwind ever since. He worked with Gov. Andrew M. Cuomo to convert a highway to a trail on the island's west side, worked for cashless tolls, helped get a visitors' center built and raised his voice against the pollution spewed toward the island by Tonawanda Coke. Local Republicans aren't exactly blown away by the whirlwind. "Since McMurray became supervisor, I've thought: 'Why did I move here?' " said the town Republican chairman, Dean Morakis, who complains that the Democrat disrespects property rights and wants to build a big town government that homeowners can't afford. But McMurray's tenure impresses Rep. Brian Higgins, a Buffalo Democrat. "He's my kind of elected official," Higgins said. "He works with purpose and for purpose. He has a vision, and he has done the hard work to make that vision real." Collins' troubles made headlines all through 2017. And even though Grand Island is not in Collins' 27th Congressional District, McMurray saw what has happening

--- EVIDENCE 3 ---
URL: https://spectrumlocalnews.com/nys/buffalo/politics/2018/01/10/nate-mcmurray-to-announce-candidacy-for-congress
Source type: question
Score: 0.7699322700500488
Text: GRAND ISLAND, N.Y. — Grand Island Town Supervisor Nate McMurray will formally announce his candidacy for Congress on Sunday. Sources with his campaign tell Spectrum News that McMurray will make the announcement at noon at Brickyard Brewing Company in Lewiston. McMurray, a Democrat, will run for the 27th district seat, currently occupied by Republican Chris Collins. Three other Democrats, Sean Bunny, Tom Casey and Nick Stankevich, have already announced they are running.

--- EVIDENCE 4 ---
URL: https://www.wnypapers.com/news/article/2018/01/18/131176/grand-island-supervisor-nate-mcmurray-to-challenge-chris-collins-for-congress
Source type: gpt_question
Score: 0.7689437866210938
Text: It has been a whirlwind week for 27th Congressional District candidate and Grand Island Supervisor Nate McMurray. On Sunday, he announced his candidacy to a standing-room-only crowd of over 200 at the Brickyard Brewing Company in Lewiston. Voters throughout the district came to support McMurray's effort to unseat incumbent Congressman Chris Collins. Supporters, including City of Tonawanda Mayor Rick Davis, said McMurray, if elected, will remain connected to the people he serves. "Nate will bring the perspective of the average American to his representation of the 27th District. Too often people elected to Congress are well off financially and they do not think of the many struggling households we have in our area. Nate will be the voice those families need in Congress." After his announcement, McMurray wasted no time introducing himself to voters from Canandaigua to Batavia to Wheatfield. On Tuesday night, he was among the five congressional hopefuls at the Turn NY 27 Blue Candidates

--- EVIDENCE 5 ---
URL: https://www.wnypapers.com/news/article/2018/01/18/131176/grand-island-supervisor-nate-mcmurray-to-challenge-chris-collins-for-congress
Source type: gpt_question
Score: 0.7688269019126892
Text: to voters from Canandaigua to Batavia to Wheatfield. On Tuesday night, he was among the five congressional hopefuls at the Turn NY 27 Blue Candidates Forum in Lancaster. Dorothy Avery, a voter from the Town of Bergen, said she was "impressed with Nate's creativity and strong ethical values. I'm confident he will represent all of NY 27's voters without regard for party affiliation or tax bracket." McMurray was a Fulbright Scholar and received advanced degrees (including law). He became fluent in Korean and Chinese, and spent time overseas en route to a successful business career. McMurray said he missed Western New York, so he returned home. He is married and the proud father of two boys. In addition to being Grand Island supervisor, he is vice president for development at Delaware North. Grand Island Democratic Party Chairman and Deputy Supervisor James Sharpe has worked with McMurray for years. "Nathan is one of the most creative people I know," Sharpe said. "He is focused and

--- EVIDENCE 6 ---
URL: https://www.cityandstateny.com/politics/2018/08/democrat-nate-mcmurray-hails-from-an-island-of-dreams/178199/
Source type: gpt_question
Score: 0.7515028119087219
Text: Democrat Nate McMurray hails from an island of dreams Democrat Nate McMurray has a realistic chance now to win the NY 27th Congressional District. Grand Island, right next to Niagara Falls on the Canadian border, has fed many grandiose dreams. There was the early 19th century plan to establish the area as a Jewish homeland. Then came an idea to place what would become part of the U.N. headquarters there – the job instead went to New York City. And this year Grand Island Supervisor Nate McMurray believes he has a chance to represent the deep red 27th Congressional District that lies just beyond the blue waters of the Niagara River. His campaign appeared doomed to remain a dream until this month, when McMurray, a Democrat, awoke to find out that three-term Republican Rep. Chris Collins had gotten arrested on charges of insider trading. Now the 43-year-old has gained national attention, campaign donations and the increasingly serious chance to get the national party to invest in winning a

--- EVIDENCE 7 ---
URL: https://www.cityandstateny.com/politics/2018/08/democrat-nate-mcmurray-hails-from-an-island-of-dreams/178199/
Source type: gpt_question
Score: 0.7356016635894775
Text: nearly a decade. McMurray points to his tenure as supervisor in Grand Island as evidence that he can eke out a narrow Democratic win in a heavily Republican area. But his critics allege his actions in office illustrate that his ambitions supersede the needs of his constituents – though they declined to say so on the record. McMurray is quick to highlight how a video he made featuring a cat pushed Gov. Andrew Cuomo to commit to installing cashless tolls on bridges leading into town, but residents still have to pay $1 each time they leave, for example. A minor scandal emerged earlier this year when he used his town email during business hours to explore a congressional run. Then there was the time that he faced an unprecedented “pitchfork-style anger,” according to Vienna Haak, a 30-year resident of the island. At issue was whether an eight-mile stretch of road along the western shore of the island would become a bike path. Opponents said they feared additional traffic and diminished

--- EVIDENCE 8 ---
URL: https://mhflsentinel.com/u-s-congressional-candidate-nate-mcmurray-visits-scottsville/
Source type: question
Score: 0.7308750152587891
Text: Since the August 8th, 2018 arrest of U.S. Rep. Chris Collins (R-NY) who is accused of insider trading, the name “Nate McMurray” has been receiving significant attention in both Western New York and nationally. Only weeks ago, however, McMurray, who secured his ballot spot in a June 26th primary win, was spending eight hours each day driving across the sizable 27th district to meet with voters. During his travels on July 28th, he made a stop in Scottsville to introduce himself to possible future constituents curious to hear his views on the challenges and opportunities facing Western New York. The talk that McMurray, who currently serves as Town Supervisor in Grand Island, NY, gave in Scottsville included a brief history lesson on the 27th district. The 27th is a largely rural district that stretches across a big piece of Western New York. In fact the sheer size of the district rivals that of some states. The counties of Genesee, Livingston, Orleans, and Wyoming comprise the district as

--- EVIDENCE 9 ---
URL: http://www.isledegrande.com/town/townnews2018.php
Source type: question
Score: 0.7270616292953491
Text: Soma Cura, Natural & Wellness Products by Seema Mojawalla, doTerra, Sheila Saph-beauty wellness and Pink Martini Gift Shop. McMurray Running for Congressional Seat - January 2018 A Buffalo News article by Robert J. McCarthy dated January 10, 2018 reports that Grand Island Supervisor Nathan McMurray will be making an official announcement at noon on Sunday, January 14th at Brickyard Brewing in Lewiston to run for Chris Collins 27th Congressional seat. McMurray will be meeting with national Democratic Party leaders in Washington on Tuesday, January 16th. In 2017, the hot topic was still the closing of West River Parkway, with the addition of Cashless Tolls and a Welcome Center. Senior Volunteers Stuff Town/County Tax Bills - January 2018 Sitting from left: Martha Muller, Nonnie Carroll and Jerrie Benzing. This is the 14th year a group of seniors from the Golden Age Center have stuffed tax bills for Town Clerk Pattie Frentzel. The seniors spend the day stuffing envelopes for the

--- EVIDENCE 10 ---
URL: https://mhflsentinel.com/u-s-congressional-candidate-nate-mcmurray-visits-scottsville/
Source type: question
Score: 0.7217058539390564
Text: Island after returning home. The town has a population of about 20,000 and sits in Erie County. McMurray described Grand Island, which is as large as Manhattan, as geographically unique, essentially resting between two nations. “There are no skyscrapers in Grand Island,” he joked, “only trails, kayak launches, boat marinas, and fields.” McMurray entered politics in 2016 when he was encouraged to run for Town Supervisor in Grand Island. Despite being a primarily Republican area, he won. From here he started on a mission to make the town easier to do business with while at the same time improving its draw as a “destination.” Through engaging with constituents in that role McMurray was exposed to the simmering unhappiness of many voters who felt like their voices had been going unheard for too long. It was a feeling he knew well. It is why he entered that race despite it being a longshot for him to win; it is the same reason he entered the Congressional race as well, ultimately beating

##### Claim 57 — `SUPPORTED`: `REFUTED`

La claim afirma que Nate McMurray, durante su etapa como Town Supervisor de Grand Island,
votó para aumentar los impuestos sobre propietarios, aunque sitúa dicha localidad en
Nebraska.

Las evidencias recuperadas identifican de forma consistente a McMurray como Town
Supervisor de Grand Island, New York, por lo que contradicen el componente geográfico
de la afirmación. Sin embargo, el Top-10 no aporta evidencia clara sobre el componente
principal relativo a una votación para aumentar impuestos a los propietarios.

El `Evidence Verifier` considera la discrepancia geográfica como una contradicción
suficiente para clasificar la claim como `REFUTED` y establece
`evidence_sufficient=True`.

El error se considera mixto. Por una parte, el retrieval recupera principalmente
información biográfica y geográfica, pero no evidencia específica sobre la supuesta
votación fiscal. Por otra, el verifier da un peso decisivo al error de localización y
utiliza ese componente para refutar la claim completa, en lugar de distinguir entre
un detalle geográfico incorrecto y el núcleo sustantivo de la afirmación.

Analizamos ahora la claim `93`, la última de nuestro análisis. Aqui queremos comprobar si ¿la evidencia de apoyo estaba en el Knowledge Store pero no llegó al Top-10? o ¿sí llegó al Top-10 y aun así el verifier no la consideró suficiente?

In [66]:
claim_id = 93

row_93 = dev_df.loc[claim_id]

result_93 = verify_averitec_claim(
    claim_id=claim_id,
    claim=row_93["claim"],
    knowledge_zip=dev_knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
)

Corpus grande detectado: 41313 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 645
Documentos únicos: 645
Documentos finales: 100
Chunks iniciales: 41313
Chunks finales: 1412

Batches: 100%|██████████| 23/23 [02:48<00:00,  7.32s/it]

In [67]:
print("Claim:")
print(row_93["claim"])

print("\nGold:")
print(normalize_averitec_label(row_93["label"]))

print("\nPredicted:")
print(result_93["verification"].verdict)

print("\nEvidence sufficient:")
print(result_93["verification"].evidence_sufficient)

print("\nExplanation:")
print(result_93["verification"].explanation)

Claim:
US Judge Amy Coney Barrett graduated at the top of her law school class at Notre Dame Law School

Gold:
SUPPORTED

Predicted:
SUPPORTED

Evidence sufficient:
True

Explanation:
The evidence sufficiently supports the claim. Multiple items establish that Amy Coney Barrett graduated from Notre Dame Law School, and Evidence 6 specifically reports that she graduated summa cum laude and received the Hoynes Prize for the best overall record in scholarship, deportment, and achievement. Evidence 2 likewise identifies the Hoynes Prize as the law school's top honor.

In [68]:
for i, evidence in enumerate(result_93["evidences"], start=1):
    print(f"\n--- EVIDENCE {i} ---")
    print("URL:", evidence["url"])
    print("Source type:", evidence["source_type"])
    print("Score:", evidence["score"])
    print("Text:", evidence["text"][:1500])

--- EVIDENCE 1 ---
URL: https://news.nd.edu/news/notre-dame-law-school-professor-barrett-nominated-to-us-supreme-court/
Source type: question
Score: 0.8889598846435547
Text: Judge Amy Coney Barrett, professor of law at the University of Notre Dame and a 1997 graduate of Notre Dame Law School, was nominated today to the Supreme Court of the United States to fill the vacancy created by the death of Associate Justice Ruth Bader Ginsburg. She is the first Notre Dame graduate and faculty member to be nominated to serve on the nation’s highest court. “The same impressive intellect, character and temperament that made Judge Barrett a successful nominee for the U.S. Court of Appeals will serve her and the nation equally well as a Justice of the United States Supreme Court,” Notre Dame President Rev. John I. Jenkins, C.S.C., said. “An alumna and a faculty member of Notre Dame Law School, Judge Barrett has epitomized the University’s commitment to teaching, scholarship, justice and service to society. She is a person of the utmost integrity who, as a jurist, acts first and foremost in accord with the law. I join her colleagues in the Law School and across the campus

--- EVIDENCE 2 ---
URL: https://swsmmagazine.com/2020/10/working-mom-distinguished-law-professor-and-supreme-court-nominee-a-profile-of-amy-coney-barrett/
Source type: claim+question
Score: 0.8565313816070557
Text: On Saturday, September 26, President Trump nominated Judge Amy Coney Barrett to the Supreme Court. Judge Barrett was appointed to the U.S. Court of Appeals for the Seventh Circuit in 2017 and is a faculty member at the University of Notre Dame’s Law School. Judge Barrett is a native of New Orleans, where she graduated from St. Mary’s Dominican High School. After high school, she received a bachelor’s degree from Rhodes College and a Juris Doctor from the University of Notre Dame. Graduating from Notre Dame as a Kiley Fellow, she earned the coveted Hoynes Prize, the law school’s top honor. She also served as the executive editor for the Notre Dame Law Review. Notably, Judge Barrett clerked for Judge Laurence H. Silberman on the U.S. Court of Appeals in the D.C. Circuit (1997-98) and Associate Supreme Court Justice Antonin Scalia (1998-99). After successful clerkships, she litigated constitutional, criminal, and commercial cases in trial and appellate courts as an associate at Miller,

--- EVIDENCE 3 ---
URL: https://law.nd.edu/news-events/news/nd-law-school-hosts-investiture-of-judge-amy-coney-barrett/
Source type: question
Score: 0.8494296073913574
Text: ND Law School hosts investiture of Judge Amy Coney Barrett Notre Dame Law School was privileged on Friday to celebrate a beloved alumna and professor, Amy Coney Barrett, ’97 J.D., by hosting her investiture as a judge for the U.S. Court of Appeals for the Seventh Circuit. An audience of colleagues, friends, and family members filled the Patrick F. McCartan Courtroom for the ceremony, which included a touching combination of praise and anecdotes from people who have known Judge Barrett personally and professionally throughout her life. “I have learned many things over the last year, but truly, the most important is how fortunate I am to have a life brimming with so many wonderful people,” Barrett said. Barrett will continue to teach at Notre Dame Law School as one of two judges on the Law School’s faculty. Judge Kenneth Ripple, also of the U.S. Court of Appeals for the Seventh Circuit, has taught at the Law School for more than 40 years. Rev. John Jenkins, C.S.C., president of the

--- EVIDENCE 4 ---
URL: https://works.bepress.com/amy_barrett/
Source type: question
Score: 0.8484739065170288
Text: The Honorable Amy Coney Barrett serves as an associate justice of the U.S. Supreme Court. She was nominated by President Donald Trump and confirmed by the U.S. Senate on October 26, Previously, she served as a judge on the U.S. Court of Appeals for the Seventh Circuit from October 2017 until her confirmation to the Supreme Court. She is a Notre Dame Law School alumna and has taught as a member of the Law School’s faculty since 2002. Justice Barrett teaches and researches in the areas of federal courts, constitutional law, and statutory interpretation. Her scholarship in these fields has been published in leading journals, including the Columbia, Virginia, and Texas Law Reviews. From 2010-2016, she served by appointment of the Chief Justice on the Advisory Committee for the Federal Rules of Appellate Procedure. She has been selected as “Distinguished Professor of the Year” by three of the Law Justice Barrett earned her B.A. in English literature, magna cum laude, from Rhodes College,

--- EVIDENCE 5 ---
URL: https://chicago.suntimes.com/2020/9/26/21456427/trump-chooses-chicago-based-amy-coney-barrett-for-high-court-pick
Source type: question_duplicate
Score: 0.8481030464172363
Text: After graduation, that pipeline led her to clerkships with the nation’s leading conservative judges, first with Laurence Silberman, now a senior judge for the U.S. Circuit Court of Appeals for D.C. and then with Scalia. Said Notre Dame Law School Professor O. Carter Snead, “There’s just consensus: Amy Barrett is the best student, the smartest and most talented person to ever come through the University of Notre Dame Law School.” After clerking for Scalia in 1998, she did a stint in private practice. Barrett served in the army of lawyers who helped George W. Bush in his successful 2000 presidential recount battle against Al Gore. It was a move she had thought about previously, recalled Notre Dame Law School Professor Nicole Garnett, who met Barrett when Garnett was clerking for Thomas and Barrett was with Scalia. “Like many of the young lawyers who we clerked with on the Supreme Court, Judge Barrett was considering the legal academy when I met her in 1998.” After a stop at the George

--- EVIDENCE 6 ---
URL: https://concernedwomen.org/meet-amy-coney-barrett/
Source type: same_entity_questions
Score: 0.8458214402198792
Text: during a prenatal screening. Judge Barrett graduated from St. Mary’s Dominican High School in New Orleans (1990). She studied English literature at Rhodes College where she graduated with a Bachelor of Arts magna cum laude (1994). She was Phi Beta Kappa and earned Most Outstanding English Major and Most Outstanding Senior Thesis. She earned a full tuition scholarship to go to the Notre Dame Law School where she graduated with a juris doctor, summa cum laude (1997). She was the Executive Editor of the Notre Dame Law Review. She was also the recipient of the Hoynes Prize (for the best record in scholarship, deportment, and achievement), the Dean’s Award (for the best exam in Administrative Law, Civil Procedure I and II, Constitutional Law, Contracts, Criminal Procedure, Evidence, First Amendment, Torts II, and Legal Research and Writing). Upon graduation, Amy Coney Barret earned some prestigious judicial clerkships. First, under Judge Laurence Silberman of the U.S. Court of Appeals for

--- EVIDENCE 7 ---
URL: https://www.deccanherald.com/world/rooted-in-faith-representing-a-new-conservatism-amy-coney-barrett-s-path-to-a-court-pick-900720.html
Source type: question_duplicate
Score: 0.8414180278778076
Text: On a winter afternoon in 2018, Judge Amy Coney Barrett rose to speak in Notre Dame Law School’s wood-paneled courtroom and thanked the people gathered there for joining her for her official investiture as a judge on the U.S. Court of Appeals for the 7th Circuit. In the audience were her parents, in town from her childhood home in New Orleans, and her husband, who had described her as a kind of superwoman, along with six of their seven children, who led the group in the Pledge of Allegiance. And there were many friends — from law school, her Supreme Court clerkship and her Catholic parish in South Bend, Indiana. Also in attendance were a number of prominent conservative legal figures, mentors who had helped make this moment happen. But perhaps the most important was a Notre Dame graduate whose eyes were on the future, not the past. That graduate, Don McGahn, President Donald Trump’s White House counsel, was known for his single-minded focus on remaking the federal judiciary according to

--- EVIDENCE 8 ---
URL: https://www.abc57.com/news/amy-coney-barrett-students-proud-of-her-nomination
Source type: question_duplicate
Score: 0.8391909003257751
Text: Amy Coney Barrett Students 'proud' of her nomination "I was very impressed with her intelligence and her ability to grasp the law," said Stan Wruble, Barrett's classmate at Notre Dame's law school. "As you might imagine there are a lot of smart people who go to Notre Dame Law School, but she was clearly one of the smartest people I've ever met." Hadyn Pettersen, one of Barrett's law students at Notre Dame said the student body at Notre Dame's law school agrees. "When registration opens every year, her class fills up within seconds," Pettersen said. "That's because people really do recognize that she is at the top of her field." Pettersen said class has been different with Judge Barrett making visits to Washington, D.C. to discuss the Supreme Court vacancy. "On Monday we heard rumblings that she was in consideration," Pettersen said. "Actually, when we showed up for class, she had sent her clerk to lead the class that day. in hindsight, we heard reports that she was at the White House

--- EVIDENCE 9 ---
URL: https://law.nd.edu/news-events/news/professor-amy-coney-barrett-to-deliver-notre-dame-law-school-commencement-address/
Source type: gpt_question
Score: 0.8388935327529907
Text: Professor Amy Coney Barrett to Deliver Notre Dame Law School Commencement Address Notre Dame Law Students have selected Amy Coney Barrett, Diane and M.O. Miller, II Research Chair in Law, for the 2016 Law School Distinguished Teaching Award. Barrett will address the graduates at Notre Dame Law School’s 2016 Commencement ceremony Saturday. “I’m incredibly honored to be recognized,” said Barrett, who also won the award in 2006. “I’ve had the privilege of teaching the majority of the graduating class. While I’m sad to see them go, I’m excited to see the great things they will accomplish as Notre Dame Lawyers.” Each year the graduating class selects a professor to receive the Law School Distinguished Teaching Award, which honors a faculty member who exhibits excellence in leadership, friendship, legal knowledge, legal teaching and professional ability. “Professor Barrett was selected as the distinguished professor of the year because she embodies the Notre Dame spirit,” said Tim

--- EVIDENCE 10 ---
URL: https://law.nd.edu/news-events/news/us-senate-confirms-professor-amy-barrett-as-federal-judge/
Source type: question
Score: 0.8383845686912537
Text: U.S. Senate confirms Professor Amy Barrett as federal judge The U.S. Senate voted Tuesday afternoon to confirm Notre Dame Law Professor Amy Coney Barrett as a judge for the U.S. Court of Appeals for the Seventh Circuit. “Amy Barrett has been a beloved teacher and outstanding scholar,” said Nell Jessup Newton, the Joseph A. Matson Dean of Notre Dame Law School. “I am confident she will be a wise, fair, and brilliant jurist as well.” Barrett earned her J.D. at Notre Dame Law School in 1997 and joined the Law School’s faculty in 2002. She teaches and researches in the areas of federal courts, constitutional law, and statutory interpretation. Students selected her as the Law School’s “Distinguished Professor of the Year” in 2006 and 2016. President Donald Trump nominated Barrett in May to fill a vacant seat on the Seventh Circuit Court of Appeals, a jurisdiction that covers Indiana, Illinois, and Wisconsin. Every full-time member of Notre Dame Law School’s faculty signed a strong letter of

#### Variabilidad entre ejecuciones del Evidence Verifier

Durante el análisis descriptivo de errores se observó que la claim 93, clasificada como
`NOT_ENOUGH_EVIDENCE` durante la evaluación inicial (held-out), produjo `SUPPORTED` al ejecutarse
posteriormente de forma individual con la misma configuración general del pipeline.

La segunda ejecución recuperó evidencia suficiente para respaldar la afirmación y
coincidió con la etiqueta gold. Esta diferencia pone de manifiesto una posible
variabilidad entre ejecuciones asociada al componente basado en LLM.

Para preservar la validez de la evaluación, las métricas reportadas se mantienen a partir
de la ejecución held-out original y no se sustituyen predicciones individuales obtenidas
en ejecuciones posteriores. Las nuevas ejecuciones se utilizan únicamente con fines
diagnósticos.

Debido al resultado obtenido con la claim 93 de nuestro análisis, no podemos atribuirle un fallo estructural concreto, por lo tanto vamos a analizar ahora la claim 305 como sustitución de la claim 93. 

En la evaluación held-out, la claim 305 obtuvo `SUPPORTED` como etiqueta gold, mientras
que el sistema predijo `NOT_ENOUGH_EVIDENCE` con `evidence_sufficient=False`.

El objetivo de este análisis es determinar si la evidencia necesaria para apoyar la claim
no fue recuperada por el componente de retrieval o si, por el contrario, sí estaba presente
en el Top-10 pero no fue considerada suficiente por el `Evidence Verifier`.

In [69]:
claim_id = 305

row_305 = dev_df.loc[claim_id]

result_305 = verify_averitec_claim(
    claim_id=claim_id,
    claim=row_305["claim"],
    knowledge_zip=dev_knowledge_zip,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
    client=client,
)

Corpus grande detectado: 63020 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 568
Documentos únicos: 566
Documentos finales: 100
Chunks iniciales: 63020
Chunks finales: 3947

Batches: 100%|██████████| 62/62 [12:05<00:00, 11.70s/it]

In [70]:
print("Claim:")
print(row_305["claim"])

print("\nGold:")
print(normalize_averitec_label(row_305["label"]))

print("\nPredicted:")
print(result_305["verification"].verdict)

print("\nEvidence sufficient:")
print(result_305["verification"].evidence_sufficient)

print("\nExplanation:")
print(result_305["verification"].explanation)

Claim:
Photo Showing the remains of Vladimir Komarov, a man who fell from space, in 1967.

Gold:
SUPPORTED

Predicted:
NOT_ENOUGH_EVIDENCE

Evidence sufficient:
False

Explanation:
The evidence supports the background fact that Vladimir Komarov died in the Soyuz 1 crash in 1967. Several posts also use the exact claimed caption, and one source mentions an open-casket image of his remains. However, none of the provided evidence independently identifies, authenticates, or links the specific photo in the claim to Komarov. Therefore, the claim about what the photo shows cannot be verified from the supplied evidence alone.

In [72]:
for i, evidence in enumerate(result_305["evidences"], start=1):
    print(f"\n--- EVIDENCE {i} ---")
    print("URL:", evidence["url"])
    print("Source type:", evidence["source_type"])
    print("Score:", evidence["score"])
    print("Text:", evidence["text"][:1500])

--- EVIDENCE 1 ---
URL: https://www.reddit.com/r/pics/comments/31i4g5/the_remains_of_astronaut_vladimir_komarov_the_man/
Source type: claim+question
Score: 0.8535376787185669
Text: The remains of astronaut Vladimir Komarov, the man who fell from space, 1967. Archived post. New comments cannot be posted and votes cannot be cast. Reddit and its partners use cookies and similar technologies to provide you with a better experience. By accepting all cookies, you agree to our use of cookies to deliver and maintain our services and site, improve the quality of Reddit, personalize Reddit content and advertising, and measure the effectiveness of advertising. By rejecting non-essential cookies, Reddit may still use certain cookies to ensure the proper functionality of our platform. For more information, please see our Cookie Notice and our Privacy Policy.

--- EVIDENCE 2 ---
URL: https://www.reddit.com/r/oldschoolcreepy/comments/haanz9/the_remains_of_the_astronaut_vladimir_komarov_a/
Source type: question_duplicate
Score: 0.8483351469039917
Text: The remains of the astronaut Vladimir Komarov, a man who fell from space. 1967 Reddit and its partners use cookies and similar technologies to provide you with a better experience. By accepting all cookies, you agree to our use of cookies to deliver and maintain our services and site, improve the quality of Reddit, personalize Reddit content and advertising, and measure the effectiveness of advertising. By rejecting non-essential cookies, Reddit may still use certain cookies to ensure the proper functionality of our platform. For more information, please see our Cookie Notice and our Privacy Policy.

--- EVIDENCE 3 ---
URL: https://www.reddit.com/r/pics/comments/45kjii/the_remains_of_the_astronaut_vladimir_komarov_a/
Source type: claim
Score: 0.8432380557060242
Text: A place for photographs, pictures, and other images. The remains of the astronaut Vladimir Komarov, a man who fell from space, 1967 Archived post. New comments cannot be posted and votes cannot be cast.

--- EVIDENCE 4 ---
URL: https://www.reddit.com/r/pics/comments/4vg8eh/the_remains_of_the_cosmonaut_vladimir_komarov_a/
Source type: question_duplicate
Score: 0.8380483388900757
Text: A place for photographs, pictures, and other images. The remains of the cosmonaut Vladimir Komarov, a man who fell from space, 1967 [Kinda NSFW] Archived post. New comments cannot be posted and votes cannot be cast.

--- EVIDENCE 5 ---
URL: https://steemit.com/history/@npatou/the-tragic-death-of-the-man-who-fell-from-space-cosmonaut-vladimir-komarov-1967
Source type: question_duplicate
Score: 0.817746639251709
Text: Komarov during official funeral - April 26, 1967 (source: AFP/Getty Images) The man who fell from space, Vladimir Komarov, was honored with his final request for an open casket funeral. Vladimir Komarov's remains in an open casket (source:RIA Novosti/Photo Researchers Inc.) Ironically, one year after Komarov’s tragic death, Gagarin died when he crashed a fighter jet.

--- EVIDENCE 6 ---
URL: https://www.reddit.com/r/WTF/comments/5hiwlh/the_remains_vladimir_komarov_the_man_who_fell/
Source type: claim+question
Score: 0.8105016350746155
Text: The remains Vladimir Komarov, the man who fell from space. Archived post. New comments cannot be posted and votes cannot be cast. Reddit and its partners use cookies and similar technologies to provide you with a better experience. By accepting all cookies, you agree to our use of cookies to deliver and maintain our services and site, improve the quality of Reddit, personalize Reddit content and advertising, and measure the effectiveness of advertising. By rejecting non-essential cookies, Reddit may still use certain cookies to ensure the proper functionality of our platform. For more information, please see our Cookie Notice and our Privacy Policy.

--- EVIDENCE 7 ---
URL: https://rarehistoricalphotos.com/search/vladimir%20komarov
Source type: claim
Score: 0.7894723415374756
Text: The remains of the astronaut Vladimir Komarov, a man who fell from space, 1967 Mankind's road to the stars had its unsung heroes. One of them was the Soviet cosmonaut Vladimir Komarov. His spaceflight on Soyuz 1 made him the first Soviet cosmonaut to fly into outer space more than once, and he became the first human to die on a sp…

--- EVIDENCE 8 ---
URL: https://steemit.com/history/@npatou/the-tragic-death-of-the-man-who-fell-from-space-cosmonaut-vladimir-komarov-1967
Source type: question_duplicate
Score: 0.7621120810508728
Text: The Tragic Death of the Man Who Fell From Space - Cosmonaut Vladimir Komarov (1967) Leonid Brezhnev wanted something special to celebrate the 50th anniversary of the October Revolution which was soon approaching. The Soviet Premier ordered a spectacle that would prove the Soviet Union's superiority in the space race. Two spaceships would meet in mid-space and dock, then a cosmonaut from a first spacecraft, Soyuz-1 would spacewalk and change places with one of two cosmonauts in another spacecraft, Soyuz-2 and then return safely to earth. Vladimir Komarov (source: Vasily Malyshev / RIA Novosti) Vladimir Komarov was appointed the cosmonaut of the Soyuz-1 which was scheduled to orbit the earth first and wait for Soyuz-2. His dear friend and Russian national hero, Yuri Gagarin was his backup cosmonaut. Gagarin (left) and Komarov out hunting (source: RIA Novosti /Photo Researchers, Inc) Despite numerous failed safety tests and serious concerns expressed by several technicians and even Yuri

--- EVIDENCE 9 ---
URL: https://www.rferl.org/a/soviet_space_death_komarov_anniversary_cosmonaut/24558877.html
Source type: question
Score: 0.7590467929840088
Text: He's known as the first person to die during spaceflight. Forty-five years ago, cosmonaut Vladimir Komarov died when the parachutes on his Soyuz 1 space capsule failed to deploy properly after reentry into the Earth's atmosphere. The capsule slammed onto Soviet soil near Orenburg, Russia, on April 24, 1967. Interest in Komarov's tragic story was rekindled last year with the publication of "Starman: The Truth Behind the Legend of Yuri Gagarin," a biography of the Soviet cosmonaut who became the first human in space in April 1961. The authors of "Starman" -- Jamie Doran and Piers Bizony -- quoted a former KGB officer, Venyamin Russayev, as saying that Komarov, even though he was aware of myriad design flaws in the Soyuz 1, refused to back out of his flight because Gagarin was his backup pilot. He didn’t want to send a national hero to his certain death. "I'm not going to make it back from this flight," Russayev quotes Komarov as saying. Russayev also says that Soviet Premier Aleksei

--- EVIDENCE 10 ---
URL: http://news.bbc.co.uk/onthisday/hi/dates/stories/april/24/newsid_2523000/2523019.stm
Source type: question
Score: 0.7574557065963745
Text: 1967: Russian cosmonaut dies in space crashThe Soviet Union has announced the catastrophic failure of its latest space mission, with the crash of Soyuz 1 and the death of the cosmonaut on board. Colonel Vladimir Komarov, 40, is the first known victim of a space flight. He was an experienced cosmonaut, on his second flight, and had completed all his experiments successfully before returning to Earth. But within seconds of landing, just after he re-entered the Earth's atmosphere, the strings of the parachute intended to slow his descent apparently became tangled. The spaceship hurtled to the ground from four miles up. It is likely that Colonel Komarov was killed instantly on impact. A message of condolence from the Communist Party in Moscow described him as "a loyal son of our motherland and a courageous explorer of space." He has been decorated posthumously with a second Gold Star for heroism, and his ashes will be buried at the Kremlin wall - one of the highest honours accorded to a

##### Claim 305 — `SUPPORTED`: `NOT_ENOUGH_EVIDENCE`

La claim afirma que una fotografía muestra los restos del cosmonauta Vladimir Komarov
tras el accidente de Soyuz 1 en 1967.

El retrieval recupera numerosas fuentes relacionadas directamente con la afirmación.
Varias de ellas utilizan descripciones prácticamente idénticas de la fotografía y otras
documentan tanto la muerte de Komarov en 1967 como la existencia de imágenes de sus
restos tras el accidente.

Sin embargo, el `Evidence Verifier` devuelve `NOT_ENOUGH_EVIDENCE` y establece
`evidence_sufficient=False`, argumentando que ninguna de las evidencias identifica o
autentica de forma independiente la fotografía concreta incluida en la claim.

En este caso, el error pone de manifiesto una limitación adicional del sistema. El
pipeline de AVeriTeC implementado trabaja exclusivamente sobre evidencia textual y no
analiza directamente el contenido visual de las imágenes. Por tanto, en claims cuya
verificación depende de identificar o autenticar una fotografía, el sistema únicamente
puede utilizar captions y descripciones textuales de las fuentes recuperadas.

El retrieval proporciona información textual ampliamente compatible con la etiqueta
`SUPPORTED`, pero el verifier aplica un criterio más restrictivo y exige una
autenticación de la imagen que el pipeline textual no puede realizar directamente. El
error se atribuye principalmente a esta limitación de modalidad, junto con un criterio
conservador del `Evidence Verifier`.

#### Resumen del análisis de errores representativos

La siguiente tabla resume los principales patrones observados en las claims seleccionadas
del conjunto `dev`. El objetivo no es reajustar el sistema a partir de estos casos, sino
identificar de forma descriptiva qué componente del pipeline parece estar relacionado
con cada error.

| Claim | Gold | Predicted | evidence_sufficient | Diagnóstico principal | Interpretación |
|---|---|--|--|---|-------|
| 457 | `CONFLICTING_EVIDENCE` | `REFUTED` | `True` | Evidence Verifier | El retrieval recupera información suficiente sobre componentes apoyados y contradichos, pero el verifier da prioridad al componente refutado y reduce el caso completo a `REFUTED`. |
| 482 | `CONFLICTING_EVIDENCE` | `NOT_ENOUGH_EVIDENCE` | `False` | Mixto, principalmente Evidence Verifier | El retrieval recupera el contexto central y evidencias sobre la tergiversación de la posición de Biden, aunque no la cita exacta completa. El verifier se centra en esa ausencia y no integra adecuadamente los componentes parcialmente respaldados y contradichos. |
| 333 | `REFUTED` | `NOT_ENOUGH_EVIDENCE` | `False` | Retrieval | Las evidencias recuperadas contienen contexto sobre demoliciones y AMMC, pero no la información específica necesaria para refutar la afirmación relativa a las 37 estates. |
| 68 | `NOT_ENOUGH_EVIDENCE` | `REFUTED` | `True` | Evidence Verifier | El retrieval recupera el contexto original y la transcripción relevante, pero el verifier interpreta la ausencia de la cita exacta como una refutación concluyente, alcanzando una conclusión más fuerte de la que permite la evidencia. |
| 57 | `SUPPORTED` | `REFUTED` | `True` | Mixto: retrieval + Evidence Verifier | El retrieval identifica correctamente la localización real de Grand Island, New York, pero no recupera evidencia clara sobre la votación fiscal. El verifier da un peso decisivo al error geográfico y refuta la claim completa. |
| 305 | `SUPPORTED` | `NOT_ENOUGH_EVIDENCE` | `False` | Limitación de modalidad + Evidence Verifier | El retrieval recupera descripciones textuales compatibles con la claim, pero el sistema no analiza directamente la imagen. El verifier exige una autenticación visual que el pipeline textual no puede proporcionar. |

En conjunto, el análisis muestra que los errores no se concentran en un único componente del sistema. Algunos casos se relacionan principalmente con el razonamiento del `Evidence Verifier`, especialmente en claims multicomponente o cuando debe distinguir entre contradicción directa, evidencia parcial y falta de evidencia. Otros errores se
deben a limitaciones del retrieval, que puede no recuperar la información decisiva para la afirmación concreta. También se observa una limitación específica en claims de naturaleza visual, ya que el pipeline implementado utiliza únicamente evidencia textual.

Estos resultados ayudan a delimitar las principales áreas de mejora futura del sistema: mejor descomposición de claims, recuperación más específica por componentes, mecanismos más robustos para distinguir `REFUTED` de `CONFLICTING_EVIDENCE` y soporte multimodal para afirmaciones cuya verificación dependa de imágenes.

### 17. Conclusiones de la evaluación con AVeriTeC

El componente de verificación factual se evaluó sobre una muestra estratificada de 40 claims del conjunto `dev` de AVeriTeC, seleccionando 10 ejemplos de cada una de las cuatro clases. La configuración del sistema se mantuvo congelada durante esta fase y los resultados obtenidos no se utilizaron para realizar nuevos ajustes.

La evaluación obtuvo una `accuracy` de 0.40 y un `macro-F1` de 0.36. El rendimiento fue desigual entre clases. El sistema obtuvo mejores resultados en `SUPPORTED` y `REFUTED`, mientras que presentó dificultades especialmente relevantes en `CONFLICTING_EVIDENCE`, categoría para la que no se clasificó correctamente ninguna de las diez claims evaluadas.

El análisis descriptivo de errores mostró que los fallos no proceden de un único componente. Se observaron errores asociados al `Evidence Verifier`, especialmente en claims multicomponente y en la distinción entre contradicción directa, información parcial y evidencia conflictiva. También se identificaron limitaciones del retrieval cuando la evidencia decisiva no alcanzaba el conjunto final de fragmentos recuperados. Adicionalmente, se observó una limitación de modalidad en claims cuya verificación depende de contenido visual, ya que el pipeline desarrollado
opera exclusivamente sobre evidencia textual.

Durante el análisis posterior también se observó variabilidad entre ejecuciones del componente basado en LLM. Por este motivo, las métricas reportadas corresponden a la ejecución original sobre la muestra reservada de `dev`; las ejecuciones posteriores de claims individuales se utilizaron únicamente con fines diagnósticos.

En conjunto, la evaluación permite validar experimentalmente el funcionamiento del pipeline factual y, al mismo tiempo, delimitar sus principales limitaciones. Los resultados no implican que el sistema resuelva de forma completa la verificación de claims reales, sino que proporcionan una medida reproducible de su comportamiento y
una base para identificar mejoras futuras relacionadas con descomposición de claims, retrieval más específico, razonamiento sobre evidencia conflictiva y soporte multimodal.

#### Configuración resultante del componente factual

Tras finalizar la evaluación, el componente factual se considera cerrado para esta versión del proyecto. Las funciones y configuraciones seleccionadas se trasladarán a módulos Python reutilizables dentro de `src/`, manteniendo sin cambios la lógica evaluada en AVeriTeC.

El notebook se conservará como registro del proceso experimental, mientras que los módulos de `src/` contendrán únicamente las versiones finales necesarias para la integración posterior con el resto de la arquitectura.

### 18. Validación del módulo `retrieval.py`

In [81]:
import sys
from pathlib import Path

PROJECT_ROOT = Path("..").resolve()

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

In [74]:
from src.retrieval import (
    load_knowledge_records,
    build_claim_index,
    retrieve_evidence,
)

Vamos a probarlas con una claim pequeña, la 93 por ejemplo:

In [75]:
claim_id = 93
claim = dev_df.loc[claim_id, "claim"]

knowledge_records_test = load_knowledge_records(
    knowledge_zip=dev_knowledge_zip,
    claim_id=claim_id,
)

print("Knowledge records:", len(knowledge_records_test))

Knowledge records: 822

Construimos el indice:

In [76]:
chunks_test, index_test, retrieval_info_test = build_claim_index(
    claim=claim,
    knowledge_records=knowledge_records_test,
    embedding_model=embedding_model,
    text_splitter=text_splitter,
)

print(retrieval_info_test)

Corpus grande detectado: 41313 chunks.
Se aplicará TF-IDF para seleccionar 100 documentos.
Documentos originales: 645
Documentos únicos: 645
Documentos finales: 100
Chunks iniciales: 41313
Chunks finales: 1412

Batches: 100%|██████████| 23/23 [02:56<00:00,  7.66s/it]

{'original_documents': 645, 'unique_documents': 645, 'final_documents': 100, 'initial_chunks': 41313, 'final_chunks': 1412, 'tfidf_filter_used': True}

Hacemos el retrieval:

In [77]:
evidences_test = retrieve_evidence(
    claim=claim,
    embedding_model=embedding_model,
    index=index_test,
    chunks=chunks_test,
)

print("Número de evidencias:", len(evidences_test))

Número de evidencias: 10

In [78]:
for i, evidence in enumerate(evidences_test, start=1):
    print(f"\n--- EVIDENCE {i} ---")
    print("Score:", evidence["score"])
    print("URL:", evidence["url"])
    print("Text:", evidence["text"][:500])

--- EVIDENCE 1 ---
Score: 0.8889598846435547
URL: https://news.nd.edu/news/notre-dame-law-school-professor-barrett-nominated-to-us-supreme-court/
Text: Judge Amy Coney Barrett, professor of law at the University of Notre Dame and a 1997 graduate of Notre Dame Law School, was nominated today to the Supreme Court of the United States to fill the vacancy created by the death of Associate Justice Ruth Bader Ginsburg. She is the first Notre Dame graduate and faculty member to be nominated to serve on the nation’s highest court. “The same impressive intellect, character and temperament that made Judge Barrett a successful nominee for the U.S. Court o

--- EVIDENCE 2 ---
Score: 0.8565313816070557
URL: https://swsmmagazine.com/2020/10/working-mom-distinguished-law-professor-and-supreme-court-nominee-a-profile-of-amy-coney-barrett/
Text: On Saturday, September 26, President Trump nominated Judge Amy Coney Barrett to the Supreme Court. Judge Barrett was appointed to the U.S. Court of Appeals for the Seventh Circuit in 2017 and is a faculty member at the University of Notre Dame’s Law School. Judge Barrett is a native of New Orleans, where she graduated from St. Mary’s Dominican High School. After high school, she received a bachelor’s degree from Rhodes College and a Juris Doctor from the University of Notre Dame. Graduating from

--- EVIDENCE 3 ---
Score: 0.8494296073913574
URL: https://law.nd.edu/news-events/news/nd-law-school-hosts-investiture-of-judge-amy-coney-barrett/
Text: ND Law School hosts investiture of Judge Amy Coney Barrett Notre Dame Law School was privileged on Friday to celebrate a beloved alumna and professor, Amy Coney Barrett, ’97 J.D., by hosting her investiture as a judge for the U.S. Court of Appeals for the Seventh Circuit. An audience of colleagues, friends, and family members filled the Patrick F. McCartan Courtroom for the ceremony, which included a touching combination of praise and anecdotes from people who have known Judge Barrett personally

--- EVIDENCE 4 ---
Score: 0.8484739065170288
URL: https://works.bepress.com/amy_barrett/
Text: The Honorable Amy Coney Barrett serves as an associate justice of the U.S. Supreme Court. She was nominated by President Donald Trump and confirmed by the U.S. Senate on October 26, Previously, she served as a judge on the U.S. Court of Appeals for the Seventh Circuit from October 2017 until her confirmation to the Supreme Court. She is a Notre Dame Law School alumna and has taught as a member of the Law School’s faculty since 2002. Justice Barrett teaches and researches in the areas of federal

--- EVIDENCE 5 ---
Score: 0.8481030464172363
URL: https://chicago.suntimes.com/2020/9/26/21456427/trump-chooses-chicago-based-amy-coney-barrett-for-high-court-pick
Text: After graduation, that pipeline led her to clerkships with the nation’s leading conservative judges, first with Laurence Silberman, now a senior judge for the U.S. Circuit Court of Appeals for D.C. and then with Scalia. Said Notre Dame Law School Professor O. Carter Snead, “There’s just consensus: Amy Barrett is the best student, the smartest and most talented person to ever come through the University of Notre Dame Law School.” After clerking for Scalia in 1998, she did a stint in private pract

--- EVIDENCE 6 ---
Score: 0.8458214402198792
URL: https://concernedwomen.org/meet-amy-coney-barrett/
Text: during a prenatal screening. Judge Barrett graduated from St. Mary’s Dominican High School in New Orleans (1990). She studied English literature at Rhodes College where she graduated with a Bachelor of Arts magna cum laude (1994). She was Phi Beta Kappa and earned Most Outstanding English Major and Most Outstanding Senior Thesis. She earned a full tuition scholarship to go to the Notre Dame Law School where she graduated with a juris doctor, summa cum laude (1997). She was the Executive Editor o

--- EVIDENCE 7 ---
Score: 0.8414180278778076
URL: https://www.deccanherald.com/world/rooted-in-faith-representing-a-new-conservatism-amy-coney-barrett-s-path-to-a-court-pick-900720.html
Text: On a winter afternoon in 2018, Judge Amy Coney Barrett rose to speak in Notre Dame Law School’s wood-paneled courtroom and thanked the people gathered there for joining her for her official investiture as a judge on the U.S. Court of Appeals for the 7th Circuit. In the audience were her parents, in town from her childhood home in New Orleans, and her husband, who had described her as a kind of superwoman, along with six of their seven children, who led the group in the Pledge of Allegiance. And

--- EVIDENCE 8 ---
Score: 0.8391909003257751
URL: https://www.abc57.com/news/amy-coney-barrett-students-proud-of-her-nomination
Text: Amy Coney Barrett Students 'proud' of her nomination "I was very impressed with her intelligence and her ability to grasp the law," said Stan Wruble, Barrett's classmate at Notre Dame's law school. "As you might imagine there are a lot of smart people who go to Notre Dame Law School, but she was clearly one of the smartest people I've ever met." Hadyn Pettersen, one of Barrett's law students at Notre Dame said the student body at Notre Dame's law school agrees. "When registration opens every yea

--- EVIDENCE 9 ---
Score: 0.8388935327529907
URL: https://law.nd.edu/news-events/news/professor-amy-coney-barrett-to-deliver-notre-dame-law-school-commencement-address/
Text: Professor Amy Coney Barrett to Deliver Notre Dame Law School Commencement Address Notre Dame Law Students have selected Amy Coney Barrett, Diane and M.O. Miller, II Research Chair in Law, for the 2016 Law School Distinguished Teaching Award. Barrett will address the graduates at Notre Dame Law School’s 2016 Commencement ceremony Saturday. “I’m incredibly honored to be recognized,” said Barrett, who also won the award in 2006. “I’ve had the privilege of teaching the majority of the graduating cla

--- EVIDENCE 10 ---
Score: 0.8383845686912537
URL: https://law.nd.edu/news-events/news/us-senate-confirms-professor-amy-barrett-as-federal-judge/
Text: U.S. Senate confirms Professor Amy Barrett as federal judge The U.S. Senate voted Tuesday afternoon to confirm Notre Dame Law Professor Amy Coney Barrett as a judge for the U.S. Court of Appeals for the Seventh Circuit. “Amy Barrett has been a beloved teacher and outstanding scholar,” said Nell Jessup Newton, the Joseph A. Matson Dean of Notre Dame Law School. “I am confident she will be a wise, fair, and brilliant jurist as well.” Barrett earned her J.D. at Notre Dame Law School in 1997 and joi

Con esto, hemos comprobado que retrieval.py se importa correctamente, lee el Knowledge Store, construye el índice, recupera 10 evidencias

### 19. Validación del módulo `evidence_verifier.py

In [84]:
from src.evidence_verifier import (
    VerificationResult,
    verify_evidence,
)

In [85]:
verification_test = verify_evidence(
    claim=claim,
    evidences=evidences_test,
    client=client,
)

In [86]:
print("Verdict:")
print(verification_test.verdict)

print("\nEvidence sufficient:")
print(verification_test.evidence_sufficient)

print("\nExplanation:")
print(verification_test.explanation)

Verdict:
SUPPORTED

Evidence sufficient:
True

Explanation:
The claim is supported by evidence stating that Barrett graduated summa cum laude and received the Hoynes Prize for the best record in scholarship, deportment, and achievement at Notre Dame Law School. Additional evidence describes the Hoynes Prize as the law school's top honor and quotes a professor calling her its best student.

In [ ]:
#Viendo las relaciones por evidencia
for assessment in verification_test.evidence_assessments:
    print(
        assessment.evidence_id,
        assessment.relation,
        assessment.reason,
    )

1 NEUTRAL It establishes that Barrett graduated from Notre Dame Law School in 1997, but gives no information about her class standing.
2 SUPPORTS It says Barrett graduated as a Kiley Fellow and received the Hoynes Prize, described as the law school's top honor, supporting the claim that she was academically at the top of her class.
3 NEUTRAL It identifies Barrett as a 1997 J.D. alumna but does not address her academic rank or class standing.
4 NEUTRAL The excerpt confirms her connection to Notre Dame Law School but contains no stated information about graduating at the top of her class.
5 SUPPORTS A Notre Dame Law School professor is quoted describing Barrett as the best student and most talented person ever to come through the law school, which supports the asserted top-of-class characterization.
6 SUPPORTS It states that Barrett graduated summa cum laude and received the Hoynes Prize for the best record in scholarship, deportment, and achievement. This directly supports that she graduated at the top of her Notre Dame Law School class.
7 NEUTRAL It discusses Barrett's investiture and professional network, not her law-school class standing.
8 NEUTRAL It reports opinions about Barrett's intelligence and stature in her field, but does not establish her law-school graduation rank.
9 NEUTRAL It concerns Barrett's teaching award and commencement address, not her academic standing as a law student.
10 NEUTRAL It confirms that she earned her J.D. from Notre Dame in 1997 but does not state her class rank or top-of-class status.

Aqui hemos comprobaddo que evidence_verifier.py se importa correctamente, que recibe las evidencias recuperadas, que llama al LLM y devuelve un VerificationResult válido